### ISSUE TITLE
Allow custom CA for s3

### ISSUE THREAD

**Issue by superguillen** [openobserve/openobserve#1011]
### Which OpenObserve functionalities are relevant/related to the feature request?

log search, ingestion

### Description

Actualy S3 storage endpoints (OnPremises) with custom CAs don't work, openobserv crash with InvalidCertificate(UnknownIssuer)

### Proposed solution

Enable skyp TLS verificacion on S3 URL

### Alternatives considered

Enable Add custom certificates/CAs

**Comment by superguillen** [comment]
Similar to feat: send notification skip cert verify #750, https://github.com/openobserve/openobserve/pull/750

**Comment by hengfeiyang** [comment]
will add it

**Comment by hengfeiyang** [comment]
Can you try this image: `public.ecr.aws/zinclabs/openobserve-dev:v0.4.8-274e187-amd64`

and add an environment:

```
ZO_S3_ALLOW_INVALID_CERTIFICATES=true
```

**Comment by superguillen** [comment]
Hi, Fix Works !!!!!, thanks a lot
