### ISSUE TITLE
Support binding to ipv6

### ISSUE THREAD

**Issue by ksmithut** [openobserve/openobserve#1019]
### Which OpenObserve functionalities are relevant/related to the feature request?

ingestion, other

### Description

openobserve only binds to an ipv4 address (0.0.0.0). It would be awesome if it could bind to an ipv6 "any" address (`::`) as well. I'm currently playing around with using openobserve on a cloud provider fly.io, which is very much ipv6 only internally. You can assign ipv4 addresses for connecting coming from outside of fly.io, but with other services I have running, I'd like them to push logs, traces, and metrics directly into openobserve without having to go pack out into the public internet. But that only works if openobserve has an option to bind to an ipv6 address, or binds to both ipv4 and ipv6 addresses.

### Proposed solution

Bind to both `0.0.0.0` and `::` (PR incoming)

### Alternatives considered

You could provide an option to let the operator narrow down what ip address/host to bind to, but just keeping with what's currently there would probably be fine.

**Comment by hengfeiyang** [comment]
even, i merged, but in my test, it can't work if I disable ipv6 in system:

To disable IPv6 on Ubuntu, you can follow these steps:

1. Open the terminal (Ctrl + Alt + T).

2. Open the `sysctl.conf` file with a text editor, such as nano or vim. For example, using nano:

```bash
sudo nano /etc/sysctl.conf
```

3. Add the following lines to the end of the `sysctl.conf` file to disable IPv6:

```conf
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
net.ipv6.conf.ens4.disable_ipv6 = 1 # here must disable you net interface
```

4. Save the changes and exit the text editor. In nano, press Ctrl + X, then press Y, and then press Enter to save and exit.

5. Apply the changes by running the following command:

```bash
sudo sysctl -p
```

6. To verify that IPv6 is disabled, run the following command:

```bash
cat /proc/sys/net/ipv6/conf/ens4/disable_ipv6
```

If the output is `1`, IPv6 has been successfully disabled.

Keep in mind that disabling IPv6 might cause issues with some applications or services that rely on it. If you encounter any issues, you can re-enable IPv6 by removing the lines you added to the `sysctl.conf` file, saving the changes, and then running `sudo sysctl -p` again.

**Comment by hengfeiyang** [comment]
we should check if the system disabled ipv6, we can't listen on ipv6.

**Comment by hengfeiyang** [comment]
and i tested on ubuntu, even i enable ipv6, it also can't work. can you try?

**Comment by hengfeiyang** [comment]
i tested on ubuntu, because the ipv6 `[::]:5080` include `0.0.0.0:5080`, only listen on `[::]:5080`, it will both listen on `0.0.0.0:5080`.

So, when you both listen on ipv4 & ipv6, it will report error:

```
Error: Address already in use (os error 98)
```

Because ipv4 already bind, the ipv6 try to bind to ipv4 again.

**Comment by hengfeiyang** [comment]
So, at the end, i found, we don't need both listen on ipv6 & ipv4. if you want enable ipv6, we can only listen on `[::]:5080` it will listen both on ipv4 & ipv6.

**Comment by ksmithut** [comment]
Thanks all for the work to fix this. I apologize for not getting out my solution more (very new to rust).

I noticed that there was [a commit](https://github.com/openobserve/openobserve/pull/1062) that reverted ipv6 support without an explanation. I understand if it’s problematic to support both IPv4 and IPv6. Would it make sense to reopen this feature request or open a new ticket?

**Comment by hengfeiyang** [comment]
Revert because it still can't work if the node has no ipv6. 

We add an option for enable ipv6 `ZO_HTTP_IPV6_ENABLED=true` in v0.5.0.

**Comment by ksmithut** [comment]
Oh awesome :) Thanks!
