### ISSUE TITLE
Show error detail for user to identify and resolve

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#1024]
### Which OpenObserve functionalities are the source of the bug?

dashboards

### Is this a regression?

Yes

### Description

Need to show the detailed error message to the user so she can take corrective action

<img width="1581" alt="image" src="https://github.com/openobserve/openobserve/assets/4242188/94a26fdf-a87e-4af4-aa9c-d74430bf605e">

**Comment by ktx-kirtan** [comment]
The error message is too long: 119769 chars

We trimmed the message to 300 chars if more than that for now

It will look like this:
![image](https://github.com/openobserve/openobserve/assets/124270523/adebbc61-7d61-4087-8a44-feae2f5b347a)
