### ISSUE TITLE
Explorer support persists view

### ISSUE THREAD

**Issue by wenerme** [openobserve/openobserve#1026]
### Description

I want to persists the view when I play with the log, I treat log Explorer as playground, I want to restore the previous state, includes

- column selection
- vrl function
- sql

### Proposed solution

Support persists view

### Alternatives considered

Explorer like the pre-dashboard stage, want to do more when playing with logs, these works may become a dashboard or panel, maybe at some point, the view can convert to a panel in dashboard.

**Comment by hengfeiyang** [comment]
The user only want to run `select count(*) from tbl` but, it is not easy to do.

**Comment by prabhatsharma** [comment]
Can now be done using saved views
