### ISSUE TITLE
v0.4.8 container image not working with podman

### ISSUE THREAD

**Issue by fatihusta** [openobserve/openobserve#1029]
### Which OpenObserve functionalities are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Basically not working these command with podman.
Interesting thing is there is nothing any error or info log.

v0.4.7 works. 

```
mkdir data
podman run -v $PWD/data:/data -e ZO_DATA_DIR="/data" -p 5080:5080 \
    -e ZO_ROOT_USER_EMAIL="root@example.com" -e ZO_ROOT_USER_PASSWORD="Complexpass#123" \
    public.ecr.aws/zinclabs/openobserve:v0.4.8

```

**Comment by hengfeiyang** [comment]
some users report that we found we enabled a feature of `avx2` in v0.4.8, but there is no in v0.4.7, we will make a new lease and remove it soon.

**Comment by fatihusta** [comment]
I uses kvm based hypervisor. not enabled avx by default. I understood why didn't work. I will test after adding cpu function for vm. Thanks.

**Comment by fatihusta** [comment]
I changed cpu mode to `host-model` in virsh for vm. And I tested with v0.5.0. It worked.
