### ISSUE TITLE
Older data unavailable in log search

### ISSUE THREAD

**Issue by marcosirianni** [openobserve/openobserve#1032]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

No

### Description

Logs I generated last Friday in my test VM are not available anymore for search even if they're in the same bucket in MinIO as new data being generated today:
![image](https://github.com/openobserve/openobserve/assets/118524535/843956d8-bdfc-4a8d-81bb-8b54bebcbdda)
Bucket with all data, unsearchable logs included.

![image](https://github.com/openobserve/openobserve/assets/118524535/b0354361-9b68-4d54-91ac-9db7ef47e44d)
"default" stream just with a bunch of logs generated today. Using time filters in search doesn't make them searchable.

Openobserve VM has been shut down during weekend just like MinIO one and Openobserve process has been started with the following command line:
`ZO_ROOT_USER_EMAIL=admin@admin.com ZO_ROOT_USER_PASSWORD=XXXXX ZO_LOCAL_MODE_STORAGE=s3 ZO_S3_SERVER_URL=http://10.0.0.8:9000 ZO_S3_REGION_NAME=local ZO_S3_ACCESS_KEY=XXXXXXXXXXXXXXXX ZO_S3_SECRET_KEY=XXXXXXXXXXXXXXXXXXXXXXX ZO_S3_BUCKET_NAME=openobserve ZO_S3_BUCKET_PREFIX=openobserve ZO_S3_PROVIDER=minio ./openobserve`

### Please provide the exception or error you saw

```true
No error, just no results
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version 0.4.8
```

**Comment by hengfeiyang** [comment]
It looks like you deleted streams or removed install and install OpenObserve again, just use the same bucket.

we logged each stream created time in metadata(db), after you recreate it, we will only fetch data from the new time. old data can't be searching. because in our metadata, we don't know the old time range.

**Comment by marcosirianni** [comment]
Thanks for your answer. I just terminated the process with CTRL+C  (from the standalone Linux binary) and shut down the VM, I didn't touch the directory:
![image](https://github.com/openobserve/openobserve/assets/118524535/8b4559b5-a9c3-497a-987c-4aa4b64959a1)
As you can see there are still files that are unmodified since last Friday

**Comment by hengfeiyang** [comment]
Did you ingest data with `_timestamp` and first ingested new data, and second ingested older data?

**Comment by marcosirianni** [comment]
On Friday I ingested data with curl, _timestamp was generated by OpenObserve as logs didn't have this field natively. Today I found that the "default" stream was there but with 0 logs. I ingested new data this morning like I did on Friday and now only this data is visible.

**Comment by prabhatsharma** [comment]
UI shows only last 15 minutes data by default. Just to be sure, you did change the time range to include data for last Friday when searching?

**Comment by marcosirianni** [comment]
Yes, also tried with last week filter. I'll see if I can reproduce the issue tomorrow, I'll keep you updated.

**Comment by marcosirianni** [comment]
I think I managed to reproduce it already:
![openobserve](https://github.com/openobserve/openobserve/assets/118524535/5e3235a7-826d-4ac1-a395-fcd8be1b5d49)

Process has been terminated with CTRL+C

**Comment by hengfeiyang** [comment]
as your description, if after restart, there is no data can be query?

**Comment by marcosirianni** [comment]
No, data doesn't seem to exist in any way on the platform anymore.

Just to mention a detail about my previously posted reproduction of the issue: sometimes terminating the process with CTRL+C, waiting a few seconds and restarting the process didn't reproduce the issue, I had to do a couple of further attempts.

**Comment by hengfeiyang** [comment]
it sees, we can list files from MinIO, list files is zero, you can see the logs when OpenObserve start. i will test again with MinIO.

**Comment by hengfeiyang** [comment]
Please try to set `ZO_S3_PROVIDER=s3_minio` and test again.

**Comment by marcosirianni** [comment]
Looks good, I tried and so far I haven't managed to reproduce that behaviour.
