### ISSUE TITLE
 The log search time is too long.

### ISSUE THREAD

**Issue by chiikin** [openobserve/openobserve#1035]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

When I select a time range of one month, the response time takes 400 seconds.How can I reduce this time?

My requirement is: I need to know which times have data within a certain time range.

![image](https://github.com/openobserve/openobserve/assets/21117413/bce24892-04fe-424c-aa26-79a86ddaa880)

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version v0.4.8
Commit Hash 5bfe67624415f0297c72c0e82ee0dbba156ba6f9
Build Date 2023-06-22T09:16:07Z
```

**Comment by hengfeiyang** [comment]
Only 358k records, it cost 400s, it is impossible. What is your machine resource? cpu and memory and which type of local disk, HDD or SSD?

Can you check the logs of OpenObserve and share with us?

Maybe you can join our WeChat Group, will be easier to discuss it.

**Comment by chiikin** [comment]
扫描了微信，申请添加好友了，通过一下？
