### ISSUE TITLE
[UI] The date type on the axis of the dashboard is not fully displayed

### ISSUE THREAD

**Issue by hanqian200705** [openobserve/openobserve#1043]
### Which OpenObserve functionalities are the source of the bug?

dashboards

### Is this a regression?

Yes

### Description

The date type on the axis of the dashboard is not fully displayed, 
and has not been converted to local time

<img width="1058" alt="image" src="https://github.com/openobserve/openobserve/assets/4269408/34213de4-28a3-4747-a693-64fade5aee67">

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version
v0.4.8
Commit Hash
5bfe67624415f0297c72c0e82ee0dbba156ba6f9
Build Date
2023-06-22T09:43:12Z
```

**Comment by ktx-kirtan** [comment]
Now it will check for the date format for the custom SQL for sample data, and if found will treat it as a time-series and format the data accordingly. 

This is completed with #1468
