### ISSUE TITLE
Enforce schema on every record  for traces

### ISSUE THREAD

**Issue by oasisk** [openobserve/openobserve#1044]
### Which OpenObserve functionalities are relevant/related to the feature request?

streams

### Description

We enforce schema on every record for logs ,should schema enforcement checks be added to:

- metrics
- traces
In case of attributes & service which are key value pairs of string , value , are flattened may cause wal file conversion to fail.

### Proposed solution

Enforce schema on every record  for metrics & traces

### Alternatives considered

NA

**Comment by hengfeiyang** [comment]
We don't need schema evolution for metrics, because in metrics every label value is a string. This is defined by Prometheus, everything is string.

**Comment by oasisk** [comment]
for traces every label value is a string, hence closing
