### ISSUE TITLE
Folders for dashboard

### ISSUE THREAD

**Issue by oasisk** [openobserve/openobserve#1053]
### Which OpenObserve functionalities are relevant/related to the feature request?

dashboards

### Description

We should support folders for dashboards like grafana :https://grafana.com/docs/grafana-cloud/infrastructure-as-code/grizzly/dashboards-folders-datasources/#add-a-folder

Single level folders

- [x]  Ui Enahncement
- [x] API changes

### Proposed solution

NA

### Alternatives considered

NA

**Comment by neha00290** [comment]
testing for this is complete. closing the same
