### ISSUE TITLE
Adding Field to query in logs page does not add where clause in SQL mode

### ISSUE THREAD

**Issue by ktx-kirtan** [openobserve/openobserve#1054]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

When we switch to the SQL mode, and try to add any fields to the query from the fields selection, it does not add where clause, it simply adds the `and field=value` 

[OpenObserve (3).webm](https://github.com/openobserve/openobserve/assets/124270523/65162881-7b2c-45c3-b890-f62cd2c37e3c)

**Comment by neha00290** [comment]
testing for this is complete.closing the same
