### ISSUE TITLE
ZO_INGEST_ALLOWED_UPTO feature at org level

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#1072]
### Which OpenObserve functionalities are relevant/related to the feature request?

ingestion

### Description

Historical data can be ingested upto 5 hours default and more by setting ZO_INGEST_ALLOWED_UPTO ) . This might be challenging if an organization in the same instance requires varying historical data ingestion.

### Proposed solution

User should be able to configure the maximum past time for which historical data can be ingested at organization level.

### Alternatives considered

setup a separate instance for each organization.

**Comment by hengfeiyang** [comment]
Why not remove it?

**Comment by prabhatsharma** [comment]
I think the reason we have this flag is that compactor does not work for older data, and it might cause inefficiency in storage and retrieval at s3 level.

**Comment by hengfeiyang** [comment]
no need
