### ISSUE TITLE
UI: metrics should use local time zone as logs page

### ISSUE THREAD

**Issue by chiikin** [openobserve/openobserve#1080]
### Which OpenObserve functionalities are the source of the bug?

metrics

### Is this a regression?

Yes

### Description

在指标的ui界面查询指标时，图表的时间轴时间显示为UTC时间，但实际使用更倾向于使用本地时间。
(When querying indicators on the indicator's ui interface, the time axis of the chart is displayed as UTC time, but the actual use is more inclined to use local time.)
![image](https://github.com/openobserve/openobserve/assets/21117413/a572109a-6298-49c4-909f-b2fcb5df51da)
![image](https://github.com/openobserve/openobserve/assets/21117413/e32ed41a-c541-4aaf-8f3f-bf3fde60ca5d)
如图所示，使用的时候看时间很不方便，容易造成误解
(As shown in the picture, it is inconvenient to check the time when using it, and it is easy to cause misunderstanding)

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version
Commit Hash
Build Date
v0.5.0
ac7214c1e75fc38f438a8019e1e35c90d5f3b19a
2023-06-28T17:04:08Z
```

**Comment by gaby** [comment]
Related #473
