### ISSUE TITLE
Allow VRL functions on unflattened data during ingestion

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#1081]
### Description

Sometimes it is important to be able to apply VRL functions on unflattened data during ingestion. Processing arrays is one use case - https://github.com/openobserve/openobserve/issues/1074

### Proposed solution

Allow applying VRL functions on unflattened data as an option when needed.

### Alternatives considered

none

**Comment by hengfeiyang** [comment]
We discussed this earlier, we have two solutions:
1. give VRL function the original record, this can achieve you request
2. give VRL function flatten record, this is what we did, because we want user use the data they can see in the logs UI

**Comment by prabhatsharma** [comment]
> * give VRL function the original record, this can achieve you request
> * give VRL function flatten record, this is what we did, because we want user use the data they can see in the logs UI

We will need to support both as both use cases are very valid.
