### ISSUE TITLE
The API for pushing traces does not support "content-type: application/json; charset=utf-8"

### ISSUE THREAD

**Issue by chiikin** [openobserve/openobserve#1090]
### Which OpenObserve functionalities are the source of the bug?

traces

### Is this a regression?

Yes

### Description

我通过API  POST `/api/{org_id}/traces` 推送http/json格式的trace时使用了`content-type: application/json; charset=utf-8`的http header头，但接口返回了 `Bad Request`.只有当 HTTP header为`content-type: application/json`时API才返回 200.

(translation: I used the content-type: application/json; charset=utf-8 http header when I pushed the trace in http/json format through API POST /api/{org_id}/traces, but the interface returned Bad Request. Only when HTTP The API returns 200 only when the header is content-type: application/json.)

通过排查代码我发现，在源代码文件`/src/handler/http/request/traces/mod.rs`中发现，对http header`content-type`的判定限定为`application/json`，导致该http header包含`charset=utf-8`时返回了`Bad Request`.源代码截图如下 

(translation: By checking the code, I found that in the source code file `/src/handler/http/request/traces/mod.rs`, the determination of the http header `content-type` is limited to `application/json`, resulting in the http `Bad Request` is returned when the header contains `charset=utf-8`. The screenshot of the source code is as follows)：
![image](https://github.com/openobserve/openobserve/assets/21117413/d52df5a3-5132-4f2e-9cee-53cd993146b7)

我希望能够兼容`content-type: application/json; charset=utf-8`

**Comment by oasisk** [comment]
https://github.com/openobserve/openobserve/blob/31d4ad7d075288367ca9ae97b3bace1dabce346b/src/handler/http/request/traces/mod.rs#L43 replace eq with starts_with

**Comment by hengfeiyang** [comment]
fixed
