### ISSUE TITLE
S3 configuration with aws force default profile

### ISSUE THREAD

**Issue by gaetronik** [openobserve/openobserve#1099]
### Which OpenObserve functionalities are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

When connecting to s3, openobserve use default profile https://github.com/openobserve/openobserve/blob/main/src/infra/storage/remote.rs#L190 . It implies such a profile exists to gather credentials and it prevents simple s3 access through instance profile in aws.

### Please provide the exception or error you saw

```true
Error listing: Generic { store: "S3", source: CredentialsNotLoaded(CredentialsNotLoaded { source: NoProfilesDefined }) }'
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.4.8
Commit Hash: 5bfe67624415f0297c72c0e82ee0dbba156ba6f9
Build Date: 2023-06-22T09:15:57Z
```

### Anything else?

aws_profile has been deprecated by object_store crate.
profile can be set optionally with the presence of an environment variable.
The workaround for my use case is to set HOME environment variable in the systemd unit and create a `$HOME/.aws/config` file with the following content:
```
[default]
region = eu-west-1
credential_source=Ec2InstanceMetadata
```
Thanks for the work on this software I greatly appreciate

**Comment by hengfeiyang** [comment]
thanks, we already remove `aws_profile`, will release it in next version.

**Comment by oasisk** [comment]
profiles are not supported, as object_store has removed support for profiles

**Comment by hengfeiyang** [comment]
@gaetronik  we are not support profile now, Can you try use ENV for s3

**Comment by gaetronik** [comment]
Thanks for your answer, if `aws_profile` was removed I guess we can close the issue
