### ISSUE TITLE
Dropdown fields for conditions are not updated when trying to update an alert

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#1102]
### Which OpenObserve functionalities are the source of the bug?

alerts

### Is this a regression?

Yes

### Description

<img width="1012" alt="image" src="https://github.com/openobserve/openobserve/assets/4242188/64a15155-5f5e-4b2c-b4ae-f9cd5c6d46b3">

**Comment by omkarK06** [comment]
This has been resolved by #1167
