### ISSUE TITLE
Inline comments are being sent out as part of the query in the promql tab

### ISSUE THREAD

**Issue by ansrivas** [openobserve/openobserve#1103]
### Which OpenObserve functionalities are the source of the bug?

metrics

### Is this a regression?

No

### Description

Inline comments are being sent out as a part of the query, this results in an `invalid promql error` from the server.
This doesn't contain any further information about the exact error for the query.

But if you remove the comments, the server returns the exact error the invalid query.

- Invalid query with inline comments
  ![query_with_comments](https://github.com/openobserve/openobserve/assets/1695056/791c8534-a4ff-4173-a307-f525459a8814)

- Request being sent:

  ![request_being_sent](https://github.com/openobserve/openobserve/assets/1695056/4810f21e-ff26-49fe-be18-49b6f57b2eb1)

- Querying without inline comments:

![query_without_comments](https://github.com/openobserve/openobserve/assets/1695056/33b9367e-b98a-4e75-8ddb-28ac168a85f7)

**Comment by prabhatsharma** [comment]
should comments be handled on server side? Also official prefix for promql comments is `#` that should be available in editor
