### ISSUE TITLE
UI: Keep the dashboard menu open

### ISSUE THREAD

**Issue by hanqian200705** [openobserve/openobserve#1106]
### Which OpenObserve functionalities are relevant/related to the feature request?

dashboards

### Description

After opening a dashboard, switching to other menus and then back to the dashboard menu, hope to return to the last opened dashboard instead of returning to the dashboard list

### Proposed solution

return to the last opened dashboard

### Alternatives considered

no

**Comment by bjp232004** [comment]
If the user will click the "Dashboard" link on the left navigation then it will take to the Dashboard list page but if the user uses the "Back" button on the browser/keyboard it will take to the last screen.
