### ISSUE TITLE
Properly handle 429 Too Many Requests from S3

### ISSUE THREAD

**Issue by MOZGIII** [openobserve/openobserve#1107]
### Which OpenObserve functionalities are the source of the bug?

ingestion

### Is this a regression?

No

### Description

My S3 (Scaleway) asks openobserve to slow down, but it crashes instead of just complying.

### Please provide the exception or error you saw

```true
thread 'tokio-runtime-worker' panicked at 'file list remote cache failed: Load file_list err: Generic S3 error: Error performing get request file_list/2023/07/06/04/7082591794764075008.json.zst: response error "<?xml version="1.0" encoding="UTF-8"?>
<Error>
<Code>Too Many Requests</Code>
<Message>Too Many Requests</Message>
</Error>

", after 0 retries: HTTP status client error (429 Too Many Requests) for url (https://s3.nl-ams.scw.cloud/openobserve/file_list/2023/07/06/04/7082591794764075008.json.zst)

Caused by:
0: Error performing get request file_list/2023/07/06/04/7082591794764075008.json.zst: response error "<?xml version="1.0" encoding="UTF-8"?>
<Error>
<Code>Too Many Requests</Code>
<Message>Too Many Requests</Message>
</Error>

", after 0 retries: HTTP status client error (429 Too Many Requests) for url (https://s3.nl-ams.scw.cloud/openobserve/file_list/2023/07/06/04/7082591794764075008.json.zst)
1: response error "<?xml version="1.0" encoding="UTF-8"?>
<Error>
<Code>Too Many Requests</Code>
<Message>Too Many Requests</Message>
</Error>

", after 0 retries: HTTP status client error (429 Too Many Requests) for url (https://s3.nl-ams.scw.cloud/openobserve/file_list/2023/07/06/04/7082591794764075008.json.zst)
2: HTTP status client error (429 Too Many Requests) for url (https://s3.nl-ams.scw.cloud/openobserve/file_list/2023/07/06/04/7082591794764075008.json.zst)

Stack backtrace:
0: <unknown>
1: <unknown>
2: <unknown>
3: <unknown>
4: <unknown>
5: <unknown>
6: <unknown>
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
OpenObserve v0.4.6
```

**Comment by hengfeiyang** [comment]
When we load file_list into memory we use multiple thread workers, by default the threads num is equal to: CPU NUM * 4. And you can control it by: `ZO_QUERY_THREAD_NUM=4`

And we haven't got this error before, can you give some details:

1. how many CPU do you have
2. how many files OpenObserve report when it loads file_list
3. do you know your s3(Scaleway) default request limit

Please use v0.5.0, it will report more details. Thanks

**Comment by MOZGIII** [comment]
1. 4 CPUs (num threads should thus be 16); but I have a k8s cpu limit of `1500m`, so the reported amount will likely be 2 CPUs, and thus 8 threads.
2. will check later once I update to 0.5, can't seem to find this at 0.4.6
3. I can't find it documented anywhere. Googling suggests it's about 250 per second, but it might be reported in the response headers.

Here's the docs: https://www.scaleway.com/en/docs/faq/new-object-storage-classes/

**Comment by hengfeiyang** [comment]
```
250 per second
```
Yes, it's a pretty low limitation, you can try to increase it, or, you can set `ZO_QUERY_THREAD_NUM=4` limit the thread num. to reduce request speed.

**Comment by MOZGIII** [comment]
How does threading work though? Each thread makes one request and waits for it to complete and then starts the next one? If so, the throughput overall they'll be yielding would be latency-dependent, which is not ideal for rate limiting.
Another option of how it could be working is that each thread could be submitting async tasks for requests, in which case the overall throughput wouldn't be bounded at all even with just a single thread. It is easily possible to submit 1000 requests momentarily and for all of them to complete in less than 1000 ms - thus exceeding the alleged 250 rps limit.

So, would be great if you could elaborate a bit more on how the execution model looks here.

**Comment by MOZGIII** [comment]
Also, why would I tweak the `ZO_QUERY_THREAD_NUM`? The `ZO_FILE_MOVE_THREAD_NUM` seems to be a more relevant variable.

**Comment by hengfeiyang** [comment]
for example:

we have 1000 files needs to be load, and the CPU NUM is 2, then thread_num = 2 * 4 = 8.

we will create at most 8 threads to concurrent request files, one thread done(one file process done) the thread quit. then create another thread to request another file.

at the same time we keep at most 8 threads. but if request one file only need 10ms, then it can process 100 files in one second. and 8 threads can process 800 files in one second. 

ps: the thread is tokio green thread, like gorutine in golang.

**Comment by hengfeiyang** [comment]
`ZO_FILE_MOVE_THREAD_NUM` used to control the thread convert json file to parquet file and upload to s3.

`ZO_QUERY_THREAD_NUM` used to load files from s3.

**Comment by MOZGIII** [comment]
So, async with bounded concurrency, got it. I'm pretty sure I'll need to downgrade the `ZO_QUERY_THREAD_NUM`/`ZO_FILE_MOVE_THREAD_NUM` to `1` to even have a chance of not hitting the 250 rps, as I estimate the latency to be around 3 ms for those requests, which is less then 4 ms which would just saturate 250 rps with this model.

I've seen the error in the ingester - so it has to be `ZO_FILE_MOVE_THREAD_NUM`, but I'll alter the `ZO_QUERY_THREAD_NUM` too just to be safe.

Also, any chance to have a more explicit rate limits support implemented? Or, maybe a more explicit request throughput bounding?

**Comment by hengfeiyang** [comment]
we only have `ZO_FILE_MOVE_THREAD_NUM` and `ZO_QUERY_THREAD_NUM` to limit the concurrency request of s3.

but have no explicit rate limits. like one second only fire 10 requests. it is based on CPU & network speed, if you have a powerful CPU and a fast network, maybe 1 second can process 100 requests.

**Comment by MOZGIII** [comment]
Yes, this is obviously the situation that I am facing. It makes openobserve actually completely unusable.

**Comment by hengfeiyang** [comment]
In our side, you can try increase:

```
ZO_MAX_FILE_SIZE_ON_DISK=32
ZO_MAX_FILE_RETENTION_TIME=600
```

to increase the file size and then reduce the file num. maybe it can reduce the qps for s3.

Can you try to increase your s3 limitation?
