### ISSUE TITLE
Add support for disaster recovery in local mode

### ISSUE THREAD

**Issue by gaetronik** [openobserve/openobserve#1108]
### Which OpenObserve functionalities are relevant/related to the feature request?

other

### Description

Even if one do not need high-availability, it could be helpful to have a way to backup openobserve to be able to recreate it in case of a disaster.
If I understand correctly, when in ha with etcd backup and configuration backup it should be fine. (Maybe it's worth adding to the documentation).
In local mode, data can be backed up using whatever backup tool (or put in an object storage) but I'm not sure backing up the sled db directory will lead to a consistent state. A way to backup this database could be helpful.
Maybe something like that exists and I didn't get it from the documentation

### Proposed solution

An API endpoint which triggers a sled.export serialized in a format that could be passed as a launch parameter in case of disaster recovery

### Alternatives considered

* Catching a signal like USR1 to create the backup
* A script to recreate database from storage
* Storing snapshot of DB in storage

**Comment by oasisk** [comment]
Not on roadmap
