### ISSUE TITLE
Implement Heatmap Chart Type in dashboards

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#1111]
### Which OpenObserve functionalities are relevant/related to the feature request?

dashboards

### Description

OpenObserve currently lacks the ability to visually represent complex multi-dimensional data in a format that is easy to understand and analyze. This restricts our capacity to provide a comprehensive overview of certain data patterns and correlations.

### Proposed solution

I propose the implementation of a heatmap chart type into OpenObserve. Heatmaps would allow us to display and analyze multi-dimensional data effectively, enhancing the overall data visualization capabilities.

A heatmap chart is especially useful in representing high-volume data and discerning patterns, correlations, and trends at a glance. They use a system of color-coding to represent different values, which makes the data more understandable and insightful.

### Alternatives considered

na

**Comment by ktx-kirtan** [comment]
Heatmap is implemented with the #1468
