### ISSUE TITLE
General feedback and potentially a bug or two

### ISSUE THREAD

**Issue by wiardvanrij** [openobserve/openobserve#1112]
### New rollout caused files to be missing in S3 (temporary?)

For some reason after a rollout I had a ton of logs saying things like:
```
[2023-07-05T12:44:26Z ERROR openobserve::service::db::file_list] service:db:file_list: add files/default/logs/default/2023/07/05/11/7082323592104538112AlU1DL.parquet, download error: Object at location files/default/logs/default/2023/07/05/11/7082323592104538112AlU1DL.parquet not found: response error "<?xml version="1.0" encoding="UTF-8"?>
    <Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>files/default/logs/default/2023/07/05/11/7082323592104538112AlU1DL.parquet</Key><RequestId>JZAA075W7HR7197H</RequestId><HostId>GXai9hJ3+pgyRHK4fhbAGPqdqY0yQEzGp9WzZhYyacWd0jdROyO3DP1vH692GvYQ5oCJ/uj4tgA=</HostId></Error>", after 0 retries: HTTP status client error (404 Not Found) for url (https://s3.us-west-2.amazonaws.com/xxxxxxxx/files/default/logs/default/2023/07/05/11/7082323592104538112AlU1DL.parquet)
```

Then on the query path, it also gave errors on saying "parquet file missing" which basically made a specific time range un-queryable. However, I tried to reproduce it today by doing queries on that time range and now it magically works. 

### CPU number calculation on K8s is using node host instead of the pod CPU's

Pods use the nodes cpu number instead of the request/limit or some other factor to calculate the amount of threads. Personally I've seen that the default for `ZO_QUERY_THREAD_NUM` is basically number of cores * 4, so I could define this manually. It would be nice if the calculation would account for containers.

Also, I'm wondering if memory related env vars are doing the same thing. 

### Memory cache

```
  ZO_MEMORY_CACHE_ENABLED: "true"
  ZO_MEMORY_CACHE_CACHE_LATEST_FILES: "false"
  ZO_MEMORY_CACHE_MAX_SIZE: "7000"
  ZO_MEMORY_CACHE_RELEASE_SIZE: "0"
```

I'm at the moment using these values. What I basically want to achieve is that there is some baseline on memory usage on queriers and if needed I will scale horizontally. Yet if I look at the actual usage of the queriers, they seem to be exceeding the amount of cache. 

<img width="1728" alt="image" src="https://github.com/openobserve/openobserve/assets/5786097/7c2cd7d9-b137-4856-a527-12e1d8f9e73d">

If anything I would expect most of them to stay around 7GB (my cache size) and potentially use _a bit_ more during query time. So from a user point of view, I want to "limit" memory usage in a way so that individual pods don't go to high vertically. Ideally it would be nice to know that if the cache size is 7GB, pods will never exceed 10GB. Basically my question here is, why is one using 14GB memory idle? 

### Too much memory usage causes connectivity issues?

I tested with 

```
  ZO_MEMORY_CACHE_ENABLED: "true"
  ZO_MEMORY_CACHE_CACHE_LATEST_FILES: "true"
  ZO_MEMORY_CACHE_MAX_SIZE: "7000"
  ZO_MEMORY_CACHE_RELEASE_SIZE: "400"
```

and this caused the cache to be instantly fill but more importantly, **it stopped connectivity to my pods**. I think there is a bug somewhere that kills something when it can't handle its memory properly. Pods were running healthy but it was impossible to reach them. After moving back to my previous settings it worked again. Unfortunately, I don't have much more data/debug stuff to show/tell.

### General memory management

I guess the gist of the whole cache/memory part here is that it's either I lack knowledge (and thus docs) to implement it properly and potentially a combination of maybe some bugs or misunderstandings. 
What I really would like is to know better on what would be appropriate settings and what would be good settings to scale performance more. 

The thing is also that I could potentially say: "well, lets cache a lot" - but perhaps my ingest rate is so high that even if I would cache 500GB, the cache would hardly ever get hit due to amount of various requests over time being made. Having insights in cache hits (thus cache performance) would be great. 

Likewise having some more information on the settings would be ideal. 

### Make the stream page easier readable

<img width="1728" alt="image" src="https://github.com/openobserve/openobserve/assets/5786097/9dcf81ed-3d1c-4340-b25b-df803abe3325">

This is pretty hard to read. The detail page is already much nicer, but quite frankly, just having GB's/TBs and such would perhaps even be better

<img width="818" alt="image" src="https://github.com/openobserve/openobserve/assets/5786097/db990f1d-4247-4181-9bfa-ea08d612d4ba">

### Allow me to copy query performance result

I'm unable to select and thus copy this part of text, which would be great if I could

<img width="818" alt="image" src="https://github.com/openobserve/openobserve/assets/5786097/693a7370-8e97-4df0-af69-9e376cfbc6c8">

### Keep "waiting for response" popup until there is a response

When doing larger queries that might take like 20 seconds, it would be great if the UI would be more 'responsive' to the fact that it's still loading. The popup about 'waiting for response' just goes away after a few seconds, regardless if the response is there already

### Just some things about the helm chart

tbh if we continue ourselves with openobserve I can make some MRs but figured to already dump some info about it;

- Don't use latest tag on the image :) 
- replicaCount are not implemented everywhere and/or simply don't work
- HPA doesn't work either (wrong selector I guess)
- `resources` are defined globally and not per component, which IMHO doesn't make sense. You want to give each component their own resources.

**Comment by wiardvanrij** [comment]
Just one correction/addition to memory usage. 

I made a booboo in my chart and it basically doubled the values... so the memory usage is actually correct and more in line at what I would have expected :) 

Updated:

<img width="1718" alt="image" src="https://github.com/openobserve/openobserve/assets/5786097/8bcd0bb8-2006-4e7a-9e69-913942b02802">

**Comment by hengfeiyang** [comment]
```
[2023-07-05T12:44:26Z ERROR openobserve::service::db::file_list] service:db:file_list: add files/default/logs/default/2023/07/05/11/7082323592104538112AlU1DL.parquet, download error: Object at location files/default/logs/default/2023/07/05/11/7082323592104538112AlU1DL.parquet not found: response error "<?xml version="1.0" encoding="UTF-8"?>
    <Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>files/default/logs/default/2023/07/05/11/7082323592104538112AlU1DL.parquet</Key><RequestId>JZAA075W7HR7197H</RequestId><HostId>GXai9hJ3+pgyRHK4fhbAGPqdqY0yQEzGp9WzZhYyacWd0jdROyO3DP1vH692GvYQ5oCJ/uj4tgA=</HostId></Error>", after 0 retries: HTTP status client error (404 Not Found) for url (https://s3.us-west-2.amazonaws.com/xxxxxxxx/files/default/logs/default/2023/07/05/11/7082323592104538112AlU1DL.parquet)
```

Fixed in #1172

**Comment by hengfeiyang** [comment]
```
  ZO_MEMORY_CACHE_CACHE_LATEST_FILES: "true"
```

We found the issue about this, will do more tests about it, I suggest disabling this option for now.

**Comment by hengfeiyang** [comment]
We found ehe issue of `ZO_MEMORY_CACHE_CACHE_LATEST_FILES: "true"` related to #1934 

that is just fixed. now we can close this issue.
