### ISSUE TITLE
no Float support?

### ISSUE THREAD

**Issue by JustinGuese** [openobserve/openobserve#1118]
### Which OpenObserve functionalities are the source of the bug?

ingestion

### Is this a regression?

Yes

### Description

When trying to curl post a float it says "can't cast to int64"... do you really not offer float support?

Failed to cast portfolio_usd to type Int64 Failed to cast portfolioworth to type Int64 . document: {'botName': 'rsi-bot-AAPL', 'portfolioWorth': 10487.336892163861, '@timestamp': 1688714662174.292, 'pctPerYear': 6, 'portfolio.USD': 10487.336892163861, 'portfolio.AAPL': 0.0}

### Please provide the exception or error you saw

```true
Failed to cast portfolio_usd to type Int64 Failed to cast portfolioworth to type Int64 . document: {'botName': 'rsi-bot-AAPL', 'portfolioWorth': 10487.336892163861, '@timestamp': 1688714662174.292, 'pctPerYear': 6, 'portfolio.USD': 10487.336892163861, 'portfolio.AAPL': 0.0}
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version
Commit Hash
Build Date
v0.5.0
ac7214c1e75fc38f438a8019e1e35c90d5f3b19a
2023-06-28T17:30:46Z
```

**Comment by hengfeiyang** [comment]
Because default we infer data type of the field use the first record. maybe your first record of the field the data type is int64.
Next, you give a float64, we can't store the value as an int64.

To resolve this, we have a feature, schema evolution. you can add an option like this:

```
ZO_WIDENING_SCHEMA_EVOLUTION=true
```

After enabling this, will allow different data type ingestion.

**Comment by JustinGuese** [comment]
I just deleted the index and inserted again, same result
 Openobserve index failed. Failed to cast portfolioworth to type Int64 Failed to cast portfolio_usd to type Int64 . document: {'botName': '10day-sharpeopt-v1', 'portfolioWorth': 7826.834938301372, '@timestamp': 1688718382340, 'pctPerYear': -261, 'portfolio.USD': -0.16, 'portfolio.VAW': 12.2, 'portfolio.TSLA': 7.65, 'portfolio.L0CK.DE': 0.03, 'portfolio.BTEC.L': 100.17, 'portfolio.VHT': 12.36, 'portfolio.W1TA.DE': 65.27}

**Comment by hengfeiyang** [comment]
I tested no problem:

```curl
curl --request POST \
  --url http://localhost:5080/api/default/test2/_json \
  --header 'Authorization: Basic cm9vdEBleGFtcGxlLmNvbTpDb21wbGV4cGFzcyMxMjM=' \
  --header 'Content-Type: application/json' \
  --data '[
	{
		"botName": "10day-sharpeopt-v1",
		"portfolioWorth": 7826.834938301372,
		"@timestamp": 1688718382340,
		"pctPerYear": -261,
		"portfolio.USD": -0.16,
		"portfolio.VAW": 12.2,
		"portfolio.TSLA": 7.65,
		"portfolio.L0CK.DE": 0.03,
		"portfolio.BTEC.L": 100.17,
		"portfolio.VHT": 12.36,
		"portfolio.W1TA.DE": 65.27
	}
]'
```

- Did you only ingest one record? 
- Is this the first record?
- Did you enable `ZO_WIDENING_SCHEMA_EVOLUTION`

**Comment by JustinGuese** [comment]
yes it was the first record, but I submitted it with python requests, maybe there's an issue... But after enabling the widening schema evolution it works
