### ISSUE TITLE
Dashboard update API creates a new blank dashboard

### ISSUE THREAD

**Issue by ktx-kirtan** [openobserve/openobserve#1119]
### Which OpenObserve functionalities are the source of the bug?

dashboards

### Is this a regression?

Yes

### Description

When we call the update dashboard API, and the update object does not have the `dashboardId`, in that case it creates the new dashboard with blank `dashboardId` with all other information as the blank details. And while deleting without a dashboard id, there is no way of deleting that dashboard.

**Comment by oasisk** [comment]
with latest release & fixes , works fine
