### ISSUE TITLE
Make text size and font in side panel table and json consistent with expanded record view

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#1122]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

<img width="683" alt="image" src="https://github.com/openobserve/openobserve/assets/4242188/d2df6144-a815-40b0-a308-02b7d5853777">

and 

<img width="923" alt="image" src="https://github.com/openobserve/openobserve/assets/4242188/036993e0-caf6-4e01-9b29-4f8ff21905f2">

have very different fonts and sizes. Also spacing between lines is a lot higher leading to real estate wastage.

**Comment by omkarK06** [comment]
This has been resolved.
