### ISSUE TITLE
side panel json view should be same as expanded view

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#1123]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

<img width="855" alt="image" src="https://github.com/openobserve/openobserve/assets/4242188/8245bf7c-6d43-403d-867c-cc80588b0ee9">

should be same as 

<img width="913" alt="image" src="https://github.com/openobserve/openobserve/assets/4242188/1dd5b96b-277e-460f-84a4-c38122878dee">

**Comment by omkarK06** [comment]
This issue is resolved.
