### ISSUE TITLE
Functions support Logs/Metrics/Traces 

### ISSUE THREAD

**Issue by domyway** [openobserve/openobserve#1126]
### Which OpenObserve functionalities are relevant/related to the feature request?

log search, functions, metrics, traces

### Description

Otel Collector has a [transformprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor) which  allows configuring multiple context statements for traces, metrics, and logs . For now, functions seems only support logs.  
I think if oo has a plan to make functions support  traces, metrics, and logs just like otel transformprocessor.

### Proposed solution

use Lua writes function is a good idea, but relevant documents is just not enough. 

### Alternatives considered

Not at the moment.

**Comment by oasisk** [comment]
@domyway 
We support similar functionality using functions for logs & metrics which are written using vrl (https://vector.dev/docs/reference/vrl/) ,check documentation at : https://openobserve.ai/docs/user-guide/functions/#what-are-functions.

We dont support functions yet for traces & syslogs.

Please check video https://youtu.be/zniTtQIfoo4

**Comment by hengfeiyang** [comment]
@oasisk Yes, the user knows that, he wants function support traces. i asked him create an issue for this.

**Comment by domyway** [comment]
any plan to support traces ?

**Comment by oasisk** [comment]
Fixed by https://github.com/openobserve/openobserve/pull/1671
