### ISSUE TITLE
Automatic query population of metrics name in query editor

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#1127]
### Which OpenObserve functionalities are relevant/related to the feature request?

metrics

### Description

Metrics explorer page allows selecting the metric name on the UI but it adds no functionality other than to show the labels.

<img width="389" alt="image" src="https://github.com/openobserve/openobserve/assets/4242188/80166b88-b094-41de-b12c-3b1329e00f0b">

### Proposed solution

I propose following:

1. When a metric name is selected from the drop down it should replace the code editor with the metric name. User can then run the query to get the results.
2. label list should allow selection of values similar to logs page that inserts the label name and/or associated value in the code editor.

### Alternatives considered

na

**Comment by omkarK06** [comment]
This issues has been resolved by #1167
