### ISSUE TITLE
two calls instead of one are made when you visit the metrics page

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#1129]
### Which OpenObserve functionalities are the source of the bug?

metrics

### Is this a regression?

Yes

### Description

<img width="1153" alt="image" src="https://github.com/openobserve/openobserve/assets/4242188/b252b621-9051-4882-ace0-e1788ec2c84f">

**Comment by omkarK06** [comment]
This issue has been resolved.
