### ISSUE TITLE
stream explorer header color should be in sync with other areas of app

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#1130]
### Which OpenObserve functionalities are the source of the bug?

streams

### Is this a regression?

Yes

### Description

<img width="1254" alt="image" src="https://github.com/openobserve/openobserve/assets/4242188/7b078469-c9e3-46e6-998e-113b9e7d2cb9">

**Comment by omkarK06** [comment]
This issue has been resolved.
