### ISSUE TITLE
Indicate the type of metric in metrics explorer

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#1131]
### Which OpenObserve functionalities are relevant/related to the feature request?

metrics

### Description

Currently the UI does not indicate if the metric type is counter, gauge, summary or histogram. A user will be better equipped to write the PromQL query if she knows what the metric type is.

<img width="550" alt="image" src="https://github.com/openobserve/openobserve/assets/4242188/bc4ae39e-c3bc-4bb1-8f8d-e1cd8045c801">

### Proposed solution

Provide indication of what is the metric type next to the metruic name in the drop down either as text or image

### Alternatives considered

na

**Comment by omkarK06** [comment]
This issue is resolved by #1167
