### ISSUE TITLE
VRL: Utf8 does not equal Null 

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#1132]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

trying to parse nginx logs using VRL results using below function results in error

function
```ruby
.nginx = parse_nginx_log!(.log, "ingress_upstreaminfo")
.
```

query editor
```sql
kubernetes_namespace_name='ingress-nginx'
```

error
```json
{
    "code": 10001,
    "message": "Server Internal Error",
    "error_detail": "Arrow error: Schema error: Fail to merge schema field 'kubernetes_annotations_checksum_config' because the from data_type = Utf8 does not equal Null"
}
```

**Comment by oasisk** [comment]
The function should be like : 
if (.stream =="stdout"){
.nginx = parse_nginx_log!(.log, "ingress_upstreaminfo")
}
if (.stream =="stderr"){
.nginx = parse_nginx_log!(.log, "error")
}
. 
https://vector.dev/docs/reference/vrl/functions/#parse_nginx_log
the formats are different ,hence need different handling
{"log":"10.128.0.22 - root@alpha1.com [21/Aug/2023:08:01:16 +0000] \"POST /api/billing_data_n022k41IUOT98m1/billings/_json HTTP/2.0\" 200 86 \"-\" \"Go-http-client/2.0\" 268 0.001 [ziox-alpha1-zo1-openobserve-router-5080] [] 10.28.6.249:5080 102 0.001 200 e3c8998b9238685f3c09b3bec04e98db","stream":"stdout"}

{"log":"2023/08/21 04:35:31 [warn] 717#717: *222268265 a client request body is buffered to a temporary file /tmp/nginx/client-body/0059542604, client: 10.128.0.48, server: alpha1.gke.zinclabs.dev, request: \"POST /api/production_n230k19AUNT56m0/prometheus/api/v1/write HTTP/2.0\", host: \"alpha1.gke.zinclabs.dev\"","stream":"stderr"}

Fix is part of https://github.com/openobserve/openobserve/pull/1405/

**Comment by oasisk** [comment]
Fix is part of https://github.com/openobserve/openobserve/pull/1405

Additionally the function should be :
if (.stream =="stdout"){
.nginx = parse_nginx_log!(.log, "ingress_upstreaminfo")
}
if (.stream =="stderr"){
.nginx = parse_nginx_log!(.log, "error")
}
.
https://vector.dev/docs/reference/vrl/functions/#parse_nginx_log , as the formats are different ,need different handling

**Comment by hengfeiyang** [comment]
@prabhatsharma And you can write the VRL function like this to avoid printing many errors:

```
.nginx, _ = parse_nginx_log(.log, "ingress_upstreaminfo")
.
```
