### ISSUE TITLE
progress indicator for query execution

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#1134]
### Which OpenObserve functionalities are relevant/related to the feature request?

log search

### Description

Currently when you start to run a query there is a pop up that appears which says `Waiting for response` and goes away. There is no indication on the screen if the query is running until you get the response.

### Proposed solution

Displaying an hourglass or something similar as progress indicator will be greatly useful for the user.

### Alternatives considered

na

**Comment by omkarK06** [comment]
This issues is resolved by #1167
