### ISSUE TITLE
ability to copy a value from the table

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#1135]
### Which OpenObserve functionalities are relevant/related to the feature request?

log search

### Description

Currently we can filter for a value using `=` and `!=` hover icons when you need the field value.
<img width="287" alt="image" src="https://github.com/openobserve/openobserve/assets/4242188/e48d286b-8e83-499a-8249-78017741e9cc">

however if you want to copy the copy the field you just can't because clicking on it will open the side panel.

### Proposed solution

Provide an icon to copy the value.

### Alternatives considered

na

**Comment by omkarK06** [comment]
This issues has resolved.
