### ISSUE TITLE
Maxmind GeoIP support  in VRL

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#1138]
### Which OpenObserve functionalities are relevant/related to the feature request?

functions

### Description

Maxmind GeoIP databases as such cannot be exported to CSV because they do not contain IP addresses. They just contain IP address prefixes. There are no methods available in maxmind libraries that will allow a full export of the data.

### Proposed solution

We must support using GeoIP databases natively using VRL.

### Alternatives considered

none

**Comment by prabhatsharma** [comment]
Maxmind provides CSV files directly for download. Trying to automate downloading them now.

**Comment by oasisk** [comment]
maxmind data is registered automatically as "geoip" enrichment table , it can used during data enrichment

**Comment by hengfeiyang** [comment]
@oasisk Can you give an example or write a document how to use it? thank you.
