### ISSUE TITLE
Flatten nested dictionaries by concatenating dictionary keys with "." instead of "_"

### ISSUE THREAD

**Issue by mrpk1906** [openobserve/openobserve#1161]
### Which OpenObserve functionalities are relevant/related to the feature request?

ingestion

### Description

OpenObserve flattened nested JSON key by concatenating with `_`
It's confused with another key containing `_`. So, I can't unpack to get the correct key.

* Sample JSON

```json
{
  "acl": "WHITELIST,",
  "agent": {
       "hostname": "test",
       "log_type": "haproxy"
  },
  "backend": "be_webserver",
  "cf_c_ip": "-",
  "client_ip": "127.0.0.1",
  "host": "localhost",
  "method": "GET",
  "path": "/server-status",
  "protocol": "HTTP/1.1",
  "referer": "-",
  "request_length": "-",
  "response_code": "200",
  "user_agent": "Monit/5.31.0",
  "x_real_ip": "127.0.0.1"
}
```

* Flattened

```json
{
  "acl": "WHITELIST,",
  "agent_hostname": "test",
  "agent_log_type": "haproxy",
  "backend": "be_webserver",
  "cf_c_ip": "-",
  "client_ip": "127.0.0.1",
  "host": "localhost",
  "method": "GET",
  "path": "/server-status",
  "protocol": "HTTP/1.1",
  "referer": "-",
  "request_length": "-",
  "response_code": "200",
  "user_agent": "Monit/5.31.0",
  "x_real_ip": "127.0.0.1"
}
```

Elasticsearch (example in screenshot below) and [VictoriaLogs](https://docs.victoriametrics.com/VictoriaLogs/keyConcepts.html#data-model) are also using `.` instead of `_`

![Screenshot 2023-07-12 at 16 23 18](https://github.com/openobserve/openobserve/assets/2736743/466d5b7c-2a0a-4763-a1de-22698cdddbf7)

### Proposed solution

Use `.` instead of `_`

### Alternatives considered

NA

**Comment by oasisk** [comment]
Underlying engine apache arrow datafusion doesn't support ".", hence we will not support "."
