### ISSUE TITLE
Log search: Duplicate filter criteria if click multiple to "Include Term" or "Exclude Term"

### ISSUE THREAD

**Issue by mrpk1906** [openobserve/openobserve#1180]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

When I click **Include Term** or **Exclude Term**, **Query Editor** show duplicate filter criteria

![Screenshot 2023-07-14 at 09 34 16](https://github.com/openobserve/openobserve/assets/2736743/5767577d-db2d-4c52-b7ab-0860650a30fb)

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.5.0
Commit Hash: ac7214c1e75fc38f438a8019e1e35c90d5f3b19a
Build Date: 2023-06-28T17:04:44Z
OS: linux x64
```

### Anything else?

No

**Comment by hengfeiyang** [comment]
Yes, it works like this.
