### ISSUE TITLE
Need to support to modify the log content in the openobserve.

### ISSUE THREAD

**Issue by jerrypjy** [openobserve/openobserve#1182]
### Which OpenObserve functionalities are relevant/related to the feature request?

log search

### Description

It seems not support to modify the items of log which already saved to the openobserve. It is only support to search.
We have three detail requirements as below:
1 We want to add one field in the existing log, 
2. We want to modify one field value of one log. 
3. We want to clean some logs.
There are not supported to do that with the openobserve sql, but there are supported in the elasticsearch.

### Proposed solution

1 We want to add one field in the existing log, 
2. We want to modify one field value of one log. 
3. We want to clean some logs.

### Alternatives considered

N/A

**Comment by prabhatsharma** [comment]
Why do you want to modify? What kind of data is it?

**Comment by jerrypjy** [comment]
@prabhatsharma 
For some logs, we want to dismiss them.
So we perfer to add one field of "dismiss“, and then we can change the value. the kind should be bool.

**Comment by oasisk** [comment]
@jerrypjy you can use functions to enrich data , you can try such functions during query..after exploration you can associate functions with stream & enrich/drop data.

Check : https://www.youtube.com/watch?v=zniTtQIfoo4

**Comment by prabhatsharma** [comment]
@jerrypjy  I don't think that we will have support for modifying existing data in openobserve anytime soon (or ever). You can follow functions approach from @oasisk to modify the streaming data while its getting ingested in OpenObserve
