### ISSUE TITLE
When an alias is set for a column in the SELECT statement, the deduplication operation fails.

### ISSUE THREAD

**Issue by chiikin** [openobserve/openobserve#1210]
### Which OpenObserve functionalities are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

When I execute the following SQL, the returned result is not deduplicated：
`select distinct host as zo_group_key from 'mem_used' order by zo_group_key `
result:
```plantext
aaa
aaa
bbb
bbb
ccc
ccc
```
I found that when an alias is set, it will result in an error, whereas without an alias, it is correct.

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version
Commit Hash
Build Date
v0.5.1
d85ceed0f3eab14b47bc70ac2e958bcfd3937fd0
2023-07-15T17:40:36Z
```

**Comment by hengfeiyang** [comment]
Please use:
```
select (distinct host) as zo_group_key from 'mem_used' order by zo_group_key 
```

**Comment by hengfeiyang** [comment]
fixed
