### ISSUE TITLE
Cannot specify multiple etcd hosts of a cluster

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#1212]
### Which OpenObserve functionalities are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

We can't specify multiple hosts of a HA etcd today. We should be able able to specify multiple hosts like.

`ZO_ETCD_ADDR` can accept a single host as value.

e.g. ZO_ETCD_ADDR = "localhost:2379"

We need to be able to provide

ZO_ETCD_ADDR=[ "host1:2379", "host2:2379", "host3:2379"]

The below code may need changes.

https://github.com/openobserve/openobserve/blob/2f41cda22e81cf3ed560463fbf4862636972c9d3/src/common/infra/db/etcd.rs#L433

**Comment by hengfeiyang** [comment]
will release v0.5.2

**Comment by hengfeiyang** [comment]
You can set it in v0.5.2 like this：
```
ZO_ETCD_ADDR = "localhost:2379,localhost:2378"
```
