### ISSUE TITLE
【UI】Comma is automatically added at the end of the log details field.

### ISSUE THREAD

**Issue by Mashull** [openobserve/openobserve#1213]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

A comma is automatically added at the end of the log details field， which will cause trouble for the content of the log itself being changed
![cc275e7892e7273e4fb6cc45d7dfc33](https://github.com/openobserve/openobserve/assets/118787336/436da962-d857-478a-a01f-f93d42d66199)

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: 0.5.1
```

**Comment by omkarK06** [comment]
@Mashull Log is displayed in JSON so it has comma at the end.
