### ISSUE TITLE
[oss] Aliyun oss forbidden error 

### ISSUE THREAD

**Issue by ximply** [openobserve/openobserve#1215]
You are forbidden to list buckets.

But I have set "oss:ListBuckets".

**Comment by ximply** [comment]
https://openobserve.ai/docs/storage/#alibaba-oss-aliyun doc is wrong, ZO_S3_SERVER_URL would be bucket address but not endpoint address.

**Comment by ixiaoyi93** [comment]
@ximply 你用OSS成功了吗？贴一下配置呢，按照文档各种报错啊。
