### ISSUE TITLE
HA mode always advertises address of first network interface

### ISSUE THREAD

**Issue by chris-palmer99** [openobserve/openobserve#1216]
### Which OpenObserve functionalities are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

When activating OpenObserve in HA mode, each node advertises its web (5080) and grpc (5081) endpoints to the other nodes. However they always advertise http URLs containing the IP address of their first network interface. (The grpc traffic is between OO nodes; the etcd traffic is handled correctly by the explicit endpoint URL).

Our hosts all have multiple NICs, with the data paths being via VLANs on bonded high-speed interfaces. The first NIC is always a low-speed management interface which isn't appropriate for OO traffic.

We need the ability to override the current behaviour by specifying the IP address that is advertised to the other OO hosts. This address _could_ also be used for restricting binding, but that is not essential for us.

### Please provide the version you discovered this bug in (check about page for version information)

```true
v0.5.0
linux x64
```

**Comment by hengfeiyang** [comment]
will release in v0.5.2

**Comment by hengfeiyang** [comment]
Now you can use:
`ZO_HTTP_ADDR=1.1.1.1` and `ZO_GRPC_ADDR=1.1.1.1` to bind a network interface.
