### ISSUE TITLE
Dashboard QueryVariables enhancements

### ISSUE THREAD

**Issue by gaby** [openobserve/openobserve#1218]
### Which OpenObserve functionalities are relevant/related to the feature request?

dashboards

### Description

When adding a query variable it requires the user to add a  `where clause` to each panel. 

Unlike Kibana where adding a filter of any kind auto filters the data on each panel. I currently have like 8-12 panels, I will have to modify each one by adding custom queries to even try this out, this is not very UX friendly. 

I currently have a test environment with +100 containers sending data, when adding the QueryVariable to the dashboard only like 10-15 values show up, there's no way to type/search on that dropdown.

### Proposed solution

- [x] Auto filter the data on each panel without the user having to add a custom SQL on each panel.
- [x]  Allow typing/searching in the QueryVariable dropdown

More information here: https://www.elastic.co/guide/en/kibana/current/add-controls.html#filter-the-data-with-options-list-controls

### Alternatives considered

N/a

**Comment by ktx-kirtan** [comment]
We have added the second currently `Allow typing/searching in the QueryVariable dropdown`. That you can now do.

Regarding the option `Auto filter the data on each panel without the user having to add a custom SQL on each panel.`, we are considering it as an enhancement. Will pick this up soon

**Comment by gaby** [comment]
@ktx-kirtan Any progress on this?

**Comment by prabhatsharma** [comment]
This is already there. I will create a video to provide guidance on this shortly.

**Comment by gaby** [comment]
@prabhatsharma That includes the auto filtering the data? Or is that still in progress.

**Comment by ktx-kirtan** [comment]
Yes that is done. You can try it out from the dev, enable dynamic filters fro the View Dashboard -> Settings -> General settings -> Enable Dynamic Filters.

**Comment by gaby** [comment]
@ktx-kirtan Is there a way this could be integrated into the regular Dashboard Query Variables dropdown?

For example: I always want dropdowns for Variables A, B, C. Right now if I add those and change the value it doesnt change the data. There's also no way in those to have "no value" selected, it always wants to filter by 1 value.
