### ISSUE TITLE
[OSS] Aliyun OSS 403 Forbidden

### ISSUE THREAD

**Issue by ximply** [openobserve/openobserve#1221]
When upgrade to v0.5.1, it does not work, get this error:
ERROR openobserve::job::files::disk] [JOB] Error while uploading disk file to storage Generic S3 error: response error.
<Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>

**Comment by hengfeiyang** [comment]
looks like you need a special algorithm? 

https://docs.rs/object_store/latest/object_store/aws/struct.AmazonS3Builder.html#method.with_checksum_algorithm

**Comment by ximply** [comment]
according to error messages，it looks like this: https://help.aliyun.com/zh/oss/support/0002-00000429?spm=a2c4g.11186623.0.0.71975dbdkPfmac

openobserve use Amazon S3 V4 but signature does not match Aliyun OSS

**Comment by ximply** [comment]
Do openobserve have any plans to fix it ？

**Comment by hengfeiyang** [comment]
It runs with aliyun oss and works well, some users are running with it. How do you configure it? Or you can join our wechat group for more detail.

**Comment by ximply** [comment]
Thanks, and how to join your wechat group ?

**Comment by hengfeiyang** [comment]
> Thanks, and how to join your wechat group ?

In Readme

**Comment by ximply** [comment]
I see it.

**Comment by ximply** [comment]
Docs error. Set ZO_S3_FEATURE_FORCE_PATH_STYLE = true, it works.
