### ISSUE TITLE
Not able to search with round bracket

### ISSUE THREAD

**Issue by bjp232004** [openobserve/openobserve#1225]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

User get error when tried to search with below string in match_all_ignore_case.

search string: search->file_list: time_range: Some((

**Comment by hengfeiyang** [comment]
@bjp232004 i tested with the sql:
```sql
SELECT * from test2 where match_all('search->file_list: time_range: Some((')
```

it works.

Can you help reproduce it?

**Comment by hengfeiyang** [comment]
I reproduced it, It got an error with the histogram. and fixed.
