### ISSUE TITLE
User name encoding issue

### ISSUE THREAD

**Issue by nerzhul** [openobserve/openobserve#1228]
### Which OpenObserve functionalities are the source of the bug?

home

### Is this a regression?

No

### Description

Look at the screenshot, there is a encoding issue on my name

### Anything else?

![image](https://github.com/openobserve/openobserve/assets/119752/a632dfe1-dc3f-4858-8252-104d629fde5c)

**Comment by bjp232004** [comment]
Hi,

Can you please verify this issue? We fixed this issue in weekend release.

**Comment by nerzhul** [comment]
i confirm it's better on your cloud instance
