### ISSUE TITLE
Dashboard: Add support for using Queries as filters

### ISSUE THREAD

**Issue by gaby** [openobserve/openobserve#1229]
### Which OpenObserve functionalities are relevant/related to the feature request?

dashboards

### Description

Currently you can only add a field ONCE as a filter when creating panels. While this works for most cases, in the case you want to filter for multiple things it wont work. 

Example:
- field[message] -> contains "some string"
- field[message] -> contains "a diff string"

### Proposed solution

Allow using Queries as a filter. That way I could use something like:

```
match_all('some string') or match_all('a diff string')
```

### Alternatives considered

N/a

**Comment by prabhatsharma** [comment]
This will come with https://github.com/openobserve/openobserve/pull/3957
