### ISSUE TITLE
Generated Authentication credentials don't work with traces sample on cloud.openobserve.ai 

### ISSUE THREAD

**Issue by artworx** [openobserve/openobserve#1231]
### Which OpenObserve functionalities are the source of the bug?

traces

### Is this a regression?

Yes

### Description

Using the example traces app.js from https://openobserve.ai/docs/ingestion/traces/nodejs/, I get an error after filling out the details from https://cloud.openobserve.ai/ingestion/traces/opentelemetry?org_identifier=akeszeg_organization_2257_SMkuBGNPgjSrW7z

> Authentication failed - invalid token: token contains an invalid number of segments

### Please provide the exception or error you saw

```true
{"stack":"OTLPExporterError: Unauthorized\n    at IncomingMessage.<anonymous> (/private/tmp/sample-tracing-nodejs-javascript/node_modules/@opentelemetry/otlp-exporter-base/build/src/platform/node/util.js:103:39)\n    at IncomingMessage.emit (node:events:523:35)\n    at endReadableNT (node:internal/streams/readable:1367:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","message":"Unauthorized","name":"OTLPExporterError","data":"{\"Error\":\"Authentication failed - invalid token: token contains an invalid number of segments\"}","code":"401"}
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version
Commit Hash
Build Date
v0.5.1
e0193bfb232e41cb1375f6e31f3e8fea2ef16c8b
2023-07-20T01:37:56Z
```

**Comment by bjp232004** [comment]
Are you still facing the issue? 

This should be an intermittent issue. Can you please check once again and let me know if the issue persists?

**Comment by artworx** [comment]
The issue is fixed. 👍

**Comment by tobi-ajasa-lot** [comment]
> The issue is fixed. 👍

How did you fix this issues, please? I have the same issue.

**Comment by PPDEMOone** [comment]
I have the same issue.
