### ISSUE TITLE
remove the custom version of vrl

### ISSUE THREAD

**Issue by happysalada** [openobserve/openobserve#1233]
### Description

right now the cargo lock contains two different versions of vrl.
The vector.dev one and the custom openzinc one.
This causes some problem with builds using vendored directory (both the dependencies have the same name and version).

### Proposed solution

Would you consider either upstreaming the changes to vrl or changing the version in your vrl fork ?

### Alternatives considered

doing nothing is definitely a possibility.

I was suggesting this in the context of packaging this for nixos (nixos uses vendored directory to cache some builds steps so currently this doesn't build properly).

**Comment by gaby** [comment]
👍🏻 for removing VRL fork, should be using upstream.

**Comment by happysalada** [comment]
@oasisk this seems to be coming from the "enrichment" dependency which is a coming from a fork of vector.
Are you missing a feature that needs upstreaming ?

**Comment by happysalada** [comment]
@oasisk thanks a lot for this, could you make a new release ? (no rush though if you want to wait a bit).

**Comment by oasisk** [comment]
@happysalada we are making a release in next couple of days.
