### ISSUE TITLE
VRL function not parsing JSON

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#1238]
### Which OpenObserve functionalities are the source of the bug?

functions

### Is this a regression?

Yes

### Description

data:

```json
{
	"_timestamp": 1689950045207265,
	"category": "kube-audit",
	"operationname": "Microsoft.ContainerService/managedClusters/diagnosticLogs/Read",
	"properties_collectedby": "fluent-bit",
	"properties_containerid": "e0a80a7ab3632cd28d7fc5a19893975457b9135f6294bf47e391cb5cd093fd2f",
	"properties_log": "{\"kind\":\"Event\",\"apiVersion\":\"audit.k8s.io/v1\",\"level\":\"Request\",\"auditID\":\"b288deb7-4be1-4c7e-9769-a3fba9d0d125\",\"stage\":\"ResponseComplete\",\"requestURI\":\"/api/v1/namespaces/default/services/kubernetes\",\"verb\":\"get\",\"user\":{\"username\":\"system:apiserver\",\"uid\":\"77a81562-6df1-4943-a2d4-5c2d1135fb4f\",\"groups\":[\"system:masters\"]},\"sourceIPs\":[\"127.0.0.1\"],\"userAgent\":\"kube-apiserver/v1.25.6 (linux/amd64) kubernetes/94c5054\",\"objectRef\":{\"resource\":\"services\",\"namespace\":\"default\",\"name\":\"kubernetes\",\"apiVersion\":\"v1\"},\"responseStatus\":{\"metadata\":{},\"code\":200},\"requestReceivedTimestamp\":\"2023-07-21T14:33:42.755039Z\",\"stageTimestamp\":\"2023-07-21T14:33:42.757552Z\",\"annotations\":{\"authorization.k8s.io/decision\":\"allow\",\"authorization.k8s.io/reason\":\"\"}}\n",
	"properties_pod": "kube-apiserver-568b5f9c8c-lbbrp",
	"properties_stream": "stdout",
	"resourceid": "/SUBSCRIPTIONS/7A1D347F-C334-4C06-A8B6-4FDE666089FE/RESOURCEGROUPS/RG1/PROVIDERS/MICROSOFT.CONTAINERSERVICE/MANAGEDCLUSTERS/AKS1",
	"time": "2023-07-21T14:33:42.757812707Z"
}
```

function

```ruby
.log = parse_json!(.properties_log)
del(.properties_log)
.
```
It fails ion OpenObserve but works fine in playground.

Check [playground](https://playground.vrl.dev/?state=eyJwcm9ncmFtIjoiLmxvZyA9IHBhcnNlX2pzb24hKC5wcm9wZXJ0aWVzX2xvZylcbmRlbCgucHJvcGVydGllc19sb2cpXG4uIiwiZXZlbnQiOnsiX3RpbWVzdGFtcCI6MTY4OTk1MDA0NTIwNzI2NSwiY2F0ZWdvcnkiOiJrdWJlLWF1ZGl0Iiwib3BlcmF0aW9ubmFtZSI6Ik1pY3Jvc29mdC5Db250YWluZXJTZXJ2aWNlL21hbmFnZWRDbHVzdGVycy9kaWFnbm9zdGljTG9ncy9SZWFkIiwicHJvcGVydGllc19jb2xsZWN0ZWRieSI6ImZsdWVudC1iaXQiLCJwcm9wZXJ0aWVzX2NvbnRhaW5lcmlkIjoiZTBhODBhN2FiMzYzMmNkMjhkN2ZjNWExOTg5Mzk3NTQ1N2I5MTM1ZjYyOTRiZjQ3ZTM5MWNiNWNkMDkzZmQyZiIsInByb3BlcnRpZXNfbG9nIjoie1wia2luZFwiOlwiRXZlbnRcIixcImFwaVZlcnNpb25cIjpcImF1ZGl0Lms4cy5pby92MVwiLFwibGV2ZWxcIjpcIlJlcXVlc3RcIixcImF1ZGl0SURcIjpcImIyODhkZWI3LTRiZTEtNGM3ZS05NzY5LWEzZmJhOWQwZDEyNVwiLFwic3RhZ2VcIjpcIlJlc3BvbnNlQ29tcGxldGVcIixcInJlcXVlc3RVUklcIjpcIi9hcGkvdjEvbmFtZXNwYWNlcy9kZWZhdWx0L3NlcnZpY2VzL2t1YmVybmV0ZXNcIixcInZlcmJcIjpcImdldFwiLFwidXNlclwiOntcInVzZXJuYW1lXCI6XCJzeXN0ZW06YXBpc2VydmVyXCIsXCJ1aWRcIjpcIjc3YTgxNTYyLTZkZjEtNDk0My1hMmQ0LTVjMmQxMTM1ZmI0ZlwiLFwiZ3JvdXBzXCI6W1wic3lzdGVtOm1hc3RlcnNcIl19LFwic291cmNlSVBzXCI6W1wiMTI3LjAuMC4xXCJdLFwidXNlckFnZW50XCI6XCJrdWJlLWFwaXNlcnZlci92MS4yNS42IChsaW51eC9hbWQ2NCkga3ViZXJuZXRlcy85NGM1MDU0XCIsXCJvYmplY3RSZWZcIjp7XCJyZXNvdXJjZVwiOlwic2VydmljZXNcIixcIm5hbWVzcGFjZVwiOlwiZGVmYXVsdFwiLFwibmFtZVwiOlwia3ViZXJuZXRlc1wiLFwiYXBpVmVyc2lvblwiOlwidjFcIn0sXCJyZXNwb25zZVN0YXR1c1wiOntcIm1ldGFkYXRhXCI6e30sXCJjb2RlXCI6MjAwfSxcInJlcXVlc3RSZWNlaXZlZFRpbWVzdGFtcFwiOlwiMjAyMy0wNy0yMVQxNDozMzo0Mi43NTUwMzlaXCIsXCJzdGFnZVRpbWVzdGFtcFwiOlwiMjAyMy0wNy0yMVQxNDozMzo0Mi43NTc1NTJaXCIsXCJhbm5vdGF0aW9uc1wiOntcImF1dGhvcml6YXRpb24uazhzLmlvL2RlY2lzaW9uXCI6XCJhbGxvd1wiLFwiYXV0aG9yaXphdGlvbi5rOHMuaW8vcmVhc29uXCI6XCJcIn19XG4iLCJwcm9wZXJ0aWVzX3BvZCI6Imt1YmUtYXBpc2VydmVyLTU2OGI1ZjljOGMtbGJicnAiLCJwcm9wZXJ0aWVzX3N0cmVhbSI6InN0ZG91dCIsInJlc291cmNlaWQiOiIvU1VCU0NSSVBUSU9OUy83QTFEMzQ3Ri1DMzM0LTRDMDYtQThCNi00RkRFNjY2MDg5RkUvUkVTT1VSQ0VHUk9VUFMvUkcxL1BST1ZJREVSUy9NSUNST1NPRlQuQ09OVEFJTkVSU0VSVklDRS9NQU5BR0VEQ0xVU1RFUlMvQUtTMSIsInRpbWUiOiIyMDIzLTA3LTIxVDE0OjMzOjQyLjc1NzgxMjcwN1oifSwiaXNfanNvbmwiOmZhbHNlLCJlcnJvciI6bnVsbH0%3D)

It fails in OpenObserve

**Comment by oasisk** [comment]
working fine with latest version

**Comment by oasisk** [comment]
with latest release & fixes , works fine
