### ISSUE TITLE
Unable to scroll down to see next set of records if less than 300

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#1239]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

<img width="1304" alt="image" src="https://github.com/openobserve/openobserve/assets/4242188/70416fbb-e668-46af-bc91-cd8512076e86">

**Comment by omkarK06** [comment]
As we don't lock/store the start time and end time of initial query. During pagination it gets result with respect to current time as end time hence the there is some difference in the total number of logs that we see in histogram and result we get during pagination.

**Solution**
Now, we will lock/store the start time and end time of initial query and use same for pagination.
