### ISSUE TITLE
Maximize panel in a dashboard

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#1278]
### Which OpenObserve functionalities are relevant/related to the feature request?

dashboards

### Description

Dashboards can contain multiple panels and each panel is generally very small and at times does not provide enough granularity and visibility due to its small size on the screen.

### Proposed solution

Provide a maximize button for each panel in the dashboard that will allow it to be maximized so it can acquire a big area of the screen and is easy to analyze.

### Alternatives considered

none

**Comment by neha00290** [comment]
this is tested
