### ISSUE TITLE
Share a logs page with query but there is no query

### ISSUE THREAD

**Issue by hengfeiyang** [openobserve/openobserve#1281]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

Share a logs query like this: https://dev.zinclabs.dev/web/logs?stream=gke-fluentbit&refresh=0&org_identifier=default&period=2h&sql_mode=false&query=bWF0Y2hfYWxsKCdlMTllZjRkNy0wZTk1LTRkZTAtYTkxNC1hODcxOTE4MjY2MGYnKQ==

it includes a query, but there is nothing in the new opened page. but if you change the time_range you will find it actually used the query. it is amazing. 

### Please provide the version you discovered this bug in (check about page for version information)

```true
v0.5.1
```

**Comment by bjp232004** [comment]
Not able to reproduce it

**Comment by hengfeiyang** [comment]
fixed
