### ISSUE TITLE
PromQL query failure - No data found for the operation lhs: None rhs: None

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#1284]
### Which OpenObserve functionalities are the source of the bug?

metrics

### Is this a regression?

Yes

### Description

Query
1. 
```ruby
sum(namespace_cpu:kube_pod_container_resource_requests:sum{}) 
```
returns results

2. 
```ruby
sum(kube_node_status_allocatable{job="kube-state-metrics",resource="cpu"})
```
also returns results

3. CPU requests commitment query
results in error:

```ruby
sum(namespace_cpu:kube_pod_container_resource_requests:sum{}) 
/ sum(kube_node_status_allocatable{job="kube-state-metrics",resource="cpu"})
```

```json
{
    "status": "error",
    "errorType": "bad_data",
    "error": "DataFusionError# This feature is not implemented: No data found for the operation lhs: None rhs: None"
}
```

**Comment by jennydaman** [comment]
I am also having this issue, with the `*` operator which is important for doing joins on label names.

**Comment by jennydaman** [comment]
A workaround is to use Lua + [Vector](https://vector.dev) to what you would otherwise do using PromQL. Example: https://github.com/containers/prometheus-podman-exporter/issues/35#issuecomment-1675427384

**Comment by prabhatsharma** [comment]
Most of the promql issues have been fixed and will be available in the next release of OpenObserve. If you are feeling adventurous then you can try the dev images from https://gallery.ecr.aws/zinclabs/openobserve-dev which has much higher PromQL support

**Comment by a0s** [comment]
Hi! I want to understand the current state of supporting for metrics storage.
It is important for me that prometheus ui and grafana can execute promql while prometheus is connected to openobserve in remote_writer mode
@prabhatsharma Where exactly are you running your promql queries - prometheus ui, grafana or openobserve ui ?

**Comment by prabhatsharma** [comment]
This is fixed. We just did not close this issue.
