### ISSUE TITLE
Custom label fo y-axis for prometheus queries in panels

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#1285]
### Which OpenObserve functionalities are relevant/related to the feature request?

metrics

### Description

to get memory utilization for each namespace

```ruby
sum(container_memory_rss{job="kubelet", metrics_path="/metrics/cadvisor", cluster="$cluster", container!=""}) by (namespace)
```
we get below.

<img width="849" alt="image" src="https://github.com/openobserve/openobserve/assets/4242188/4456843f-e28c-42cf-be29-41b1e76a4482">

### Proposed solution

memory for ziox namespace is 10 billion. I would like to represent it as 10 GB

### Alternatives considered

na

**Comment by ktx-kirtan** [comment]
Now you will see the unit option in the config sidebar where you can apply multiple units.

![image](https://github.com/openobserve/openobserve/assets/124270523/f6071f31-31f2-4733-84cd-f000ada48d76)
