### ISSUE TITLE
traces query timeout 

### ISSUE THREAD

**Issue by domyway** [openobserve/openobserve#1290]
### Which OpenObserve functionalities are the source of the bug?

traces

### Is this a regression?

Yes

### Description

http://127.0.0.1:5080/api/default/default/_values?fields=service_name&size=10&start_time=1690462303880000&end_time=1690635103880000&type=traces

traces data is too  large to query.  timeout  everytime.  
I just want to get all the distinct service_name(select distinct service_name from table )

**Comment by hengfeiyang** [comment]
<img width="1474" alt="image" src="https://github.com/openobserve/openobserve/assets/1628250/6b9d58e1-5197-43dd-a661-61e86573d1d4">

I plan to create a `distinct_values` table to resolve this issue. The `distinct_values` table should be very small and query very fast.

**Comment by domyway** [comment]
> <img alt="image" width="1474" src="https://user-images.githubusercontent.com/1628250/277665470-6b9d58e1-5197-43dd-a661-61e86573d1d4.png">
> I plan to create a `distinct_values` table to resolve this issue. The `distinct_values` table should be very small and query very fast.

it seems great
