### ISSUE TITLE
Field variables are not being replaced 

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#1310]
### Which OpenObserve functionalities are the source of the bug?

dashboards

### Is this a regression?

Yes

### Description

<img width="1593" alt="image" src="https://github.com/openobserve/openobserve/assets/4242188/3151990e-6b9e-4b1b-b4af-4c1dd8f9edbd">

**Comment by ktx-kirtan** [comment]
Only 1st instance of the variable value was being replaced. Also, need to use the `name` of the variable in the queries for its values to be replaced. 

This issue is fixed in #1315
