### ISSUE TITLE
What is the correct way to deploy the openobserve container behind a reverse proxy?

### ISSUE THREAD

**Issue by miversen33** [openobserve/openobserve#1350]
### Discussed in https://github.com/openobserve/openobserve/discussions/1337

Converting this to an issue

<div type='discussions-op-text'>

<sup>Originally posted by **miversen33** August  4, 2023</sup>
The title pretty much covers the question but I will elaborate a bit.

I have deployed the openobserve container on port 5080 and can access it over that port.

However I would like to put it behind a reverse proxy (that handles ssl and such for us, as well as makes it accessible outside the specified port in a production environment). I am using the below nginx configuration currently

```nginx
        location /logs {
            return 302 /logs/;
        }

        location /logs/ {
            proxy_pass http://127.0.0.1:5080/;
            proxy_redirect default;
        }
```

This gets the initial response to the container, however requests for `./assets` can be seen going to `MYDOMIAIN/web/assets` instead of the preferred `MYDOMAIN/logs/web/assets`.

What is the correct way to perform this? I found [this link](https://discuss.openobserve.ai/kb/t/troubleshooting-nginx-reverse-proxy-for-zincobserve/2M4f) which briefly touches on it, but I am not getting any further with it. 

I can probably do some sub filter rewrites but that seems really icky and I try to avoid doing that.

Thanks!</div>

**Comment by hengfeiyang** [comment]
try this:

```
        location /logs {
            return 302 /logs/;
        }

        location /logs/ {
            proxy_pass http://127.0.0.1:5080;
        }
```

You need remove the last slash in `proxy_pass`.

And set 

```
ZO_BASE_URI = "/logs"
```
for OpenObserve.

**Comment by miversen33** [comment]
I had tried several variations of the `proxy_pass` but could not get it to work. The `ZO_BASE_URI` is what I was missing.

Thank you!

**Comment by desprit** [comment]
I have `ZO_BASE_URI=/openobserve`. And I have the following nginx config:
```
server {
  listen 80 default_server;
  listen [::]:80 default_server;
  server_name _;
  proxy_max_temp_file_size 0;
  root /app/web/dist;

  location /api {
    proxy_pass http://0.0.0.0:8089;
    proxy_set_header Host $host;  
    proxy_set_header X-Real-IP $remote_addr;
  }
  location /openobserve {
    return 302 /openobserve/;
  }
  location /openobserve/ {
    proxy_pass http://0.0.0.0:5080;
    proxy_set_header Host $host;  
    proxy_set_header X-Real-IP $remote_addr;
  }
  location / {
    try_files $uri $uri/ /index.html;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
  }
  location ~* ^.+\.css$ {
    default_type text/css;
  }
  location ~* ^.+\.js$ {
    default_type text/javascript;
  }

  index index.html index.htm;

  access_log /dev/stdout;
}
```

Nginx error:
```
2023/08/15 06:40:17 [error] 7#7: *22 open() "/app/web/dist/openobserve/web/assets/index.05ee9c02.css" failed (2: No such file or directory)......."
```

How can I fix it?

**Comment by desprit** [comment]
Solved by adding two additional locations:
```
location ~* /openobserve/web/assets/.+\.js$ {
    proxy_pass http://0.0.0.0:5080;
    proxy_set_header Host $host;  
    proxy_set_header X-Real-IP $remote_addr;
  }
  location ~* /openobserve/web/assets/.+\.css$ {
    proxy_pass http://0.0.0.0:5080;
    proxy_set_header Host $host;  
    proxy_set_header X-Real-IP $remote_addr;
  }
```
maybe there's a better way?

**Comment by hengfeiyang** [comment]
maybe you can delete this section:

```
  location ~* ^.+\.css$ {
    default_type text/css;
  }
  location ~* ^.+\.js$ {
    default_type text/javascript;
  }
```

default it should be no problem.

**Comment by desprit** [comment]
@hengfeiyang 
Yes, much better, thank you!
