### ISSUE TITLE
Alert custom sql lost during editing

### ISSUE THREAD

**Issue by chris-palmer99** [openobserve/openobserve#1366]
### Which OpenObserve functionalities are the source of the bug?

alerts

### Is this a regression?

No

### Description

1. Create an alert using some custom SQL
2. The listing of all the alerts shows the custom SQL
3. Edit the alert
4. The custom SQL has been replaced with the default SQL
5. Cancel the edit
6. The listing of all alerts shows the default SQL
7. Navigate away and back to Alerts
8. The listing now shows the custom SQL again

Editing of an alert can be done with care by copying the custom SQL before hitting edit, reinstating it in the edit screen, then saving.

Also the width of the SQL column in the list of all alerts seems unconstrained. It might be better to constrain it with a scroll bar on that column? It would also be good to have the three time values there too.

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version 0.5.1
Linux x86_64
```

**Comment by hengfeiyang** [comment]
fixed
