### ISSUE TITLE
json_array true is not converting json log entries to array of Json. 

### ISSUE THREAD

**Issue by RVaidhy** [openobserve/openobserve#1367]
### Which OpenObserve functionalities are the source of the bug?

ingestion

### Is this a regression?

No

### Description

Need help to resolve FluentD configuration issue.

We had set the open observe in our system. When we try to ingest the application logs to open observe using FluentD, we are getting this issue. json_array true is not converting json log entries to array of Json. We have copied the code snippet and property tag value from the open observe ingestion section only. But still the ingestion is not happening. 

Open Observe Version from the log entries as follows, 
Starting OpenObserve v0.5.1

### Please provide the exception or error you saw

```true
Actual logs from the system looks like this:

data1 | data2 | data3 | data4 | data5 
data1 | data2 | data3 | data4 | data5 
data1 | data2 | data3 | data4 | data5 


P.S : delimeter is a | symbol.

After we applied the parser and regex inside fluentd configuration file (td-agent.conf) and uploaded to S3, we are getting the data as a zip like this format (ie individual JSON entries as a single zip) 

{"key1":"data1","key2":"data2","key3":"data3","key4":"data4","key5":"data5"}
{"key1":"data1","key2":"data2","key3":"data3","key4":"data4","key5":"data5"}
{"key1":"data1","key2":"data2","key3":"data3","key4":"data4","key5":"data5"}
{"key1":"data1","key2":"data2","key3":"data3","key4":"data4","key5":"data5"}
{"key1":"data1","key2":"data2","key3":"data3","key4":"data4","key5":"data5"}


What we wanted to have is a array of json like below to ingest the data into Open observe.

[

{"key1":"data1","key2":"data2","key3":"data3","key4":"data4","key5":"data5"},

{"key1":"data1","key2":"data2","key3":"data3","key4":"data4","key5":"data5"},


{"key1":"data1","key2":"data2","key3":"data3","key4":"data4","key5":"data5"}

]

Could you please tell me how to get that. We are using this configuration recommendations from open observe but it didn't help us to ingest the data into the system.
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
Open Observe Version : Starting OpenObserve v0.5.1
```

**Comment by prabhatsharma** [comment]
couple of things:

1. You may have missed the 

```ruby
json_array true
```

in your fluentd config. Can you please check for this.

2. You can use data in below format with OpenObseerve too:

```json
{"key1":"data1","key2":"data2","key3":"data3","key4":"data4","key5":"data5"}
{"key1":"data1","key2":"data2","key3":"data3","key4":"data4","key5":"data5"}
```

instead of _json endpoint, use [_multi](https://openobserve.ai/docs/api/ingestion/multi/) endpoint.

3. Any specific reason to use fluentd? We recommend that you use fluentbit or vector unless something strong is compelling you to choose fluentd.

**Comment by RVaidhy** [comment]
Hi Prabhat,


Thanks for your answer and recommendation. 

"instead of _json endpoint, use [_multi](https://openobserve.ai/docs/api/ingestion/multi/) endpoint." - This solution really helped us to achieve what we are intended. Thanks so much.

To answer your question, we are using fluentd especially because we are sending the logs to multiple locations (ie) to many services like S3, OpenObserve etc. Also our volume of logs is also high, nearly ~35GB of logs are getting generated. Since fluentbit is a light weight component we have decided to go for fluentD. If you have any recommendation please let us know. 

Thanks,
Vaidhy R
