### ISSUE TITLE
filebeat submits logs errors

### ISSUE THREAD

**Issue by macaty** [openobserve/openobserve#1370]
### Which OpenObserve functionalities are the source of the bug?

ingestion

### Is this a regression?

Yes

### Description

Openobserve's ZO_INGEST_ALLOWED_UPTO defaults to 5 hours, when filebeat submits logs with more than 5 hours of historical data, it will prompt for UNKNOWN CHARACTER, which can feed back more friendly logs for troubleshooting, for example, the logs are more than 5 hours old, and Openobserve has already discarded them.

### Please provide the exception or error you saw

```true
filebat log：
{"log.level":"error","@timestamp":"2023-08-10T03:16:18.738Z","log.logger":"elasticsearch","log.origin":{"file.name":"elasticsearch/client.go","file.line":404},"message":"unknown character","service.name":"filebeat","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2023-08-10T03:16:18.741Z","log.logger":"elasticsearch","log.origin":{"file.name":"elasticsearch/bulk.go","file.line":94},"message":"Failed to parse bulk response item: unknown character","service.name":"filebeat","ecs.version":"1.6.0"}
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
version:0.5.1
filebeat:8.9.0
```

**Comment by macaty** [comment]
It's much more friendly to use curl to submit, hassle assisted：
curl -u root@example.com:ScUSPhdBPkknVW3t -k http://172.31.xx.50:5080/api/default/default/_json -d "@k8slog_json.json"
{"code":200,"status":[{"name":"default","successful":3838,"failed":8,"error":"Too old data, only last 5 hours data can be ingested. Data discarded. You can adjust ingestion max time by setting the environment variable ZO_INGEST_ALLOWED_UPTO=<max_hours>"}]}

**Comment by hengfeiyang** [comment]
i did some optimize of error message of bulk api. you can try again after release v0.5.2
