### ISSUE TITLE
add openobserve to show the number of logs processed per second in real time

### ISSUE THREAD

**Issue by macaty** [openobserve/openobserve#1371]
### Description

It is suggested to add openobserve to show the number of logs processed per second in real time, so that we can easily grasp the performance of this system.

### Proposed solution

![image](https://github.com/openobserve/openobserve/assets/16797633/41259b4a-1b42-4181-8f9c-45037ea09417)

### Alternatives considered

![image](https://github.com/openobserve/openobserve/assets/16797633/64e74e21-a829-4bf5-8087-d6f968d17dfc)

**Comment by prabhatsharma** [comment]
This is available via prometheus metrics that are exposed by OpenObserve. Check https://openobserve.ai/docs/expose-metrics/
