### ISSUE TITLE
recommended to add the algorithm Percentile

### ISSUE THREAD

**Issue by macaty** [openobserve/openobserve#1372]
### Description

In addition to algorithms such as Average sum, it is recommended to add the algorithm Percentile

### Proposed solution

![image](https://github.com/openobserve/openobserve/assets/16797633/516c1340-782b-42f3-95d7-10782850c9cc)

### Alternatives considered

![image](https://github.com/openobserve/openobserve/assets/16797633/a1e502c2-ae82-4d61-904b-6896c74dda7d)

**Comment by prabhatsharma** [comment]
Added
