### ISSUE TITLE
UI: Loading Icon while loading data on dashboard panel 

### ISSUE THREAD

**Issue by bjp232004** [openobserve/openobserve#1375]
### Which OpenObserve functionalities are the source of the bug?

dashboards

### Is this a regression?

Yes

### Description

Loading icon while loading data on dashboard panel.

![image](https://github.com/openobserve/openobserve/assets/551527/53461da1-e4e0-4864-a301-313993d2ca14)

**Comment by ktx-kirtan** [comment]
This is a resize-related bug, where the panel is not able to get the correct parent width due to grid rendering with transition when the chart starts the initial drawing.

This bug is fixed and merged in #1468
