### ISSUE TITLE
Column sorting incorrect behavior

### ISSUE THREAD

**Issue by KristinnVikarJ** [openobserve/openobserve#1380]
### Which OpenObserve functionalities are the source of the bug?

streams

### Is this a regression?

Yes

### Description

When sorting by Ingested/Compressed size, the sorting is seemingly based on string comparison and not value.

This means if I have 5 streams with ingested sizes of 10MB, 9MB and 2000MB, it would be sorted as 9MB 2000MB 10MB instead of the expected 2000MB 10MB and then 9MB.

The current functionality makes the sorting very unhelpful since its mostly dependent on the first digit of the number. 

### Anything else?

![image](https://github.com/openobserve/openobserve/assets/12851382/4c8adc33-2cfa-40a9-abbc-a56c4febe707)

This is what the current behavior looks like.

**Comment by Pandry** [comment]
Just came here to report the same issue
![image](https://github.com/openobserve/openobserve/assets/17499836/4a1ad1bc-b366-4070-9776-2058fb8c3961)

Glad it's already being sorted out!

**Comment by omkarK06** [comment]
This issue will be resolved by #1222
