### ISSUE TITLE
Suggest to add Global filter bar to the Dashboard

### ISSUE THREAD

**Issue by macaty** [openobserve/openobserve#1383]
### Description

Suggest to add filter bar to the dashboard module, easy for users to refine and reuse the panel, more convenient to query logs and troubleshooting.

### Proposed solution

![image](https://github.com/openobserve/openobserve/assets/16797633/dedfa714-57e2-4884-8bc4-e0464a683c6b)
Just add a filter bar like in the screenshot above

### Alternatives considered

1

**Comment by macaty** [comment]
like this 
![image](https://github.com/openobserve/openobserve/assets/16797633/f92e53c0-1246-4369-bb02-70c557fa58d6)

**Comment by prabhatsharma** [comment]
can be now added using match_all for all the fields that have an inverted index associated with them

**Comment by squeeb** [comment]
> can be now added using match_all for all the fields that have an inverted index associated with them

Can you explain a little more what you mean by this? It's not clear how one uses this information to add a global search filter to a dashboard.
