### ISSUE TITLE
In the log query function，if you select Weeks, you will get the error "Invalid SQL Syntax".

### ISSUE THREAD

**Issue by macaty** [openobserve/openobserve#1384]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

In the log query function, if you select Minutes, Hours, Days, Months in Relative, it works fine。
 But if you select Weeks, you will get the error "Invalid SQL Syntax".
1、error Screenshot
![企业微信截图_16919853318168](https://github.com/openobserve/openobserve/assets/16797633/178e0b6a-363d-49b3-8983-907c78ae86e9)

2、normal Screenshot
![image](https://github.com/openobserve/openobserve/assets/16797633/5deefa7c-e0e7-4a9f-af98-3d43d412f7c5)

### Please provide a link to a minimal reproduction of the bug

1

### Please provide the exception or error you saw

```true
1
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version:public.ecr.aws/zinclabs/openobserve:0.5.1
```

### Anything else?

1

**Comment by gaby** [comment]
@macaty This has been fixed for a while now, but we won't get the fix until a new release is done.

**Comment by gaby** [comment]
Related https://github.com/openobserve/openobserve/issues/1204

**Comment by prabhatsharma** [comment]
Yeah, we are due for a release for a while. We are working on some thorny issues and will make a release as soon as we can.
