### ISSUE TITLE
mutil-line chart for each domain，like graylog or aliyun  sls do

### ISSUE THREAD

**Issue by macaty** [openobserve/openobserve#1388]
### Which OpenObserve functionalities are relevant/related to the feature request?

dashboards

### Description

Line chart, I want to do 5xx's for each domain, at each time, how do I do it?
`SELECT histogram(_timestamp,'1 minute') as "x_axis_1",host, count(host) as code_5xx_count FROM "default" where status > 499  GROUP BY x_axis_1,host ORDER BY x_axis_1 desc limit 10`

Even more 2xx, 4xx, 5xx line CHART for each domain name
`SELECT histogram(_timestamp,'1 minute') as "x_axis_1", count(case when status >= 200 AND status <= 299 then 1 end) as code_2xx_count, count(case when status >= 400 AND status <= 499 then 1 end) as code_4xx_count, count(case when status >= 500 AND status <= 599 then 1 end) as code_5xx_count  FROM "default"  GROUP BY x_axis_1,host ORDER BY x_axis_1 desc limit 10`

### Proposed solution

Graylog can add sub group to X-Axis，as Row or Column，as much as you can
![d5644a25770f937b93f2a73576cca8f](https://github.com/openobserve/openobserve/assets/16797633/85620aa7-7e15-4228-9149-3a658e9b26d2)

oo cann't be sub group.
![image](https://github.com/openobserve/openobserve/assets/16797633/41a44a93-9bee-47ea-b05d-01f672454318)

### Alternatives considered

1

**Comment by ktx-kirtan** [comment]
Now, when you add 2 x-axis for the line chart, it will subgroup by 2nd x-axis. And whenever, you will have multiple y-axis, the group of 2nd x-axis will show which line is represents the value of which y axis. 

Example: 

2 X-Axis, 1 Y-Axis

![image](https://github.com/openobserve/openobserve/assets/124270523/3f23db89-4fd0-44ae-88b0-da22656bb1a5)

2 X-Axis, 2 Y-Axis:

![image](https://github.com/openobserve/openobserve/assets/124270523/f2c12379-369b-41fd-8e2e-7a3b39b5d536)


This feature is implemented and merged in the main #1483

**Comment by ktx-kirtan** [comment]
This has been released

**Comment by prabhatsharma** [comment]
Available in v0.6.4
