### ISSUE TITLE
Add a share link function to log search and Dashboard

### ISSUE THREAD

**Issue by macaty** [openobserve/openobserve#1390]
### Which OpenObserve functionalities are relevant/related to the feature request?

log search, dashboards

### Description

Add a share link function to log search and Dashboard with corresponding search criteria (including, search, filter, time)
Facilitate quick sharing with people who need to view data and assist in troubleshooting issues ，to improve technical support efficiency.

### Proposed solution

share link with search criteria (including, search, filter, time)

### Alternatives considered

1

**Comment by macaty** [comment]
example:

http://172.28.99.99:9000/search?q=host%3Awww.baidu.com+and+message%3A%22uid%3D111%22&rangetype=relative&from=300

http://172.28.99.99:9000/search?q=host%3Awww.baidu.com+and+message%3A%22uid%3D111%22&rangetype=absolute&from=2023-09-22T01%3A02%3A39.518Z&to=2023-09-22T01%3A07%3A39.518Z

**Comment by prabhatsharma** [comment]
completed
