### ISSUE TITLE
Options for Alert Destination 

### ISSUE THREAD

**Issue by mdepedrof** [openobserve/openobserve#1401]
### Which OpenObserve functionalities are relevant/related to the feature request?

alerts

### Description

I think that would be great to add more options to use in destinations. Mail should be a basic option but would be great if add another options like telegram or similar. 

### Proposed solution

add Mail as minimun

### Alternatives considered

telegram, discord, etc…

**Comment by cbueche** [comment]
I wanted to open yet another issue for alerting, but there are many already, so I'm adding my 2ct here. Please allow for an external script, so we could add whatever we want as target. My customer particular case is support for Mailgun.com, which would be dead simple if I could do it [using an external script](https://documentation.mailgun.com/en/latest/quickstart-sending.html#send-with-smtp-or-api) .

**Comment by prabhatsharma** [comment]
You could use any destination, including mailgun. Just do below.

1. Create a template
2. Create a destination

Check - https://openobserve.ai/docs/user-guide/alerts/templates/ and https://openobserve.ai/docs/user-guide/alerts/destinations/

**Comment by cbueche** [comment]
Thanks but it's not that simple. I haven't found how to create a template body that works with Mailgun. As far as I understand they do not take JSON, but form-encoded stuff. Any example that you got working would be appreciated.

**Comment by prabhatsharma** [comment]
Ah, I just checked. Damn, mailgun using form-encoded request in 2023.

**Comment by prabhatsharma** [comment]
sendgrid has better API

**Comment by cbueche** [comment]
My customer works with Mailgun and I can't change that. What I have done is a minimal API gateway : listens on 127.0.0.1 for HTTP POST with Openobserve format, extract the parameters, and send to Mailgun.

Then came the next disappointment : event attributes are not available to use in template... the content is static... that's a worse show-stopper. I studied the source code, however it's my 1st time seeing Rust and so no idea how to make it better, event after staring at `src/service/alerts/mod.rs` for long. Anyway that has nothing to do with this issue.

**Comment by prabhatsharma** [comment]
Event attributes are coming in next release. Should be available in next couple of weeks. Code is already merged. Its under testing. If you would like to give it a test run, you could try `public.ecr.aws/zinclabs/openobserve-dev:v0.7.2-a8ee052`

**Comment by cbueche** [comment]
great thing how OpenObserve is progressing, thanks I will give it a go !
... aborted, I use `*-linux-amd64.tar.gz` and no container. No problem I'll wait for the next release.

**Comment by tleerai** [comment]
I don't see built in SMTP support for Open Observe alert destinations so I think this is still desired.

**Comment by cbueche** [comment]
Using Python, Flask and Gunicorn, I have written a small middleware that gets Openobserve POST, translates to Mailgun format, and send it. It's a bit wiggly but it got the job done.

**Comment by Subhra264** [comment]
> I don't see built in SMTP support for Open Observe alert destinations so I think this is still desired.

SMTP support for alerts are actually already implemented in the backend - #2825 . But not yet included in the UI. @omkarK06 can you please check this?

**Comment by gaby** [comment]
Any progress on this feature and #3976 ? It's been pending for a year now

**Comment by prabhatsharma** [comment]
Next week

**Comment by gaby** [comment]
@Subhra264 @omkarK06 @prabhatsharma Any updates on this feature?

**Comment by hengfeiyang** [comment]
We already support email(SMTP) as destination
