### ISSUE TITLE
$__rate_interval variable for dashboards based on PromQL

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#1408]
### Which OpenObserve functionalities are relevant/related to the feature request?

dashboards

### Description

`$__rate_interval` variable as defined in 
https://grafana.com/blog/2020/09/28/new-in-grafana-7.2-__rate_interval-for-prometheus-rate-queries-that-just-work/

This is going to be important for importing grafana dashboards.

### Proposed solution

implement

### Alternatives considered

do nothing

**Comment by neha00290** [comment]
closing this and fixed and released
