### ISSUE TITLE
Trace UI repeat drawing

### ISSUE THREAD

**Issue by domyway** [openobserve/openobserve#1414]
### Which OpenObserve functionalities are the source of the bug?

traces

### Is this a regression?

No

### Description

<img width="549" alt="image" src="https://github.com/openobserve/openobserve/assets/2039546/83de0e09-8bf0-43f3-b08f-0a874409e374">

the api response data 
[oodemodata.json.zip](https://github.com/openobserve/openobserve/files/12409342/oodemodata.json.zip)

### Please provide the version you discovered this bug in (check about page for version information)

0.5.2

**Comment by omkarK06** [comment]
This issue has been fixed in #2075
