### ISSUE TITLE
Integrate with Sweaver

### ISSUE THREAD

**Issue by gedw99** [openobserve/openobserve#1416]
### Description

https://serviceweaver.dev/docs.html#logging

https://serviceweaver.dev/ Is pretty amazing and I would like to use it with open observe.

Service weaver is a huge dev ux boost and so is open observe so teaming them up would be great 

### Proposed solution

I don’t have one but their already have an interfsce based system in order to log to AWS or GCP, so there has to be a way.

### Alternatives considered

None

**Comment by gedw99** [comment]
https://github.com/ServiceWeaver/weaver/blob/main/examples/collatz/weaver_gen.go Shows the integration point 

So looks like the way to do this is to write a generator .

**Comment by prabhatsharma** [comment]
I am not a great fan of injecting code to log and in general prefer to pick logs from standard out using a log forwarder following the [12 factor app best practices](https://12factor.net/logs) unless for some reason it has to be done. If it needs to be done then a simple HTTP call to OpenObserve `_json` endpoint should do the job.
