### ISSUE TITLE
How to call a function from inside a function. 

### ISSUE THREAD

**Issue by RVaidhy** [openobserve/openobserve#1420]
### Which OpenObserve functionalities are the source of the bug?

streams, functions, ingestion

### Is this a regression?

Yes

### Description

Based on the VRL expression output we wanted to call another function for further execution. How shall we do this.

### Please provide the exception or error you saw

```true
Hi Team,

Greetings. Small clarification needed. We are trying to implement Openobserve for our application. By using VRL, we are doing to operations. 

Those things are part of a function and we have associated that function with a stream. Here, based on the outcome from function 
1 we wanted to invoke function 
2. Basically, from the outcome of a statement we wanted to invoke the other function. How to do this with Openobserve ? Please help. TIA.
```

**Comment by prabhatsharma** [comment]
You can have 2 functions associated withe the stream and that should help you.

**Comment by RVaidhy** [comment]
Okay thank you PrabhatSharma. Hope I can perform conditional based invocation of functions.
