### ISSUE TITLE
Include SIMD tar files in downloads

### ISSUE THREAD

**Issue by chris-palmer99** [openobserve/openobserve#1430]
### Which OpenObserve functionalities are relevant/related to the feature request?

other

### Description

Downloading SIMD tar.gz images for use on dedicated servers currently requires getting hold of the corresponding docker image, pulling it apart, locating the binary, and copying that back to where it is needed.

### Proposed solution

Include the SIMD tar.gz files in the downloads available in github (in the same way as the MUSL ones are)

### Alternatives considered

-

**Comment by hengfeiyang** [comment]
Because the SIMD depends on CPU arch, and the binary we provided many platforms. we suggest use docker to run SIMD version. 

Or we can add a SIMD version only for `amd64-simd-linux`. but it will has some requirements like you must use a new Intel CPU with AVX512 and run Ubuntu 22.

**Comment by chris-palmer99** [comment]
We are using it without any problems under Debian11, and all our servers are Intel with AVX512. So just that one would be much appreciated.

**Comment by hengfeiyang** [comment]
We can test in next release.

**Comment by hengfeiyang** [comment]
@chris-palmer99 Can you run this [openobserve-v0.5.2-linux-amd64.tar.gz](https://github.com/openobserve/openobserve/releases/download/v0.5.2/openobserve-v0.5.2-linux-amd64.tar.gz) on Debian11?

**Comment by chris-palmer99** [comment]
Yes, both that one and the SIMD version (for AVX512 CPUs) work

**Comment by hengfeiyang** [comment]
It will be provided in the next release.
