### ISSUE TITLE
Ingestion functions not working for Syslog

### ISSUE THREAD

**Issue by alidamji** [openobserve/openobserve#1435]
### Which OpenObserve functionalities are the source of the bug?

functions, ingestion

### Is this a regression?

No

### Description

When ingesting logs via Syslog, running a function on that stream does not work.

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.5.2
Commit Hash: 7c95c24c9d8a6427eb833557897d7fabfc54012b
Build Date: 2023-08-22T11:05:14Z
```

**Comment by prabhatsharma** [comment]
Ingestion functions are not implemented for syslog

**Comment by temp** [comment]
Will this be added in the near future?

**Comment by oasisk** [comment]
Fixed by https://github.com/openobserve/openobserve/pull/1671
