### ISSUE TITLE
Histogram query optimization

### ISSUE THREAD

**Issue by bjp232004** [openobserve/openobserve#1440]
### Which OpenObserve functionalities are relevant/related to the feature request?

log search

### Description

While "Run Query", histogram is disabled by the user, it should not pull data for the histogram.

### Proposed solution

Maintain the flag for the last query when the histogram is disabled, Once the user enables the histogram pull the histogram data.

### Alternatives considered

No

**Comment by hengfeiyang** [comment]
fixed
