### ISSUE TITLE
Missing api endpoints when using reverse proxy with ZO_BASE_URI

### ISSUE THREAD

**Issue by pitastrudl** [openobserve/openobserve#1447]
### Which OpenObserve functionalities are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

If you want to run openobserve behind a reverse proxy, swagger UI will work but you will not be able to use the functions.  

Example nginx config

```
set $$upstream_service http://openobserve:5080/;
          location /openobserve {
            return 302 /openobserve/;
          }
          location /openobserve/ {
            proxy_pass $$upstream_service;
            proxy_set_header Host $$host;
            proxy_set_header X-Real-IP $$remote_addr;
          }

```
For openobserve we set:  `ZO_BASE_URI: "/openobserve"`

When in Swagger UI if you want to do the GET /healthz endpoint it wants to call to 

`example.com/healtzh` instead of` example.com/openobserve/healthz`

Also for API endpoint if i try to CURL it or with postman, i will get 404

`curl -Lu username:password https://example.com/openobserve/api -v`
```

> User-Agent: curl/8.2.1
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Server: nginx/1.20.1
< Date: Thu, 31 Aug 2023 14:24:49 GMT
< Content-Length: 0
< Connection: keep-alive
< vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers

```
Maybe relevant commit: https://github.com/openobserve/openobserve/commit/b527374d3c79c2f7ee17b5566aef3ad785fd3d9a
https://github.com/openobserve/openobserve/issues/785 

And other relevant issue https://github.com/openobserve/openobserve/issues/1350

### Please provide the version you discovered this bug in (check about page for version information)

```true
v0.5.2
7c95c24c9d8a6427eb833557897d7fabfc54012b
2023-08-22T11:34:15Z
```

**Comment by hengfeiyang** [comment]
fixed, will be released in v0.5.3
