### ISSUE TITLE
Use local disk cache when memory cache is not enough

### ISSUE THREAD

**Issue by hengfeiyang** [openobserve/openobserve#1457]
### Which OpenObserve functionalities are relevant/related to the feature request?

other

### Description

When the memory cache is not enough we will search from s3. it will make a lot of network requests. maybe we can cache the files into a local disk (SSD) when the memory cache is not enough, it will much reduce network requests. maybe the search will be faster.

### Proposed solution

Local disk cache

### Alternatives considered

no

**Comment by hengfeiyang** [comment]
Do we need a size limit for the local disk cache? LRU?

**Comment by prabhatsharma** [comment]
LRU should be good

**Comment by hengfeiyang** [comment]
done
