### ISSUE TITLE
Openobserve functions not accepting codes if it is more than 10 lines

### ISSUE THREAD

**Issue by RVaidhy** [openobserve/openobserve#1466]
### Which OpenObserve functionalities are the source of the bug?

functions

### Is this a regression?

Yes

### Description

Hi Team,

When we write anything execution statements inside a newly created function and if it is less than 10 lines then it is getting executed without any issue.

If it exceeds more than 10 lines means, it simply says  "unexpected end of program" and throws some generic error like expected one of and its options.

I have shared the URL which consists of a logic that we intended to use with some random data. It is working well in VRL playground. But in OpenObserve FUNCTION, once the code crosses it is showing error. Please help.

Also, how can we accommodate this piece of code with in 10 lines ? Is there any workaround or way is there in OpenObserve ? If so please let me know. That will be helpful.

We are using openobserve-v0.5.1-linux-amd64-musl.tar. 

Please help. 

### Please provide a link to a minimal reproduction of the bug

https://playground.vrl.dev/?state=eyJwcm9ncmFtIjoiLnBhY2thZ2VfaW5mb19hcnJheSA9IFtcImJvd2VyXCIsXCJjYXJnby1sb2NhbFwiLFwiY2hlZlwiLFwicG9kc1wiLFwiY29uYW5cIixcImNvbmRhXCIsXCJjcmFuXCIsXCJkZWJcIixcImRvY2tlclwiLFwibGZzXCIsXCJoZWxtXCIsXCJucG1cIixcIm51Z2V0XCIsXCJjb21wb3NlclwiLFwicHlwaVwiLFwiZ2Vtc1wiLFwic3dpZnRcIixcInZhZ3JhbnRcIixcInZjc1wiXVxuXG5pZiAoLm9wZXJhdGlvbiA9PSBcIlVTRVIgQ0FMTFwiKSB7IFxuICAucmVxdWVzdF9VUkwgPSBzdHJpbmchKC5yZXF1ZXN0X1VSTClcbiAgLnJlc3VsdD1zdGFydHNfd2l0aCgucmVxdWVzdF9VUkwsIFwiL2FwaVwiLCBmYWxzZSlcblxuICBpZiAucmVzdWx0IHsgXG4gICAgLnJlcV91cmxfc3BsaXQ9c3BsaXQoLnJlcXVlc3RfVVJMLCBcIi9cIilcbiAgICAucGFja2FnZUluZm89LnJlcV91cmxfc3BsaXRbMl1cbiAgICAucGFja2FnZUluZm9SZWdleCA9IHRvX3JlZ2V4KC5wYWNrYWdlSW5mbyk%2FPyByJydcbiAgICAuaXNQYWNrYWdlRXhpc3QgPSBtYXRjaF9hcnJheSgucGFja2FnZV9pbmZvX2FycmF5LC5wYWNrYWdlSW5mb1JlZ2V4KVxuICAgIGlmIC5pc1BhY2thZ2VFeGlzdCB7XG4gICAgICAucGFja2FnZSA9IC5yZXFfdXJsX3NwbGl0WzJdXG4gICAgICAucmVwb19uYW1lPS5yZXFfdXJsX3NwbGl0WzNdXG4gICAgICAucmVwb19zcGxpdCxlcnIxPXNwbGl0KC5yZXBvX25hbWUsIFwiX1wiKVxuICAgICAgLnZzYWQ9LnJlcG9fc3BsaXRbMF1cbiAgICB9IFxuICB9ICBlbHNlIHtcbiAgICAucGFja2FnZSA9IFwiTi9BXCJcbiAgICAucmVxX3VybF9zcGxpdD1zcGxpdCgucmVxdWVzdF9VUkwsIFwiL1wiKVxuICAgIC5yZXBvX25hbWU9LnJlcV91cmxfc3BsaXRbMV1cbiAgICAucmVwb19zcGxpdCxlcnIyPXNwbGl0KC5yZXBvX25hbWUsIFwiX1wiKVxuICAgIC52c2FkPS5yZXBvX3NwbGl0WzBdXG4gICAgfVxufVxuZGVsKC5wYWNrYWdlX2luZm9fYXJyYXkpXG5kZWwoLnJlcG9fc3BsaXQpXG5kZWwoLnJlcV91cmxfc3BsaXQpXG4uXG5cbiIsImV2ZW50Ijp7InRpbWVzdGFtcCI6IjIwMjMtMDgtMjNUMTA6NDk6NTkuNDA5VFoiLCJpZCI6IjMycXFqaGFzZDM0cTM0biIsInVzZXJuYW1lIjoiYW5vbnltb3VzIiwicmVxdWVzdF9tZXRob2QiOiJHRVQiLCJyZXF1ZXN0X1VSTCI6Ii9hcGkvY2FyZ28tbG9jYWwvR1lRVl9NQVRBTk9fU0FNUExFX1JFUE8vc2FtcGxlLmpzb24iLCJhZ2VudCI6IkphdmEiLCJodHRwX3N0YXR1cyI6IjIyMCIsInJlcXVlc3RfdXNlcl9hZ2VudCI6Impmcm9nLW1pc3Npb24tY29udHJvbC9lcmVyZSIsIm9wZXJhdGlvbiI6IlVTRVIgQ0FMTCJ9LCJpc19qc29ubCI6ZmFsc2UsImVycm9yIjpudWxsfQ%3D%3D

### Please provide the exception or error you saw

```true
unexpected end of program
   │ expected one of: "!", "(", "[", "_", "abort", "false", "float literal", "function call", "identifier", "if", "integer literal", "null", "raw string literal", "regex literal", "string literal", "timestamp literal", "true", "{", "}", "path literal"
   │
   = see language documentation at https://vrl.dev
   = try your code in the VRL REPL, learn more at https://vrl.dev/examples
```

**Comment by RVaidhy** [comment]
Hi PrabhatSharma / Oasisk,
Since I am facing restrictions inside openobserve's function (ie) cannot create more than 10 lines of code, is there any option to store the value in the first function and retrieve the same in second function ?  At least with that I can achieve my goals without waiting much for a resolution in the meantime. Because our development activities are affected because of this number of lines limitation issue. Please help. 

openobserve function 1 {

  #with less than 10 lines of code  i shall do the following thing
   - do something -
   #store it in a variable for later access
   .temp = "user request"
}


=============


openobserve function 2 {

    if (.temp == "user request")
        - do something - 
        - do something - 
        - do something - 
        - do something - 
}


Thanks,
R Vaidhy

**Comment by RVaidhy** [comment]
Is there a possibility to transfer a value by using a variable from function to function is that what I wanted to know. Thanks!

**Comment by prabhatsharma** [comment]
You can use 2 functions and set them to run in sequence. You get output of 1st function as input to the other function.

**Comment by oasisk** [comment]
@RVaidhy this issue is fixed in v0.5.2 of openobserve, can you please try upgrading.

Also please note , when you ingest data to openobserve all fields names are in small case , for eg : 

{"_timestamp":1694143686586724,"agent":"Java","http_status":"220","id":"32qqjhasd34q34n","operation":"USER CALL","request_method":"GET","request_url":"/api/cargo-local/GYQV_MATANO_SAMPLE_REPO/sample.json","request_user_agent":"jfrog-mission-control/erere","timestamp":"2023-08-23T10:49:59.409TZ","username":"anonymous"}

Hence your function needs to be modified to use:

  .request_URL = string!(.request_url)

**Comment by RVaidhy** [comment]
Thanks for the responses.

@prabhatsharma , I have already tried this scenario by having functions created and attached to a stream. when I expected the key ( from previous function's output ) it was not present. Let me check the same in this version and I shall confirm you back. Thanks for the clarity provided. 

@oasisk , Sure . I shall test the same mentioned version and update you back. I will correct case-sensitive  in naming standard issue too. Let me revert you back with the result.


Thanks,

**Comment by RVaidhy** [comment]
Hello Oasisk,

Thanks so much for the fix. 

I am testing the scenarios. As of now nothing is failing and works as expected. I shall close this by tomorrow once our testing is completed.

**Comment by oasisk** [comment]
@RVaidhy  please re-open the issue in case you face it again, closing for now.

**Comment by RVaidhy** [comment]
Hi Oasisk,

We have tested this feature. Working with out any issues. You can close this. Thanks for your support.

- R Vaidhy
