### ISSUE TITLE
Increase the precision of the duration field to nanoseconds.

### ISSUE THREAD

**Issue by domyway** [openobserve/openobserve#1471]
### Which OpenObserve functionalities are relevant/related to the feature request?

traces

### Description

For some performance-sensitive concurrent spans, higher precision is needed to ensure more accuracy when rendering them in the UI.

### Proposed solution

just like this : 

"duration": 1000    
 should be  
"duration": 1719

### Alternatives considered

none

**Comment by domyway** [comment]
jaeger UI for the duration ： 
<img width="522" alt="image" src="https://github.com/openobserve/openobserve/assets/2039546/7a34578f-ff3c-4ca0-915e-e63b093f48c2">


OO traces data transform jaeger data, and jaeger UI for the duration:
<img width="583" alt="image" src="https://github.com/openobserve/openobserve/assets/2039546/66953238-3925-4dd4-ab4f-37bc7f761744">


it seems. all the duration has been truncated from 1719 to 1000

**Comment by hengfeiyang** [comment]
@oasisk We are planning to store it in nanosecond then will resolve this issue.
