### ISSUE TITLE
Show history alarm message

### ISSUE THREAD

**Issue by segment11** [openobserve/openobserve#1509]
### Description

If alerm trigger, add log and show in web page.

### Proposed solution

add a history alarm log page.

### Alternatives considered

add a history alarm log page.

**Comment by hengfeiyang** [comment]
@Subhra264 are we already done this? but need enable report, right?

**Comment by Subhra264** [comment]
@hengfeiyang Yes, and already enabled for reports as well, the `triggers` stream contains triggers for both alerts and reports.
