### ISSUE TITLE
ZO_S3_FEATURE_FORCE_PATH_STYLE not work expected

### ISSUE THREAD

**Issue by yinheli** [openobserve/openobserve#1510]
### Which OpenObserve functionalities are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Based on my understanding, the environment variable `ZO_S3_FEATURE_FORCE_PATH_STYLE` should imply the usage of the "path" style, which is `http://endpoint/bucket_name`. However, from what you've described, it seems that the code implementation is the opposite. Am I correct in my understanding? 

https://github.com/openobserve/openobserve/blob/98c00665a494106c2a8f89446fc89ab104214d4d/src/common/infra/storage/remote.rs#L223

Should that be `.with_virtual_hosted_style_request(!CONFIG.s3.feature_force_path_style);`?

**Comment by hengfeiyang** [comment]
@yinheli You are right, this is a history problem. earlier we use AWS SDK s3 https://docs.rs/aws-sdk-s3/latest/aws_sdk_s3/config/struct.Builder.html#method.force_path_style

It works like what it did, after we move to `object_store` we have not rename it.

Next release, i will create a new environment for `virtual_hosted_style`, maybe named:

```
ZO_S3_FEATURE_FORCE_HOSTED_STYLE=true
```
