### ISSUE TITLE
Trace UI enahcements

### ISSUE THREAD

**Issue by oasisk** [openobserve/openobserve#1513]
### Which OpenObserve functionalities are relevant/related to the feature request?

traces

### Description

Enhancements

### Proposed solution

- [ ] Show list of traces (parent span with trace id)  #1507
![image](https://github.com/openobserve/openobserve/assets/35160958/a7339b2b-1462-438a-819c-14d5486da11d)
- [ ] Store service name & operation for quick searches 
- [ ] Add Service name before span

### Alternatives considered

NA

**Comment by domyway** [comment]
hi @oasisk  ,  I want to know how has the progress on this issue been?  
especially about "Store service name & operation for quick searches "

**Comment by prabhatsharma** [comment]
This has not started yet. We are looking forward to pick it up in next 2-4 weeks
