### ISSUE TITLE
Name of the panel and dashboard is compulsory but it allows only blank spaces

### ISSUE THREAD

**Issue by neha00290** [openobserve/openobserve#1541]
### Which OpenObserve functionalities are the source of the bug?

dashboards

### Is this a regression?

Yes

### Description

Steps
- Go to dashboard and start creating new panel
- Under name of the panel enter blank spaces
- Observe

Actual result - Name of the panel is compulsory but it allows only blank spaces

Expected result - Error to be displayed when only blank spaces added  ubder name of the panel and user saves the panel

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version
Commit Hash
Build Date
v0.6.1
b639dfd055ebdcb745179f67611ecab423f729f4
2023-09-19T08:32:03Z
```

**Comment by ktx-kirtan** [comment]
This has been fixed and available in main

**Comment by neha00290** [comment]
closing this issue as fixed
