### ISSUE TITLE
Scroll bar move so fast in Log query editor

### ISSUE THREAD

**Issue by RogerLiNing** [openobserve/openobserve#1550]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

In the query editor, when I want to select text, it moves down very fast and affects my operation.

watch this video:

https://github.com/openobserve/openobserve/assets/18111035/caa968e2-24a0-46e2-b39c-25bb8ddcb43c

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version v0.6.1
Commit Hash267a14fa6b4f616aee7e0c5b62b37f89df222c19
Build Date 2023-09-18T13:46:38Z
OS  macbook m1
```

**Comment by neha00290** [comment]
this is tested. closing the same
