### ISSUE TITLE
Unit also to be copied when user duplicates a panel

### ISSUE THREAD

**Issue by neha00290** [openobserve/openobserve#1552]
### Which OpenObserve functionalities are the source of the bug?

dashboards

### Is this a regression?

Yes

### Description

Steps
- Go to an existing dashboard with panels.
- Duplicate a panel with any unit other than default.
- Observe the unit on UI of the duplicate panel

Actual result - Unit is set to default and unit that was added for the original panel is not copied 

Expected result - Unit to be same as the panel that was copied

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version
Commit Hash
Build Date
v0.6.1
84da4a917eb81ed9ed2cde6ad9073a2d64e5fb2f
2023-09-20T09:29:09Z
```

**Comment by ktx-kirtan** [comment]
This has been fixed with https://github.com/openobserve/openobserve/pull/1635

**Comment by neha00290** [comment]
this is fixed
