### ISSUE TITLE
Nginx OTLP does not support authentication

### ISSUE THREAD

**Issue by macaty** [openobserve/openobserve#1553]
### Which OpenObserve functionalities are relevant/related to the feature request?

ingestion

### Description

The trace of openobserve must be Authorization: Basic authentication, but NGINX with OpenTelemetry does not support authentication
https://opentelemetry.io/blog/2022/instrument-nginx
please help! Please help!

### Proposed solution

ingrest supports custom authentication or no authentication

or Push Nginx OTLP to support authentication

### Alternatives considered

none

**Comment by hengfeiyang** [comment]
There is an option: `NginxModuleOtelExporterOtlpHeaders`, you can try set it:

```
NginxModuleOtelExporterOtlpHeaders "Basic xxxx"
```

https://github.com/open-telemetry/opentelemetry-cpp-contrib/tree/main/instrumentation/otel-webserver-module#configuration-1

**Comment by macaty** [comment]
thx
