### ISSUE TITLE
Custom SQL query editor error message go away

### ISSUE THREAD

**Issue by bjp232004** [openobserve/openobserve#1573]
### Which OpenObserve functionalities are the source of the bug?

dashboards

### Is this a regression?

Yes

### Description

After clicking on the custom SQL option in the Add Panel page, after adding a long query, and clicking on the query editor error message section goes to the bottom of the page and the user can not see it.

https://www.loom.com/share/6c56b3140f7b4fb49447cee850c297a0

**Comment by neha00290** [comment]
this is fixed
