### ISSUE TITLE
Incorrect statistics on the amount of data in the data stream

### ISSUE THREAD

**Issue by FengZh61** [openobserve/openobserve#1576]
### Which OpenObserve functionalities are the source of the bug?

streams

### Is this a regression?

Yes

### Description

After creating a partition for a field in the metrics, the volume stats appear to be incorrect, then execute . /openobserve reset -c stream-stats.
![a122c3069fddf0e71e36ed340f64e84](https://github.com/openobserve/openobserve/assets/98309003/db99397e-dbcc-4361-b4a3-f23b9e80cc7c)
This screenshot shows the data volume statistics after the partition was created

![e4194f61cefbe2bd6c3944fd6168338](https://github.com/openobserve/openobserve/assets/98309003/50d2b90e-e16b-4445-bcdb-b235b3979188)

This screenshot shows the statistics of the amount of data before the partition was created.

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version v0.6.2
Commit Hash 4509c4da2a61d4d6bbdb58dca794a90cf2786ea2
Build Date 2023-09-21T13:33:18Z
OS Linux x86_64 GNU/Linux
```

**Comment by FengZh61** [comment]
![image](https://github.com/openobserve/openobserve/assets/98309003/71cd5baf-bd22-4626-9c9b-63ec3bd1b66e)
The next day look at the amount of data was reset again at some point in time

**Comment by hengfeiyang** [comment]
Can you upgrade to v0.6.4 and then try again?

**Comment by FengZh61** [comment]
> Can you upgrade to v0.6.4 and then try again?

![image](https://github.com/openobserve/openobserve/assets/98309003/efd8bf23-1f80-42b7-9a22-9a90247070db)

I upgraded to version 0.6.4 to observe for a while

**Comment by FengZh61** [comment]
> Can you upgrade to v0.6.4 and then try again?

I set the partition field count results are still anomalous, the stats get smaller and then continue to accumulate.
I set Data Retention and the count first goes to 0, then after a while the stats appear again, but this doesn't match the numbers coming out via sql count either.
