### ISSUE TITLE
Enrichment data successfully got ingested / loaded but unable to see the same under the logs section.

### ISSUE THREAD

**Issue by RVaidhy** [openobserve/openobserve#1578]
### Which OpenObserve functionalities are the source of the bug?

log search, streams, ingestion

### Is this a regression?

Yes

### Description

Hi Team, 
This is a child ticket. Please find the parent ticket details as below. As requested in the email thread I am creating a separate ticket for this. 

**Data enrichment data not showing in logs #1554**

Actual issue is as follows : 

1. Unable to load large csv into the enrichment tables option (Resolved. Tested)
2. Viewing the uploaded data under the logs section as per document ( Not working)
3. Using VRL creating a query/program to process / create new fields based on the conditions in it and generating report on runtime and as well as for the existed data as per document (Not working)

Requesting you to kindly fix the 2 & 3 and help us please. 

Version that I am using is - (https://github.com/openobserve/openobserve/releases/download/v0.6.3/openobserve-v0.6.3-linux-amd64-musl.tar.gz
)

The installation is running on an EC2 server.

Hope this helps. 

Thanks,
R Vaidhy

**Comment by oasisk** [comment]
@RVaidhy thx for bringing this to notice , please note we need to update our docs , enrichment tables will not be visible under logs . Please navigate to Streams tab , where you can check enrichment table for data: 
![image](https://github.com/openobserve/openobserve/assets/35160958/d11529cd-dcb0-4c35-b029-170299667718)

**Comment by RVaidhy** [comment]
Hello Aashish, 

Thanks for the update on this. you can close this. I am fine.
