### ISSUE TITLE
Histogram and results show incomplete data

### ISSUE THREAD

**Issue by jsargiot** [openobserve/openobserve#1587]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

A period of time seem to be missing, both from logs and histogram

![image](https://github.com/openobserve/openobserve/assets/1591461/c4ab9681-6692-42b1-83bf-96ab351129e1)

The results of the query also show this gap:

![image](https://github.com/openobserve/openobserve/assets/1591461/bfc202f5-9744-4633-9819-c8190e32eb4b)
    This image shows the gap between data in 18:09 and 19:17.

If I wait a few minutes, the logs shown in the previous screenshot after 18:09 are also gone and replaced with the latest, so it doesn't seem to be an ingestion problem, but rather a querying problem.

![image](https://github.com/openobserve/openobserve/assets/1591461/3ed9cfce-99e5-4403-a0d0-b0f8041fe2b2)
    This image shows that the gap now is between 18:09 and 19:23

This is what the response looks when doesn't contain all of the data:
![image](https://github.com/openobserve/openobserve/assets/1591461/4ae6370a-b4e1-48bf-97e3-3c65aafeef1e)

The only workaround I've found so far is to restart the queriers pods, after restart the gap is gone and this is the response:

![image](https://github.com/openobserve/openobserve/assets/1591461/bd3c9797-298e-40ae-a253-13e02175802d)

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.6.3
Commit Hash: c66284613c53308d03439f2d94ede0c87963ed80
Build Date: 2023-09-26T10:20:34Z
OS: linux x64
```

**Comment by hengfeiyang** [comment]
Can you restart the pod, and check it again?

**Comment by jsargiot** [comment]
Restarting the pod works as a temporary measure, because after a while the same thing happens

**Comment by hengfeiyang** [comment]
Can you try v0.6.4?

**Comment by jsargiot** [comment]
Thanks @hengfeiyang , v0.6.4 seems to fix the issue, I've upgraded yesterday's morning and so far everything works as expected. I think you can close this issue.
