### ISSUE TITLE
specify interval for visualizations

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#1599]
### Which OpenObserve functionalities are relevant/related to the feature request?

dashboards

### Description

For any timeseries panels based on the duration of the panel `histogram` function gets a sane interval assigned automatically. `histogram(field, 'interval')`

https://openobserve.ai/docs/functions/#histogram

There are scenarios where a user would like to specify the interval herself in order to have better control of the data being displayed.

### Proposed solution

Provide a drop down to specify interval along with duration. It will have its value populated automatically unless selected manually.

### Alternatives considered

write custom sql query and specify interval to the histogram function.

**Comment by neha00290** [comment]
this is done
