### ISSUE TITLE
KB and MB as units

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#1600]
### Which OpenObserve functionalities are relevant/related to the feature request?

dashboards

### Description

Some data is stored in KB and MB and being able to handle the units. Currently only bytes is available as unit

<img width="310" alt="image" src="https://github.com/openobserve/openobserve/assets/4242188/bc40be91-76bc-45fe-9dc2-5a4c706c504b">

### Proposed solution

Allow for KB and MB as units

### Alternatives considered

Write custom SQL and divide the values every time you need them.

**Comment by neha00290** [comment]
testing is complete for this ticket. no issues found
