### ISSUE TITLE
enrichment VRL is not working 

### ISSUE THREAD

**Issue by RVaidhy** [openobserve/openobserve#1609]
### Which OpenObserve functionalities are the source of the bug?

functions, ingestion

### Is this a regression?

No

### Description

Hello Team,

Need your help on this data enrichment part. 

**what version of openobserve are we using :-** 

_### openobserve-v0.6.3-linux-amd64-musl.tar.gz_

**what are we trying here :-** 

We are trying to manipulate new columns by getting the input value from a existed column.
      - we have a column named repo_name (basically its a folder name)
      - we have the enrichment data uploaded into the system and it contains the relationship data as below. For your understanding i am sharing some sample data. In the form of CSV we have uploaded and I am able to see the uploaded data under the streams section.

### repoenrichment.csv

                       repo_name | package | repo_type | 
                     ---------------------------------------
                      AAAAAA.     |    basic.   |   Federated
                      BBBBBB.      | premium |   Virtual
                      CCCCCC.    | special.    |    Generic. 

Here, based on the repo_name from log entry, we are trying to derive the above 2 new columns (ie) package,repo_type

For that we are using the below VRl.

**********
repo_name, err = get_enrichment_table_record("repoenrichment",
{
  "repo_name": to_string!(.repo_name)
})
.package = repo_name.package
.repo_type = repo_namxe.repo_type
.
**************

 **what error are we getting for the above VRL :-** 

   Error: Search SQL execute error.116

When we run the above VRL we are getting the SQL error. 

Are we mistaken anything here in the  VRL ? please advise. 

Thanks,
R Vaidhy 

### Please provide the exception or error you saw

```true
Error: Search SQL execute error.116
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
We are using this version :-

openobserve-v0.6.3-linux-amd64-musl.tar.gz
```

**Comment by RVaidhy** [comment]
Hi Team,

Any updates on this please. Would be helpful if we get a fix for this or any guidance incase if we are making any mistakes.

Thanks,
R Vaidhy

**Comment by RVaidhy** [comment]
Hi Team,
Any updates on this please.

**Comment by oasisk** [comment]
@RVaidhy for me it works fine on latest dev code as well on v0.6.3 , fn def is:
repo_name, err = get_enrichment_table_record("repoenrichment",{"repo_name": to_string!(.repo_name)})
.package = repo_name.package
.repo_type = repo_name.repo_type
.

**Comment by RVaidhy** [comment]
Hello Aashish,

Thanks for the update. We got rid of the SQL error. But I am wondering how it is not yielding the actual result in our environment even now.

* I have tested the code provided by you in the VRL Function Editor:  (Under logs section we have this block on top right corner) and it gives back nothing


* As a function I have created and associated with stream and ingested 15k logs into that to test. It didn't generate package and repo-type column.

From our logs are generating a column called repo_name. Inside the csv we have the same column along with two others (package & repo_type). Is there a possibility for a conflict ? Are we making any mistakes here. 

Small query here, if I test the code in VRL Function Editor, in that case will it create a new columns (package & repo_type) as a result of execution ? Please clarify. Meanwhile let me test the things one more time freshly.

Thanks,
R Vaidhy

**Comment by oasisk** [comment]
@RVaidhy can you please join openobserve slack channel ,would be easy to communicate .

**Comment by RVaidhy** [comment]
Hello Aashish,

Thanks. Sure. That helps really to close issues soon.

Thanks,
R Vaidhy

**Comment by RVaidhy** [comment]
Hi Aashish, 

I have joined the openobserve slack and raised the case.  Kindly help.

Thanks,
Vaidhy R

**Comment by RVaidhy** [comment]
Thanks Aashish for your slack support. As recommended, I shall create the CSV file and try it in our environment and update you back. 

Thanks,
Vaidhy R

**Comment by RVaidhy** [comment]
Its working fine. Thanks Aashish for your support. Hence I am closing this. Thank you!
