### ISSUE TITLE
drop down values are failing

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#1610]
### Which OpenObserve functionalities are the source of the bug?

metrics

### Is this a regression?

Yes

### Description

e.g. `k8s_node_name` values are not appearing
<img width="981" alt="image" src="https://github.com/openobserve/openobserve/assets/4242188/dd6b9acb-1af9-4321-a249-e7ff7296c0cf">

### Please provide the exception or error you saw

```true
Maybe we need to get all the values for the `k8s_node_name` in this case.
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
v0.6.4
```

**Comment by bjp232004** [comment]
The "By" keyword causing this issue. For now, we will keep it as it is.

**Comment by hengfeiyang** [comment]
@prabhatsharma I checked there is no problem, can you reproduce it?

**Comment by neha00290** [comment]
i verified as well, not able to replicate @hengfeiyang  @prabhatsharma

**Comment by prabhatsharma** [comment]
I am still able to reproduce it.

v0.7.0-rc1
4a8497e75024d1055debcd3e5ac4f4f0e9595a29
2023-11-07T13:00:11Z

**Comment by prabhatsharma** [comment]
Works with:

avg(k8s_pod_cpu_utilization{}) by (k8s_pod_name, k8s_namespace_name)

Does not work with:

avg(k8s_pod_cpu_utilization) by (k8s_pod_name, k8s_namespace_name)


Fetch query
Correct:

https://url/api/otlp-production/prometheus/api/v1/series?match[]={__name__=%22k8s_pod_cpu_utilization%22}&start=1699527123906000&end=1699528023906000

Wrong (This is the issue)

https://url/api/otlp-production/prometheus/api/v1/series?match[]={}&start=1699527123906000&end=1699528023906000
