### ISSUE TITLE
Logs search UI issues

### ISSUE THREAD

**Issue by oasisk** [openobserve/openobserve#1622]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

- [x] During logs search when we have get search results , if there is only one record or you are on the first record "Search around" button remains disabled
- [ ] Infinite scroll stops working : switch to full sql mode , set filtering criteria like namespace name = 'ziox' , infinite scroll doesnt work
- [ ] Switch to non-sql mode infinite scroll doesnt work in non-sql mode as well

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version v0.6.4
Commit Hash 
0bb4429af52058c1c12fddc2e9c0c149ed76813a
Build Date 2023-10-02T00:32:01Z
```

**Comment by bjp232004** [comment]
other two points w

**Comment by bjp232004** [comment]
Point# 2 & 3 put on hold.
