### ISSUE TITLE
OpenID Connect authentification

### ISSUE THREAD

**Issue by genofire** [openobserve/openobserve#1626]
### Which OpenObserve functionalities are relevant/related to the feature request?

users

### Description

like to use central usermanagement:
  - user with permission
  - maybe group-mapping of usermanagement to organisation of openobserve

### Proposed solution

OIDC

### Alternatives considered

Ldap or Header by proxy

**Comment by hengfeiyang** [comment]
we already support OpenID by https://dexidp.io/, it is an enterprise feature, you for small company you can use it for free.
