### ISSUE TITLE
Invalid SQL Syntax appears on the log search page

### ISSUE THREAD

**Issue by xinjie-sunshine** [openobserve/openobserve#1627]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

No

### Description

I used the public. ecr. aws/zinlabs/openobserve: v0.6.3 version deployed by Docker. After installation, I wrote sample data through curl, but when searching on the log search page, an Invalid SQL Syntax error was reported. I can query the data in both the data flow menu and dashboard menu. What is the reason for this?

![image](https://github.com/openobserve/openobserve/assets/52701892/795460ae-d7d1-4ab6-850e-8f454eb1914f)
![1f572446777b7e708c94064b5bb87ca](https://github.com/openobserve/openobserve/assets/52701892/eef660c3-904b-4aba-ba00-77f6139ff4ad)
![image](https://github.com/openobserve/openobserve/assets/52701892/70fcedbc-7191-4703-bd1b-9db909ef4926)

### Please provide the exception or error you saw

```true
log search page  Invalid SQL Syntax
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
public.ecr.aws/zinclabs/openobserve:v0.6.3
CentOS Linux release 7.6.1810 (Core)
```

**Comment by prabhatsharma** [comment]
Can you try 0.6.4

**Comment by xinjie-sunshine** [comment]
I have tested versions 0.6.4 and 0.5.2, and the problem still exists

**Comment by hengfeiyang** [comment]
Can you share the logs of OpenObserve use `docker logs` maybe it reports some error logs

**Comment by xinjie-sunshine** [comment]
![image](https://github.com/openobserve/openobserve/assets/52701892/2907ccf8-150f-4065-abd1-cedb95e69f4a)
No obvious error logs were found in the logs

**Comment by hengfeiyang** [comment]
You shared logs nothing related search, Can you search again and to reproduce the error and then check the logs.

**Comment by xinjie-sunshine** [comment]
I reproduced the error, but there was no error log in the log. However, I saw an error on the console of the browser console. Does this error have an impact?

![image](https://github.com/openobserve/openobserve/assets/52701892/1d38892c-d547-404b-8f8e-974724aa1b98)

**Comment by hengfeiyang** [comment]
The error looks like response by the backend. Can you check the HTTP request payload in the chrome of search request.
