### ISSUE TITLE
panic if wal json file not correct

### ISSUE THREAD

**Issue by domyway** [openobserve/openobserve#1642]
### Which OpenObserve functionalities are the source of the bug?

ingestion

### Is this a regression?

No

### Description

 if wal json file not correct, oo will panic.  I believe that we should skip JSON files with formatting errors and log the errors, then proceed with execution. Incorrect file data can be lost, but we shouldn't panic and halt the service. Additionally, when opening JSON files, we should validate the file extension, as using text editing tools like VIM might leave behind .swp files, which could cause the program to panic.

### Please provide the exception or error you saw

```true
[2023-10-12T11:31:10Z INFO  openobserve::service::db::syslog] SyslogServer settings Cached
thread 'main' panicked at 'parse wal file list failed:
file: /data/wal/file_list/0/2023/10/12/00/7118095654391521280P6hLAv.json
line_no: 10
line: {"key":"files/default/traces/default/2023/10{"key":"files/default/traces/default/2023/10/12/00/service_name=charge-virtual-device/7118096418987974656z0KICV.parquet","meta":{"min_ts":1697085044559000,"max_ts":1697085655543227,"records":78,"original_size":188249,"compressed_size":36943},"deleted":false}
err: expected `,` or `}` at line 1 column 47', /app/src/service/db/file_list/local.rs:92:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
v0.6.4
```

**Comment by hengfeiyang** [comment]
We need a better WAL solution.🤔

**Comment by domyway** [comment]
```
thread 'main' panicked at /app/src/service/db/file_list/local.rs:92:21:
parse wal file list failed:
file: /data/wal/file_list/0/2023/11/21/13/7132721327416438784nW1ULs.json
line_no: 3
line:
err: expected value at line 1 column 1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```


happend again , any progress about this issue?
