### ISSUE TITLE
VRL failure

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#1643]
### Which OpenObserve functionalities are the source of the bug?

functions

### Is this a regression?

Yes

### Description

This function results in `Error: Search SQL execute error.116` :

```javascript
vendor = .fields_sc4s_vendor

if vendor=="pan" {
    log = parse_csv!(event)
} else if vendor=="Thycoti: Software" {
    log = parse_cef!(.event) 
}
.
```

To reproduce follow the below steps and try to execute the above function:

```shell
wget https://github.com/openobserve/openobserve/releases/download/v0.6.4/cef1.json.zip
unzip cef1.json.zip
curl http://localhost:5080/api/default/filrewall/_json -i -u "root@example.com:Complexpass#123"  -d "@cef1.json"
```

### Please provide the version you discovered this bug in (check about page for version information)

Version
Commit Hash
Build Date
v0.6.4
0bb4429af52058c1c12fddc2e9c0c149ed76813a
2023-10-02T00:22:07Z

**Comment by oasisk** [comment]
@prabhatsharma the function should be:

vendor = .fields_sc4s_vendor

if vendor=="pan" {
    log = parse_csv!(.event)
} else if vendor=="Thycoti: Software" {
    log = parse_cef!(.event) 
}
.

**Comment by prabhatsharma** [comment]
```vendor = .fields_sc4s_vendor

if vendor=="pan" {
    .log = parse_csv!(.event)
} else if vendor=="Thycoti: Software" {
    .log = parse_cef!(.event)
}
.
```
