### ISSUE TITLE
Descriptive SQL error messages

### ISSUE THREAD

**Issue by mr-karan** [openobserve/openobserve#1644]
### Description

When there's any issue in the SQL, the UI shows `Error: Search SQL execute error.116`. This lacks any context/meaningful information to debug and fix the issue. The user is left clueless as to what the actual issue is which caused it.

![image](https://github.com/openobserve/openobserve/assets/5689132/8d204b07-509c-4838-a918-463b0622afde)

### Proposed solution

On inspecting the response of `/api/default/_search?type=logs`, I could see an appropriate response code/descriptive error message:

```json
{
    "code": 20008,
    "message": "Search SQL execute error",
    "error_detail": "Schema error: No field named abc. Valid fields are tbl._hostname, tbl._timestamp, ..."
}
```

This is really helpful and will be great if the UI can show the same.

### Alternatives considered

Inspect network tab to see the actual backend response.

**Comment by hengfeiyang** [comment]
@bjp232004 First, i will fix the `message` from backend. Second, you should show the `message` from backend to the frontend. Becuase in the frontend only tell the user `field not found`, `function not found`, but the message from the backend give the message like this:

```
{
    "code": 20005,
    "message": "Search function not defined: match_all",
    "error_detail": ""
}
```

Then the user will know which `function` and `field` not found.
