### ISSUE TITLE
Copy to clipboard doesn't work

### ISSUE THREAD

**Issue by mr-karan** [openobserve/openobserve#1645]
### Which OpenObserve functionalities are the source of the bug?

log search, dashboards

### Is this a regression?

No

### Description

On Linux, Chrome `(Version 117.0.5938.149 (Official Build) (64-bit))`, the copy to clipboard is not working. Tried multiple times, but the clipboard is empty

### Please provide the exception or error you saw

```true
No errors.
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.6.4
Commit Hash: 0bb4429af52058c1c12fddc2e9c0c149ed76813a
Build Date: 2023-10-02T00:32:01Z
```
```


### Anything else?

_No response_

**Comment by hengfeiyang** [comment]
should work now
