### ISSUE TITLE
Missing logs in UI

### ISSUE THREAD

**Issue by mr-karan** [openobserve/openobserve#1647]
### Which OpenObserve functionalities are the source of the bug?

log search, dashboards, streams

### Is this a regression?

No

### Description

On searching for `nomad_namespace=kite-charts`, I see no response in the SQL query:

![image](https://github.com/openobserve/openobserve/assets/5689132/078b3d01-9646-471d-bab3-4b58773a2c67)

However, when I simply select the relevant namespace from the side panel (dropdown selection for `nomad_namespace` field), I can see the highlighted logs which match the word `kite-charts`.

![image](https://github.com/openobserve/openobserve/assets/5689132/be53bc63-d3df-414e-9220-64270556331c)

![image](https://github.com/openobserve/openobserve/assets/5689132/8a9135f8-94d6-4650-a8b4-09e67d8c45a7)

I can even confirm that unless I hit `run query` button, I can see the logs on the main dashboard. But when I search for them (after sending the API call), I see no results.

Here's the cURL after redacting a few fields:

```sh
curl 'http://openobserve.redacted.tld:5080/api/default/_search?type=logs' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: en-US,en;q=0.9' \
  -H 'Authorization: Basic REDACTED==' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Origin: http://openobserve.redacted.tld:5080' \
  -H 'Pragma: no-cache' \
  -H 'Referer: http://openobserve.redacted.tld:5080/web/logs?stream=debug_v3&period=10m&refresh=0&sql_mode=false&query=bm9tYWRfbmFtZXNwYWNlPSdraXRlLWNoYXJ0cyc=&org_identifier=default' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36' \
  --data-raw $'{"query":{"sql":"select * from \\"debug_v3\\"  WHERE nomad_namespace=\'kite-charts\'","start_time":1697181036834000,"end_time":1697181636834000,"from":0,"size":150},"aggs":{"histogram":"select histogram(_timestamp, \'10 second\') AS zo_sql_key, count(*) AS zo_sql_num from query GROUP BY zo_sql_key ORDER BY zo_sql_key"}}' \
  --compressed \
  --insecure
  ```
  
  The response:
  
  ```json
  {
    "took": 5,
    "took_detail": {
        "total": 7,
        "wait_queue": 0,
        "cluster_total": 7,
        "cluster_wait_queue": 2
    },
    "hits": [],
    "total": 0,
    "from": 0,
    "size": 150,
    "scan_size": 0
}
```

Let me know if you need any more details

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.6.4
Commit Hash: 0bb4429af52058c1c12fddc2e9c0c149ed76813a
Build Date: 2023-10-02T00:32:01Z
```

**Comment by mr-karan** [comment]
Something that maybe relevant: I added a partition key using `nomad_namespace` _while_ the logs are being ingested around that time.

![image](https://github.com/openobserve/openobserve/assets/5689132/2dfb232b-9c96-4a99-b4f3-6169de79b675)


The API response has the data till 10:27 only, which is when I think I made the above change ^

![image](https://github.com/openobserve/openobserve/assets/5689132/ef455266-18ef-4d55-8923-e922bfb62ac3)

**Comment by mr-karan** [comment]
Update: I unchecked the partition key and now I can see the latest logs on UI (_post_ this change):

![image](https://github.com/openobserve/openobserve/assets/5689132/4f54f34a-5dc3-4e0a-bf22-140a12d4309c)

However, logs during this time range where the partition key was selected are missing :scream: Are they lost?

![image](https://github.com/openobserve/openobserve/assets/5689132/2eb70802-2342-45b8-b69d-0f603f451267)

**Comment by hengfeiyang** [comment]
Data shouldn't lost, because we don't delete data, maybe some bug case can't be queried. I will check it. and try to reproduce it. Thanks report.

**Comment by hengfeiyang** [comment]
I can't reproduce this error. maybe we can have a call about this.
