### ISSUE TITLE
Unbounded Memory Growth

### ISSUE THREAD

**Issue by mr-karan** [openobserve/openobserve#1648]
### Which OpenObserve functionalities are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Memory usage on the openobserve instance seems to be constantly growing:

![image](https://github.com/openobserve/openobserve/assets/5689132/d3bce097-620b-4a22-bf1b-a57c854eee60)

After midnight the rate of ingestion of logs is dramatically lesser compared to the day, but it results in constant memory being allocated for this instance. This graph is for Memory usage and doesn't include cache/buffers (RSS).

After I restarted the instance, I could see a drop in memory but it again shows inclination:

![image](https://github.com/openobserve/openobserve/assets/5689132/58395a2e-dc21-4f2c-831c-b1f52feecefb)

Will update this issue in a day or 2 attaching more screenshots if it helps.

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.6.4
Commit Hash: 0bb4429af52058c1c12fddc2e9c0c149ed76813a
Build Date: 2023-10-02T00:32:01Z
```

**Comment by hengfeiyang** [comment]
Can you provide some details about your instance:

1. Binary or docker?
2. What is the hardware resource, How many cores of CPU and the total memory size
3. What is your configure of OpenObserve

**Comment by hengfeiyang** [comment]
And this memory usage chart is about OpenObserve or the node total memory usage? Any other application run on the same node?

Can you add a dashboard for monitoring OpenObserve? we export some metrics https://openobserve.ai/docs/expose-metrics/

**Comment by mr-karan** [comment]
It's total memory usage but nothing apart from Openobserve runs on this instance. I'll setup metrics for Openobserve soon and update this thread.

**Comment by hengfeiyang** [comment]
First, We will try to use all memory for performance. 
Second, you can set some limits of the memory:

https://openobserve.ai/docs/environment-variables/

```
ZO_MEMORY_CACHE_MAX_SIZE = 4096
ZO_MEMORY_CACHE_DATAFUSION_MAX_SIZE = 4096
```

This will limit the query cache to 4GB, and limit the query engine memory pool to 4GB. And then this can limit the memory for the query to about 8GB memory.

But, The OpenObserve has other components, like: `Ingester`, `Compactor`, these also need memory, but the most part is the query. after you set these two environments, the memory of OpenObserve will be limited to about 10GB.

You can have a try. Thanks.

**Comment by mr-karan** [comment]
After setting the above 2 env variables, I can see that there's no unbounded memory growth anymore. Thanks for the explanation!
