### ISSUE TITLE
Data deleted but values not updated Home and streams page

### ISSUE THREAD

**Issue by neha00290** [openobserve/openobserve#1651]
home, streams

### Is this a regression?

Yes

### Description

Steps
- Go to steams and delete logs
- Start ingesting data again
-  Go to home and streams page
- Observe the data values

Expected - Deleted data values still appear on home and streams page

Actual result - Updated values to be displayed on both pages
<img width="418" alt="Screenshot 2023-10-13 at 7 38 05 PM" src="https://github.com/openobserve/openobserve/assets/144308844/4e1bcaf3-fc12-4eb8-a0eb-6d729a33675a">
<img width="1405" alt="Screenshot 2023-10-13 at 7 38 26 PM" src="https://github.com/openobserve/openobserve/assets/144308844/66aeb7a1-5f9b-40b6-8b84-abe8f6011b3b">
<img width="1458" alt="Screenshot 2023-10-13 at 7 43 02 PM" src="https://github.com/openobserve/openobserve/assets/144308844/a2dff0af-4978-41d8-8f20-24a097050fb8">

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version
Commit Hash
Build Date
v0.6.4
0bb4429af52058c1c12fddc2e9c0c149ed76813a
2023-10-02T00:20:13Z
```

**Comment by hengfeiyang** [comment]
I checked this issue, it should be no problem. 

The deletion is an async operation, it needs some time to be done, maybe 1 minute, maybe 10 minutes. 

And the stats calculation also is a backend job, it updates every 10 minutes.

So, we can check it after 10 minutes. it should work.
