### ISSUE TITLE
Escape a reserved word when is identical to a field name on SELECT clause is not possible - Search SQL Mode

### ISSUE THREAD

**Issue by canob** [openobserve/openobserve#1652]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

No

### Description

Escape a reserved word when is identical to a field name on SELECT clause is not possible in SQL Mode on Log Search. You can escape it in WHERE clause using double quotes, but not in SELECT clause.
For example:
`SELECT type, action, to FROM "firewall"`
Is not working, because I cannot escape "to" field with anything.
![imagen](https://github.com/openobserve/openobserve/assets/30271927/3efad713-e1f4-4515-934a-ada3225a0f66)

### Please provide the exception or error you saw

```true
Error: Search SQL execute error.116
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.6.4
Commit Hash: 0bb4429af52058c1c12fddc2e9c0c149ed76813a
Build Date: 2023-10-02T00:32:01Z
OS: Ubuntu 22.04, OpenObserve Docker Image
```

**Comment by hengfeiyang** [comment]
Just use a double quote for the field like this:

```sql
SELECT fn, "to" FROM "test3" 
```

**Comment by hengfeiyang** [comment]
For your case, can you share the error detail (response for the search request) by chrome console?

**Comment by canob** [comment]
Hi @hengfeiyang ,
I'm an idiot. I review again my query, and I'm trying to SUM on srcuser, and I need to COUNT on it, and that is the error.
Sorry for my stupidity, and thanks for your help.
Maybe in the future OpenObserve error messages can be more verbose about which is the exact error on SQL syntax, for dumb users like me.

**Comment by hengfeiyang** [comment]
@canob Yep, there is an issue report that  https://github.com/openobserve/openobserve/issues/1644
