### ISSUE TITLE
Wrapping the search results log lines to enable quick glance at the logs without horizontal scroll

### ISSUE THREAD

**Issue by bikashmishra100** [openobserve/openobserve#1655]
### Which OpenObserve functionalities are relevant/related to the feature request?

log search

### Description

This is about wrapping the contents of log search to help avoid scrolling right.
![image](https://github.com/openobserve/openobserve/assets/2292713/0c1129ce-6ad3-4925-b6f1-ca82a2ac9b51)
![image](https://github.com/openobserve/openobserve/assets/2292713/a36f1686-eb0e-4e01-be79-0ee3f25928b2)

### Proposed solution

I was trying to make some local changes to see if this is possible. I am new to Vue. The QVirtualScroll control wraps a QMarkupTable and setting wrap-cells="true" makes the content wrapped. Not sure if this is the official way to do it.

### Alternatives considered

None

**Comment by cea5** [comment]
I also wish to implement this featrue

**Comment by cea5** [comment]
@bikashmishra100 Can you tell me where did you change the  "wrap-cells" ?

**Comment by bikashmishra100** [comment]
In the file web/src/plugins/logs/SearchResult.vue, I added these things to the q-virtual-scroll control.

1. wrap-cells="true"
2. There is a :style attribute. I added  wordBreak: 'break-word'

**Comment by OGSteve** [comment]
This would be extremely helpful and save a good bit of time. I do not see a word wrap toggle or option anywhere in the current UI. Was this removed?
