### ISSUE TITLE
SQL syntax in doc not working

### ISSUE THREAD

**Issue by pierrehenrymuller** [openobserve/openobserve#1667]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

No

### Description

In the doc here : https://openobserve.ai/docs/functions/
I understand that I can filter date with different function.

I would like to filter events by date and after with more complex filter based on date.
For beginning I would like to have have all lines on monday:
```
SELECT * FROM "default"  WHERE  extract(day FROM to_timestamp(syslog_timestamp)) = 1;
```
But I get an "Invalid syntax error"
I have test with field _timestamp in epoch format but with the same error.

There is an exemple for _timestamp:1697568469793280 and syslog_timestamp:Oct 17 20:47:47 

It seems like a bug and I have no information about which item is wrong in SQL syntax.
Thanks for help

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version v0.6.2
Commit Hash 4509c4da2a61d4d6bbdb58dca794a90cf2786ea2
Build Date 2023-09-21T13:33:04Z
```

**Comment by hengfeiyang** [comment]
I tested this SQL has no problem. `SELECT * FROM "default"  WHERE  extract(day FROM to_timestamp(syslog_timestamp)) = 1;`

The problem is your `syslog_timestamp` format can't be convert to `timestamp` , you can follow here: https://openobserve.ai/docs/functions/#to_timestamp

**Comment by pierrehenrymuller** [comment]
I have the same result with the _timestamp who is in epoch format like this : 
_timestamp:1698306621000000

And with this request I have also sql error :
`SELECT * FROM "default"  WHERE  extract(day FROM _timestamp) = 1;`

In the doc `source` of extract must be in timestamp, I suppose epoch time.
There is any debug info for SQL syntax to known where is the error?

**Comment by hengfeiyang** [comment]
You can try :
```
SELECT * FROM "default"  WHERE  extract(day FROM to_timestamp_micros(_timestamp)) = 26;
```

Our `_timestamp` is microseconds.
