### ISSUE TITLE
Need to see query statistics when histogram is not selected

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#1682]
### Which OpenObserve functionalities are relevant/related to the feature request?

log search

### Description

When histogram is deselected during log search, query statistics are not shown.

### Proposed solution

Query statistics should be shown when histogram is not shown.
<img width="650" alt="image" src="https://github.com/openobserve/openobserve/assets/4242188/59c716a5-3494-45fe-bd70-be1dd48fbdad">

### Alternatives considered

NA

**Comment by bjp232004** [comment]
Also, can you rename "Property Name" to "Field" and "Property Type"  to "Type"

![image](https://github.com/openobserve/openobserve/assets/551527/0ea8f2bd-aa60-4ad7-95cd-51f32b91ff7a)

**Comment by neha00290** [comment]
closing this ticket as fixed
