### ISSUE TITLE
Drop down selection doesn't work when filters are applied

### ISSUE THREAD

**Issue by mr-karan** [openobserve/openobserve#1685]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

No

### Description

When a filter is applied in the query, the dropdown bar in all fields show `No values found`:

![image](https://github.com/openobserve/openobserve/assets/5689132/56810691-ef77-4f99-8d83-096cb3017ef2)

However, when the filter isn't applied, then the dropdown selection works normally:

![image](https://github.com/openobserve/openobserve/assets/5689132/1b9c874e-d0fc-4ec6-9509-cbab0115075b)

### Please provide the version you discovered this bug in (check about page for version information)

```true
v0.6.4
```

**Comment by hengfeiyang** [comment]
fixed
