### ISSUE TITLE
is there a possibility to use multiple streams at a same time in Query Editor and get the results out of it ?

### ISSUE THREAD

**Issue by RVaidhy** [openobserve/openobserve#1692]
### Which OpenObserve functionalities are the source of the bug?

log search, streams

### Is this a regression?

No

### Description

Hi Team, 

We are using fluentd agent to collect the data and push it to openobserve like one stream per log file. In-order to distinguish the data from which log file it got generated we are using this approach. So here, if we wanted to include all the streams and query instead of a single stream, is it possible for us to execute queries that way ? or is it restricted one stream at a time under query editor. 

 

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version : - Release v0.6.4

Running in an EC2
```

**Comment by oasisk** [comment]
As of today we only support query on single stream.You can send all relevant data to single stream to query it .

**Comment by RVaidhy** [comment]
Thanks you Aashish for your confirmation. We shall plan accordingly. Thanks Much.
