### ISSUE TITLE
Some of the front-end UI fonts request a public address, which is not adapted to the intranet environment.

### ISSUE THREAD

**Issue by FengZh61** [openobserve/openobserve#1695]
### Which OpenObserve functionalities are relevant/related to the feature request?

other

### Description

Some of the front-end UI fonts request a public address, which is not adapted to the intranet environment.

https://fonts.googleapis.com/css2?family=Nunito+Sans:ital,wght@0,300;0,400;0,600;0,700;1,400;1,600;1,700&display=swap

### Proposed solution

Using native UI fonts

### Alternatives considered

No

**Comment by hengfeiyang** [comment]
dup #3067
