### ISSUE TITLE
How can I delete old data (or stream) ?

### ISSUE THREAD

**Issue by kentzhu** [openobserve/openobserve#170]
### Description

I try to storage my log data by ZincObserve. 
I plan to save data as `stream-yyyy-mm-dd`.
But how can I delete the old data? 
I didn't find any method to delete stream.

Thanks.

### Proposed solution

Maybe:
1. support delete whole stream.
2. support delete some data in stream by range.

### Alternatives considered

none

**Comment by hengfeiyang** [comment]
We use a different architecture compared to Elasticsearch, We store data by hours, and we have no inverted index, So we will be easy to delete old data. So:

- You don't need to create stream by day, this is a way from es, we suggest just create one stream
- We are developing a data lifecycle, then you can delete a stream or just set a policy for a stream, and it will auto-delete old data.

**Comment by hengfeiyang** [comment]
duplicated #182

**Comment by kentzhu** [comment]
So great! Thank you!
