### ISSUE TITLE
The partition field cannot be searched

### ISSUE THREAD

**Issue by chiikin** [openobserve/openobserve#1701]
### Which OpenObserve functionalities are the source of the bug?

traces

### Is this a regression?

Yes

### Description

I have a stream of traces with a partition field called “service_name”, and I am unable to query condition values that contain ‘.’ (dot).
For example, the following query statement returns an empty result.
```sql
and service_name='EP.API'
```
However, if I use the following statement, I can retrieve the results.
```sql
str_match( service_name,'EP.API')
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version
Commit Hash
Build Date
v0.6.4
0bb4429af52058c1c12fddc2e9c0c149ed76813a
2023-10-02T00:32:01Z
```

**Comment by hengfeiyang** [comment]
dup #1647 , fixed #1670
