### ISSUE TITLE
Re-query the value of a variable when changing the time range

### ISSUE THREAD

**Issue by mahuihuang** [openobserve/openobserve#1708]
### Which OpenObserve functionalities are relevant/related to the feature request?

dashboards

### Description

When I first enter the dashboard, the values of the variables are listed. I hope that when I change the time range, the values of the variables will be re-queried.

### Proposed solution

Add a dashboard switch option on settings. This option selects whether to enable re-querying variable values based on changes in the time range.

### Alternatives considered

Add the switch option on dashboard page.

**Comment by ktx-kirtan** [comment]
@mahuihuang That is already happening. When you change the time range, variable values reload. To verify, you can check the networks tab. However, if the value you selected is already there in the new data, it will keep the same value selected.
