### ISSUE TITLE
Dashboard variables support cascading queries

### ISSUE THREAD

**Issue by mahuihuang** [openobserve/openobserve#1709]
### Which OpenObserve functionalities are relevant/related to the feature request?

dashboards

### Description

When I configured two variables in the dashboard, the query condition of one variable depends on the value of the other variable. For example, when I query the pod logs of kubernetes, my first choice is to obtain the namespace, and then select the pod based on the namespace.

### Proposed solution

dashboard Variable support sql and promql

### Alternatives considered

*

**Comment by neha00290** [comment]
this is done
