### ISSUE TITLE
Text is not clearly visible on Hovering over options - RUM video page in dark mode 

### ISSUE THREAD

**Issue by neha00290** [openobserve/openobserve#1736]
### Which OpenObserve functionalities are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Steps
- Go to RUM video page
- Switch to dark mode
- Hover over the options on the RHS 
- Observe the text

<img width="355" alt="Screenshot 2023-10-23 at 11 23 11 PM" src="https://github.com/openobserve/openobserve/assets/144308844/307dc9e6-1c2d-4f32-a597-321ad1d91272">

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version
Commit Hash
Build Date
v0.6.4
be240a29e2679eb0e279f2a3ef645fdae48b75d7
2023-10-23T10:56:48Z
```

**Comment by gaby** [comment]
I also ran into this issue. It's been there since Dark mode was introduced.

**Comment by neha00290** [comment]
retested. this is fixed now. closing the same.
<img width="377" alt="Screenshot 2023-10-26 at 3 14 47 PM" src="https://github.com/openobserve/openobserve/assets/144308844/5fde16d2-dba6-445e-8756-395c5c12f230">
