### ISSUE TITLE
Is it safe to delete the `data/openobserve/db` directory

### ISSUE THREAD

**Issue by cheng6563** [openobserve/openobserve#1739]
I couldn't locate certain old data while performing a search, but I did find the corresponding files in the `data/openobserve/stream` directory. I suspect it may be a database issue, so I decided to delete the `data/openobserve/db` directory. After restarting, it appears to have returned to normal, but I'm somewhat concerned about any potential risks involved.

**Comment by hengfeiyang** [comment]
If you run in a single node, you already lost your data, because the `db` is real database information. You can't simply delete `db` directory to resolve any problem.

If you run in a cluster mode, local `db` directory as a local cache, after you delete it, it will auto-create after restart.

The OpenObserve store `log data` as parquet format into `stream` directory. and store `metadata` into `db` directory or `etcd`.

The metadata includes:

1. users
2. streams, schemas
3. dashboards
4. alerts
5. functions
6. progress offsets
7. parquet files index

**Comment by cheng6563** [comment]
> If you run in a single node, you already lost your data, because the `db` is real database information. You can't simply delete `db` directory to resolve any problem.
> 
> If you run in a cluster mode, local `db` directory as a local cache, after you delete it, it will auto-create after restart.
> 
> The OpenObserve store `log data` as parquet format into `stream` directory. and store `metadata` into `db` directory or `etcd`.
> 
> The metadata includes:
> 
> 1. users
> 2. streams, schemas
> 3. dashboards
> 4. alerts
> 5. functions
> 6. progress offsets
> 7. parquet files index

Thank you for your reply.
The actual problem I'm having is this
In the `data/openobserve/stream` directory I can see the file data from 2023-06.
But on the Stream page in the UI I can only see that the data starts from 2023-09-26, and also I can't search for data before that.
The reason for this issue would be that I did a version upgrade on 2023-09-26 from the original v0.5.x to the current v0.6.4.
So I tried clearing the database in my backup copy to allow it to be regenerated, and that did fix the problem of the data not being searchable.
Is there a way to rebuild the streams metadata separately?
![image](https://github.com/openobserve/openobserve/assets/15995816/d266a3ff-e998-4598-8465-43960d7848f5)
![image](https://github.com/openobserve/openobserve/assets/15995816/b37bb77d-2741-42a6-9505-3f13eccd2b0d)

**Comment by hengfeiyang** [comment]
Do you still have the backup data? Then you can copy the old data directory:

```
data/stream
data/db
```

with those data, you can manually run the migration first:

```
./openobserve migrate-file-list
```

It will read the data from `data/stream/file_list/` and import the old data into new db.

**Comment by cheng6563** [comment]
> Do you still have the backup data? Then you can copy the old data directory:
> 
> ```
> data/stream
> data/db
> ```
> 
> with those data, you can manually run the migration first:
> 
> ```
> ./openobserve migrate-file-list
> ```
> 
> It will read the data from `data/stream/file_list/` and import the old data into new db.

This command worked, thanks!
