### ISSUE TITLE
clicking the  menu leaves the page blank

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#1742]
### Which OpenObserve functionalities are the source of the bug?

real user monitoring

### Is this a regression?

Yes

### Description

Check the attached video 

https://github.com/openobserve/openobserve/assets/4242188/715e08a3-a6b2-445f-ba6c-9f03636052e3

### Please provide the version you discovered this bug in (check about page for version information)

```true
main branch
```

**Comment by neha00290** [comment]
testing is complete. will close post release
