### ISSUE TITLE
On the metrics page, adding the dashboard reports an error!

### ISSUE THREAD

**Issue by FengZh61** [openobserve/openobserve#1757]
### Which OpenObserve functionalities are the source of the bug?

dashboards

### Is this a regression?

No

### Description

# Creating a new dashboard
![image](https://github.com/openobserve/openobserve/assets/98309003/bcdd72e5-8038-4c71-8d69-a04784ef39dc)

## Dashboard created
![image](https://github.com/openobserve/openobserve/assets/98309003/7d9402d2-b2b8-4fdf-9037-0c972d181633)

## It's empty.
![image](https://github.com/openobserve/openobserve/assets/98309003/9e5f044a-3834-46a8-acb4-2e55ee9b7315)

# Add to an existing dashboard

## Clicked Add and jumped to the dashboard page
![image](https://github.com/openobserve/openobserve/assets/98309003/25b354b5-4add-46c0-910b-31bf78500d79)

![image](https://github.com/openobserve/openobserve/assets/98309003/a76f99ed-6515-42a7-b7b8-fb8898380530)

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version v0.6.4
Commit Hash 0bb4429af52058c1c12fddc2e9c0c149ed76813a
Build Date 2023-10-02T00:04:43Z
```

**Comment by neha00290** [comment]
testing is done. no issues found
