### ISSUE TITLE
Folder creation and dashboard mismatch when creating a dashboard via metrics, Unable to find the folder created as well

### ISSUE THREAD

**Issue by neha00290** [openobserve/openobserve#1791]
### Which OpenObserve functionalities are the source of the bug?

metrics

### Is this a regression?

Yes

### Description

Steps -

- Create a dashboard
- Go to any folder that has dashboard
- Select a dashboard.
- Now switch the folder to the one that has no dashboards.
- Create this dashboard and observe if it is created in the folder

https://github.com/openobserve/openobserve/assets/144308844/462c5975-cd1a-4191-ba92-4bc15ae21db2

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version
Commit Hash
Build Date
v0.6.4
0bb4429af52058c1c12fddc2e9c0c149ed76813a
2023-10-02T00:32:01Z
```

**Comment by ktx-kirtan** [comment]
This has been fixed

**Comment by neha00290** [comment]
this is fixed and retested. No issues found
