### ISSUE TITLE
Support Grafana reading metrics stream

### ISSUE THREAD

**Issue by mahuihuang** [openobserve/openobserve#1798]
### Which OpenObserve functionalities are relevant/related to the feature request?

metrics, other

### Description

Compatible with prometheus query API, you can add prometheus datasource in grafana

### Proposed solution

*

### Alternatives considered

*

**Comment by hengfeiyang** [comment]
We provide the Prometheus API, with a compatibility of 90%. You can configure OpenObserve as a Grafana data source like this:
```
http://localhost:5080/api/default/prometheus
```
And enable `HTTP Basic` authentication.

**Comment by gaby** [comment]
@hengfeiyang Is that 90% compatibility still the case. Are there plans to make that 100% ?

**Comment by hengfeiyang** [comment]
😄 100% it is too difficult. but you can try, if you find something we don't support, please tell me.

**Comment by gaby** [comment]
@hengfeiyang Will do, thanks! Whats the diffence between using the approach suggested above and this https://openobserve.ai/docs/operator-guide/grafana_plugin/ ?

**Comment by hengfeiyang** [comment]
`Grafana plugin` just for query logs in Grafana.

**Comment by prabhatsharma** [comment]
@gaby grafana plugin provides following capabilities - query logs in grafana, build dashboards in grafana for logs.

Grafana supports multiple data sources. One of them is prometheus. If you want OpenObserve metrics in grafana then you can configure grafana to use OpenObserve as a prometheus source.

**Comment by gaby** [comment]
@prabhatsharma I was interested in using Grafana as the UI, and OpenObserve and the backend/storage of metrics/logs/traces.

**Comment by coutouly** [comment]
the http://localhost:5080/api/default/prometheus/ doesnt work in grafana last version

**Comment by hengfeiyang** [comment]
@coutouly use `http://localhost:5080/api/default/prometheus` and `Basic Auth`, please try again.
