### ISSUE TITLE
IoError# No such file or directory (os error 2)

### ISSUE THREAD

**Issue by domyway** [openobserve/openobserve#1808]
### Which OpenObserve functionalities are the source of the bug?

traces

### Is this a regression?

Yes

### Description

it seems when search in ingester, wal file has already been deleted , so search result return  "IoError# No such file or directory (os error 2)" , after a while, do the search again and everything alright.

this case need to be improved

### Please provide the version you discovered this bug in (check about page for version information)

```true
v0.6.4
```

**Comment by hengfeiyang** [comment]
Related to #1856
