### ISSUE TITLE
Add tini as parent process management in dockerfile

### ISSUE THREAD

**Issue by cooting-cn** [openobserve/openobserve#1853]
### Description

Add tini as the parent process management during container operation to prevent it from becoming a zombie process during container operation

### Proposed solution

RUN ["/openobserve", "init-dir", "-p", "/data/"]
ENTRYPOINT ["tini", "-g", "--"]
CMD ["/openobserve"]

### Alternatives considered

无

**Comment by prabhatsharma** [comment]
I am not sure if we need this functionality, especially since in most production scenarios OpenObserve will be run in kubernetes and tini does not really add value there as kubelet handles such responsibilities already.
