### ISSUE TITLE
Improve ingest storage design

### ISSUE THREAD

**Issue by hengfeiyang** [openobserve/openobserve#1856]
### Which OpenObserve functionalities are relevant/related to the feature request?

ingestion

### Description

Our current system creates a WAL (Write-Ahead Log) file for each stream, based on the schema hash. This file is used for both data ingestion, where JSON data is written into it, and data retrieval, where it is read to find the latest data. However, this approach is presenting several issues:

1. **Lack of Checksum for WAL Files:** Our system does not generate a checksum for the WAL files. Consequently, in the event of a system crash, the file may become corrupted. Currently, we identify corrupted entries by attempting to parse the file line by line in JSON. If parsing fails, we assume the line is corrupted and discard it. This method is not only inefficient but also risks loss of valuable data. 

2. **Inefficient Data Searching:** Searching within the JSON file is not efficient, slowing down data retrieval processes.

3. **Inefficient Data Ingestion:** The current method of data ingestion also lacks efficiency, potentially slowing down data processing.

4. **IOPS Issue during Metrics Ingestion:** The Prometheus remote-write provides all the metrics data in a single request. Since we have a WAL file for each stream, we end up writing to thousands of files per request. This process is causing an IOPS (Input/Output Operations Per Second) issue.

5. **Search Error during WAL File Transition:** Errors occur when searching the WAL file while it is being moved to S3 and subsequently deleted.

6. **Increased Load on Ingester:** If a user consistently searches for the most recent 15 minutes of data, it may cause an excessive load on the ingester.

We need to address these issues to improve the efficiency, reliability, and performance of our ingestion storage system.

### Proposed solution

todo

**Comment by domyway** [comment]
I think router should support grpc ingest. because when use otel grpc export data to oo ingester directly ,  most traffic export to ingester-0 because of statfulset deploy one by one . and other ingester has no any traffic almostly

**Comment by hengfeiyang** [comment]
@domyway router for gRPC we will do that.

**Comment by hengfeiyang** [comment]
The answer for these issues:

1. add checksum
2. searching with Arrow file
3. maybe, it is faster now
4. write into a few big files, use kv or memory table
5. delay deletion or add locker for using file
6. after switch to Arrow format maybe faster, and we also can use sidecar mode

**Comment by oasisk** [comment]
![image](https://github.com/openobserve/openobserve/assets/35160958/cdb2b443-fb84-4bbb-a790-782ab07f6a81)

**Comment by hengfeiyang** [comment]
@domyway Report a new issue, Even though he was searching for the data 2 hours ago,  but the ingester still searched in WAL.

The reason is we don't know if the WAL contains the data belonging to 2 hours ago. because we don't know the time range in a JSON file we have to search it if contains the data 2 hours ago. especially, when we enable daily partition for traces.
