### ISSUE TITLE
Keep the header style unify

### ISSUE THREAD

**Issue by hengfeiyang** [openobserve/openobserve#1862]
### Description

Logs header
<img width="815" alt="image" src="https://github.com/openobserve/openobserve/assets/1628250/84a53509-4bc5-41c8-8fe4-fdcc6450ae05">

Traces header
<img width="793" alt="image" src="https://github.com/openobserve/openobserve/assets/1628250/b468aa21-a07c-47e6-ac52-2015614d207a">

Metrics header
<img width="724" alt="image" src="https://github.com/openobserve/openobserve/assets/1628250/e1110298-3129-4b54-a749-ce7a3da6fc12">

### Proposed solution

I have some suggestions:

1. both of these headers should keep the same size
2. the export button should be kept at the end
3. the traces header should add a bottom line

### Alternatives considered

no

**Comment by neha00290** [comment]
@hengfeiyang please confirm if any more changes needed, tested the same.works fine

**Comment by hengfeiyang** [comment]
@neha00290 I talked to @bjp232004 there is a small issue still need to be fixed.
