### ISSUE TITLE
On deleting or creating a function- the state does not reset and user has to refresh the page

### ISSUE THREAD

**Issue by neha00290** [openobserve/openobserve#1867]
### Which OpenObserve functionalities are the source of the bug?

functions

### Is this a regression?

Yes

### Description

Steps
- Create/ Delete a function
- Observe if the function is deleted and disappear from the screen or new function created is displayed 

This happens after upgrading from 0.6.4 to current release

https://github.com/openobserve/openobserve/assets/144308844/47fa392d-79ac-4818-91c9-4c650936deb4

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version
Commit Hash
Build Date
v0.7.0-rc1
ad748795148952b1572ff54207b2edb6da79c13c
2023-11-03T17:19:08Z
```

**Comment by bjp232004** [comment]
I am not able to reproduce this issue. I have tried to multiple times to create and delete function but all times page refreshed with latest state.

**Comment by neha00290** [comment]
not able to replicate for now. will recheck and if I am able to replicate, will reopen the issue
