### ISSUE TITLE
Language translation & UI issue

### ISSUE THREAD

**Issue by bjp232004** [openobserve/openobserve#1869]
### Which OpenObserve functionalities are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

This issue cover all issue related to language translation text & UI issue because of translation.

https://docs.google.com/spreadsheets/d/1GxNhQb5vy_CF6LHFLuaODEyPzV1kTNHYiXADhwmGMS0/edit#gid=0

**Comment by neha00290** [comment]
closing this issue as fixed
