### ISSUE TITLE
Error while writing distinct values: Error# channel closed

### ISSUE THREAD

**Issue by domyway** [openobserve/openobserve#1873]
### Which OpenObserve functionalities are the source of the bug?

traces

### Is this a regression?

Yes

### Description

<img width="1269" alt="WX20231106-102042@2x" src="https://github.com/openobserve/openobserve/assets/2039546/ccb0f2e4-e076-46e2-ada5-955b295f03e5">

distinct values writing error after grpc shutdown

**Comment by hengfeiyang** [comment]
@domyway Thank you, the reason is we haven't do the graceful shutdown for gRPC, so maybe the gRPC still working after we close the db. we will fix it.
