### ISSUE TITLE
oo logs should print traceid 

### ISSUE THREAD

**Issue by domyway** [openobserve/openobserve#1904]
### Which OpenObserve functionalities are relevant/related to the feature request?

traces

### Description

oo logs should print traceid for a better way to trouble shooting

### Proposed solution

log with traceid 

### Alternatives considered

none

**Comment by hengfeiyang** [comment]
Maybe we should change the logs to `JSON` format and with the request-id context.

**Comment by hengfeiyang** [comment]
Already added session_id in logs
