### ISSUE TITLE
Please let us know you if you are using OpenObserve

### ISSUE THREAD

**Issue by hengfeiyang** [openobserve/openobserve#191]
### Which OpenObserve functionalities are relevant/related to the feature request?

other

### Description

Please let us know you if you are using OpenObserve. Thanks.

We would appreciate it if you could tell us your `company name`, `company website` and project name. Thank you.

**Comment by hengfeiyang** [comment]
We are the first user 😄

ZincLabs http://zinc.dev

**Comment by hanqian200705** [comment]
Grandsys 🍺🍺🍺

**Comment by eddyyuen** [comment]
一区科技 https://www.an1ai.com/

**Comment by loyous** [comment]
oh

**Comment by colorado666** [comment]
几米物联  https://www.jimiiot.com/   这款轻量的日志管理工具，非常好用

**Comment by Kua-Fu** [comment]
elasticsearch killer ！

**Comment by RogerLiNing** [comment]
我作为个人开发者，使用的是一个小的服务器，磁盘也比较小，但是我的NGINX日志每天可能有2~3GB，磁盘很快就会不够。但是使用observe之后，不仅可以压缩存储，还能查看分析。我还能把原日志文件给删除掉。 真是个好工具啊。

微信小程序《热血查线助手》

**Comment by mosajjal** [comment]
Just added zincobserve support to [dnsmonster](https://github.com/mosajjal/dnsmonster). Impressive compression ratio!
