### ISSUE TITLE
Use postgresql as`CLUSTER_COORDINATOR` db

### ISSUE THREAD

**Issue by gaetan-craft** [openobserve/openobserve#1915]
### Which OpenObserve functionalities are relevant/related to the feature request?

other

### Description

At the moment CLUSTER_COORDINATOR is set to etcd for non-local setup and to Sled/Sqlite for local setup.
Since there is plenty of managed postgresql services it might be convenient to use postgresql as database for CLUSTER_COORDINATOR. In local mode it will also help to have stateless servers without the hassle of maintaining an etcd cluster.
 

### Proposed solution

Not sure if it's viable to implement, it's more a question

### Alternatives considered

none

**Comment by hengfeiyang** [comment]
The `CLUSTER_COORDINATOR` just used for nodes communication, there will not store any data in `CLUSTER_COORDINATOR`.

so actually, the `etcd` is stateless when you using `PostgreSQL` as metastore.
https://openobserve.ai/docs/ha_deployment/#metadata-store
