### ISSUE TITLE
ZO_HTTP_ADDR and ZO_GRPC_ADDR are ignored for standalone exec

### ISSUE THREAD

**Issue by cbueche** [openobserve/openobserve#1929]
### Which OpenObserve functionalities are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

I'm using the standalone exec v6.4.0 on Ubuntu 20.04.6 LTS (tarball : openobserve-v0.6.4-linux-amd64.tar.gz). When setting this I expect the process to listen to 127.0.0.1:9080 and 127.0.0.1:9081:

```
ZO_HTTP_ADDR = 127.0.0.1
ZO_HTTP_PORT = 9080
ZO_HTTP_IPV6_ENABLED = false
ZO_GRPC_ADDR = 127.0.0.1
ZO_GRPC_PORT = 9081
```

It does respect the "PORT" settings, but seems to ignore the "ADDR" :

```
Nov 10 16:58:02 XXX openobserve[4128567]: [2023-11-10T15:58:02Z INFO  openobserve] starting gRPC server at 0.0.0.0:9081
Nov 10 16:58:02 XXX openobserve[4128567]: [2023-11-10T15:58:02Z INFO  actix_server::builder] starting 4 workers
Nov 10 16:58:02 XXX openobserve[4128567]: [2023-11-10T15:58:02Z INFO  actix_server::server] Tokio runtime found; starting in existing Tokio runtime
Nov 10 16:58:02 XXX openobserve[4128567]: [2023-11-10T15:58:02Z INFO  openobserve] starting HTTP server at: 0.0.0.0:9080, thread_id: 0
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version : v0.6.4
Commit Hash : 0bb4429af52058c1c12fddc2e9c0c149ed76813a
Build Date : 2023-10-02T00:02:44Z
```

**Comment by hengfeiyang** [comment]
Yep, the `ADDR` doesn't apply to the listener. will fix it soon.

**Comment by cbueche** [comment]
that's good news. If you want me to test a specific commit let me know, I'm still in the testing phase.
