### ISSUE TITLE
Login name does not support simple email form

### ISSUE THREAD

**Issue by dmitry-oshurkov** [openobserve/openobserve#1943]
### Which OpenObserve functionalities are the source of the bug?

login

### Is this a regression?

Yes

### Description

Login name does not support simple email form: ```user@host```.
user@host is valid email address.

**Comment by hengfeiyang** [comment]
Yep, you must set the email like `user@host.com`.

**Comment by a0s** [comment]
Is `somename@cluster.local` valid email for openobserve?

**Comment by prabhatsharma** [comment]
Yes
