### ISSUE TITLE
 Old stream still remains in the drop down when stream type is changed

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#1947]
### Which OpenObserve functionalities are the source of the bug?

dashboards

### Is this a regression?

Yes

### Description

Old stream still remains in the drop down when stream type is changed.

https://github.com/openobserve/openobserve/assets/4242188/762e30f1-25c6-47dd-8b00-0e38092c6ead

### Please provide the version you discovered this bug in (check about page for version information)

```true
v0.7.0
96e35d799c4f60130cb912b51497103773be33e4
2023-11-13T11:53:30Z
```

**Comment by neha00290** [comment]
this is fixed
