### ISSUE TITLE
The histogram x-axis is always using browser timezone, irrespective of the timezone selected

### ISSUE THREAD

**Issue by laurst** [openobserve/openobserve#1955]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

No

### Description

The histogram x-axis is always using browser timezone, irrespective of the timezone selected. It should instead be the selected timezone.

The hover is correctly using the selected timezone.

It is especially confusing when zooming in on a time range because what is shown on the x-axis (local time) doesn't match what the user will get.

See the screenshot below, where I have UTC selected. The hover is showing UTC, but the x-axis is using my system timezone (GMT+1 in my case).

![2023-11-16-14:01:38-screenshot](https://github.com/openobserve/openobserve/assets/44269292/33eaa070-a8a5-477f-bd51-6149b2479bd8)

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version
v0.7.0

Commit Hash
96e35d799c4f60130cb912b51497103773be33e4

Build Date
2023-11-13T11:30:08Z
```

**Comment by neha00290** [comment]
closing this issue as fixed
