### ISSUE TITLE
Ingestion tabs not visible in safari

### ISSUE THREAD

**Issue by prabirshrestha** [openobserve/openobserve#1967]
### Which OpenObserve functionalities are the source of the bug?

ingestion

### Is this a regression?

Yes

### Description

Safari is missing the "Recommended" and "Custom" tab in "Ingestion" page.

Safari:
![image](https://github.com/openobserve/openobserve/assets/287744/ff7ab7fa-f344-44f5-b19a-6e5590a2a38e)

Chrome:
![image](https://github.com/openobserve/openobserve/assets/287744/97110499-a909-4c7a-a400-1a21ab7c0264)

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.7.0
```

**Comment by neha00290** [comment]
closing this as fixed
