### ISSUE TITLE
Reg Enrichment table updation

### ISSUE THREAD

**Issue by RVaidhy** [openobserve/openobserve#1989]
### Which OpenObserve functionalities are the source of the bug?

functions, ingestion

### Is this a regression?

No

### Description

Hi Team,

We have implemented openobserve for our environment and we need some clarification regarding data enrichment updation. 
Since we need to update the enrichment data constantly and often in order to achieve the desired results under the logs section. 

1. If the enrichment data is changing (more than 1 record is changing) - deletion of enrichment stream and reinjection makes sense; but will this deletion of enrichment stream also delete the enriched columns in the log and needs to be recomputed?

2) If there are 1 or 2 new enrichment data records that needs to be added to existing one, and this new enrichment record is not going to impact older records and applicable only for newer records there should be a way to add these 1-2 new records every time it gets identified.. how can we do this?

Thanks in advance. 

Regards,
Vaidhy R

**Comment by oasisk** [comment]
@RVaidhy 

1.  If the enrichment data is changing (more than 1 record is changing) - deletion of enrichment stream and reinjection makes sense; but will this deletion of enrichment stream also delete the enriched columns in the log and needs to be recomputed? 
 **[OpenObserve]** : no already enriched data of streams(logs/metrics/traces) need not be recomputed 
 
For point 2 , let us come back to you.

**Comment by oasisk** [comment]
Point 2 is fixed by https://github.com/openobserve/openobserve/pull/2011

**Comment by RVaidhy** [comment]
Thanks Aashish. As recommended by you we are planning to use the 0.7.0 for our PROD deployment. Please update us on this thing once your testing is over. 

Thanks,
Vaidhy R
