### ISSUE TITLE
API should give 400 instead of 200 when adding empty payload for logs ingestion

### ISSUE THREAD

**Issue by neha00290** [openobserve/openobserve#1998]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

Steps -

API endpoint -
```
/api/{org_id}/{stream_name}/_json
```

Added payload  on pytest-
```
payload = [
       
    ]
```

Actual result - API gives 200 instead of 400

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version
Commit Hash
Build Date
v0.7.0
fbbb73b73404f3935bfb64677c13eaf430861a8b
2023-11-22T09:18:11Z
```

**Comment by hengfeiyang** [comment]
@neha00290 I think this is not a problem, it is a valid json format, just has zero items, and the API returns
```
{
	"code": 200,
	"status": [
		{
			"name": "default",
			"successful": 0,
			"failed": 0
		}
	]
}
```

it is expected.

**Comment by neha00290** [comment]
got it, thanks @hengfeiyang - closing this issue
