### ISSUE TITLE
Dashboard variables (Query values) - default option ALL / None should exist by default to ignore the filter

### ISSUE THREAD

**Issue by rgidda** [openobserve/openobserve#2000]
### Description

Dashboard variables (Query values) - default option ALL / None should exist by default .

Currently there is no option to ignore filter and to get complete data, It is very much helpful if we can add default value in the dropdown to to ignore the filters.

### Proposed solution

Currently there is no option to ignore filter and to get complete data, It is very much helpful if we can add default value in the dropdown to to ignore the filters.

### Alternatives considered

Currently there is no option to ignore filter and to get complete data, It is very much helpful if we can add default value in the dropdown to to ignore the filters.

**Comment by ktx-kirtan** [comment]
@rgidda We now have that option in the latest release
