### ISSUE TITLE
Traces - blank page displayed when user selects 6 months on the org which does not have enough data

### ISSUE THREAD

**Issue by neha00290** [openobserve/openobserve#2008]
### Which OpenObserve functionalities are the source of the bug?

traces

### Is this a regression?

Yes

### Description

https://github.com/openobserve/openobserve/assets/144308844/8e559f78-816e-4649-8498-5562a95c4fd7

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version
Commit Hash
Build Date
v0.7.0
fbbb73b73404f3935bfb64677c13eaf430861a8b
2023-11-22T09:18:11Z
```

**Comment by hengfeiyang** [comment]
I checked the error, it is because of the cluster communication, after restarting the pod, it works.

**Comment by neha00290** [comment]
thanks @hengfeiyang , closing this issue
