### ISSUE TITLE
[OTLP-Metrics] The http_server_duration metric data format is incorrectly stored

### ISSUE THREAD

**Issue by mingyifei** [openobserve/openobserve#2009]
### Which OpenObserve functionalities are the source of the bug?

streams, metrics

### Is this a regression?

Yes

### Description

**http_server_duration_sum** and **http_server_duration_count** should be used as separate streams

![image](https://github.com/openobserve/openobserve/assets/38995810/cd21b43d-25dc-4761-b38a-608db297ed23)

### Please provide the version you discovered this bug in (check about page for version information)

```true
v0.7.0
96e35d799c4f60130cb912b51497103773be33e4
2023-11-13T11:27:32Z
```

**Comment by GhostBoyBoy** [comment]
![image](https://github.com/openobserve/openobserve/assets/38995810/3a03c653-ca5b-45e8-a177-015762009701)

By the way, #2006 solves the problem of string formatting.
