### ISSUE TITLE
Variable dropdown in dashboads doesn't provide option for unselect/select

### ISSUE THREAD

**Issue by ranjanshashankhv** [openobserve/openobserve#2015]
### Which OpenObserve functionalities are the source of the bug?

dashboards

### Is this a regression?

No

### Description

Plot dashboard, create variable (say **test**), and reference the variable in custom query (select * from db where '**$test**'=something).
 Now when some value is selected from the dropdown, gets expected result, but there is no option to unselect test again once some value is selected from dropdown.
 
 **Example:**
 Initially pie(p1) loads in dashboard, now on selecting some value of variable from dropdown (test) an updated pie(p2) gets loaded, now there is now way to load pie(p1) again.

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: 0.6.4
```

**Comment by neha00290** [comment]
this is done
