### ISSUE TITLE
[OTLP-Metrics] Metrics store format error

### ISSUE THREAD

**Issue by GhostBoyBoy** [openobserve/openobserve#2020]
### Which OpenObserve functionalities are the source of the bug?

metrics

### Is this a regression?

Yes

### Description

Missing http_server_duration_bucket,http_client_duration_sum, http_client_duration_count, and http_client_duration_bucket

![21391700794775_ pic](https://github.com/openobserve/openobserve/assets/38995810/ea75ce7b-2a54-4a0c-803f-6134fe5ad97e)
![21441700794910_ pic](https://github.com/openobserve/openobserve/assets/38995810/92ba5b5e-6134-412d-8fbe-eaea8a9019b7)

**Comment by oasisk** [comment]
fixed by https://github.com/openobserve/openobserve/pull/2027
