### ISSUE TITLE
UI improvements for alerts

### ISSUE THREAD

**Issue by oasisk** [openobserve/openobserve#203]
### Which ZincObserve functionalities are the source of the bug?

alerts

### Is this a regression?

No

### Description

Alerts UI need below improvements: 

- [x] Better space management
- [x] Query validation 
- [x] Operators & values based on type of selected field for condition
- [x] Duration unit defaults
- [x] Preview query results for stream
- [x] Add PUT as an option for HTTP method support
- [x] Allow multiple destination for alerts
- [x] Separate destination creation 
- [x] Have option to add contextual information for sending alert

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version
v0.1.8
Commit Hash
e83a952232d38d8f422c663b4177d0ab547f96a8
Build Date
2023-03-06T10:37:08Z
```

**Comment by hengfeiyang** [comment]
For multiple destinations:

| Label | Type | Values |
|--|--|--|
| Method | Dropdown | POST, PUT, GET|
| URL | Input | -- |
| Authentication Header | Input | Name & Value |
| Body | Textarea | Json with template values |

We need to provide some `variables` for body templates.
