### ISSUE TITLE
TraceUI about list and trace detail page

### ISSUE THREAD

**Issue by domyway** [openobserve/openobserve#2037]
### Which OpenObserve functionalities are relevant/related to the feature request?

traces

### Description

1. the trace list page search form do not like jaeger which is easy to do some filter
2. should have a traceid detail page for sharing, and the detail should also improve.  jaeger detail, every span has process , tags, event region
3. detail page can search keyword, and the span Start Time is base on the first span start_time is 0 
<img width="1397" alt="image" src="https://github.com/openobserve/openobserve/assets/2039546/658d64f9-24ee-4114-94af-44719188460e">

### Proposed solution

copy jaeger

### Alternatives considered

none

**Comment by hengfeiyang** [comment]
## Traces index
1. The left fields list is not very useful. There are too many fields and most of those never been used, we often use `service_name` and `operation_name` but mixed in the fields list is not easy to find out. and the `service_name` is too many, the top 10 is not enough, the service_name what i need is not in the top 10, but i don't know what it is.
2. There is no duration range filter, we often use this filter in jaeger, but in the sql editor, we have to type it by hand, it's not convenient.
3. The filter is on the left side, but the time range is on the top right, it's not easy to use.
5. The sql editor is not very useful, we don't use it, and the business think it is a trouble.

![image](https://github.com/openobserve/openobserve/assets/1628250/32ad1e2e-296e-4d3e-b54e-f3988786e9ec)


## Traces detail
1. There is a big timeline in the top, it is too big, and actually we don't use it.
2. Jaeger has some details but OpenObserve has no, as the screenshot.

![image](https://github.com/openobserve/openobserve/assets/1628250/40fd63dd-f272-4cfd-8ccb-a1da83592b22)
3. The detail should also improve. jaeger detail, every span has process , tags, event region
4. detail page can search keyword, and the span Start Time is base on the first span start_time is 0
<img width="1393" alt="image" src="https://github.com/openobserve/openobserve/assets/1628250/817da9b4-8484-485a-b598-58b3322ccc06">

**Comment by domyway** [comment]
We are most concerned about the state of spans being 'error,' which is currently not very convenient in Jaeger. I think it can be done like this, pulling out 'span_status' to make it as convenient for filtering as 'operation_name' and others.

**Comment by prabhatsharma** [comment]
>We are most concerned about the state of spans being 'error,'

Understand this part on error state. We can figure out an UI for that.

Regarding other details, they are all available. Just differently than Jaeger. No details are missing compared to jaeger.

<img width="1568" alt="image" src="https://github.com/openobserve/openobserve/assets/4242188/96a21b32-ea95-433a-987d-18d275fa4fd0">

**Comment by domyway** [comment]
> > We are most concerned about the state of spans being 'error,'
> 
> Understand this part on error state. We can figure out an UI for that.
> 
> Regarding other details, they are all available. Just differently than Jaeger. No details are missing compared to jaeger.
> 
> <img alt="image" width="1568" src="https://private-user-images.githubusercontent.com/4242188/285724982-96a21b32-ea95-433a-987d-18d275fa4fd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNjQ4MzAsIm5iZiI6MTcwMTA2NDUzMCwicGF0aCI6Ii80MjQyMTg4LzI4NTcyNDk4Mi05NmEyMWIzMi1lYTk1LTQzM2EtOTg3ZC0xOGQyNzVmYTRmZDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjdUMDU1NTMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzdiYzJmMzJkMDBkYzg4YzdlZWIwNGUzOTBhM2U2MTU4NGJjOTcyMDY0OTYwZTkyMWRiYzVhNjdhMzhiYmYzOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5L9fqmqRi0sVo2TaInKu4OoS3ogUWpTLcY6_rRweAC0">

yes, but Jaeger UI's data display is better categorized, making it more convenient for problem localization.  oo can be better

**Comment by prabhatsharma** [comment]
We can look at better catgeorization. First set of actions we can do is:

1. Provide search capability for `service` and `operation` fields - in case of more services values lets say 500 values , we should offer typeahead
2. Provide min/max and slider for `duration` field. This will avoid extra typing
3. Add `StartTime` to the UI - on span details page

**Comment by domyway** [comment]
> We can look at better catgeorization. First set of actions we can do is:
> 
> 1. Provide search capability for `service` and `operation` fields - in case of more services values lets say 500 values , we should offer typeahead
> 2. Provide min/max and slider for `duration` field. This will avoid extra typing
> 3. Add `StartTime` to the UI - on span details page

good news~~
by the way, I think oo trace ui colors don't look very comfortable sometimes,  and  trace details page is presented as a modal, which is not user-friendly. Additionally, the modal has a small area, and it is not as effective for displaying a large amount of information in a well-organized manner as a complete page would be
