### ISSUE TITLE
Too slow for high dim data

### ISSUE THREAD

**Issue by wenerme** [openobserve/openobserve#2039]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

No

### Description

Use the apisix for request logging, include all querystring, this makes a lot of query keys.

A small query takes alot of time

<img width="1061" alt="image" src="https://github.com/openobserve/openobserve/assets/1777211/c391c46e-caad-400e-897b-495fe5675cae">

I dont find any previouse issues, so I create this one.

### Please provide the version you discovered this bug in (check about page for version information)

```true
- 版本 v0.7.0
- 提交ID 96e35d799c4f60130cb912b51497103773be33e4
- 编译时间 2023-11-13T11:53:30Z
```

**Comment by prabhatsharma** [comment]
Looks like something is wrong here. Your scan size is 0 MB. Have you set any partitions?

**Comment by wenerme** [comment]
```
[2023-11-27T04:37:18Z INFO  openobserve::service::search] search->grpc: result node: http://127.0.0.1:5081, is_querier: true, total: 0, took: 48610, files: 2, scan_size: 0
[2023-11-27T04:37:18Z INFO  openobserve::service::search] search->result: total: 217, took: 48694, scan_size: 0
```

Has result but size is zero

**Comment by hengfeiyang** [comment]
Do you have thousands fields?

**Comment by wenerme** [comment]
> Do you have thousands fields?

Maybe, I thinks this could be an attack vector, if I know a website use oo as logging, just post random query key & header to generate many keys, admin can not even open the oo logging panel.
