### ISSUE TITLE
Global variables in the chart, query data list, response content is incomplete.

### ISSUE THREAD

**Issue by GhostBoyBoy** [openobserve/openobserve#2040]
### Which OpenObserve functionalities are the source of the bug?

dashboards

### Is this a regression?

Yes

### Description
My interface list is about 50+, and the actual query limit length is 10.

![image](https://github.com/openobserve/openobserve/assets/38995810/259a6027-fd0a-4e58-ad3a-34722a2f2e57)

### Please provide the version you discovered this bug in (check about page for version information)

```true
v0.7.0
96e35d799c4f60130cb912b51497103773be33e4
2023-11-13T11:27:32Z
```

**Comment by prabhatsharma** [comment]
You can set the values here 
<img width="814" alt="image" src="https://github.com/openobserve/openobserve/assets/4242188/f5096b5e-905d-44be-90ee-d45d5b61dc2b">

**Comment by GhostBoyBoy** [comment]
thanks you
