### ISSUE TITLE
Why change license from Apache 2.0 to AGPL-3

### ISSUE THREAD

**Issue by cjen07** [openobserve/openobserve#2055]
My team is doing a survey on observability platform and will pick one to customize for our own product.
Just notice that you change the license, does this new license mean if we modify the software and sell this modified version as part of our product, this modified version must be open source?

**Comment by prabhatsharma** [comment]
Change of license was to keep the code available to everyone freely now and in the future. In absence of this, future code from contributors can be closed source and community and the developers will lose the benefit of open source.

Yes, if you modify the software and sell the modified version as part of your product the modified version of OpenObserve and your software (yes, your software too) need to be released as open source. You are free to sell both though without any obligation to OpenObserve team.

We would love for you to build your application on top of OpenObserve and make the source code available to everyone, so everyone can benefit from it.

We however understand that there may be scenarios where the requirements of AGPL may not be a right fit for your situation. If that is the case, please do reach out to us at hello@openobserve.ai, and we can help you figure out an alternate license.

**Comment by cjen07** [comment]
thanks a lot for explanation, will reach out by email later.
