### ISSUE TITLE
Metrics: HTTP endpoint to ingest metrics data

### ISSUE THREAD

**Issue by oasisk** [openobserve/openobserve#206]
## Design Spec:

POST `/api/:org/metrics/_json`
```json
{
    "metadata": [
        {
            "name": "metrics stream name",
            "metric_type": "counter / gauge / histogram / summary",
            "help": "help text"
        }
    ],
    "timeseries": [
        {
            "labels": {
                "__name__": "metrics stream name",
                "label_name1": "label_value1",
                "label_name2": "label_value2"
            },
            "samples": [
                {
                    "timestamp": 0, // unix timestamp in millisecond
                    "value": 0.0 // float64 value
                }
            ]
        }
    ]
}
```

This is the API design by Prometheus, but prometheus is gRPC protobuf, this is HTTP JSON.

## How to use this API:
- First call or when you add new metrics, You should provide `metadata`, we need to know the metric type.
- Next call, you can only provide `timeseries`
- Without `metadata`, it also can work in SQL mode, but for PromQL, you must provide `metric type`.

**Comment by hengfeiyang** [comment]
## Design Spec version 2:

- POST `/api/:org/_json/metrics`
- POST `/api/:org/_json?type=metrics`
- POST `/api/:org/ingest/metrics/_json`

```json
[
    {
        "__name__": "stream name",
        "__type__": "counter / gauge / histogram / summary",
        "label_name1": "label_value1",
        "label_name2": "label_value2",
        "_timestamp": 0, // unix timestamp in millisecond
        "value": 0.0 // float64 value
    }
]
```

## How to use this API:
- must use `__name__` set stream name.
- must use `__type__` set metrics type. and the type can't be updated after first record
- `_timestamp` need UNIX timestamp
- `value` should be float64 or int64
