### ISSUE TITLE
RBAC needed since users mistakenly changing functions (VRL) after seeing the code affects enrichment totally

### ISSUE THREAD

**Issue by RVaidhy** [openobserve/openobserve#2074]
### Which OpenObserve functionalities are the source of the bug?

home, users, functions

### Is this a regression?

Yes

### Description

Hi Team,

Greetings. 

We have been using Openobserve for our PROD system since from its 0.6.X onwards.
Since its being a centralised portal for our applications, while using the portal users are also opening the functions due the curiosity they got after seeing the enrichment part. Many times unknowingly they change something inside while looking at the statements and hitting 'Save' button to escape. One the VRL got corrupted the entire enrichment efforts are going vein.
Each and every time I am working on it to fix that. Requesting you to kindly provide Role Based Access Control feature so that we could restrict who could see what. This save us time and also the system can perform its enrichment part without interruption. 

Thanks,
R Vaidhy 

### Please provide a link to a minimal reproduction of the bug

N/A

### Please provide the exception or error you saw

```true
N/A
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
https://github.com/openobserve/openobserve/releases/download/v0.7.0/openobserve-v0.7.0-linux-amd64-musl.tar.gz

Release v0.7.0

 96e35d7
```

**Comment by prabhatsharma** [comment]
Available in enterprise version
