### ISSUE TITLE
When histogram is disabled only 150 logs are displayed in result

### ISSUE THREAD

**Issue by neha00290** [openobserve/openobserve#2079]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

Steps
1. Add absolute time 
2. Disable histogram
3. Click run query
4. Observe the results 

<img width="1399" alt="Screenshot 2023-11-28 at 7 59 54 PM" src="https://github.com/openobserve/openobserve/assets/144308844/519f451a-9ad5-4812-b85d-b6f4937a058e">

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version
Commit Hash
Build Date
v0.7.0
9f2facc6d0d76a5b1324c9f59d0ad29695cb4e90
2023-11-28T12:33:44Z
```

**Comment by keithlovingcats** [comment]
also shown in version v0.7.2, any idea when this will be fixed?

**Comment by prabhatsharma** [comment]
This has already been fixed. It will be available in the next release.
