### ISSUE TITLE
Etcd Interface to postgres

### ISSUE THREAD

**Issue by oasisk** [openobserve/openobserve#208]
### Which ZincObserve functionalities are relevant/related to the feature request?

other

### Description

We use etcd/sled db as metadata store, postgres should be one of the store for metadata.

### Proposed solution

Created etcd Interface to postgres , so that postgres can be used as metadata store

### Alternatives considered

NA

**Comment by rinshadka** [comment]
Hi,

Do we have a progress in this enhancement to keep postgreSQL as the metadata store.

Thanks.

**Comment by prabhatsharma** [comment]
> Do we have a progress in this enhancement to keep postgreSQL as the metadata store.

Not yet

**Comment by hengfeiyang** [comment]
It will be released in v0.5.3
