### ISSUE TITLE
The alarm task 50+ is queried very slowly

### ISSUE THREAD

**Issue by GhostBoyBoy** [openobserve/openobserve#2084]
### Which OpenObserve functionalities are the source of the bug?

alerts

### Is this a regression?

Yes

### Description

Now the query is queued and needs to wait for the current query result to finish before executing the next query task, if the previous task is a query 7 days and full text search sql, then it will be very slow.

### Please provide the version you discovered this bug in (check about page for version information)

```true
v0.7.0
96e35d799c4f60130cb912b51497103773be33e4
2023-11-13T11:27:32Z
```

**Comment by hengfeiyang** [comment]
Yes, it works like this. but today we have more about it:
- We have multiple `work group` in enterprise version, check the detail: https://openobserve.ai/docs/work_group/
- We have multiple `node group`, you can configure a `background` node group for alerts. `ZO_NODE_ROLE_GROUP`

At the end, if you have many alerts, maybe you should add some nodes.
