### ISSUE TITLE
Error displayed on setting a particular time range using absolute and then scrolling to the end of the result

### ISSUE THREAD

**Issue by neha00290** [openobserve/openobserve#2087]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

Steps
1. Set a particular time range 
2. Keep scrolling the results to view the logs
3. Observe that on reaching the bottom of the result, an error is displayed 

<img width="1353" alt="Screenshot 2023-11-29 at 9 58 14 AM" src="https://github.com/openobserve/openobserve/assets/144308844/b2c43c90-b6fa-48ad-98dd-545cddc6cb4d">

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version
Commit Hash
Build Date
v0.7.1
99d6f7afd9ec500bf6b59ad1dbdd730502cfa2b7
2023-11-28T16:27:37Z
```

**Comment by bjp232004** [comment]
This issue occurs based on the user's machine configuration and the volume of data in that stream as we are doubling the number of records in each call. As of now, not adding any restrictions on several records in each request.
