### ISSUE TITLE
Missing checkstyle.xml

### ISSUE THREAD

**Issue by GhostBoyBoy** [openobserve/openobserve#2102]
### Which OpenObserve functionalities are relevant/related to the feature request?

other

### Description

When everyone writes code, the format is not uniform

### Proposed solution

add checkstyle.xml

### Alternatives considered

none

**Comment by hengfeiyang** [comment]
Any suggestion? i am not sure we need it. we just use `cargo fmt`

**Comment by GhostBoyBoy** [comment]
> Any suggestion? i am not sure we need it. we just use `cargo fmt`

Should we customize a code format standard for checking during CI

**Comment by hengfeiyang** [comment]
any standard suggestion? or can you give some example in other projects. thanks.

**Comment by GhostBoyBoy** [comment]
> any standard suggestion? or can you give some example in other projects. thanks.

such as : 
![image](https://github.com/openobserve/openobserve/assets/38995810/554568c3-a24c-4421-a18e-1f39f7106246)

https://github.com/tikv/tikv/pull/16131
