### ISSUE TITLE
Failed to find city-database from path "/data/mmdb//GeoLite2-City.mmdb"

### ISSUE THREAD

**Issue by domyway** [openobserve/openobserve#2103]
### Which OpenObserve functionalities are the source of the bug?

traces

### Is this a regression?

Yes

### Description

[2023-12-01T03:33:09Z WARN  openobserve::job::mmdb_downloader] Failed to create MaxmindClient with path: /data/mmdb//GeoLite2-City.mmdb, Failed to find city-database from path "/data/mmdb//GeoLite2-City.mmdb"

**Comment by htdangkhoa** [comment]
Hi @hengfeiyang i'm try to install OpenObserve via helm chart, I'm also having this problem, can you tell me when this patch will be released?
Thanks

**Comment by hengfeiyang** [comment]
Next week will release the new version.

**Comment by htdangkhoa** [comment]
hi @hengfeiyang, It seems like the [v0.8.0](https://github.com/openobserve/openobserve/releases/tag/v0.8.0) release is missing this ticket, so when will this bug be fixed?

**Comment by hengfeiyang** [comment]
it should be fixed, Any problem for this?

**Comment by htdangkhoa** [comment]
@hengfeiyang I see in the v0.8.0 Changelog it does not include this issue

**Comment by hengfeiyang** [comment]
it is already fixed. do you still have any problem about this?

**Comment by htdangkhoa** [comment]
@hengfeiyang I confirm it fixed, the problem from my helm fetching from my side. Thank you for your supporting.
