### ISSUE TITLE
sql error

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#2113]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

Works

```sql
event='OpenObserve ' and properties_1 is not null
```

Results in

```
Error: Not a valid SQL.
```

Does not work

```sql
event='OpenObserve' and ((properties_1 is not null) or properties_1!=" ")
```

**Comment by hengfeiyang** [comment]
In the SQL we should use double quote for field and single quote for value, so you need change the SQL like this:

```sql
event='OpenObserve' and ((properties_1 is not null) or properties_1!=' ')
```

Then it will works.
