### ISSUE TITLE
stream names appear multiple times

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#2117]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

<img width="374" alt="image" src="https://github.com/openobserve/openobserve/assets/4242188/759cb0e0-6878-4629-8eb8-f258fe3a727c">

### Please provide the version you discovered this bug in (check about page for version information)

```true
v0.7.0
e4cd082a0c6ca9a508aee89dbb7db24a45997260
2023-11-29T14:32:35Z
```

**Comment by neha00290** [comment]
this is fixed
