### ISSUE TITLE
Multiple null in value list

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#2119]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

<img width="389" alt="image" src="https://github.com/openobserve/openobserve/assets/4242188/78cd4237-d8b4-49de-921f-eb4a88cea2f1">

### Please provide the version you discovered this bug in (check about page for version information)

```true
v0.7.2
99cdd1a94966695838d13cfd51725884f49ffe57
2023-12-01T15:02:12Z
```

**Comment by hengfeiyang** [comment]
fixed
