### ISSUE TITLE
Log query page UI masking

### ISSUE THREAD

**Issue by FengZh61** [openobserve/openobserve#2141]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

No

### Description

When you click on the details of a log, the description above the histogram will be obscured and restored after refreshing the page

![image](https://github.com/openobserve/openobserve/assets/98309003/8d99f8de-81ff-4944-9d55-ef39c53a4a95)

![image](https://github.com/openobserve/openobserve/assets/98309003/3cc20ee7-5018-45a8-b05f-9ea6439da221)

### Please provide the version you discovered this bug in (check about page for version information)

```true
v0.7.2
```

**Comment by hengfeiyang** [comment]
fixed
