### ISSUE TITLE
Normal query based on Trace Id, failed query based on HTTP route

### ISSUE THREAD

**Issue by GhostBoyBoy** [openobserve/openobserve#2147]
### Which OpenObserve functionalities are the source of the bug?

traces

### Is this a regression?

Yes

### Description

![image](https://github.com/openobserve/openobserve/assets/38995810/cc03d54f-3baf-4903-9eff-782f60bf373a)
![image](https://github.com/openobserve/openobserve/assets/38995810/071e915e-39fb-440f-b36e-4c48145ae990)

Request header: 
filter=operation_name=%27GET%20/ocr/api/case-detail-data/handle/before%27&start_time=1701859020000000&end_time=1701862620000000&from=0&size=25

Response results：
{
    "took": 602,
    "size": 25,
    "hits": [
        {
            "duration": 0,
            "end_time": 1701948382099558976,
            "first_event": null,
            "service_name": [],
            "spans": [
                0,
                0
            ],
            "start_time": 1701948307922747000,
            "trace_id": "e4bf404a32b0063433199c386720a4c2"
        },
        {
            "duration": 3936839,
            "end_time": 1701948011315886751,
            "first_event": {
                "_timestamp": 1701948007379047,
                "duration": 3936839,
                "end_time": 1701948011315886751,
                "operation_name": "POST /ocr/api/case-img-delayed-base64",
                "service_name": "mishu-robot-management",
                "span_status": "UNSET",
                "start_time": 1701948007379047000,
                "trace_id": "e201d2955fead5c2c421ab1bdd0cb1c6"
            },
            "service_name": [
                {
                    "count": 27,
                    "service_name": "mishu-robot-management"
                },
                {
                    "count": 3,
                    "service_name": "mishu-foreign-server"
                }
            ],
            "spans": [
                30,
                0
            ],
            "start_time": 1701948007379047000,
            "trace_id": "e201d2955fead5c2c421ab1bdd0cb1c6"
        },
        {
            "duration": 0,
            "end_time": 1701948383826329627,
            "first_event": null,
            "service_name": [],
            "spans": [
                0,
                0
            ],
            "start_time": 1701948374466249000,
            "trace_id": "ccc050e9959036beffe0dc72a5916502"
        },
        {
            "duration": 0,
            "end_time": 1701948239001613195,
            "first_event": null,
            "service_name": [],
            "spans": [
                0,
                0
            ],
            "start_time": 1701948196742797000,
            "trace_id": "c9419cb55df6c015ad040a0a976d3607"
        },
        {
            "duration": 0,
            "end_time": 1701948310788673895,
            "first_event": null,
            "service_name": [],
            "spans": [
                0,
                0
            ],
            "start_time": 1701948244278666000,
            "trace_id": "f7a050a498acce0f6c5e946182611827"
        },
        {
            "duration": 0,
            "end_time": 1701948116380896528,
            "first_event": null,
            "service_name": [],
            "spans": [
                0,
                0
            ],
            "start_time": 1701948086423433000,
            "trace_id": "a913712959b22e97f1f6efc572d162b7"
        },
        {
            "duration": 7994587,
            "end_time": 1701948052162140433,
            "first_event": {
                "_timestamp": 1701948035259327,
                "duration": 3329429,
                "end_time": 1701948038588756519,
                "operation_name": "POST /ocr/api/case-img-delayed-base64",
                "service_name": "mishu-robot-management",
                "span_status": "UNSET",
                "start_time": 1701948035259327000,
                "trace_id": "d28966b9dfd6c384c1d1eaaa760940ba"
            },
            "service_name": [
                {
                    "count": 11,
                    "service_name": "mishu-foreign-server"
                },
                {
                    "count": 270,
                    "service_name": "mishu-robot-management"
                }
            ],
            "spans": [
                281,
                0
            ],
            "start_time": 1701948035259327000,
            "trace_id": "d28966b9dfd6c384c1d1eaaa760940ba"
        },
        {
            "duration": 3531890,
            "end_time": 1701947989384847839,
            "first_event": {
                "_timestamp": 1701947985852957,
                "duration": 3531890,
                "end_time": 1701947989384847839,
                "operation_name": "POST /ocr/api/case-img-delayed-base64",
                "service_name": "mishu-robot-management",
                "span_status": "UNSET",
                "start_time": 1701947985852957000,
                "trace_id": "adbc9d508f66429171795f901483faa4"
            },
            "service_name": [
                {
                    "count": 3,
                    "service_name": "mishu-foreign-server"
                },
                {
                    "count": 29,
                    "service_name": "mishu-robot-management"
                }
            ],
            "spans": [
                32,
                0
            ],
            "start_time": 1701947985852957000,
            "trace_id": "adbc9d508f66429171795f901483faa4"
        },
        {
            "duration": 0,
            "end_time": 1701948358601781632,
            "first_event": null,
            "service_name": [],
            "spans": [
                0,
                0
            ],
            "start_time": 1701948350911911000,
            "trace_id": "42599a3db8fa18733544f4ce7ca7bdca"
        },
        {
            "duration": 0,
            "end_time": 1701948328048777224,
            "first_event": null,
            "service_name": [],
            "spans": [
                0,
                0
            ],
            "start_time": 1701948287008886000,
            "trace_id": "2a94b9049b5af2f2579263127549805b"
        },
        {
            "duration": 0,
            "end_time": 1701948378361408528,
            "first_event": null,
            "service_name": [],
            "spans": [
                0,
                0
            ],
            "start_time": 1701948372255904000,
            "trace_id": "9d1a34610a4a512c182a0f075a7f6198"
        },
        {
            "duration": 0,
            "end_time": 1701948172335973594,
            "first_event": null,
            "service_name": [],
            "spans": [
                0,
                0
            ],
            "start_time": 1701948141655347000,
            "trace_id": "a942dad748818f40ac89270428ddab2c"
        },
        {
            "duration": 8739021,
            "end_time": 1701948043657751328,
            "first_event": {
                "_timestamp": 1701948034918730,
                "duration": 8739021,
                "end_time": 1701948043657751328,
                "operation_name": "GET /ocr/api/case-diagnoses",
                "service_name": "mishu-robot-management",
                "span_status": "UNSET",
                "start_time": 1701948034918730000,
                "trace_id": "877933938d886b1eae192e65c44fc136"
            },
            "service_name": [
                {
                    "count": 94,
                    "service_name": "mishu-robot-management"
                },
                {
                    "count": 6,
                    "service_name": "mishu-foreign-server"
                }
            ],
            "spans": [
                100,
                0
            ],
            "start_time": 1701948034918730000,
            "trace_id": "877933938d886b1eae192e65c44fc136"
        },
        {
            "duration": 0,
            "end_time": 1701948318497772503,
            "first_event": null,
            "service_name": [],
            "spans": [
                0,
                0
            ],
            "start_time": 1701948310149704000,
            "trace_id": "19c3549eb74a2fb9e0ed14448e0ea867"
        },
        {
            "duration": 0,
            "end_time": 1701948253020583248,
            "first_event": null,
            "service_name": [],
            "spans": [
                0,
                0
            ],
            "start_time": 1701948172777615000,
            "trace_id": "59f2cba10884fb320e145462192b3908"
        },
        {
            "duration": 0,
            "end_time": 1701948374095959492,
            "first_event": null,
            "service_name": [],
            "spans": [
                0,
                0
            ],
            "start_time": 1701948363878036000,
            "trace_id": "00d18af511cccecd7cc25543f01f156a"
        },
        {
            "duration": 0,
            "end_time": 1701948329473616143,
            "first_event": null,
            "service_name": [],
            "spans": [
                0,
                0
            ],
            "start_time": 1701948309940914000,
            "trace_id": "b7db5816b77c4aa9a687de9b16411659"
        },
        {
            "duration": 17458001,
            "end_time": 1701948083476375843,
            "first_event": {
                "_timestamp": 1701947861848139,
                "duration": 53253,
                "end_time": 1701947861901392161,
                "operation_name": "POST /ocr/api/client/case/createCase",
                "service_name": "mishu-robot-management",
                "span_status": "UNSET",
                "start_time": 1701947861848139000,
                "trace_id": "d10e3fd91683af3ab64c6fc437676425"
            },
            "service_name": [
                {
                    "count": 60,
                    "service_name": "mishu-foreign-server"
                },
                {
                    "count": 464,
                    "service_name": "mishu-robot-management"
                }
            ],
            "spans": [
                524,
                0
            ],
            "start_time": 1701947861848139000,
            "trace_id": "d10e3fd91683af3ab64c6fc437676425"
        },
        {
            "duration": 24474888,
            "end_time": 1701948056686482888,
            "first_event": {
                "_timestamp": 1701947989914390,
                "duration": 14748597,
                "end_time": 1701948004662987567,
                "operation_name": "POST /ocr/api/case-img-delayed-base64",
                "service_name": "mishu-robot-management",
                "span_status": "UNSET",
                "start_time": 1701947989914390000,
                "trace_id": "865b3517a8f368f173791988d155f428"
            },
            "service_name": [
                {
                    "count": 150,
                    "service_name": "mishu-foreign-server"
                },
                {
                    "count": 7504,
                    "service_name": "mishu-robot-management"
                }
            ],
            "spans": [
                7654,
                0
            ],
            "start_time": 1701947989914390000,
            "trace_id": "865b3517a8f368f173791988d155f428"
        },
        {
            "duration": 0,
            "end_time": 1701948176968920918,
            "first_event": null,
            "service_name": [],
            "spans": [
                0,
                0
            ],
            "start_time": 1701948128137089000,
            "trace_id": "92d7172ef2505be8bf25ffc226aa14c9"
        },
        {
            "duration": 38998227,
            "end_time": 1701948028924699226,
            "first_event": {
                "_timestamp": 1701947989819849,
                "duration": 38998227,
                "end_time": 1701948028818076194,
                "operation_name": "GET /ocr/api/case-diagnoses",
                "service_name": "mishu-robot-management",
                "span_status": "UNSET",
                "start_time": 1701947989819849000,
                "trace_id": "8d6e5b66a2129b508ddc6ecb2a134770"
            },
            "service_name": [
                {
                    "count": 75,
                    "service_name": "mishu-foreign-server"
                },
                {
                    "count": 1272,
                    "service_name": "mishu-robot-management"
                }
            ],
            "spans": [
                1347,
                0
            ],
            "start_time": 1701947989819849000,
            "trace_id": "8d6e5b66a2129b508ddc6ecb2a134770"
        },
        {
            "duration": 0,
            "end_time": 1701948362755357681,
            "first_event": null,
            "service_name": [],
            "spans": [
                0,
                0
            ],
            "start_time": 1701948355571780000,
            "trace_id": "46e7491d1bf07d2370f49d0b84bda87d"
        },
        {
            "duration": 0,
            "end_time": 1701948196217454366,
            "first_event": null,
            "service_name": [],
            "spans": [
                0,
                0
            ],
            "start_time": 1701948152987336000,
            "trace_id": "268860ebdb4822d2f2a607e0d7d4c205"
        },
        {
            "duration": 0,
            "end_time": 1701948142603768506,
            "first_event": null,
            "service_name": [],
            "spans": [
                0,
                0
            ],
            "start_time": 1701948068020709000,
            "trace_id": "d7f8d1f9b10ddcbcc67ffa932366bf61"
        },
        {
            "duration": 5963486,
            "end_time": 1701947992890698065,
            "first_event": {
                "_timestamp": 1701947986927212,
                "duration": 5963486,
                "end_time": 1701947992890698065,
                "operation_name": "POST /ocr/api/case-img-delayed-base64",
                "service_name": "mishu-robot-management",
                "span_status": "UNSET",
                "start_time": 1701947986927212000,
                "trace_id": "d24176ffec83de695b31feb66583961f"
            },
            "service_name": [
                {
                    "count": 3,
                    "service_name": "mishu-foreign-server"
                },
                {
                    "count": 28,
                    "service_name": "mishu-robot-management"
                }
            ],
            "spans": [
                31,
                0
            ],
            "start_time": 1701947986927212000,
            "trace_id": "d24176ffec83de695b31feb66583961f"
        }
    ],
    "from": 0,
    "total": 25
}

### Please provide the version you discovered this bug in (check about page for version information)

```true
v0.7.1
99d6f7afd9ec500bf6b59ad1dbdd730502cfa2b7
2023-11-28T16:27:37Z
```

**Comment by hengfeiyang** [comment]
The problem is in your case there is no `service_name` in the response data, i will test it, thanks.

**Comment by hengfeiyang** [comment]
And i checked the backend the reason is in one sql we set the maximum `10000` of the limit, in the sql 
```sql
[2023-12-11T09:49:15Z INFO  openobserve::service::search::datafusion::exec] [session_id e1cb93fe-1cb1-4149-93fd-3bd186638a64] Query sql: SELECT _timestamp, trace_id, start_time, end_time, duration, service_name, operation_name, span_status FROM tbl WHERE (_timestamp >= 1702287254624000 AND _timestamp < 1702288154651017843) AND (trace_id IN ('bf195ee2c2f6bdb50edd8eefe66d1043','48c763d006c151688bdb5306e8ab4227','98d0f3b21aad1b2df6f83b1fb503267f','1edfbde4cacb787d792286fe0e37684e','21bda38d337d47b2031cb01d27898dd0','cfb1dbe789c58e61cc38f9c35f0900ae','e2a98cf3aa12d7f7b938d5535db781d7','e0973c0fc09bb619ce410688f215c75e','07f642e116f020d2f9120d6e7652a0ee','de1efae72d5e7f8f515ce72f8550e7a1','5b8b78645a4b6e0dceb59aa945580cf7','00d8edab01adbabc23aaff768821e3f3','fe3b8eead3a1f74e58455f4d0422cc4e','378c972d603bab09ba5a138cc9294934','f2ed52644c6f5495f0256aa40430a53c','7ca3b19458dcd2ca804a7bef6066a2b8','4066c7bc13c52cee543b7fa6a1cbba28','90d3a23e40daf8365e62b27a03ac4b9b','0cdbbad869443b01cb794331f3e85cbd','ef66dcbb25ccdb9c28f5f478616e2179','fb922a4ed13acc701858bba7dac4ad2a','61571dafb704bfc7930ce8dd9b1b7705','6ad281d2b86f61c4f0de9b2a2a00bf74','6645ecd8e01d7f89525a6c77040fc9cf','943dcc336a4985b908aef8f9b734e6cb')) ORDER BY _timestamp ASC LIMIT 9999
```

It has more than `10000` records, in your data that you gave me, per trace_id has 1614 spans, in this sql we need return about `30000` records to calculate the result.
