### ISSUE TITLE
Deleting Stream Associated Function doesn't work

### ISSUE THREAD

**Issue by Kalki5** [openobserve/openobserve#2151]
### Which OpenObserve functionalities are the source of the bug?

functions

### Is this a regression?

No

### Description

<img width="1552" alt="image" src="https://github.com/openobserve/openobserve/assets/20438413/64d5388d-c51d-486c-afe2-a1d3224ff037">
<img width="1552" alt="image" src="https://github.com/openobserve/openobserve/assets/20438413/d372928f-4ab9-41ed-9adc-bcae43812828">

I tried deleting the stream associated function and the UI doesn't respond at all. The Chrome Dev tools network tab shows that the Function is not found.

### Please provide the version you discovered this bug in (check about page for version information)

```true
Found it in the about page of OpenObserve cloud.
Version - v0.7.0
Commit Hash - 96e35d799c4f60130cb912b51497103773be33e4
Build Date - 2023-11-13T11:53:30Z
```

**Comment by prabhatsharma** [comment]
This is a UI problem. The stream is getting deleted, but the UI is not getting refreshed. 2nd time deleting the same stream generates 404.  Hard refresh of the page fixes this.

**Comment by bjp232004** [comment]
Not able to reproduce it now. May be fixed as a part of another issue.

I have tried to delete the association, worked fine for me. It's deleted from the list without a refresh.
I have tried to delete the stream first, in that case, it will not display the same stream and association as the stream got deleted.

Let me know if I missed any scenario.
