### ISSUE TITLE
(- ) allowed under threshold >> value dropdown

### ISSUE THREAD

**Issue by neha00290** [openobserve/openobserve#2168]
### Which OpenObserve functionalities are the source of the bug?

alerts

### Is this a regression?

No

### Description

Steps
- Go to alerts 
- Go to threshold >> value dropdown
- Enter "-000" and save the alert.
- Observe

**Note** - Please check the above scenario for conditions field too
<img width="827" alt="Screenshot 2023-12-12 at 12 33 23 PM" src="https://github.com/openobserve/openobserve/assets/144308844/423dcdc0-846f-4378-923c-13a0fbf732d8">

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version
Commit Hash
Build Date
v0.7.2
9666161459dc69300bfcbd9cb5a1250be7290057
2023-12-12T05:39:38Z
```

**Comment by hengfeiyang** [comment]
@neha00290 @omkarK06  here we need to limit the value is int or float. but `-0` it is a valid value, just a negative number, right?

**Comment by neha00290** [comment]
yes, correct @omkarK06 i ll close this issue
