### ISSUE TITLE
Display an error when user adds variable name but leaves variable value blank

### ISSUE THREAD

**Issue by neha00290** [openobserve/openobserve#2169]
### Which OpenObserve functionalities are the source of the bug?

alerts

### Is this a regression?

Yes

### Description

https://github.com/openobserve/openobserve/assets/144308844/fb182970-e599-4c85-a4ef-bac35cc515de

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version
Commit Hash
Build Date
v0.7.2
9666161459dc69300bfcbd9cb5a1250be7290057
2023-12-12T05:39:38Z
```

**Comment by hengfeiyang** [comment]
@neha00290 We removed the item that value is blank in the backend, it is not a valid item, so removed. Any suggestion?

**Comment by neha00290** [comment]
this is fixed
