### ISSUE TITLE
On editing a destination, sometimes duplicate entries are displayed and user is unable to delete the destination as well

### ISSUE THREAD

**Issue by neha00290** [openobserve/openobserve#2171]
### Which OpenObserve functionalities are the source of the bug?

alerts

### Is this a regression?

No

### Description
Steps-
1. Go to destination
2. Create a new destination
3. Edit the same and observe all list of destinations

<img width="1410" alt="Screenshot 2023-12-12 at 3 33 39 PM" src="https://github.com/openobserve/openobserve/assets/144308844/72065620-a2e5-47a4-9e5f-53f93660ce3c">

### Please provide the version you discovered this bug in (check about page for version information)
version0.7.2

_No response_

**Comment by hengfeiyang** [comment]
all of this because you add some blank space in the name. fixed.

**Comment by neha00290** [comment]
closing this issue as fixed
