### ISSUE TITLE
Syslog listen port disappears after a while

### ISSUE THREAD

**Issue by haitun3721** [openobserve/openobserve#2174]
### Which OpenObserve functionalities are the source of the bug?

ingestion

### Is this a regression?

Yes

### Description

监听的UDP 5514过段时间就没有了，0.7能大概1天，0.72能坚持3天左右，其他正常。

The monitored UDP 5514 disappears after a while, 0.7 can last about a day, and 0.72 can last around three days, everything else is normal.

**Comment by hengfeiyang** [comment]
Can you check your logs if there are any errors or panic about syslog?

**Comment by FengZh61** [comment]
Are the listening ports available to enable editing on the front-end page?

**Comment by haitun3721** [comment]
是的在web前端编辑的收集信息：/web/ingestion/custom/logs/syslog

   cat /etc/openobserve.env 
ZO_DATA_DIR = "/data/openobserve"
ZO_DATA_DB_DIR = "/data/openobserve/db"
ZO_DATA_WAL_DIR = "/data/openobserve/wal/"
ZO_DATA_STREAM_DIR = "/data/openobserve/stream"
ZO_DATA_CACHE_DIR = "/data/openobserve/cache"
ZO_COMPACT_DATA_RETENTION_DAYS = 180
ZO_TCP_PORT = 5514
ZO_UDP_PORT = 5514
ZO_TELEMETRY=false
ZO_BASE_URI = "/logs"

停止收集日志的时候， 有这么3条日志信息：
Dec 18 10:28:54 OpenObserve openobserve[1080]: thread 'tokio-runtime-worker' panicked at /home/runner/work/openobserve/openobserve/src/handler/tcp_udp/mod.rs:33:61:
Dec 18 10:28:54 OpenObserve openobserve[1080]: called `Result::unwrap()` on an `Err` value: FromUtf8Error { bytes: [60, 54, 62, 68, 101, 99, 32, 49, 56, 32, 49, 48, 58, 50, 56, 58, 53, 48, 32, 88, 72, 45, 65, 83, 71, 59, 53, 56, 48, 49, 48, 49, 50, 48, 48, 49, 50, 48, 48, 56, 51, 49, 53, 52, 53, 55, 50, 56, 56, 51, 59, 105, 112, 118, 52, 59, 51, 59, 32, 102, 105, 108, 101, 95, 116, 114, 97, 110, 115, 102, 101, 114, 58, 32, 117, 115, 101, 114, 95, 110, 97, 109, 101, 61, 49, 48, 46, 50, 48, 56, 46, 52, 46, 50, 59, 117, 115, 101, 114, 95, 103, 114, 111, 117, 112, 95, 110, 97, 109, 101, 61, 97, 110, 111, 110, 121, 109, 111, 117, 115, 59, 116, 101, 114, 109, 95, 112, 108, 97, 116, 102, 111, 114, 109, 61, 229, 164, 154, 231, 187, 136, 231, 171, 175, 40, 87, 105, 110, 100, 111, 119, 115, 44, 65, 110, 100, 114, 111, 105, 100, 231, 179, 187, 231, 187, 159, 91, 78, 65, 77, 45, 65, 76, 48, 48, 93, 41, 59, 116, 101, 114, 109, 95, 100, 101, 118, 105, 99, 101, 61, 229, 164, 154, 231, 187, 136, 231, 171, 175, 59, 112, 105, 100, 61, 49, 59, 115, 114, 99, 95, 109, 97, 99, 61, 55, 48, 58, 56, 49, 58, 56, 53, 58, 49, 54, 58, 50, 97, 58, 48, 49, 59, 115, 114, 99, 95, 105, 112, 61, 49, 48, 46, 50, 48, 56, 46, 52, 46, 50, 59, 100, 115, 116, 95, 105, 112, 61, 53, 57, 46, 50, 51, 48, 46, 50, 52, 54, 46, 52, 53, 59, 100, 115, 116, 95, 112, 111, 114, 116, 61, 56, 48, 59, 97, 112, 112, 95, 110, 97, 109, 101, 61, 72, 84, 84, 80, 230, 150, 135, 228, 187, 182, 228, 184, 139, 232, 189, 189, 59, 97, 112, 112, 95, 99, 97, 116, 95, 110, 97, 109, 101, 61, 230, 150, 135, 228, 187, 182, 228, 188, 160, 232, 190, 147, 59, 104, 97, 110, 100, 108, 101, 95, 97, 99, 116, 105, 111, 110, 61, 48, 59, 97, 99, 99, 111, 117, 110, 116, 61, 59, 97, 99, 116, 105, 111, 110, 95, 110, 97, 109, 101, 61, 230, 142, 165, 230, 148, 182, 59, 102, 105, 108, 101, 95, 110, 97, 109, 101, 61, 222, 254, 117, 245, 5, 150, 166, 232, 210, 7, 144, 241, 130, 67, 127, 33, 84, 117, 93, 81, 46, 32, 199, 21, 152, 151, 237, 81, 202, 119, 179, 30, 64, 247, 52, 189, 164, 135, 200, 143, 23, 32, 59, 109, 115, 103, 61], error: Utf8Error { valid_up_to: 389, error_len: Some(1) } }
Dec 18 10:28:54 OpenObserve openobserve[1080]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by haitun3721** [comment]
收到的日志信息中有中文UTF8编码，设备是huawei ASG，能正常收集和显示；还有huawei USG 设备编码为GBK，设置为英文发送日志，也能正常收集和显示。

**Comment by hengfeiyang** [comment]
> Dec 18 10:28:54 OpenObserve openobserve[1080]: thread 'tokio-runtime-worker' panicked at /home/runner/work/openobserve/openobserve/src/handler/tcp_udp/mod.rs:33:61:
> Dec 18 10:28:54 OpenObserve openobserve[1080]: called `Result::unwrap()` on an `Err` value: FromUtf8Error { bytes: [60, 54, 62, 68, 101, 99, 32, 49, 56, 32, 49, 48, 58, 50, 56, 58, 53, 48, 32, 88, 72, 45, 65, 83, 71, 59, 53, 56, 48, 49, 48, 49, 50, 48, 48, 49, 50, 48, 48, 56, 51, 49, 53, 52, 53, 55, 50, 56, 56, 51, 59, 105, 112, 118, 52, 59, 51, 59, 32, 102, 105, 108, 101, 95, 116, 114, 97, 110, 115, 102, 101, 114, 58, 32, 117, 115, 101, 114, 95, 110, 97, 109, 101, 61, 49, 48, 46, 50, 48, 56, 46, 52, 46, 50, 59, 117, 115, 101, 114, 95, 103, 114, 111, 117, 112, 95, 110, 97, 109, 101, 61, 97, 110, 111, 110, 121, 109, 111, 117, 115, 59, 116, 101, 114, 109, 95, 112, 108, 97, 116, 102, 111, 114, 109, 61, 229, 164, 154, 231, 187, 136, 231, 171, 175, 40, 87, 105, 110, 100, 111, 119, 115, 44, 65, 110, 100, 114, 111, 105, 100, 231, 179, 187, 231, 187, 159, 91, 78, 65, 77, 45, 65, 76, 48, 48, 93, 41, 59, 116, 101, 114, 109, 95, 100, 101, 118, 105, 99, 101, 61, 229, 164, 154, 231, 187, 136, 231, 171, 175, 59, 112, 105, 100, 61, 49, 59, 115, 114, 99, 95, 109, 97, 99, 61, 55, 48, 58, 56, 49, 58, 56, 53, 58, 49, 54, 58, 50, 97, 58, 48, 49, 59, 115, 114, 99, 95, 105, 112, 61, 49, 48, 46, 50, 48, 56, 46, 52, 46, 50, 59, 100, 115, 116, 95, 105, 112, 61, 53, 57, 46, 50, 51, 48, 46, 50, 52, 54, 46, 52, 53, 59, 100, 115, 116, 95, 112, 111, 114, 116, 61, 56, 48, 59, 97, 112, 112, 95, 110, 97, 109, 101, 61, 72, 84, 84, 80, 230, 150, 135, 228, 187, 182, 228, 184, 139, 232, 189, 189, 59, 97, 112, 112, 95, 99, 97, 116, 95, 110, 97, 109, 101, 61, 230, 150, 135, 228, 187, 182, 228, 188, 160, 232, 190, 147, 59, 104, 97, 110, 100, 108, 101, 95, 97, 99, 116, 105, 111, 110, 61, 48, 59, 97, 99, 99, 111, 117, 110, 116, 61, 59, 97, 99, 116, 105, 111, 110, 95, 110, 97, 109, 101, 61, 230, 142, 165, 230, 148, 182, 59, 102, 105, 108, 101, 95, 110, 97, 109, 101, 61, 222, 254, 117, 245, 5, 150, 166, 232, 210, 7, 144, 241, 130, 67, 127, 33, 84, 117, 93, 81, 46, 32, 199, 21, 152, 151, 237, 81, 202, 119, 179, 30, 64, 247, 52, 189, 164, 135, 200, 143, 23, 32, 59, 109, 115, 103, 61], error: Utf8Error { valid_up_to: 389, error_len: Some(1) } }
> Dec 18 10:28:54 OpenObserve openobserve[1080]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

The problem is everything in OpenObserve is UTF8, some GBK chars can't convert to UTF8 string but we haven't check it.

Thanks for report, i will add some checks to print an `warn` log for skip no UTF8 characters.

**Comment by haitun3721** [comment]
Thank you! Waiting for your next version to be released
