### ISSUE TITLE
Dashboard adds integer type

### ISSUE THREAD

**Issue by addname** [openobserve/openobserve#2178]
### Description

Dashboard adds integer type

### Proposed solution

![WechatIMG4761](https://github.com/openobserve/openobserve/assets/3360883/12a19b8f-0dec-4525-9f2d-8b86d49d1510)

### Alternatives considered

Dashboard adds integer type

**Comment by ktx-abhay** [comment]
@addname  to use integer type set decimal point value as a 0.
