### ISSUE TITLE
Dashboard ratio data display, SQL query the percentage of a specific value compared to the total quantity.

### ISSUE THREAD

**Issue by addname** [openobserve/openobserve#2229]
### Description

Dashboard ratio data display, SQL query the percentage of a specific value compared to the total quantity.
For example:
![52311702890042_ pic](https://github.com/openobserve/openobserve/assets/3360883/dcdd7d62-362a-490c-8bf9-12bfa5694c7e)

### Proposed solution

1

### Alternatives considered

1

**Comment by hengfeiyang** [comment]
The user wants to show a percentage of different status. he tries to wrong a query in the dashboard:

```sql
((SELECT COUNT(status) FROM "default" WHERE status = '404') / (SELECT COUNT(status) FROM "default")) as "y_axis_1" 
```

It definitely can't work, let's think about that how to support this type of chart.

**Comment by JPFrancoia** [comment]
Hi @hengfeiyang , is there any new development regarding querying the percentage of a value vs the total?

I'm trying to achieve that at the moment. I'm not using http but rpc for my services, but it's the same concept. I don't think it's possible at the moment, correct? I have watched the dashboard tutorial but couldn't find anything about it.

FYI, there is a very precise use case for this: people will be tempted to do this computation to build a [SLO](https://cloud.google.com/blog/products/devops-sre/sre-fundamentals-slis-slas-and-slos). This is basically a metric expressed as: `# of good requests / # total requests`. SRE teams use this as a metric to detect problems with their applications.

This is the last thing that prevents me from using openobserve at work.

![screen-2024-08-20-18-44-12](https://github.com/user-attachments/assets/0222f8bb-d88f-42df-8214-52d43ea203e5)

**Comment by hengfeiyang** [comment]
we can use `CASE THEN` https://openobserve.ai/docs/example-queries/

```sql
SELECT histogram(_timestamp) as ts_histogram, 
count(case when code=200 then 1 end) as code_200_count, 
count(case when code=401 then 1 end) as code_401_count, 
count(*) as code_total_count, (count(case when code=200 then 1 end) * 100 / count(*)) as code_200_ratio FROM test8 GROUP BY ts_histogram
```
