### ISSUE TITLE
Add reset filter button for log search UI

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#2295]
### Which OpenObserve functionalities are relevant/related to the feature request?

Logs

### Description

Manually need to delete the log filters when we need to restart search

### Proposed solution

<img width="177" alt="image" src="https://github.com/openobserve/openobserve/assets/4242188/2d727c1e-80a8-4bb3-8150-34a4ea469d57">

### Alternatives considered

manually delete query

**Comment by neha00290** [comment]
this is tested
