### ISSUE TITLE
for some reason, we always ingest yesterday log and compact will not work for yesterday log

### ISSUE THREAD

**Issue by domyway** [openobserve/openobserve#2305]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

some device will not upload logs when it offline, and after a few days it has wifi and then can upload logs, but right now compact offset is now, the logs will not be compacted and it will cause search slowly~

**Comment by domyway** [comment]
may be provide a custom compact time range api , we can call the api according to our needs

**Comment by hengfeiyang** [comment]
fixed, you can set a environment:
```
ZO_COMPACT_LOOKBACK_HOURS=24
```

Then it will check the hour -24 when it run merge.
