### ISSUE TITLE
Bugs - Dev image testing

### ISSUE THREAD

**Issue by jhuynh08** [openobserve/openobserve#2329]
Hi guys,

Some things I noticed as I was testing the new dev image provided.

1. I can't seem to delete my alert destinations. I would get a response in the console showing that there is something using the destination when in fact there isn't.
```
{
    "code": 403,
    "message": "Alert destination is in use for alert [standup] namespace container restarts"
}
```

2. I had to rebuild my alerts from the previous build if I want to set conditions for the alerts. Rebuilding the alerts will fix it but could be a hassle if there are hundreds of alerts.
<img width="743" alt="image" src="https://github.com/openobserve/openobserve-helm-chart/assets/57417573/a720ee26-c457-4a66-8baf-fc4d0632fc22">

I will update this thread if I find more. Thanks!

Image: openobserve-dev:v0.7.2-ddb806f-amd64

**Comment by jhuynh08** [comment]
Another bug I observed when creating a new alert.

After I try to save the new alert I get an error but if I hit save again it will save.
```
Json deserialize error: invalid type: string "5", expected i64 at line 1 column 310
```

**Comment by jhuynh08** [comment]
Hello,

I noticed within the new GUI for alerts that there is a pause button now presumably to enable/disable alerts as needed. When I try to pause the alert I get this error.

```
{"code":404,"message":"Alert not found"}
```

**Comment by hengfeiyang** [comment]
try again? with latest version, it should be fixed
