### ISSUE TITLE
Unable to access Web UI from mobile device

### ISSUE THREAD

**Issue by gaby** [openobserve/openobserve#2332]
### Which OpenObserve functionalities are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Currently it is not possible to use OpenObserve from a mobile device. The sidebar disappears and the navbar is missing items unless using the phone in landscape.

![Screenshot_20231230-223332](https://github.com/openobserve/openobserve/assets/835733/863164d9-0a74-4a15-9d9e-8fdddec72e2c)
![Screenshot_20231230-222834](https://github.com/openobserve/openobserve/assets/835733/f073d468-b1e3-4100-8601-31ee8283d26e)

### Please provide the version you discovered this bug in (check about page for version information)

```true
All versions
Mobile device
```

**Comment by helloobaby** [comment]
Doesn't OpenObServe plan to optimize browsing on mobile phones?

**Comment by hengfeiyang** [comment]
We have no plan for it yet. maybe in the next year we can optimize this case.
