### ISSUE TITLE
Make visualizations title optional

### ISSUE THREAD

**Issue by gaby** [openobserve/openobserve#2358]
### Which OpenObserve functionalities are relevant/related to the feature request?

dashboards

### Description

Currently the visualizations force having a title, in some cases the data is enough and doesnt require a title. 

### Proposed solution

In the dropdown for the visualization add an option for changing or hidding the title.

### Alternatives considered

None

**Comment by gaby** [comment]
@ktx-kirtan @ktx-vaidehi Any updates on this?

**Comment by ktx-kirtan** [comment]
Not yet @gaby . We haven't had any discussion on this. Maybe we will have a take on this by the end of the next week. Will keep you posted

**Comment by gaby** [comment]
🥲
