### ISSUE TITLE
Current cluster for kubernetes ingestion

### ISSUE THREAD

**Issue by bjp232004** [openobserve/openobserve#2367]
### Description

Add tabs to display current cluster and external cluster information on kubernetes ingestion page.

![image](https://github.com/openobserve/openobserve/assets/551527/1c598790-31ea-494d-a7c6-e22c2fcfb0d2)

### Proposed solution

Find attached screen shot.

### Alternatives considered

NA

**Comment by neha00290** [comment]
this is done
