### ISSUE TITLE
Errors when using functions during log search

### ISSUE THREAD

**Issue by abvarun226** [openobserve/openobserve#2374]
### Which OpenObserve functionalities are the source of the bug?

log search, functions

### Is this a regression?

No

### Description

When I try to use functions during log search, I get a status 500 Internal Server Error from server. I get a `Error: Something went wrong. Internal server error.` on the UI.

Function used:
```
. |= {"test": "foo"}
.
```

### Please provide the exception or error you saw

```
{
    "code": 10001,
    "message": "Server Internal Error",
    "error_detail": "task 36422564 panicked"
}
```

### Please provide the version you discovered this bug in (check about page for version information)

```
Version: v0.7.2
```

**Comment by oasisk** [comment]
this should be fixed with next release
