### ISSUE TITLE
SQL error: TokenizerError(\"Unterminated string literal at Line: 1, Column 23\")

### ISSUE THREAD

**Issue by GhostBoyBoy** [openobserve/openobserve#2375]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

Using SQL statements to query results with errors at different times.

sql such as: SELECT arrow_cast(split_part(body,'当前线程池队列长度:',2),'Int32') as qsize FROM "mishu_foreign_server" WHERE str_match(body,'当前线程池队列长度:');

Request passed: {"query":{"sql":"SELECT arrow_cast(split_part(body,'当前线程池队列长度:',2),'Int32') as qsize FROM \"mishu_foreign_server\" WHERE str_match(body,'当前线程池队列长度:');","start_time":1704271200000000,"end_time":1704272340000000,"from":0,"size":150,"sql_mode":"full"}}

Failed Request:
{"query":{"sql":"SELECT arrow_cast(split_part(body,'当前线程池队列长度:',2),'Int32') as qsize FROM \"mishu_foreign_server\" WHERE str_match(body,'当前线程池队列长度:');","start_time":1704213600000000,"end_time":1704272340000000,"from":0,"size":150,"sql_mode":"full"}}

Failed Response:
"SQL error: TokenizerError(\"Unterminated string literal at Line: 1, Column 23\")"

### Please provide the version you discovered this bug in (check about page for version information)

```true
v0.7.2
c6e7b19b28e948cfc65e4dfb3d26a0cfebbec3f8
2023-11-30T07:59:17Z
```

**Comment by hengfeiyang** [comment]
This should be fixed in v0.10.0
