### ISSUE TITLE
custom variables are not accessible inside alerts template

### ISSUE THREAD

**Issue by RVaidhy** [openobserve/openobserve#2443]
### Which OpenObserve functionalities are the source of the bug?

alerts

### Is this a regression?

No

### Description

Hi Team,

We have got a scenario where we wanted to trigger an alert with additional details **apart from template variables to make it more meaningful and really actionable alerts.** Lets say, we are checking the logs against some conditions and once its available we are triggering an alert. Here we wanted to append the details which we used in the condition under where clause.
So that the team can directly go the concerned issue and start working on it.

Example, consider this scenario. which group accessed the portal against blocked / prohibited credentials. We need to trigger email against that condition. 

Now by using the SQL query, we can get the count of that prohibited credentials usage and trigger email. But what we really need is, who / which team used that credentials, which used triggered, what resource they tried to access (these details are available in logs, we are also seeing that in the sql query and wanted to send this info in email) .

How to pass this details to webhook as a template custom variable. Please help !!! Thanks.

Regards,
R Vaidhy 

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: 0.7.0
```

**Comment by RVaidhy** [comment]
Additional info: 
stream_name	
org_name	
alert_name
alert_type
timestamp

Apart from this, how can we add our custom variables with values that we are getting it from SQL query.

**Comment by prabhatsharma** [comment]
It should be available soon

**Comment by RVaidhy** [comment]
Thank you so much Prabhath for the reply.

Meanwhile, till you add this feature to openobserve, is there any way for us to query the data and create alerts on top of it ? We are storing the logs into S3 bucket from the openobserve EC2 . Here, even from inside the EC2 if we can query and send the meaningful alerts with the help of custom scripts (shell/python for identify the log entries) + SMTP (for email) is also fine for us in the interim. Kindly let me know.

Regards,
R Vaidhy

**Comment by hengfeiyang** [comment]
@RVaidhy OpenObserve has only a binary, but it also has separate backend API and frontend UI. everything you can do in our UI, you also can do it by call our API, we have a embed Swagger UI for look up the APIs.
