### ISSUE TITLE
Can Tencent Cloud’s COS be used as a substitute for S3 in an HA configuration?

### ISSUE THREAD

**Issue by liaohongqing-A** [openobserve/openobserve#2476]
### Which OpenObserve functionalities are relevant/related to the feature request?

ingestion

### Description

I don’t possess an S3 storage account; however, I do have an account for Tencent Cloud’s COS service. I am unaware whether OpenObserve currently supports integration with Tencent Cloud’s COS, and I haven’t conducted any tests on this matter. Can it be compatible with Tencent Cloud’s COS storage?

### Proposed solution

Tencent Cloud’s COS 

### Alternatives considered

Tencent Cloud’s COS

**Comment by hengfeiyang** [comment]
https://openobserve.ai/docs/storage/#tencent-cos

**Comment by liaohongqing-A** [comment]
ok
