### ISSUE TITLE
[UI] The width of the stream drop-down box is not adaptive

### ISSUE THREAD

**Issue by hanqian200705** [openobserve/openobserve#2494]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

The width of the stream drop-down box is not adaptive

<img width="217" alt="image" src="https://github.com/openobserve/openobserve/assets/4269408/11a25112-fa2f-42b4-ad79-09e17b5e6c5b">

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version v0.8.0-rc1
Commit Hash c057bf40f34206914e17b623c6bc31e4ad8f17c7
Build Date 2024-01-16T13:21:57Z
```

**Comment by hanqian200705** [comment]
It should be set to a minimum width, and if it is less than this width, the width of the drop-down box will not continue to decrease. The same minimum width can be set for the dragable area below

**Comment by hengfeiyang** [comment]
improved
