### ISSUE TITLE
The parameters in the alerts page can support obtaining data from another custom SQL query

### ISSUE THREAD

**Issue by hanqian200705** [openobserve/openobserve#2503]
### Which OpenObserve functionalities are relevant/related to the feature request?

alerts

### Description

The parameters in the alarm page can support obtaining data from another custom SQL query.

### Proposed solution

For example, after obtaining parameters such as traceid and time in the initial alert, a correlation query can be used to filter out the logs of interest using traceid and time conditions and send them to another system for processing. Of course, if the system supports alert events that are processed in multiple steps similar to a rule engine, it is better to obtain the final result and then push it. However, this should take longer to develop.

This image is from another system and can be used as a reference
![image](https://github.com/openobserve/openobserve/assets/4269408/6193a6f6-b35d-441c-82fa-8b6da8414d17)

### Alternatives considered

1. Customized association queries should be prioritized.
2. SQL supports subqueries, but the implementation is difficult and requires consideration of generality, such as indicator data.
3. Support for using custom function syntax, where the system provides functions that can be used for secondary queries to support subqueries, similar to an embedded rule engine, with greater freedom and implementation difficulty.

**Comment by hengfeiyang** [comment]
added to the summary issue: #1970
