### ISSUE TITLE
There are 5 minutes dely ,how can I improve this?

### ISSUE THREAD

**Issue by loveyang2012** [openobserve/openobserve#2505]
openabserve is great, but I get a trouble,when I use vector collector  ,I have found there are 5 minutes dely. 
My Server  is  48C-750G-1.5TSSDD.

![1705559541139](https://github.com/openobserve/openobserve/assets/24237714/9aeb2477-a5de-4e2a-8053-6f7cd552e773)

how can I improve this?

thinks,please.

**Comment by hengfeiyang** [comment]
In our system we always show the latest data ingested in. maybe you need to check your data source if latest time or the time of your server.
