### ISSUE TITLE
[alert] When using the count function in the alarm module, the dropdown menu cannot select fields

### ISSUE THREAD

**Issue by oslet** [openobserve/openobserve#2518]
### Which OpenObserve functionalities are the source of the bug?

alerts

### Is this a regression?

Yes

### Description

When using the count function in the alarm module, the dropdown menu cannot select fields,
Even after selecting the threshold comparison operator, it still prompts that the field is required

### Please provide the version you discovered this bug in (check about page for version information)

```true
openobserve v0.8.0-rc1
```

### Anything else?

![2024-01-19_20-16](https://github.com/openobserve/openobserve/assets/1573303/c54acd31-8b03-467e-84a8-4fa60535fe6a)

**Comment by hengfeiyang** [comment]
fixed, will be released in `v0.8.0-rc2` next week.
