### ISSUE TITLE
Time-based search is not working

### ISSUE THREAD

**Issue by alex-jitbit** [openobserve/openobserve#2527]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

Two bug in the timeline search:

1. When I select time range with a mouse, for example "from 4:00am to 4:05am" this results in s search "from 2:00am to 2:05am" (which looks like a UTC offset).
2. When I scroll the logs down, to the end of the screen, and the next portion of the logs is supposed to be loaded - the new portion is loaded from wrong time

Screenshot for the 2nd issue:
![image](https://github.com/openobserve/openobserve/assets/33555768/0137acdd-02c9-4a2b-b826-a413411b86c7)

Looks like it's using my browser local time which is UTC +2 why??

### Please provide the version you discovered this bug in (check about page for version information)

```true
I'm using the saas-hosted verison of openobserve with Fluent-Bit ingesting nginx logs. Nginx logs time is in UTC.
```

**Comment by hengfeiyang** [comment]
1. it should because of your browser timezone, when you fire a query it fired the time range with your timezone.
2. it is a bug, fixed in 0.8.0-rc1

**Comment by alex-jitbit** [comment]
@hengfeiyang 

Not sure, why "it should" do that. Just in case I wasn't clear enopugh - here's the video that shows the bug:

https://github.com/openobserve/openobserve/assets/33555768/972b6c6d-9484-4715-adc1-30572ac7e9b5

**Comment by hengfeiyang** [comment]
fixed
