### ISSUE TITLE
Functions tab invisible when active in dark mode

### ISSUE THREAD

**Issue by srstrickland** [openobserve/openobserve#2543]
### Which OpenObserve functionalities are the source of the bug?

functions

### Is this a regression?

No

### Description

When selecting `Functions` in dark mode, the icon & text disappear (white on white)

<img width="200" alt="Screenshot 2024-01-23 at 8 30 25 PM" src="https://github.com/openobserve/openobserve/assets/11576127/b6cf8cb5-2288-4a98-a8d7-69e589f39beb">

...even while collapsed:

<img width="273" alt="Screenshot 2024-01-23 at 8 34 44 PM" src="https://github.com/openobserve/openobserve/assets/11576127/17a36846-888f-446c-9a1f-a94c09f06db0">

All other menu items render properly.

### Please provide the exception or error you saw

```true
None; just a UI bug.
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.8.0-rc1
Commit Hash: c057bf40f34206914e17b623c6bc31e4ad8f17c7
Build Date: 2024-01-16T13:21:57Z
```

**Comment by ktx-vaidehi** [comment]
This has already been fixed and is available in the main branch.
