### ISSUE TITLE
Cache the latest data

### ISSUE THREAD

**Issue by hengfeiyang** [openobserve/openobserve#2562]
### Description

All the queries are executed by the querier, but each time we need to fetch the recent data from S3 and cache it locally. If we could automatically cache the recent data in the querier, it would be faster.

### Proposed solution

1. send the file to querier when ingester generate a new parquet file and move to S3
2. move the file to disk cache when memory cache is full
3. drop the file when disk cache is full.
4. use FIFO for the cacher

### Alternatives considered

--

**Comment by hengfeiyang** [comment]
# Caching Latest Data: Solutions Considered

We have considered several solutions for caching the latest data:

## 1. Extending File Retention

- **Approach:** Increase the `ZO_MAX_FILE_RETENTION_TIME` environment variable to keep Parquet files on the Ingester for a longer duration (e.g., 1, 2, or 10 hours).
- **Issues:**
  - Potential for very large data sizes on the Ingester (potentially reaching TB levels).
  - Limited data distribution as files are restricted to a single Ingester.
  - Increased risk of data loss as files remain on the Ingester longer before being moved to S3.

## 2. Sending Files to Queriers

- **Approach:** Transmit files to Queriers when moving them to S3 for caching.
- **Benefits:** Facilitates distributed queries by leveraging cached data across Queriers.
- ** Issues:**
  - Data duplication across Queriers, multiplying storage requirements.
  - Inefficient storage utilization as Queriers only use a fraction of cached files.
  - Wasted network resources and storage space.
  - New Queriers require downloading data segments from S3.
  - After compaction the cache will be invalid.
 
This solution also is simple and very easy to understand, for example we have `10` queriers:

We send files to each queriers, we need store `10x` data. But each querier only use `1/10` files because of the partition query. `90%` cached files never used.

## 3. Consistent Hashing for File Distribution

![image](https://github.com/openobserve/openobserve/assets/1628250/035b69d9-0671-4b4f-8d2e-3095d3cc00b1)

Same to the `solution 2`, we still send files to querier, but use [consistent hashing](https://en.wikipedia.org/wiki/Consistent_hashing) only send to one of the queriers, when we run distribute query we use same hash and then each querier will search on the piece what it has already cached.

- **Approach:** Employ consistent hashing to distribute files strategically among Queriers, ensuring each file resides on a single Querier.
- **Improvements:**
  - Eliminates data duplication.
  - Optimizes storage utilization.
- **Limitation:**
  - New Queriers require downloading data segments from S3.
  - **After compaction the cache will be invalid.**

For example we have `10` queriers:

We send files to one of the queriers by hashing, we only store `1x` data. And each querier will query on the data that it has already cached because will use same hashing for partition.

**But it will bring a new problem:**

- Metrics calculations, which necessitate time-based data partitioning, cannot fully utilize hash-based partitioning for queries.

## 4. Consistent Hashing for File Distribution and Download file from S3

Same to the `solution 3`, But we download file from `S3` then we don't need to change ingester. because there is no difference between download file from ingester and S3, both intranet. and if we download file or push file from ingester will let the ingester more heavier.

## Conclusion

So, i think the final solution will be:

- Add a consistent hashing on Querier and the Querier will download files from S3 based on parquet file hashing.
- Add a query distribution strategy by consistent hashing.
- Configure the environments to reduce compactor impact:
  ```
  ZO_MAX_FILE_SIZE_ON_DISK = 96
  ZO_MEM_FILE_MAX_SIZE = 256
  ZO_MAX_FILE_RETENTION_TIME = 3600
  ```

**Comment by domyway** [comment]
> "All the queries are executed by the querier, but each time we need to fetch the recent data from S3 and cache it locally. If we could automatically cache the recent data in the querier, it would be faster."

I don't see much benefit in sending Parquet from the ingester to the querier:

1. The only difference between downloading from S3 during a query and having the querier pre-cache the Parquet from the ingester is the saving of S3 download time during the first query. S3 downloads are generally done over the internal network, and this overhead can be negligible with optimizations for the first query. Aside from not wasting S3 download bandwidth, I don't see any other significant benefits in other scenarios.

2. Adding this cache mechanism would pose a challenge to the ingester's stability. The ingester already handles multiple tasks like WAL, index building, compaction, etc. Introducing a cache mechanism doesn't seem meaningful except for optimizing the first query.

3. When the ingester is handling a high volume of writes, it implies a large number of files being sent (each 256M). The ingester's bandwidth will constantly be at double, and CPU and IO consumption will become issues. This means providing more CPU and memory, and these costs may outweigh the S3 download costs.

I think this cache solution is completely unnecessary.

**Comment by prabhatsharma** [comment]
The difference when it comes to downloading files from s3 for caching vs moving data from ingester to querier has the following trade-offs:

1. Making a GET call to s3 costs money ([$0.0004 / per thousand requests](https://aws.amazon.com/s3/pricing/)). Transfer from s3 to querier does not cost money.
3. Moving data from ingester to querier has no call cost but may incurs inter-az data transfer cost ($0.02 / GB).

pulling data from s3 for caching is significantly cheaper.

**Comment by domyway** [comment]
> The difference when it comes to downloading files from s3 for caching vs moving data from ingester to querier has the following trade-offs:
> 
> 1. Making a GET call to s3 costs money ([$0.0004 / per thousand requests](https://aws.amazon.com/s3/pricing/)). Transfer from s3 to querier does not cost money.
> 2. Moving data from ingester to querier has no call cost but may incurs inter-az data transfer cost ($0.02 / GB).
> 
> pulling data from s3 for caching is significantly cheaper.

Transferring data also incurs additional CPU and memory consumption. If acquiring an extra core and 1GB of memory is necessary for this task, could the costs of CPU and memory be higher than the costs associated with S3 GET operations? Moreover, since the benefits are only realized during the initial query, and the ingester becomes heavier and more complex over time, I genuinely feel that the cost-effectiveness is low.
