### ISSUE TITLE
VRL error yellow bar does not disappear after entering a valid function

### ISSUE THREAD

**Issue by neha00290** [openobserve/openobserve#2568]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

No
### Description

https://github.com/openobserve/openobserve/assets/144308844/56dd95ca-aeaf-4a3a-831b-fec043f505e7

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version
Commit Hash
Build Date
v0.8.0-rc1
0b7b3078dfb92ee357435f132d3357ccf4bb40e2
2024-01-25T04:41:35Z
```

**Comment by bjp232004** [comment]
not reproducible

**Comment by neha00290** [comment]
closing this for now as unable to replicate
