### ISSUE TITLE
Support proxy auth for login authentication

### ISSUE THREAD

**Issue by xiaoziv** [openobserve/openobserve#2575]
### Which OpenObserve functionalities are relevant/related to the feature request?

login

### Description

Some companies typically have a unified authentication gateway. Proxy authentication support is convenient, as it retrieves user information from HTTP headers.

[grafana proxy auth docs](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/auth-proxy/)

### Proposed solution

None

### Alternatives considered

None

**Comment by hengfeiyang** [comment]
@xiaoziv We implemented DEX support in enterprise version and DEX support https://dexidp.io/docs/connectors/authproxy/

**Comment by gorootde** [comment]
Ok but how to connect this to my OIDC provider when self hosting this for my homelab? I don't run the enterprise version.

**Comment by prabhatsharma** [comment]
You install Enterprise version

**Comment by gorootde** [comment]
Ok, that was not a constructive answer. For my home server with a dozen docker containers, the enterprise version is probably overkill.

**Comment by prabhatsharma** [comment]
It has nothing to do with the answer. Only Enterprise version has the feature. I understand that you do not want multiple containers. It is what it is though.

**Comment by opnath-dev** [comment]
Is SSO support on the roadmap for the OSS version? The Enterprise version is often overkill for home lab environments, and enabling SSO in the OSS edition would make it much more practical and convenient for many users.
