### ISSUE TITLE
v0.8.0-rc2 breaks syslog ingestion

### ISSUE THREAD

**Issue by descensus** [openobserve/openobserve#2597]
### Which OpenObserve functionalities are the source of the bug?

ingestion

### Is this a regression?

Yes

### Description

When running v0.8.0-rc2, its impossible to enable syslog ingestion and keep state after exiting the menu.
Enable syslog and go somewhere else, then back and its disabled again.

Also, without any data ingested, all menus leads to the ingestion page for me.

**Comment by neha00290** [comment]
@descensus - can you help me with a video for the syslog button appears disabled issue? I tried the same and unable to replicate.

**Comment by descensus** [comment]
Its a bit peculiar, it seemed to work fine on RC1, but saw this behavior here as well, but not always. 
Think its related to enable -> disable -> enable.

Running firefox without ublock enabled. Overall I have problems receiving syslog, I got one only messages from multiple sources once, and at other times I got quite a few messages then it suddenly stopped. UI says its enabled but it feels like the internal state is disabled while listeners is still online, but nothing is routed anywhere (?).


I can see that enable returns code 500:
` actix_web::middleware::logger: 10.1.1.2 "POST /api/default/syslog-server HTTP/1.1" 500 78 "14"`

Also firefox reports
```
Uncaught (in promise) 
Object { message: "Request failed with status code 500", name: "AxiosError", code: "ERR_BAD_RESPONSE", config: {…}, request: XMLHttpRequest, response: {…}, stack: "" }
code: "ERR_BAD_RESPONSE"
config: Object { timeout: 0, xsrfCookieName: "XSRF-TOKEN", xsrfHeaderName: "X-XSRF-TOKEN", … }
message: "Request failed with status code 500"
name: "AxiosError"
request: XMLHttpRequest { readyState: 4, timeout: 0, withCredentials: false, … }
response: Object { data: {…}, status: 500, statusText: "Internal Server Error", … }
stack: ""
<prototype>: Object { constructor: pL(t, r, a, i, s), toJSON: toJSON(), stack: "", … }

```

Stopping works in the UI, its registered as stopped in the UI, but the TCP/UDP listener is not stopping, it still listens on 5514 UDP/TCP.

https://github.com/openobserve/openobserve/assets/134628590/ca0eba8a-bf21-4013-9ffb-ddb682b48a7c

**Comment by hengfeiyang** [comment]
fixed
