### ISSUE TITLE
SMTP server setting for alerts and reports

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#2601]
### Which OpenObserve functionalities are relevant/related to the feature request?

other

### Description

Settings should allow the capture of details of the SMTP server that can send an email. This setting can be used by alerts and reports

### Proposed solution

<img width="764" alt="image" src="https://github.com/openobserve/openobserve/assets/4242188/83dc6092-e14f-44d5-88af-df2d6a9e5e04">

### Alternatives considered

NA

**Comment by czy-29** [comment]
Yes, I really need this feature, I hope it can be added, thank you! 🫶🏻
