### ISSUE TITLE
Why didn't I?  ZO_DATA_LIFECYCLE

### ISSUE THREAD

**Issue by wanghao123123** [openobserve/openobserve#2604]
### Which OpenObserve functionalities are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

![image](https://github.com/openobserve/openobserve/assets/38528031/3d0c48a2-2e0e-4d00-a842-12c01cb18fdb)
version：v0.8.0-rc1   HA Deployment  Helm
But if I use stand-alone deployment, there will be options on the page.
Is there any other way? Or the configuration in the configuration does not need to be visualized on the page

### Please provide the version you discovered this bug in (check about page for version information)

```true
K8s
version：v0.8.0-rc1   HA Deployment Helm
```

**Comment by hengfeiyang** [comment]
We changed it to: `ZO_COMPACT_DATA_RETENTION_DAYS`

https://openobserve.ai/docs/environment-variables/

**Comment by wanghao123123** [comment]
> 我们将其更改为：`ZO_COMPACT_DATA_RETENTION_DAYS`
> 
> https://openobserve.ai/docs/environment-variables/

I saw it. Thank you.
