### ISSUE TITLE
COUNT(DISTINCT(field)) result is wrong

### ISSUE THREAD

**Issue by hengfeiyang** [openobserve/openobserve#2607]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

```sql
SELECT COUNT(DISTINCT(field)) as cnt FROM table
```

The result is wrong.

The reason is we send this SQL to each querier and get multiple response, in the end merge the result like this:

```sql
SELECT SUM(cnt) FROM table
```

The value can't be `SUM`, because different querier maybe have same `distinct` value. i think we fetch rewrite the first stage SQL like this:

```sql
SELECT DISTINCT(field) as field FROM table
```

We will get multiple `distinct` values from each querier, at the second stage we rewrite the SQL like this:

```sql
SELECT COUNT(DISTINCT(feild)) FROM table
```

it should get right result.

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: 0.8.0
```

**Comment by haohuaijin** [comment]
after some discussion with @hengfeiyang, we will first support below four type of `count(distinct)` query.
Our query plan is split into some phases; the first phase is execution in memtable, immutable, sst and object storage; the second phase is execution in a single node to merge the result in the first phase; the third phase is execution to merge all node's results.
## type A
```sql
select count(distinct name) from table;
-> phase 1: select distinct name from table;
-> phase 2: select distinct name from table;
-> phase 3: select count(distinct name) from table;
```
## type B
```sql
select city, count(distinct name) from table group by city;
-> phase 1: select distinct city, name from table;
-> phase 2: select distinct city, name from table;
-> phase 3: select city, count(distinct name) from table group by city;
```
## type C
```sql
select city, count(distinct name), count(distinct foo) from table group by city;
-> phase 1: select distinct city, name, foo from table;
-> phase 2: select distinct city, name, foo from table;
-> phase 3: select city, count(distinct name), count(distinct foo) from table group by city;
```
## type D
```sql
select city, count(distinct name), count(name) from table group by city;
-> phase 1: select city, name from table;
-> phase 2: select * from table;
-> phase 3: select city, count(distinct name), count(name) from table group by city;
```

**Comment by hengfeiyang** [comment]
### Type A
```
select count(distinct name) from table;
-> phase 1: select distinct name from table;
-> phase 2: select distinct name from table;
-> phase 3: select count(distinct name) from table;
```
Can we use `select * from table` for `phase 2` like other cases ?

**Comment by haohuaijin** [comment]
> ### Type A
> ```
> select count(distinct name) from table;
> -> phase 1: select distinct name from table;
> -> phase 2: select distinct name from table;
> -> phase 3: select count(distinct name) from table;
> ```
> 
> Can we use `select * from table` for `phase 2` like other cases ?

yes, we can, but use `distinct name` maybe can reduce some data transfer from phase 2 to phase 3

**Comment by hengfeiyang** [comment]
okay, but, why other case use `select *`, it looks the same.

**Comment by haohuaijin** [comment]
oh, this is my mistake, I update the description.
