### ISSUE TITLE
[UI] Clicking on any function without data requires prompting to collect data first, rather than jumping to a page

### ISSUE THREAD

**Issue by baerwang** [openobserve/openobserve#2614]
### Which OpenObserve functionalities are relevant/related to the feature request?

other

### Description

such as the title

### Proposed solution

a pop up prompt

### Alternatives considered

NONE

**Comment by bjp232004** [comment]
Use the below environment variable to disable redirection on no data.

ZO_RESTRICTED_ROUTES_ON_EMPTY_DATA=false

**Comment by cbueche** [comment]
After starting a new, empty instance, I searched for one hour until I found this issue. Thanks for the trick, to me that looks like a bug. My next issue is, how do I add an organization... hopefully there isn't another hidden variable ?

**Comment by cbueche** [comment]
for those having the same issue: to create an organization, create its admin-user, and in the form, select role=admin, organization=other, and then you can name it. Relogin under this new user.
