### ISSUE TITLE
Provide an official fluentd daemonset for Kubernetes

### ISSUE THREAD

**Issue by collimarco** [openobserve/openobserve#2662]
### Which OpenObserve functionalities are relevant/related to the feature request?

ingestion

### Description

Hello,

I would like to migrate some logs from Logz.io to OpenObserve cloud.

However I find the migration more difficult than expected. In particular I was using the configurations in this official repository:
https://github.com/fluent/fluentd-kubernetes-daemonset

For Logz.io we use the file named `fluentd-daemonset-elasticsearch.yaml` which clearly shows the config and how to set the api token.

For OpenObserve cloud, can you provide a similar config?

### Proposed solution

In particular I think that [adding your provider configuration here](https://github.com/fluent/fluentd-kubernetes-daemonset) would also be beneficial to the visibility of your project in general.

### Alternatives considered

-

**Comment by prabhatsharma** [comment]
Once you login to the OpenObserve cloud, It shows you the configuration for fluentd under `Ingestion` menu. You can copy the configuration and use it right away.

**Comment by prabhatsharma** [comment]
If you are looking for a full configuration, we provide that with otel-collector that you can use. Just a couple of copy-paste commands from `Ingestion` menu.

**Comment by collimarco** [comment]
@prabhatsharma there isn't any fluentd daemonset configuration in the dashboard. There is only a small/partial snippet of Fluentd config. It's not related to this issue... see the repo that I have linked. There are many examples of what I mean.

**Comment by collimarco** [comment]
I find Fluentd very convenient because it's written in Ruby (our primary language) and it can be installed In Kubernetes as a single object (without need for complex installations or Helm charts).

**Comment by prabhatsharma** [comment]
We do not recommend fluentd due to its high resource requirements and are unlikely to provide full configuration for that. We would recommend you to use fluentbit - https://openobserve.ai/blog/how-to-send-kubernetes-logs-using-fluent-bit or otel-collector

**Comment by collimarco** [comment]
@prabhatsharma Ok, I have successfully used Fluentbit as described in your tutorial. However the `log` field that comes from my application is a nested JSON. 

Can you please suggest how to index all the fields in this nested JSON?

i.e. Basically I have a field that is not a simple string, number, etc. but it is of type json and I would like to index it.

**Comment by collimarco** [comment]
To be more clear. This is a log entry that I am getting from Fluentbit into OpenObserve:

```
{
  kubernetes_pod_id: df37-4054-ar5c-5eb7f9f76939,
  kubernetes_pod_name: web-867f46db5-mpwf2,
  log: I, [2024-02-07T08:52:56.625004 #12]  INFO -- : [326261cb-ce7a-403b-9642897d] {"method":"GET","path":"/viwwwsogou","format":"*/*","controller":"EmailsController","action":"index","status":404,"allocations":1131,"duration":4.18,"view":0.0,"db":0.98,"ip":"129.226.147.239","user_id":null,"@timestamp":"2024-02-07T08:52:56.624Z","@version":"1","message":"[404] GET /viwwwsogou (EmailsController#index)"},
  stream: stdout,
  time: 2024-02-07T08:52:56.625394826Z
}
```

As you can see the relevant information that comes from my Rails app is inside (nested) in the `log` field. Is it possible to extract and index those fields (e.g. method, path, format, controller, etc.)?

**Comment by collimarco** [comment]
Ok, doesn't matter... I found a way to parse the nested JSON using VRL functions. Not simple to use, but after some guesswork I think that I got the expected result.
