### ISSUE TITLE
Fail dashboard geolocation

### ISSUE THREAD

**Issue by qhz-redes** [openobserve/openobserve#2670]
### Which OpenObserve functionalities are the source of the bug?

dashboards, localization

### Is this a regression?

Yes

### Description

Good afternoon, I found this project yesterday and I really like it, I'm using it to collect flows. I imported the dashboards into netflow and the input graph is displaying an error.

![Screenshot_20240207_112822](https://github.com/openobserve/openobserve/assets/125511907/146980e7-d789-44d5-91cc-9c5df125acf7)

However, if I click on edit, it displays the data

![Screenshot_20240207_131736](https://github.com/openobserve/openobserve/assets/125511907/e8d13e5b-e4cc-40b9-852c-d0894c67a816)

**Comment by neha00290** [comment]
testing for this is complete
