### ISSUE TITLE
sankey chart

### ISSUE THREAD

**Issue by qhz-redes** [openobserve/openobserve#2671]
### Which OpenObserve functionalities are relevant/related to the feature request?

dashboards, ingestion, metrics

### Description

Good afternoon, is it possible to add the sankey graph for creation with netflow?

![images](https://github.com/openobserve/openobserve/assets/125511907/63b130ab-6292-47f3-9211-f3bb1a4d28fd)
![rtaImage](https://github.com/openobserve/openobserve/assets/125511907/b18adb81-1e37-447a-ae97-e52101795611)

### Proposed solution

Add new graph model to visualize network traffic.

### Alternatives considered

Add new graph model to visualize network traffic.

**Comment by prabhatsharma** [comment]
https://github.com/openobserve/openobserve/issues/2455

**Comment by prabhatsharma** [comment]
closing as duplicate
