### ISSUE TITLE
edit the root user (mail and password)

### ISSUE THREAD

**Issue by cbueche** [openobserve/openobserve#2751]
### Which OpenObserve functionalities are relevant/related to the feature request?

login

### Description

When installing Openobserve, I used a dummy value for root mail and password in `ZO_ROOT_USER_EMAIL` and `ZO_ROOT_USER_PASSWORD`. I have not found how to change them. I cannot create another `root` user.

### Proposed solution

Allow to change these values, either in GUI or better by setting an env variable with their new values and some flag `ZO_ROOT_USER_CHANGE`.

### Alternatives considered

Stopping openobserve, deleting the existing data and restarting from scratch with the desired root user.

**Comment by alhimik45** [comment]
Password can be changed on IAM page

**Comment by tedparagon** [comment]
@alhimik45 what if you need to reset the email or password because you can't login?

**Comment by alhimik45** [comment]
> @alhimik45 what if you need to reset the email or password because you can't login?

Yeah, this is a good reason to get some reset capability for the one who can set env vars

**Comment by hengfeiyang** [comment]
```
./openobserve reset -c root
```
Run tis command will reset the root username & password from `ENV`
