### ISSUE TITLE
Option to control "offline" time of metrics

### ISSUE THREAD

**Issue by ancoron** [openobserve/openobserve#2774]
### Which OpenObserve functionalities are relevant/related to the feature request?

dashboards, metrics

### Description

As a user, I want to set an "offline" timeout of "5 minutes" (or "2 hours") in a panel for a dashboard, so that if no metrics are retrieved from a certain group, the graph is interrupted and starts again once data becomes available.

This would allow me to see devices/sources "downtime" for a specific metric.

Current handling (metric not available between 12:40 and 14:05):
![image](https://github.com/openobserve/openobserve/assets/598136/1f191d15-89e9-46df-a386-20c13dfec4d7)

Desired handling (option 1 - interrupted):
![image](https://github.com/openobserve/openobserve/assets/598136/9cbdbe40-24ea-4cf4-a0c9-296146a669df)

Desired handling (option 2 - set to specific "offline" value):
![image](https://github.com/openobserve/openobserve/assets/598136/1fd38870-c982-4c44-8a12-e36c3af4dd13)

### Proposed solution

Simplest would be a new option in the panel "config", ideally with behavior configuration, e.g.:

* "Downtime detection":
  * type: checkbox
  * if enabled, brings up behavior configuration options
* downtime configuration options:
  * "Timeout":
    * type: text field
    * validation: time interval
    * default: "15 minutes"
  * "Downtime value":
    * type: textbox
    * validation: numeric
    * default: "0"
    * if set empty, will cause the graph to ignore the group entirely for the time bucket

### Alternatives considered

None available (AFAIK)

**Comment by ancoron** [comment]
I think the behavior is known as gap-filling in other graph/analysis tools.

**Comment by ktx-kirtan** [comment]
@ancoron I think you can now do this with the null value replacement. Set it to 0 and you should get this. Let me know if any issues with that.

**Comment by ancoron** [comment]
@ktx-kirtan Indeed, we have some options for some time now inside the "Config" of a Dashboard Panel:

![image](https://github.com/user-attachments/assets/5e01beb6-8a8e-486c-b6ec-7d9fb83035c8)
