### ISSUE TITLE
Logs: Search around not working

### ISSUE THREAD

**Issue by neha00290** [openobserve/openobserve#2776]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

https://github.com/openobserve/openobserve/assets/144308844/746f8faf-0984-4300-843f-f29b75a69a4a

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version
Commit Hash
Build Date
v0.8.2-rc3
f00cf14b430c27a54ff99ecc5407e76e28be5d7e
2024-02-22T07:45:07Z
```

**Comment by hengfeiyang** [comment]
@omkarK06 @bjp232004 i checked the API response, it returned some data, but it doesn't show in the UI.

**Comment by neha00290** [comment]
this is working now. closing the issue
