### ISSUE TITLE
streams: streams do not appear in all list when user clears text from search field 

### ISSUE THREAD

**Issue by neha00290** [openobserve/openobserve#2796]
### Which OpenObserve functionalities are the source of the bug?

streams

### Is this a regression?

Yes

### Description

https://github.com/openobserve/openobserve/assets/144308844/73bd38bc-0c80-448f-8ede-b758f08e16e4

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version
Commit Hash
Build Date
v0.8.2-rc4
07fee903708aef113d685d8b0a720f6f16bcd8d3
2024-02-26T23:15:20Z
```

**Comment by omkarK06** [comment]
Fixed by #2808
