### ISSUE TITLE
convert array to named fields

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#2815]
### Which OpenObserve functionalities are relevant/related to the feature request?

other

### Description

parsing fields using regex works, but the data cannot be used further in the query.

e.g.
```json
{
  "_timestamp": 1709165734047787,
  "body": "2024-02-29 00:15:30 15.128.22.213 GET /Administradores_Elina/service-worker.js - 443 - 15.128.69.103 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/122.0.0.0+Safari/537.36 https://ccwsqa/Administradores_Elina 200 0 0 6 15.159.53.87,+15.128.69.103:54910",
  "dropped_attributes_count": 0,
  "log_file_name": "u_ex240229_x.log",
  "severity": ""
}
```

can be parsed using

```sql
SELECT REGEXP_MATCH(body, '(?P<timestamp>[^\s]+ [^\s]+) (?P<client_ip>[^\s]+) (?P<http_method>[^\s]+) (?P<requested_path>[^\s]+) (?P<placeholder1>[^\s]+) (?P<server_port>[^\s]+) (?P<placeholder2>[^\s]+) (?P<referrer_ip>[^\s]+) (?P<user_agent>[^\s]+) (?P<referrer_url>[^\s]+) (?P<http_status>[^\s]+) (?P<other_codes>[^\s]+ [^\s]+) (?P<response_time>[^\s]+) (?P<forwarded_ips>.+)$') 
FROM "abc-stream"
```
regexp_match returns an array which cannot be used in a further subquery (we do not support subqueries yet)

### Proposed solution

a function like `array_to_fields` might be handy for this.

### Alternatives considered

use VRL to parse duirng ingestion

**Comment by hengfeiyang** [comment]
@taimingl i think we should use UDF to resolve this problem.

**Comment by taimingl** [comment]
> @taimingl i think we should use UDF to resolve this problem.

thanks @hengfeiyang for the pointer. I'll look into UDF and try that.

**Comment by taimingl** [comment]
> @taimingl i think we should use UDF to resolve this problem.

Hey @hengfeiyang, after learning more about UDF, I tried below three approaches, but none would work so far. If you have any other pointers or suggestions, please let me know. 

1. implementing a `string_to_fileds(input)` UDF, where `input` in the result of REGEXP_MATCH().
  [x] Issue: the result of REGEXP_MATCH() only contains matches, not the regex patterns. Can’t parsed the appropriate field names from that.
2. implementing a customized regexp_match_to_fields(field, pattern) UDF. I thought about parsing the pattern here to get field names and call DataFusion native regexp_match() function within.
  [x] Issue: we wouldn’t know how many fields are going to be returned by regexp_match beforehand, but that `return_type` is required when registering the UDF function.
3. Define the UDF by implementing the `ScalarUDFImpl` trait, which has a `return_type_from_exprs()` function to dynamically get the return type from input args.
  [x] Issue: currently, the only acceptable `return_type` when defining a UDF is `Result<Arc<DataType>> + Send + Sync>`, which only accepts one column, so **we wouldn't be able to expand the number of columns and change schema through UDF,** and this makes me think UDF can't help resolve this problem. 


Thanks @hengfeiyang for answering my questions on Slack. Will try if returning `DataType::Dictionary` works

**Comment by haohuaijin** [comment]
Hi @taimingl, for approach 3, maybe you can return the `DataType::Struct` type in `return_type_from_exprs()` method.
