### ISSUE TITLE
Log search breaks for some strings

### ISSUE THREAD

**Issue by laurst** [openobserve/openobserve#2831]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

No

### Description

When doing plain-text search, either in SQL mode or not, it seems like some strings are not escaped correctly and cause generated SQL to be invalid.

For instance:
```str_match(message, ' limit') -- note the space between limit```
returns an error: ```Error: Search SQL execute error```

Equivalent in SQL mode, same error:
```SELECT * FROM "my_stream" WHERE str_match(message, ' limit')```

Error in the server logs:
```ERROR openobserve::service::search::grpc: [session_id 2d2zsiqUqiU33b8LgzngYXC36zp] datafusion merge error: SQL error: TokenizerError("Unterminated string literal at Line: 1, Column 44")```

---

The issue is not the space, because ```str_match(message, ' header')``` works.

```str_match(message, 'limit')``` (without a space before `limit`) also works. So there's something about ``` limit```, with a space before, that causes it to not work.

---

Also note that it doesn't break when I have no logs that match this criteria (if I narrow down the date enough for instance). It just returns no results in this case. But if I do have logs that match ``` limit```, then I get the error.

### Please provide the version you discovered this bug in (check about page for version information)

```true
v0.8.2-rc3
e1bf4af0b69a2e7ed812c6a20fdb84c24557b629
2024-02-20T04:54:19Z

Also present in:
v0.8.1
1fd8d3d869c793345b4af300525b8ff2df24c5b2
2024-02-15T14:19:14Z
```

**Comment by hengfeiyang** [comment]
Thanks for report, i think this is a bug.
