### ISSUE TITLE
v0.8.2-rc5 vs v0.8.2-rc4 Significant performance degradation

### ISSUE THREAD

**Issue by faust93** [openobserve/openobserve#2839]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

Same hardware, same settings but rc5 is MUCH slower while observing or searching the logs.

## Details

Single node. Plain binary `openobserve-v0.8.2-rc5-linux-amd64-musl.tar.gz` (no docker)

#### Settings
```
ZO_DISK_CACHE_MAX_SIZE=1024 \
ZO_FEATURE_PER_THREAD_LOCK=true \
ZO_MEMORY_CACHE_MAX_SIZE=1024 \
ZO_MEMORY_CACHE_DATAFUSION_MAX_SIZE=1024 \
ZO_FEATURE_FULLTEXT_EXTRA_FIELDS="short_message,full_message" \
ZO_ROOT_USER_EMAIL="devops@company.com" \
ZO_ROOT_USER_PASSWORD="password" \
ZO_LOCAL_MODE_STORAGE="s3" \
ZO_S3_SERVER_URL="http://127.0.0.1:9000" \
ZO_S3_REGION_NAME="eu-dev-1" \
ZO_S3_ACCESS_KEY="admin" \
ZO_S3_SECRET_KEY="password123" \
ZO_S3_BUCKET_NAME="oob" \
ZO_S3_PROVIDER="minio" \
RUST_LOG="error" \
./openobserve
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.8.2-rc5-linux-amd64-musl
Linux: AlmaLinux release 8.6 (Sky Tiger) / Linux dev-apm 4.18.0-372.26.1.el8_6.x86_64 #1 SMP Tue Sep 13 06:07:14 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by hengfeiyang** [comment]
What is your previous version? and can you give same search response result for both version.

**Comment by faust93** [comment]
> What is your previous version? and can you give same search response result for both version.

Previous version:  openobserve-v0.8.2-rc4-linux-amd64-musl.tar.gz
Version v0.8.2-rc4:
`Showing 1 to 250 out of 2,383,443 hits in 557 ms. (Scan Size: 2.24 GB)`
Version v0.8.2-rc5:
`Showing 1 to 250 out of 2,531,393 hits in 3876 ms. (Scan Size: 2.37 GB)`

**Comment by hengfeiyang** [comment]
Thanks, Can you give some server side logs of the query, there are some logs like: 

```
[session_id 2d5IBI2VNIMyxJC3cXD8YpMBClI] ....
```

One search request have a session_id and will response in the result. then you can use the session_id to find out all of the logs related to the search request.

**Comment by faust93** [comment]
> Thanks, Can you give some server side logs of the query, there are some logs like:
> 
> ```
> [session_id 2d5IBI2VNIMyxJC3cXD8YpMBClI] ....
> ```
Sure, see logs attached
[rc4.log](https://github.com/openobserve/openobserve/files/14460550/rc4.log)
[rc5.log](https://github.com/openobserve/openobserve/files/14460551/rc5.log)

**Comment by hengfeiyang** [comment]
Got it, thank you very much, will check it. please rollback to rc4.

I found the reason is we changed the ingestion in memory implement, it caused an issue that there are too many groups of memtable and parquet files.

```
2024-03-01T11:35:25.268020160+00:00 INFO openobserve::service::search::grpc::wal: [session_id 2d5LK6wHlq4vGkQ958tpbnMrxqz] wal->mem->search: load groups 137, files 623, scan_size 19845685    
2024-03-01T11:35:25.293864936+00:00 INFO openobserve::service::search::grpc::storage: [session_id 2d5LK6wHlq4vGkQ958tpbnMrxqz] search->storage: stream default/logs/default, load files 16, into Memory cache done    
2024-03-01T11:35:25.373668368+00:00 INFO openobserve::service::search::grpc::wal: [session_id 2d5LK6wHlq4vGkQ958tpbnMrxqz] wal->parquet->search: load groups 176, files 713, scan_size 106094834    
```

**Comment by hengfeiyang** [comment]
Do you use binary or docker? I hope you can help test the hotfix.

**Comment by faust93** [comment]
> Do you use binary or docker? I hope you can help test the hotfix.

Plain binary, no docker

**Comment by hengfeiyang** [comment]
Thanks, Can you try rc6?

**Comment by faust93** [comment]
> Thanks, Can you try rc6?

It works! No issues with rc6 so far. Thanks!

ps: Initial logs display (no query) is snappy but queries are a bit slower compared to rc4 (rc6: 11211 ms vs rc4: 10576 ms) but much faster than rc5.
