### ISSUE TITLE
metadata stream has disappeared in web/streams

### ISSUE THREAD

**Issue by domyway** [openobserve/openobserve#2849]
### Which OpenObserve functionalities are the source of the bug?

streams

### Is this a regression?

Yes

### Description

<img width="1166" alt="image" src="https://github.com/openobserve/openobserve/assets/2039546/b5f88815-04d0-4974-8711-72e7c2d1e945">

metadata stream has disappeared. And why so many request in web/streams?

### Please provide the version you discovered this bug in (check about page for version information)

v0.8.2-rc4-732052c-amd64

**Comment by hengfeiyang** [comment]
@bjp232004 We need add another stream type `metadata`, and why there are 5 requests?

**Comment by bjp232004** [comment]
In some scenarios stream data volume got increased so we have to split stream api's into different stream types to accommodate all scenarios.

**Comment by bjp232004** [comment]
> @bjp232004 We need add another stream type `metadata`, and why there are 5 requests?

We will also check to dynamically fetch all types.
