### ISSUE TITLE
Restore the deleted stream?

### ISSUE THREAD

**Issue by lens0021** [openobserve/openobserve#2856]
### Which OpenObserve functionalities are relevant/related to the feature request?

streams

### Description

Hi, I am using OpenObserve by single node deployment on my laptop while considering deploying it as production usage.

I've noticed The log ingestion is good, but if I deleted the stream, the logs of the stream would have gone too.

Though I know the existence of confirming dialog, I want to know whether there is a way to restore the stream, or make it pending status instead of immediate deletion?

### Proposed solution

Provides restoring the deleted streams.

### Alternatives considered

Provides an server option to disallow to delete all stream.

**Comment by prabhatsharma** [comment]
the files do get deleted physically. So, unfortunately, you can't recover the deleted streams.

**Comment by lens0021** [comment]
Oh, Is it true for OpenObserve Cloud or Enterprise also? If so, is there a plan for pending deletion feature?

**Comment by prabhatsharma** [comment]
Yes, it's true for cloud and Enterprise too. Let's use this issue to discuss how the deletion protection feature should look like so we can add it to the roadmap
