### ISSUE TITLE
Automatically remove outdated data from the memory cache

### ISSUE THREAD

**Issue by hengfeiyang** [openobserve/openobserve#2874]
### Description

Automatically purge obsolete data from the memory cache to guarantee sufficient space for future requests.

## Reason

We've observed that a full cache significantly slows down search speed. 

## Solution

Implement a backend job to monitor available cache size, and initiate data removal until adequate space is secured. 

The size can be set using an environment variable like: `ZO_MEMORY_CACHE_KEEP_SIZE`. If not specified by the user, we can default to the value from `ZO_MEMORY_CACHE_RELEASE_SIZE`.

This strategy should apply to both memory cache and disk cache.

**Comment by domyway** [comment]
1. Expose the configuration for how often this job runs.
2. Be mindful of the frequency and the amount cleaned up each time during the cleaning process, to avoid causing instability by getting stuck in the cleanup process.
