### ISSUE TITLE
Realtime Alert silence period doesn't work

### ISSUE THREAD

**Issue by Rajin9601** [openobserve/openobserve#2908]
### Which OpenObserve functionalities are the source of the bug?

alerts

### Is this a regression?

No

### Description

Trying the realtime alert, I made an log based alert that triggers alot (condition like app_name = istio-proxy).
silence time was set as 10 (minutes).

However, as soon as i turned on the alert, slack messages were sent mulitple times in a minutes.

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version v0.8.1
Commit Hash 1fd8d3d869c793345b4af300525b8ff2df24c5b2
Build Date 2024-02-15T14:47:14Z
```

**Comment by tleerai** [comment]
Is this scheduled to be done? This is a blocker for our team.

**Comment by hengfeiyang** [comment]
@Subhra264 Can you help confirm this issue on v0.10.1?
