### ISSUE TITLE
UI: Has the way to view log pop-up window been changed to expand in place?

### ISSUE THREAD

**Issue by mongoliaredmountain** [openobserve/openobserve#291]
### Which ZincObserve functionalities are relevant/related to the feature request?

logs search

### Description

查看日志弹浮层的方式是否改变为原地展开

### Proposed solution

查看日志弹浮层的方式是否改变为原地展开，如同elk的那种方式

### Alternatives considered

查看日志弹浮层的方式是否改变为原地展开

**Comment by hengfeiyang** [comment]
@mongoliaredmountain  Let me translate the issue:

Can we change the method of viewing log dialog to expand in place like Kibana?

**Comment by mongoliaredmountain** [comment]
个人感觉搞成Kibana的那样查看更加的方便，更多的是查询，一眼能看到底的

**Comment by hengfeiyang** [comment]
done
