### ISSUE TITLE
OpenObserve unresponsive after trying to ingest data with telegraf

### ISSUE THREAD

**Issue by pizzarabe** [openobserve/openobserve#2921]
### Which OpenObserve functionalities are the source of the bug?

streams, ingestion, metrics

### Is this a regression?

Yes

### Description

Hi, the following setup:

I am running the OpenObserve prebuild binary version 0.9.0-rc6 on a Debian 12 server.

I was ingesting data with filebeat which worked fine.

However, after also installing telegraf (1.29.5-1) and pointing it to OpenObserve using the generated telegraf configuration the server starts to experience problems.

After telegram connects to OpenObserve it is looging stuff like that:

```
Mär 08 21:49:23 nsm openobserve[5148]: 2024-03-08T20:49:23.911230815+00:00 WARN openobserve::service::db::schema: Schema doesn't exist: /schema/default/metrics/mem_vmalloc_chunk DbError# key /schema/default/metrics/mem_vmalloc_chunk does not exist
Mär 08 21:49:23 nsm openobserve[5148]: 2024-03-08T20:49:23.912613361+00:00 WARN openobserve::service::db::schema: Schema doesn't exist: /schema/default/metrics/mem_buffered DbError# key /schema/default/metrics/mem_buffered does not exist
```

OpenObserve then adds the steams it was complaining about (I believe this is the expected behaviour)

![grafik](https://github.com/openobserve/openobserve/assets/12611136/cb733191-b9bf-4f4a-bca8-54bc42e1cb04)

After generating ~ 10-20 streams both telegraf and the previously working filebeat will stop and log errors like the following:

```

Mär 08 22:05:18 nsm telegraf[4967]: 2024-03-08T21:05:18Z E! [agent] Error writing to outputs.http: Post "http://127.0.0.1:5080/api/default/prometheus/api/v1/write": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
Mär 08 22:05:20 nsm filebeat[4523]: {"log.level":"error","@timestamp":"2024-03-08T22:05:20.815+0100","log.logger":"elasticsearch","log.origin":{"function":"github.com/elastic/beats/v7/libbeat/outputs/elasticsearch.(*Client).publishEvents","file.name":"elasticsearch/client.go","file.line":260},"message":"failed to perform any bulk index operations: Post \"http://127.0.0.1:5080/api/default/_bulk?filter_path=errors%2Citems.%2A.error%2Citems.%2A.status\": net/http: request canceled (Client.Timeout exceeded while awaiting headers)","service.name":"filebeat","ecs.version":"1.6.0"}
```

The OpenObserve web ui is still reponding and http 200s are still logged:

```
Mär 08 22:06:29 nsm openobserve[5148]: 2024-03-08T21:06:29.630250550+00:00 INFO actix_web::middleware::logger: 127.0.0.1 "GET /api/default/_data_stream/zeek HTTP/1.1" 200 76 "-" "-" "Elastic-filebeat/8.12.2 (linux; amd64; 0b71acf2d6b4cb6617bff980ed6caf0477905efa; 2024-02-15 13:39:15 +0000 UTC)" 0.000093
Mär 08 22:06:29 nsm openobserve[5148]: 2024-03-08T21:06:29.631023111+00:00 INFO actix_web::middleware::logger: 127.0.0.1 "GET /api/default/ HTTP/1.1" 200 222 "-" "-" "Elastic-filebeat/8.12.2 (linux; amd64; 0b71acf2d6b4cb6617bff980ed6caf0477905efa; 2024-02-15 13:39:15 +0000 UTC)" 0.000443
```

However, it seems like new information are not index anymore (e.g. no new files under the data folder) and parts of the ui are also stuck loading.
![grafik](https://github.com/openobserve/openobserve/assets/12611136/f4c405b2-57ec-423c-87bb-3ad5c505fe3c)

![grafik](https://github.com/openobserve/openobserve/assets/12611136/857f3550-07ec-44d4-9a22-d0a6d5e82070)

The service has to be restarted and as soon as telegraf connects the same process is started again.
OpenObserve does not log any errors or other warnings then the one mentioned before.

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: 0.9.0-rc6
OS: Debian GNU/Linux 12 (bookworm) (x86_64)
Kernel: 6.1.76-1
```

**Comment by hengfeiyang** [comment]
Thanks for report, Can you try rc5?

**Comment by pizzarabe** [comment]
@hengfeiyang yes, rc5 works. 
Also tried rc8, but it did show the same problems.
