### ISSUE TITLE
Pagination issue in aggregated query

### ISSUE THREAD

**Issue by bjp232004** [openobserve/openobserve#2973]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

Pagination getting displayed in aggregation query

https://alpha1.dev.zinclabs.dev/web/logs?stream_type=logs&stream=default&from=1710405780000000&to=1710406680000000&refresh=0&sql_mode=true&query=U0VMRUNUIG1heChfdGltZXN0YW1wKSBhcyBfdGltZXN0YW1wICwgY291bnQoKikgYXMgdGVzdCBGUk9NICJkZWZhdWx0IiA=&org_identifier=default&fast_mode=false

**Comment by neha00290** [comment]
this is fixed
