### ISSUE TITLE
The partition key flag isn't displaying on the Streams configuration page

### ISSUE THREAD

**Issue by hello2dj** [openobserve/openobserve#2976]
### Which OpenObserve functionalities are the source of the bug?

dashboards

### Is this a regression?

Yes

### Description

I've chosen the Kubernetes namespace as the partition key, but when I refresh the page, the flag isn't displaying. Partition is already working. It might just be a  ui bug
![image](https://github.com/openobserve/openobserve/assets/10645383/13c7fc42-6ba7-4d2c-b523-1ff5a8fb8cae)

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: V0.9.1
```

**Comment by neha00290** [comment]
@hello2dj - just confirmed, this is a bug. @omkarK06 please check

**Comment by neha00290** [comment]
this issue is fixed.
