### ISSUE TITLE
It's possiable to insert data like clickhouse use command line?（能否使用像clickhouse那样的命令行形式插入数据？）

### ISSUE THREAD

**Issue by sangensong** [openobserve/openobserve#299]
### Description

Now, insert data to zincobserve use http protocol. I think it's inconvenient

In addition, use json file will waste too much disk space. It's possible to support CSV file with Columns Name.

现在，为了向zincobserver插入数据，需要使用http请求，而且似乎只支持json格式，这样的话，可能不是很方便。
而且，使用json文件的话，我觉得很浪费原始文件的空间，能不能除了支持json文件外，也支持csv格式。
有没有一种可能是提供一个自己的客户端，然后使用客户端的形式，不走http协议，而是走[tcp协议](https://blog.csdn.net/pang_2899/article/details/125131718)。然后插入数据，提高性能

### Proposed solution

```sh
cat xxx.csv|zincobserver-client --usename='username' --password='password' --query='insert into org_id.stream format CSV'
```

### Alternatives considered

无

**Comment by hengfeiyang** [comment]
will resolve in #2056
