### ISSUE TITLE
Feature request: make database connection pool size configurable

### ISSUE THREAD

**Issue by TessaIO** [openobserve/openobserve#2995]
### Which OpenObserve functionalities are relevant/related to the feature request?

other

### Description

Currently, we're running openobserve in our sandbox environment with 3 ingesters, 3 compactors, and 2 queriers. 

After a while of setting up the environment and connecting openobserve to MySQL which serves as our Metadata storage, we found an increase in the connections to the MySQL database. 

After looking deeply into the code, we found that each replica would create a connection pool of size varying between `[min, max]` where `min = the number of cpu limits`. In our case, we're not specifying in CPU limit to any replica, therefore `min` would be equal to the number of cores of the host machine which is equal to 8, and that makes our openobserve creates at least 64 connection to the database which is not very convenient in our use case.

### Proposed solution

Add two environment variables `ZO_MIN_CONNECTION_POOL_SIZE` and `ZO_MAX_CONNECTION_POOL_SIZE` so control the number of connections made to the database. If one of these env variables is not set, we can proceed to the existing behavior of creating the connection pool based on the CPU limits.

### Alternatives considered

Nothing for the moment, but I'd be happy if there are easy workarounds for this problem.

**Comment by TessaIO** [comment]
Can you assign it to me? I can open a PR for this.

**Comment by hengfeiyang** [comment]
@TessaIO Thanks, and i suggest the env name could be:

```
ZO_META_CONNECTION_POOL_MIN_SIZE
ZO_META_CONNECTION_POOL_MAX_SIZE
```

use the same prefix `ZO_META_` will easy to recognition the options.

And the default value should be still use the `cpu_num` i think it is a good default value for everyone.
