### ISSUE TITLE
When I clicked the button 'Run Query', the query condition in the left panel would be cleared

### ISSUE THREAD

**Issue by xcxzzx-1** [openobserve/openobserve#3005]
### Which OpenObserve functionalities are the source of the bug?

traces

### Is this a regression?

Yes

### Description

![image](https://github.com/openobserve/openobserve/assets/18734720/8be7cec5-28a2-4d8e-ae32-1d83d9a283c2)
When I clicked the button 'Run Query', the query condition in the left panel would be cleared, as shown in the picture above.

### Please provide a link to a minimal reproduction of the bug

NA

### Please provide the exception or error you saw

```true
The query condition in the left panel should be hold when run query.
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.8.0
Commit Hash: 921b3971cda5cb69b128398c23b30242aa8272de
Build Date: 2024-01-29T17:50:18Z
OS: Linux x64
```

**Comment by neha00290** [comment]
@xcxzzx-1 checked this issue and for me its happening intermittently, Is this happening for you always? Will check and get back to you.

**Comment by xcxzzx-1** [comment]
@neha00290 yes, always. Every time I clicked 'Run Query', the duration value I inputed would be cleared. Need a gif?

**Comment by neha00290** [comment]
yes @xcxzzx-1  a gif would be great. Thank you

**Comment by xcxzzx-1** [comment]
@neha00290 

https://github.com/openobserve/openobserve/assets/18734720/b29dc559-c36d-4400-9157-e749b06e94dc

**Comment by omkarK06** [comment]
@xcxzzx-1 The maximum duration input value in the filters is set to correspond with the longest trace duration found in the response trace data.

**Comment by xcxzzx-1** [comment]
@omkarK06 Yes, I had got it. I just want to filter some traces by duration, and I find it  couldn't work when scroll or run query.
