### ISSUE TITLE
Question: Is there any way to cast a specific field from a type to another?

### ISSUE THREAD

**Issue by TessaIO** [openobserve/openobserve#3055]
### Description
I have a question regarding the casting of fields being ingested from one type to another. Is there any way that Openobserve can manage to do that or not?
For more context, I have a specific field in the logs that can be integer or float (depending on the use case). Can I use Openobserve to always cast that field to float during ingestion?

**Comment by hengfeiyang** [comment]
You can use `cast` or `arrow_cast` https://arrow.apache.org/datafusion/user-guide/sql/scalar_functions.html#arrow-cast

**Comment by TessaIO** [comment]
@hengfeiyang Any hint on how to use that to indicate to openobserve to cast the data before putting it in S3?

**Comment by hengfeiyang** [comment]
Sorry, you need `function` for ingestion part.

https://openobserve.ai/docs/user-guide/functions/#function-with-specified-input-columnsfields
https://openobserve.ai/docs/user-guide/functions/stream-association/
https://playground.vrl.dev/

**Comment by TessaIO** [comment]
Cool thanks! Is there any way to create these functions using Kubernetes config map or in any IAC format, or should I create them manually?

**Comment by prabhatsharma** [comment]
manually for now or using API calls. no IaC yet.

**Comment by TessaIO** [comment]
Thanks!
