### ISSUE TITLE
URL safe encoding

### ISSUE THREAD

**Issue by bjp232004** [openobserve/openobserve#3060]
### Which OpenObserve functionalities are the source of the bug?

alerts

### Is this a regression?

Yes

### Description

The current encoding mechanism lacks URL safety. Consequently, when passed into a URL, it may not function as anticipated.

### Anything else?
Below list of modules using encoding. 
- Need to test share URL functionality.
- Check copy functionality on ingestion page where we have data encoding.
- Under traces
- Stream explorer navigating back to logs page.
- RUM page query editor

**Comment by neha00290** [comment]
this is done
