### ISSUE TITLE
In some cases, this request would pend the homepage for a long time.

### ISSUE THREAD

**Issue by xcxzzx-1** [openobserve/openobserve#3067]
### Which OpenObserve functionalities are the source of the bug?

login, home

### Is this a regression?

Yes

### Description

https://fonts.googleapis.com/css2?family=Nunito+Sans:ital,wght@0,300;0,400;0,600;0,700;1,400;1,600;1,700&display=swap
![QQ20240322104742](https://github.com/openobserve/openobserve/assets/18734720/256ec40c-58e1-42cf-bd80-86a3de087503)
![QQ20240322104824](https://github.com/openobserve/openobserve/assets/18734720/a368e45f-f8c9-4a4d-a739-a46484eb447f)

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.8.0
Commit Hash: 921b3971cda5cb69b128398c23b30242aa8272de
Build Date: 2024-01-29T17:50:18Z
OS : linux 64
```

**Comment by hengfeiyang** [comment]
@bjp232004 @prabhatsharma They can't access google in some countries, maybe we need change the font resource into our own CDN or not use google fonts.

**Comment by faust93** [comment]
> @bjp232004 @prabhatsharma They can't access google in some countries, maybe we need change the font resource into our own CDN or not use google fonts.

I would suggest to embed fonts and all external resources into the local bundle. Otherways it's no go for air-gapped environments.

**Comment by bjp232004** [comment]
Please allow us some time. We will embed fonts in the next release.

**Comment by hengfeiyang** [comment]
I found a tools: https://www.jsdelivr.com/package/npm/get-google-fonts
