### ISSUE TITLE
Quick Mode issues

### ISSUE THREAD

**Issue by neha00290** [openobserve/openobserve#3077]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

- [x] Should not display error when user navigates to logs and directly switches sql more, - **fixed**
- [x] Interesting fields icon overlaps text on LHS - **fixed**
- [x] In sql mode when user selects some interesting fields and then edits the stream name manually, then the fields selected on editor to reset  - **Not sure how this should behave, currently the manually added stream loads but schema for that stream does not load** 
- [x] In sql mode if filters added after order by , the query fails by clicking on include/exclude search filter - **fixed**
- [x] Unable to search around due to debug popup. **fixed**
- [x] Currently see all values after search around instead of the selected interesting fields
- [x] Copy pasting query of stream A to stream B and run query, displays results of stream A but selection shows of Stream  - **it selects the copied stream again but throws an error to add order by, even when order by is added** 
- [ ] Match all index query- unable to view all results via pagination even when enough data is available
- [x] Invalid field name gets added in interesting field in SQL mode
- [x] Removing some field partially from SQL mode and then removing completely, switching off the SQL mode and then hitting run query, enables the removed options in interesting fields  **fixed**
- [x] Search around goes blank in a saved view scenario [Not able to reproduce]
- [x] Remove * when switch to quick mode from query  **fixed**
- [x] On deselecting and selecting fields, the fields do not reappear in the editor 

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version
Commit Hash
Build Date
v0.9.2-rc1
501846fdefba0aec0ff1b05546d749d41036171a
2024-03-22T10:37:04Z
```

**Comment by bjp232004** [comment]
Search around goes blank in a saved view scenario

Not able to reproduce
