### ISSUE TITLE
Querier pod ephemeral local storage exceeds the total limit.

### ISSUE THREAD

**Issue by mehrdad-khojastefar** [openobserve/openobserve#3159]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

No

### Description

When deployed OpenObserve in HA mode on kubernetes, querier pod exceeds the limit of 2G.
Since the querier is being deployed as an stateless component I think that there should be some retention on the files that is being processed in the container, and one more thing is I couldn't figure out why the querier ( which should be an stateless app ) relies on the ephemeral storage.

**Comment by hengfeiyang** [comment]
Didn't get you, What is the mean querier used exceeds storage? And how did you limit the storage 2GB?

**Comment by mehrdad-khojastefar** [comment]
When deployed on kubernetes we can limit the resources. So I've set the ephemeral storage limit to 2Gi
```
    Limits:
      cpu:                512m
      ephemeral-storage:  2Gi
      memory:             2Gi
    Requests:
      cpu:                100m
      ephemeral-storage:  2Gi
      memory:             128Mi
```
And I see that the querier pod exceeds this limit. 
```
Events:
  Type     Reason   Age    From     Message
  ----     ------   ----   ----     -------
  Warning  Evicted  5m57s  kubelet  Pod ephemeral local storage usage exceeds the total limit of containers 2Gi.
  Normal   Killing  5m57s  kubelet  Stopping container openobserve
```
From `kubectl describe`

**Comment by hengfeiyang** [comment]
Please disable disk cache
```
ZO_DISK_CACHE_ENABLED=false
```

**Comment by prabhatsharma** [comment]
We changed the helm chart and queriers are now statefulsets with dedicated PVCs for this purpose.
