### ISSUE TITLE
Replay wal error

### ISSUE THREAD

**Issue by aa1ss2** [openobserve/openobserve#3172]
### Which OpenObserve functionalities are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

![image](https://github.com/openobserve/openobserve/assets/79680252/3ee9f6e2-b5e6-454d-bfd1-723036b0c25c)

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version:openobserve v0.9.2-rc1
os:windows
```

**Comment by hengfeiyang** [comment]
Can you share the wal file for test? maybe you can connect me on Slack.

**Comment by aa1ss2** [comment]
[1712213149357554.zip](https://github.com/openobserve/openobserve/files/14889996/1712213149357554.zip)

**Comment by hengfeiyang** [comment]
i found the issue, because of windows path, will fix it soon
