### ISSUE TITLE
Is it possible to set a default time range for dashboards?

### ISSUE THREAD

**Issue by ericsheris-rumble** [openobserve/openobserve#3179]
Maybe this is a bug, maybe a feature request? We use different dashboards in grafana with different default time ranges. I don't see a way to do this in open observe dashboards. It seems like it defaults to 15 m until I change it, then it stays at whatever i changed it to as I move between dashboards. Am I missing something. Perhaps this could just be a `magic` dashboard variable or something if it doesn't already exist.

**Comment by gaby** [comment]
@prabhatsharma Any way of doing this? I have the same issue.

For example if i have a dashboard for cronjobs, data would be for example every 1hr. So every time I open the dashboard i have to change the interval.

**Comment by prabhatsharma** [comment]
This would be a feature request. Let's add this to backlog.

**Comment by neha00290** [comment]
this is done
