### ISSUE TITLE
Logs: web interface super slow

### ISSUE THREAD

**Issue by enote-kane** [openobserve/openobserve#3234]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

No

### Description

Even if queries are fast, the web UI is super slow and extremely resource-intensive compared to other log analysis web UIs like Kibana or Grafana.

Very often, it takes multiple seconds after the result from the query has been received until the new data is displayed and all UI components updated, so that one can actually work with the returned data.

This is in SQL mode, so without the additional histogram query.

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.9.1
Commit Hash: 67078a084907cec6e62f477fc51a0ab6746396df
Build Date: 2024-03-12T13:32:26Z
OS: Linux x64
```

**Comment by prabhatsharma** [comment]
How many columns do you have in your result set?

**Comment by ghost** [comment]
@prabhatsharma Depends on our analysis, but usually between 5 and 10.

**Comment by prabhatsharma** [comment]
and what is the size of each log record?

CPU?
RAM?
Browser?

**Comment by ghost** [comment]
@prabhatsharma The record size varies, but total uncompressed result JSON (from `/_search?type=logs`) is usually less than 1 MiB for 250 records returned.

My system:
* CPU: AMD Ryzen 7 PRO 6850U
* RAM: 32 GiB
* Browser: Firefox 124

Attaching a profile for a small session I just captured, demonstrating the lag that occurs on nearly any Web UI interaction, including but not limited to:
* adding columns to the output table
* removing columns
* resizing UI components
* opening log record details

[Firefox 2024-04-16 09.18 profile.json.gz](https://github.com/openobserve/openobserve/files/14993199/Firefox.2024-04-16.09.18.profile.json.gz)

I hope this may help a bit in diagnosing.

**Comment by prabhatsharma** [comment]
fixed by https://github.com/openobserve/openobserve/pull/4097
