### ISSUE TITLE
ALERTS: When upgrading from version 0.8.0 to 0.10.0, it was found that the alarm rules were not synchronized

### ISSUE THREAD

**Issue by oslet** [openobserve/openobserve#3249]
### Which OpenObserve functionalities are the source of the bug?

alerts

### Is this a regression?

No

### Description

When upgrading from version 0.8.0 to 0.10.0, it was found that the alarm rules were not synchronized

### Please provide the version you discovered this bug in (check about page for version information)

```true
version: v0.10.0
```

**Comment by hengfeiyang** [comment]
@Subhra264 I think we need migrate `trigger` into `scheduled_jobs` table.
