### ISSUE TITLE
ALERTS: Due to incorrect alarm URL links, logs cannot be opened correctly for query.

### ISSUE THREAD

**Issue by oslet** [openobserve/openobserve#3251]
### Which OpenObserve functionalities are the source of the bug?

alerts

### Is this a regression?

No

### Description

alarm url: https://xxxx.xxx.com/web/logs?stream_type=logs&from=1713176100000000&to=1713176160000000&refresh=0&sql_mode=true&query=U0VMRUNUICogRlJPTSAiImFwcGxpY2F0aW9ubG9nIFdIRVJFICJsZXZlbCIgPSAnRVJST1InIE9SREVSIEJZIF90aW1lc3RhbXAgREVTQw..&org_identifier=test&quick_mode=true&show_histogram=true

the queery parameters is incorrect
`
❯ printf 'U0VMRUNUICogRlJPTSAiImFwcGxpY2F0aW9ubG9nIFdIRVJFICJsZXZlbCIgPSAnRVJST1InIE9SREVSIEJZIF90aW1lc3RhbXAgREVTQw..' |base64 -d
SELECT * FROM ""applicationlog WHERE "level" = 'ERROR' ORDER BY _timestamp DESCbase64: 无效的输入
`

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.10.0
```

**Comment by hengfeiyang** [comment]
@bjp232004 @omkarK06 i think this PR caused this problem: https://github.com/openobserve/openobserve/pull/3133
I tested build UI use the version before this PR it works. You can test with this link:

http://localhost:5080/web/logs?stream_type=logs&stream=default&from=1713322883146246&to=1713322943146246&sql_mode=true&query=U0VMRUNUICogRlJPTSAiZGVmYXVsdCIgV0hFUkUgInN0YXR1cyIgPSA1MDM.&org_identifier=default

Please create `default` stream first.

**Comment by oslet** [comment]
![2024-04-19_13-58](https://github.com/openobserve/openobserve/assets/1573303/5a708064-ac3f-476f-8f82-1bea5a9b9de4)

{alert_url} variable encoding had some errors ?

**Comment by hengfeiyang** [comment]
Yes, we found that, fixing.
