### ISSUE TITLE
Error Using COALESCE in Dashboard Edit Panel

### ISSUE THREAD

**Issue by teandt** [openobserve/openobserve#3289]
### Which OpenObserve functionalities are the source of the bug?

dashboards

### Is this a regression?

Yes

### Description

After updating to Release v0.10.2-rc1, an error occurred in my dashboard. This did not happen with v0.9.2-rc1.

The error message is "Search field not found:" although it occurs with an existing field name used in the second argument of COALESCE. The error does not occur when the first argument is removed, leaving only one argument. Additionally, reversing the first and second arguments still results in an error with the second argument.
![image](https://github.com/openobserve/openobserve/assets/50020829/8e9b6ee9-eb5d-4e6f-a0d4-5a85b6388d60)

This operation worked correctly in the previous version, v0.9.2-rc1.
![image](https://github.com/openobserve/openobserve/assets/50020829/48b6b678-59ee-4d31-ae7e-945c0cc23130)

Has the COALESCE become unusable?

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.10.2-rc1
Commit Hash: ebdc19d02e1e3860dfad73a69b95e0ff059abd21
Build Date: 2024-04-19T01:24:32Z
OS: Linux x64 (use docker image)
```

**Comment by prabhatsharma** [comment]
I am not able to reproduce this. Coalesce works for me. @ktx-kirtan,  @hengfeiyang Are you able to reproduce this?

**Comment by hengfeiyang** [comment]
This is a bug of function `COALESCE` we didn't recognize the second column.
