### ISSUE TITLE
Logs- Getting search field not found when selecting interesting fields for enrichment table data under logs 

### ISSUE THREAD

**Issue by neha00290** [openobserve/openobserve#3362]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

Steps
1. Go to logs
2. Go to any enrichment table 
3. Run query and see results
4. Select interesting fields and run query
5. Observe the error

Actual result: Search field not found displayed 

Expected result: Selected interesting fields data to be displayed 

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version
Commit Hash
Build Date
v0.10.3
37d5ed662cf40d51fe69dccbb2c30d61a8a7c04d
2024-04-26T06:35:11Z
```

**Comment by hengfeiyang** [comment]
Because the field name include `-`, then we need use double quote for it, like this:
```sql
select "field-a" from tbl
```

**Comment by hengfeiyang** [comment]
@oasisk, Could we change the `-` to `_` in enrichment table fields, similar to what we did with log stream fields? 

Specifically:
1. Convert all letters to lowercase.
2. Replace everything that isn't `0-9a-z` with `_`.
