### ISSUE TITLE
Implement UI for Opentelemetry links between spans

### ISSUE THREAD

**Issue by cortopy** [openobserve/openobserve#3379]
### Which OpenObserve functionalities are relevant/related to the feature request?

traces

### Description

The opentelemetry specification defines [Links](https://opentelemetry.io/docs/specs/otel/trace/api/#link) as a way to link two or more `SpanContext`.

Each SDK has to implement this feature. For example, in Rust, this can be done with a span `add_link` method as documented [here](https://docs.rs/tracing-opentelemetry/latest/tracing_opentelemetry/trait.OpenTelemetrySpanExt.html#tymethod.add_link).

I have an application where I am linking two spans from two systems, to represent a `follows_from` type of relationship. However, there is no way that I know of in Openobserve to explore this in the UI console.

For the record, this is already implemented in Jaeger within the references section, where I can see the following for my traces, It looks like this:

![Screenshot from 2024-04-29 11-45-47](https://github.com/openobserve/openobserve/assets/8725825/e64cff8b-c12c-4746-9839-3e1e658c1065)

where I can click on both where the label that says " span from another trace " and the span id. By clicking on any of these I'm taken to the Span linked.

### Proposed solution

Do something similar in OpenOberve, where in addition to Tags, Process, and Events, the user can also see "links".

I'm not sure if the word is "links" or "references". The most recent specs mention [Links](https://opentelemetry.io/docs/specs/otel/trace/api/#link), but not References, which are defined in an archived [document](https://github.com/opentracing/specification/blob/master/specification.md#references-between-spans) here. The latter is also the document that Jaeger mentions as [supported](https://www.jaegertracing.io/docs/1.18/features/).

Links may more flexible and up to date, not a 100% certain. 

As a bonus, it would be great if this feature could be implemented in a way that the `Links` are displayed in both spans. Currently, Jaeger only displays one way as in "follows_from", but there's no way to inspect if a span has a "followed_by" type of relationship. This is probably because the Link was added only to one span and not the other.

### Alternatives considered

There is none provided by Openobserve.

**Comment by neha00290** [comment]
this is fixed
