### ISSUE TITLE
Line Chart thickness is not user-friendly with multiple fields

### ISSUE THREAD

**Issue by gaby** [openobserve/openobserve#3425]
### Which OpenObserve functionalities are the source of the bug?

dashboards

### Is this a regression?

No

### Description

When using a Line Chart with 2 variables in the Y-AXIS, it's impossible to see what the value is. The line thickness is too thin. There should be an option to configure line thickness, or the default should be higher.

### Please provide the version you discovered this bug in (check about page for version information)

```true
Latest version
```

**Comment by gaby** [comment]
Preview:

![image](https://github.com/openobserve/openobserve/assets/835733/06f0d9a5-e5c9-4b01-ae9e-50b62dbca4e0)

It's impossible to read the lines. The same happens in dark-mode:

![image](https://github.com/openobserve/openobserve/assets/835733/0eda5f45-0187-456c-80af-641b29c43c9f)

Using a longer timeframe:

![image](https://github.com/openobserve/openobserve/assets/835733/09be09b3-8b7c-43d6-885b-fb2934e20993)

Another example:

![image](https://github.com/openobserve/openobserve/assets/835733/c7abfd1c-d3a9-4e4d-b4cf-48a8fae99f80)

**Comment by gaby** [comment]
@ktx-kirtan Any update on this?

**Comment by gaby** [comment]
@ktx-vaidehi @ktx-kirtan I'm pretty sure this was fixed? I remember seeing a setting for line chart on OpenObserve recently

**Comment by ktx-kirtan** [comment]
Yes it is added: 
![image](https://github.com/user-attachments/assets/0154f47c-186c-4b0c-8f52-319985d8d298)

**Comment by gaby** [comment]
Thanks! 💪
