### ISSUE TITLE
[UI] Select regions for federated search

### ISSUE THREAD

**Issue by hengfeiyang** [openobserve/openobserve#3439]
### Which OpenObserve functionalities are relevant/related to the feature request?

log search

### Description

We need add region filter on the logs page with super cluster.

i already added the API for list regions:

`GET /api/clusters`

```json
{
	"us-east-1": [
		"dev3"
	],
	"us-west-2": [
		"dev4"
	]
}
```

The key is region name, the value is the clusters in the region.

### Proposed solution

-

### Alternatives considered

-

**Comment by neha00290** [comment]
testing new changes is done
