### ISSUE TITLE
[DOCS] Environment variables page is outdated and misleading

### ISSUE THREAD

**Issue by erkexzcx** [openobserve/openobserve#3445]
https://openobserve.ai/docs/environment-variables/ is outdated/misleading and does not represent current status of the project (based on breaking changes disclaimer in https://github.com/openobserve/openobserve/releases/tag/v0.10.0)

1. `ZO_META_STORE` does not contain anything related to `mysql`.
2. `nats` not mentioned at all.
3. Some information is misleading? `etcd` will not be used by default for cluster mode. :thinking: 

> For local mode, OpenObserve use sqlite as the metadata store.
> For cluster mode, OpenObserve use etcd as the metadata store.

Additionally, I am requesting you to update this page and specify which are needed for `cluster` version, which are needed for `standalone` version and which are common for both. :pray: Preferably, an additional column specifying for what version variable should be used.

Also, could you please fix (or update docs if that's already the case) the default values of these?

![image](https://github.com/openobserve/openobserve/assets/5955795/f5b7a23a-25cc-473e-8b1e-29dbcfd1fa56)

To my belief, setting only `ZO_DATA_DIR` to something like `/var/lib/openobserve/` should be enough for `ZO_DATA_DB_DIR`, `ZO_DATA_WAL_DIR`, `ZO_DATA_STREAM_DIR` and `ZO_DATA_CACHE_DIR` to default to `/var/lib/openobserve/<dir>` rather than remain `./data/openobserve/<dir>`. :thinking: Their defaults should be updated (if that's the case) to `$ZO_DATA_DIR/<dir>`

**Comment by erkexzcx** [comment]
Related: https://github.com/openobserve/openobserve/discussions/3310#discussioncomment-9366248

**Comment by gaby** [comment]
This variable is also missing from the docs `ZO_INGEST_FLATTEN_LEVEL`, it was introduced in https://github.com/openobserve/openobserve/pull/3218

This issue should probably go in https://github.com/openobserve/openobserve-docs

@prabhatsharma @hengfeiyang Updates to docs are urgent, kind of hard to be checking the source code to see which new ENV's are available

**Comment by prabhatsharma** [comment]
I am working on updating it. Already made some updates. I'll try to finish it as soon as possible.

**Comment by prabhatsharma** [comment]
Closing this as all variables have been covered. We will keep improving the minor ones.
