### ISSUE TITLE
Bug with stacked horizontal view 

### ISSUE THREAD

**Issue by MennaKassem** [openobserve/openobserve#3453]
### Which OpenObserve functionalities are the source of the bug?

dashboards

### Is this a regression?

Yes

### Description

[](url)there is an issue with the horizontal stalked view it gives wrong numbers although the same sql query for vertical stalked view is working fine , the response for ex here shows that the nymcard has the most calls but the view for horizontal gives wrong indication.
![Uploading Screen Shot 2024-05-09 at 1.46.36 PM.png…]()
![Uploading Screen Shot 2024-05-09 at 1.48.29 PM.png…]()
![Uploading Screen Shot 2024-05-09 at 1.55.10 PM.pn
<img width="746" alt="Screen Shot 2024-05-09 at 1 58 11 PM" src="https://github.com/openobserve/openobserve/assets/106233281/b2a1a579-e26d-49dd-b16c-a9f4ad37c175">
g…]()

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.10.5
Commit Hash: 30d06f180da82120f75eb08b702eeb0e10438470
Build Date: 2024-04-30T09:31:56Z
```

**Comment by prabhatsharma** [comment]
None of your image attachments are visible. Can you help fix it.

**Comment by neha00290** [comment]
this is fixed and retested
