### ISSUE TITLE
Stream Pipelines 

### ISSUE THREAD

**Issue by omkarK06** [openobserve/openobserve#3464]
### Which OpenObserve functionalities are relevant/related to the feature request?

streams

### Description

**Overview:**
Stream pipelines offer a visual and intuitive way to process streams. With an easy drag-and-drop interface, users can construct stream pipelines, add conditional routing which creates new streams from existing stream, and associate functions with ease. This feature enhances the platform's capability to handle streaming data efficiently.

### Proposed solution

**Features:**

1. Stream Pipeline Creation:
   Users can easily create stream pipelines using a drag-and-drop interface.
2. Conditional Routing (Stream Creation):
   Conditional routing of streams allows users to create new streams based on predefined conditions from the existing stream.
3. Function Association:
   Users can associate functions with streams to process data as required.
4. Pipeline Visualization:
   Users can visualize the the pipeline, making it easy to understand and debug.

**Flow of Pipeline**
During execution of pipeline, routings will get executed before functions

![Screenshot 2024-05-10 at 1 42 52 PM](https://github.com/openobserve/openobserve/assets/127078473/d3022428-c0fb-42c9-98f9-f3e3f1e967a3)

### Alternatives considered

no

**Comment by omkarK06** [comment]
Feature PR - #3282

**Comment by gaby** [comment]
@omkarK06 That's a pretty cool feature, are the functions a specific language? Having VRL there would be nice / performant.

**Comment by neha00290** [comment]
testing for this ticket is complete
