### ISSUE TITLE
Error displayed when user clicks pagination and then search around

### ISSUE THREAD

**Issue by neha00290** [openobserve/openobserve#3473]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

https://github.com/openobserve/openobserve/assets/144308844/31125dee-0a93-44d5-b82d-3c99794c9970

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version
Commit Hash
Build Date
v0.10.5
5ce8f1dd7cdfdaf5676d73fdab39da68fef73aa3
2024-05-10T12:49:41Z
```

**Comment by bjp232004** [comment]
I am not able to reproduce it after following the steps. Must be fixed with latest deployment.

**Comment by neha00290** [comment]
closing this as unable to replicate
