### ISSUE TITLE
User defined schema for existing streams

### ISSUE THREAD

**Issue by omkarK06** [openobserve/openobserve#3483]
### Which OpenObserve functionalities are relevant/related to the feature request?

streams

### Description

User can select fields and add to "User Defined Schema". 
During querying/exploring only those defined schema fields will be available in schema, rest all fields will be available in "_all" field in the schema

### Proposed solution

Enable selection of fields in stream setting and define fields as "User Defined Schema"

### Alternatives considered

no

**Comment by neha00290** [comment]
this is tested and complete
