### ISSUE TITLE
debian

### ISSUE THREAD

**Issue by gorec2005** [openobserve/openobserve#3495]
### Which OpenObserve functionalities are the source of the bug?

Don't known / other

### Description

Hi!
Got only 'Illegal instruction' after try to exec openobserve (from openobserve-v0.10.6-rc1-linux-amd64.tar.gz)
under:
`Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm`
with:
`Architecture:             x86_64
  CPU op-mode(s):         32-bit, 64-bit
  Address sizes:          48 bits physical, 48 bits virtual
  Byte Order:             Little Endian
CPU(s):                   2
  On-line CPU(s) list:    0,1
Vendor ID:                AuthenticAMD
  BIOS Vendor ID:         AMD              
  Model name:             AMD Athlon(tm) II X2 B24 Processor
`
processor - in proxmox LXC and in proxmox HOST-OS...

### Please provide the exception or error you saw

```true
root@pve:/opt# ./openobserve
Illegal instruction

root@pve:/opt#
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version v0.10.6-rc1-linux-amd64
```

**Comment by hengfeiyang** [comment]
```
Illegal instruction
```

it means there are some cpu feature that your cpu don't support, we need:
```
+sse2,+ssse3,+sse4.1,+sse4.2,+aes
```

**Comment by gorec2005** [comment]
You right! my cpu does not have +sse4.1,+sse4.2,+aes :-(...
