### ISSUE TITLE
Horizontal Dashboard has issue with ORDER BY 

### ISSUE THREAD

**Issue by MennaKassem** [openobserve/openobserve#3499]
### Which OpenObserve functionalities are the source of the bug?

dashboards

### Is this a regression?

Yes

### Description

The horizontal dashboard has issue with the order by although it is working well with the vertical dashboard. here the ORDER BY requests DESC , should show as the vertical dashboards shows nymcard then zoho then lago and so on . it works fine with vertical as shown but not working with horizontal.
<img width="1084" alt="Screen Shot 2024-05-13 at 10 35 24 AM" src="https://github.com/openobserve/openobserve/assets/106233281/b6eefc58-39f3-4be3-b780-1fba30546e20">
<img width="1088" alt="Screen Shot 2024-05-13 at 10 35 32 AM" src="https://github.com/openobserve/openobserve/assets/106233281/f1818e4f-5316-4822-adf6-56a96d3de8b5">

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.10.5
Commit Hash: 30d06f180da82120f75eb08b702eeb0e10438470
Build Date: 2024-04-30T09:31:56Z
```

**Comment by gaby** [comment]
@ktx-abhay I seen this affect the Data Table too. When I use Order By and LIMIT the data changes every time I click "Run Query" when creating a visualization.

**Comment by ktx-abhay** [comment]
- When the ORDER BY clause is not used with LIMIT, the SQL query will return a random set of 'n' results. 
- However, if you specify both ORDER BY and LIMIT, the query will return the top 'n' results based on the ordering specified in the ORDER BY clause.

**Comment by neha00290** [comment]
this is fixed
