### ISSUE TITLE
Stream settings- On re-adding the user defined schema to the list, settings UI appears in loading state

### ISSUE THREAD

**Issue by neha00290** [openobserve/openobserve#3540]
### Which OpenObserve functionalities are the source of the bug?

streams

### Is this a regression?

Yes

### Description

https://github.com/openobserve/openobserve/assets/144308844/c51a1c3c-471d-46b5-8fe8-2c29561b043b

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version
Commit Hash
Build Date
v0.10.6-rc2
5bd7bf13a7d28152c53a3225e985aa993c4f6e31
2024-05-17T07:54:09Z
```

**Comment by bjp232004** [comment]
Deloyment was in-progress

**Comment by neha00290** [comment]
closing this issue as this working as expected
