### ISSUE TITLE
Dashboard Reports

### ISSUE THREAD

**Issue by Subhra264** [openobserve/openobserve#3565]
### Which OpenObserve functionalities are relevant/related to the feature request?

dashboards

### Description

Overview: Dashboard reports are introduced to let users generate pdf of selected dashboards and send it over smtp to appropriate recipients automatically by the openobserve server in a scheduled manner. For now, only one dashboard tab can be selected for one report.

### Proposed solution

Prerequisite:
1. SMTP configurations must be enabled.
2. Chrome ENV configurations must be enabled.
3. `ZO_WEB_URL`, `ZO_REPORT_USER_NAME`, `ZO_REPORT_USER_PASSWORD` must be specified.

Features:
1. Report creation: User can create a report by going to the `Report` section of the UI, clicking on `Add Report` button, and filling up all the required fields.
2. In the `Schedule` section there are various options to schedule report - 
    - Cron jobs: User can specify the cron expression (e.g. 0 * * * * * to trigger report every minute)
    - Once: The report will be triggered only once.
    - Hourly: Report will be triggered hourly.
    - Daily: Report will be triggered daily (every 24 hours)
    - Weekly: Report will triggered weekly (every 7 days).
    - Monthly: Report will be triggered monthly (every 30 days).
    - Custom: The interval can be customized.
    If `Send Now` button is clicked, the report trigger will start immediately and the frequency of trigger is as selected (Once, Hourly etc). Instead of sending immediately, the user also can customize from when the user wants to start the report triggers.
 
<img width="1473" alt="Screenshot 2024-05-22 at 12 10 34 PM" src="https://github.com/openobserve/openobserve/assets/59690052/47fe127a-503a-40c2-9708-4837cd7f89c0">

3. In the `Share` section, user can give the email subject in the `Title` field, comma(',')/semi colon(';') separated emails in recipients section and the email message as well.
<img width="1476" alt="Screenshot 2024-05-22 at 12 25 08 PM" src="https://github.com/openobserve/openobserve/assets/59690052/d7faf31f-477d-43ff-8577-74ad19fdc564">

4. Just like alerts, reports also can be enabled/disabled and all the details can also be updated (except the report name).

### Alternatives considered

NA

**Comment by neha00290** [comment]
this is done

**Comment by atonusgit** [comment]
I've set these environment variables (values mostly hidden)

ZO_DATA_DIR=
ZO_ROOT_USER_EMAIL=
ZO_ROOT_USER_PASSWORD=
ZO_REPORT_USER_EMAIL=
ZO_REPORT_USER_PASSWORD=
ZO_WEB_URL=https://example.com
ZO_REPORT_SERVER_URL=https://example.com
ZO_REPORT_SERVER_HTTP_PORT=443
ZO_REPORT_SERVER_HTTP_ADDR=
ZO_CHROME_ENABLED=true
ZO_SMTP_ENABLED=true
ZO_SMTP_HOST=example-smtp.com
ZO_SMTP_PORT=587
ZO_SMTP_USER_NAME=
ZO_SMTP_PASSWORD=
ZO_SMTP_FROM_EMAIL=

But I'm getting this error, when I try to trigger a report:

`ERROR openobserve::service::alerts::scheduler: Error sending report to subscribers: Error contacting report server: error sending request for url (https://example.com/api/Company/reports/testing_report/send?timezone=Europe%2FHelsinki) `

Turning on RUST_LOG=debug didn't help.

Maybe you can help me?
