### ISSUE TITLE
Multiple field selection in stream settings

### ISSUE THREAD

**Issue by omkarK06** [openobserve/openobserve#3568]
### Which OpenObserve functionalities are relevant/related to the feature request?

streams

### Description

1. All fields in the table can be selected to Delete or Add/Remove from User Defined Schema.
2. User can search and click on select all fields checkbox to select all the filtered fields.

![Screenshot 2024-05-22 at 1 41 18 PM](https://github.com/openobserve/openobserve/assets/127078473/a00b804c-b943-4b98-909b-2923500aba36)

### Proposed solution

Add a checkbox in the table header selection column

### Alternatives considered

-

**Comment by neha00290** [comment]
this is tested and works as expected
