### ISSUE TITLE
Could not create member user in OSS version

### ISSUE THREAD

**Issue by Mart-Bogdan** [openobserve/openobserve#3601]
### Which OpenObserve functionalities are the source of the bug?

users

### Is this a regression?

Yes

### Description

https://openobserve.ai/docs/user-guide/users/ says that new users can be admins and members

U can't create new member, only admin. Either this is a bug in code or bug in documentation, if this is Enterprise feature.
![image](https://github.com/openobserve/openobserve/assets/775038/7c847160-f094-4c0a-8f0f-e952452afd37)

### Please provide the exception or error you saw

```true
I've run using docker command from readme


docker run -d \ 
      --name openobserve \
      -v $PWD/data:/data \
      -p 5080:5080 \
      -e ZO_ROOT_USER_EMAIL="root@example.com" \
      -e ZO_ROOT_USER_PASSWORD="Complexpass#123" \
      public.ecr.aws/zinclabs/openobserve:latest
```
```


### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.10.6-rc2
Commit Hash: 4d7cc602dc62856fbd14912dbf4e0e8375b5bc2
Build Date: 2024-05-13T10:04:50Z
OS: linux x64 (docker)


Docker image: public.ecr.aws/zinclabs/openobserve:latest
Digest: sha256:6758d62bff83894a4cdf2be3e6612300fa39690f498bc29c0b87e0f46f285deb
```

**Comment by gaby** [comment]
@Mart-Bogdan The member role was removed in early 2024/ late 2023, the docs were not updated.

**Comment by Mart-Bogdan** [comment]
@gaby thanks for answer. Do you know why it was removed?

It seems very useful.

**Comment by prabhatsharma** [comment]
member and admin were not really any different other than member could not create another user. We had to remove it as we were working on advanced RBAC for enterprise version and the manual implementation of roles was conflicting with that. We chose to get rid of it since it was not of much use anyways. We will bring the functionality back soon.

**Comment by prabhatsharma** [comment]
For anyone stumbling upon this, please use the enterprise version to get RBAC. Enterprise version is free to use if you are ingesting under 200 GB of data daily.
