### ISSUE TITLE
Histogram count while aggregation query

### ISSUE THREAD

**Issue by bjp232004** [openobserve/openobserve#3609]
### Description

Since pagination will be used with the aggregation query, the sum of "zo_sql_num" doesn't reflect the number of rows. We decided to include the track_total_hits flag in the histogram query during aggregation, but this still returns the count of all records rather than the number of rows in the actual data.

### Proposed solution

TBD

### Alternatives considered

NA

**Comment by neha00290** [comment]
this is fixed
