### ISSUE TITLE
[Upgrade] from v0.10.3 up to v0.10.6 some erros

### ISSUE THREAD

**Issue by oslet** [openobserve/openobserve#3640]
### Which OpenObserve functionalities are the source of the bug?

alerts

### Is this a regression?

No

### Description

After upgrading from v0.10.3 to v0.10.6, I noticed the following error in the console, but the alert functionality has not been affected. Could you please help identify the cause of this issue?
the console log error:
`
openobserve[162471]: 2024-05-31T05:45:27.372951704+00:00 ERROR openobserve::job::alert_manager: [ALERT MANAGER] run schedule jobs error: SqlxError# error returned from database: 1292 (22007): Truncated incorrect INTEGER value: '15,11,12,16,7'
`

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.10.6
```

**Comment by hengfeiyang** [comment]
@Subhra264 The user use `MySQL 8.0.36`
