### ISSUE TITLE
Docker container stops without error on RPi4

### ISSUE THREAD

**Issue by MijnUsername** [openobserve/openobserve#3654]
### Description

I've followed the Docker instructions at https://openobserve.ai/docs/quickstart/#self-hosted-installation and performed the following command 
`docker run -i -v /home/pihole/openobserve/data:/data -e ZO_DATA_DIR="/data" -p 5080:5080 \
    -e ZO_ROOT_USER_EMAIL="root@example.com" -e ZO_ROOT_USER_PASSWORD="Complexpass#123" \
    public.ecr.aws/zinclabs/openobserve:latest`

The following appears in the console;
2024-05-31T13:36:50.421676398+00:00 INFO openobserve: Starting OpenObserve v0.10.7-rc2
2024-05-31T13:36:50.421791823+00:00 INFO openobserve: System info: CPU cores 4, MEM total 7810 MB, Disk total 234 GB, free 172 GB

After that the container stops. No error messages, nothing. 

I've tried changing the permissions of the /home/pihole/openobserve folder by chown -R, but that didn't change anything. The same messages as above appear in the console and the containers stops. 

I don't know what I could try next. 

Processor details: 
processor       : 0 [1, 2 and 3]
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

Hardware        : BCM2835
Revision        : d03115
Serial          : [removed]
Model           : Raspberry Pi 4 Model B Rev 1.5

```true
OpenObserve v0.10.7-rc2 from public.ecr.aws/zinclabs/openobserve:latest
```

**Comment by hengfeiyang** [comment]
Default, we need the CPU features: `+aes,+neon` for ARM CPU architecture.  i think that is the problem. can you confirm do your CPU support this features?

**Comment by hengfeiyang** [comment]
dup #3910
