### ISSUE TITLE
The query data does not have an ID

### ISSUE THREAD

**Issue by yupor5** [openobserve/openobserve#3682]
### Description

The query data does not have an ID

We need to add a self increasing ID so that we can query more accurately

### Proposed solution

The query data does not have an ID

support

select * from test3 where id=22

### Alternatives considered

The query data does not have an ID

support

select * from test3 where id=22

**Comment by prabhatsharma** [comment]
What is your use case for this?

**Comment by yupor5** [comment]
When querying, it was found that the time would have the same timestamp

When adding a self increasing ID, only one piece of data can be queried, and sub queries and join queries cannot be performed within it

**Comment by prabhatsharma** [comment]
Why do you want to query based on ID or timestamp?
