### ISSUE TITLE
Version: v0.10.7-rc4 gives ERROR in the logs:  ingester::wal: Unable to open the wal file err: FileIdentifierMismatch, skip

### ISSUE THREAD

**Issue by sudhirbits** [openobserve/openobserve#3689]
### Which OpenObserve functionalities are the source of the bug?

streams, Don't known / other

### Is this a regression?

Yes

### Description

Upgraded from v0.8.0 to v0.10.7-rc4 and started seeing some errors in the logs: 

obsrv  | 2024-06-06T11:02:48.708588765+00:00 ERROR ingester::wal: Unable to open the wal file err: FileIdentifierMismatch, skip    
obsrv  | 2024-06-06T11:02:48.708592605+00:00 WARN ingester::wal: starting replay wal file: "/var/lib/openobserve/wal/logs/0/default/logs/1714479388293476.wal"    
obsrv  | 2024-06-06T11:02:48.708628375+00:00 ERROR ingester::wal: Unable to open the wal file err: FileIdentifierMismatch, skip    
obsrv  | 2024-06-06T11:02:48.708631585+00:00 WARN ingester::wal: starting replay wal file: "/var/lib/openobserve/wal/logs/0/default/logs/1714479388293535.wal"    
obsrv  | 2024-06-06T11:02:48.708677825+00:00 ERROR ingester::wal: Unable to open the wal file err: FileIdentifierMismatch, skip    
obsrv  | 2024-06-06T11:02:48.708680965+00:00 WARN ingester::wal: starting replay wal file: "/var/lib/openobserve/wal/logs/0/default/logs/1714479388208604.wal

The server starts fine no issues after these ERRORS are displayed in the logs. 

### Please provide the exception or error you saw

```true
obsrv  | 2024-06-06T11:02:48.708588765+00:00 ERROR ingester::wal: Unable to open the wal file err: FileIdentifierMismatch, skip    
obsrv  | 2024-06-06T11:02:48.708592605+00:00 WARN ingester::wal: starting replay wal file: "/var/lib/openobserve/wal/logs/0/default/logs/1714479388293476.wal"    
obsrv  | 2024-06-06T11:02:48.708628375+00:00 ERROR ingester::wal: Unable to open the wal file err: FileIdentifierMismatch, skip    
obsrv  | 2024-06-06T11:02:48.708631585+00:00 WARN ingester::wal: starting replay wal file: "/var/lib/openobserve/wal/logs/0/default/logs/1714479388293535.wal"    
obsrv  | 2024-06-06T11:02:48.708677825+00:00 ERROR ingester::wal: Unable to open the wal file err: FileIdentifierMismatch, skip    
obsrv  | 2024-06-06T11:02:48.708680965+00:00 WARN ingester::wal: starting replay wal file: "/var/lib/openobserve/wal/logs/0/default/logs/1714479388208604.wal
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.10.7-rc4
Commit Hash: 43e2392ebb1f60b77f9bad98366852a7e947636d
Build Date: 2024-06-03T12:32:46Z
```

**Comment by hengfeiyang** [comment]
This is expect, the wal file is corrupt, when we reply the data, will print this and skip it. maybe the app crashed or the system crashed, or the disk is full.
