### ISSUE TITLE
Logs- Histogram not showing correct data on zoom in 

### ISSUE THREAD

**Issue by neha00290** [openobserve/openobserve#3690]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

Steps
1. Go to logs.
2. Enable histogram and run query
3. Zoom in to histogram
4. Observe if the data displayed appears for selected date

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version
Commit Hash
Build Date
v0.10.7-rc3
747765970be923cc49de0c26f6aae18c93a9ed91
2024-06-04T13:40:05Z
```

**Comment by bjp232004** [comment]
As we discussed, after zoom in user need to click on Run Query button on logs page. So no need to change anything,

**Comment by neha00290** [comment]
closing this issue
