### ISSUE TITLE
Wrong data type for a field after applying a function

### ISSUE THREAD

**Issue by TessaIO** [openobserve/openobserve#3740]
### Which OpenObserve functionalities are the source of the bug?

functions

### Is this a regression?

No

### Description

We have a function associated with our stream which is the following:

```
. = map_values(., recursive: true) -> |value| { 
    if is_integer(value) {
        to_float!(value)
    } else {
        value
    }
}
.level = to_string!(.level) 
.
```

It mainly tries to convert every int to a float. It works since the Glue crawler is inferring all the integer fields as a float. 
However, when I download one of the parquet files and read the schema e.g. using this python Library `pyarrow.parquet` it shows that there are some fields that are of type int64.
It should be noted that the values for the field are always null in the parquet files that we checked.

Does the ingester change the parquet schema after applying the stream functions?

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.10.1
```

**Comment by TessaIO** [comment]
@oasisk are you working on it? I can give it a shot actually if you didn't start.

**Comment by TessaIO** [comment]
@hengfeiyang @oasisk any updates on this?

**Comment by hengfeiyang** [comment]
i tested, but i can't reproduce it.

i tried your function, and in the end, everything is float64

what is you version? and after you setting this function please wait at least 10 minutes and then check the latest parquet file.

also, after you setting this function and association to the stream, then you can refresh and check the stream detail, it should tell you what is the field type, it should be float.

**Comment by TessaIO** [comment]
> i tried your function, and in the end, everything is float64

Yes, I can confirm that. Even in MySQL, everything is float64.

> what is you version?

0.10.1



> also, after you setting this function and association to the stream, then you can refresh and check the stream detail, it should tell you what is the field type, it should be float.

This is also done, and I can confirm that it's float. The problem happens when the field value is null, the parquet file header shows that the type of the field is int. I'm suspecting that when the value of the field is null in the parquet file, there can be a problem with type inference. But I don't really know whether it's true or not.

**Comment by hengfeiyang** [comment]
If the field in the schema is `float64` then even some record the field value is null, in the parquet file it also should be `float64`, can you confirm the parquet file again?

**Comment by hengfeiyang** [comment]
You can try use `bdt` to check the schema in the parquet. https://github.com/datafusion-contrib/bdt

**Comment by TessaIO** [comment]
This is the result from `bdt`, and btw all of the other fields are converted successfully, but that field specifically is not.

<img width="841" alt="Screenshot 2024-06-21 at 12 51 09" src="https://github.com/openobserve/openobserve/assets/161601825/10b858c1-d6f9-4f4a-a230-bb963979a43e">

**Comment by hengfeiyang** [comment]
what is the field type you can see in the stream page of this field? can you give a screenshot?

**Comment by TessaIO** [comment]
It's float
<img width="628" alt="Screenshot 2024-06-21 at 13 16 26" src="https://github.com/openobserve/openobserve/assets/161601825/bc3fdb2d-562a-4aa7-ad3b-091b86201bd2">

**Comment by hengfeiyang** [comment]
okay, did the parquet file generate after you set the function? or, can you try v0.10.8? i followed your steps, but it works fine.

**Comment by TessaIO** [comment]
> okay, did the parquet file generate after you set the function?

Yes.



> or, can you try v0.10.8? i followed your steps, but it works fine.

We're planning the upgrade next week, I will keep you updated. Thanks!

**Comment by TessaIO** [comment]
@hengfeiyang 0.10.8 is till in rc phase, so we'll probably upgrade to 0.10.7. Can you confirm that the problem does not exist on v0.10.7?

**Comment by hengfeiyang** [comment]
you can safe upgrade to v0.10.8-rc2

**Comment by TessaIO** [comment]
@hengfeiyang seems to be working thanks!
