### ISSUE TITLE
Error in displaying for trace span info

### ISSUE THREAD

**Issue by dangweiwu** [openobserve/openobserve#3742]
### Which OpenObserve functionalities are the source of the bug?

traces

### Is this a regression?

Yes

### Description

When there are multiple span bars, click on the new one, and the old information will not disappear.

![70bdc9d92b288ff5ce6c92ea452dcad](https://github.com/openobserve/openobserve/assets/39506573/666aab6e-4ac2-45ef-b0de-82c95d0d0e8a)
![f0a3932173ec551b66f859f38ca2b6b](https://github.com/openobserve/openobserve/assets/39506573/1dab36ca-7709-4d3f-94b0-7f7efe6d62da)
![d8a4a7d2012f544887c3413603e9bcc](https://github.com/openobserve/openobserve/assets/39506573/087c2320-ba47-4e60-81aa-dac986bd6d58)

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version v0.10.7
Commit Hash 611f2e1c29df33a2df8e3be8a726889b07485284
Build Date 2024-06-12T14:30:31Z
```

**Comment by hengfeiyang** [comment]
fixed
