### ISSUE TITLE
Dashboard- On hover, Line chart values visible but Line is missing 

### ISSUE THREAD

**Issue by neha00290** [openobserve/openobserve#3755]
### Which OpenObserve functionalities are the source of the bug?

dashboards

### Is this a regression?

Yes

### Description

Steps
1. Go to dashboard and create a line chart
2. Hover and observe that line is not visible but values are displayed on hover

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version
Commit Hash
Build Date
v0.10.7
6ca8a352b38ee930fda106bc613b29621ad024b3
2024-06-17T10:35:03Z
```

**Comment by ktx-kirtan** [comment]
This can be fixed with the new show symbol option
