### ISSUE TITLE
Query error with case when as the group field

### ISSUE THREAD

**Issue by hengfeiyang** [openobserve/openobserve#3757]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

```sql
SELECT max(_timestamp) as _timestamp, (CASE WHEN variations LIKE '%value%' THEN 'correct' ELSE 'incorrect' END) as bucket, count(*) as counts 
FROM tbl 
WHERE myfield='view' 
GROUP BY bucket 
ORDER BY _timestamp
```
This will got an error:

Internal error: Input field name CASE WHEN tbl.variations LIKE Utf8(\"%value%\") THEN Utf8(\"correct\") ELSE Utf8(\"incorrect\") END does not match with the projection expression CASE WHEN tbl.variations LIKE Utf8(\"%value%\")  THEN Utf8(\"correct\") ELSE Utf8(\"incorrect\") END.\nThis was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker

**Comment by hanqian200705** [comment]
I seem to have encountered the same problem. The version I'm using is v0.10.8-rc2

```sql
SELECT histogram(_timestamp) as "times"
, (case when str_match(message, 'sql error:') then 'SqlErr' else 'other' end) as errtype
, count(*) as "cnt"
FROM 'log' where level='ERROR' GROUP BY "times","errtype" 
```

error message：
```json
{
    "code": 20008,
    "message": "Search SQL execute error",
    "error_detail": "Internal error: Input field name CASE WHEN str_match(tbl.message, Utf8(\"sql error:\")) THEN Utf8(\"SqlErr\") ELSE Utf8(\"other\") END does not match with the projection expression CASE WHEN str_match(tbl.message,Utf8(\"sql error:\")) THEN Utf8(\"SqlErr\") ELSE Utf8(\"other\") END.\nThis was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker",
    "trace_id": "2iMDsqz9EKxLcupESOoGrp95EYG"
}
```

**Comment by haohuaijin** [comment]
a regression of datafusion https://github.com/apache/datafusion/issues/11118

**Comment by hengfeiyang** [comment]
Datafusion already fixed this issue, let's wait for new version release
