### ISSUE TITLE
Logs: Getting something went wrong on query cancellation, instead of correct message

### ISSUE THREAD

**Issue by neha00290** [openobserve/openobserve#3817]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

Steps
1. Run a 4 week query with large data
2. Go to query cancel UI
3. Cancel the query and observe the page when query was running

Actual result: Get error as - Something went wrong

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version
Commit Hash
Build Date
v0.10.8-rc2
d484886041bb5fe09a09db57e7122fbb755df5d9
2024-06-25T05:06:13Z
```

**Comment by neha00290** [comment]
getting error for histogram so discarding

**Comment by bjp232004** [comment]
I have included relevant error messages for all client-side processing.

**Comment by neha00290** [comment]
this is re-tested and fixed
