### ISSUE TITLE
Does the version match?

### ISSUE THREAD

**Issue by thenitai** [openobserve/openobserve#3828]
Hi there,

Using the latest Docker image as in public.ecr.aws/zinclabs/openobserve:latest shows me 10.2 in the Dashboard. Is that just some version mismatch as the version here is 10.7? Thank you.

**Comment by prabhatsharma** [comment]
if you just run `docker run public.ecr.aws/zinclabs/openobserve:latest` and you have an older version of image on your machine then docker will not pull the latest image. 

You can do either of the following:

1. Delete the existing older `latest` tag `docker rmi public.ecr.aws/zinclabs/openobserve:latest` and then rerun `docker run public.ecr.aws/zinclabs/openobserve:latest`
2. Do not use the latest tag. Use something like: `docker run public.ecr.aws/zinclabs/openobserve:v0.10.8-rc3`

**Comment by thenitai** [comment]
Hi,

Yeah, I just realized I made a typical dummy error. Quick thing, should I add all the ENV vars into the docker compose file because right now I'm using the docker run commands  as in "docker run -e ZO_LOCAL_MODE_STORAGE=s3....."

Thank you for this awesome tool.

**Comment by hengfeiyang** [comment]
@thenitai You can only add the ENV that you need.
