### ISSUE TITLE
"distinct" query failed

### ISSUE THREAD

**Issue by deepX95** [openobserve/openobserve#3837]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

1 SELECT distinct caller FRoM "default"  

![error](https://github.com/openobserve/openobserve/assets/16909357/0aa08d33-1f9c-4237-9405-abfa025f4c89)

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.10.7
Commit Hash: 611f2e1c29df33a2df8e3be8a726889b07485284
Build Date: 2024-06-12T14:30:31Z
```

**Comment by prabhatsharma** [comment]
Try `SELECT distinct(caller) FROM "default"`

**Comment by deepX95** [comment]
> Try `SELECT distinct(caller) FROM "default"` 尝试 `SELECT distinct(caller) FROM "default"`
If we want to call distinct on multiple columns, how to do that? Something like `Select distinct(msg,caller)  FROM "default"` doesn't work.
