### ISSUE TITLE
Log show default Favorite Views

### ISSUE THREAD

**Issue by pisken** [openobserve/openobserve#3838]
### Which OpenObserve functionalities are relevant/related to the feature request?

log search

### Description

When I setup "Favorite Views", and go to "Logs" for time after, currently, I need choose a previous view to show.

### Proposed solution

I think this feature will useful, It's allow user choose a default View in "Favorite Views" to show when user enter the Logs page.

### Alternatives considered

Or other flow allow me view default page

**Comment by MennaKassem** [comment]
it is a very useful feature , to set the default view according to the needs of the organization. what most attributes need to be shown directly once entering the logs page .

**Comment by bjp232004** [comment]
Thank you for the suggestion. We’ve previously discussed this feature but decided not to implement it for now, as selecting a default view could lead to unnecessary processing and resource consumption in some scenario. However, we are actively working on a feature that will make it easier for users to access logs directly from the landing page, addressing this need more efficiently.
