### ISSUE TITLE
metrics promsql regex bug

### ISSUE THREAD

**Issue by domyway** [openobserve/openobserve#3883]
### Which OpenObserve functionalities are the source of the bug?

metrics

### Is this a regression?

Yes

### Description

`SUM BY (service_name, span_name, status_code) (increase(zo_span_duration_milliseconds_count{service_name=~"hasystem",operation_name=~"GET /jmreport/checkParam/\{id\}"}[5m]))`

operation_name cant not use regex and errors :
`"Execution error: unknown escape sequence '{'"
`

**Comment by taimingl** [comment]
#3888 should fix the escaping issue. The underlying `promql_parser` library already handles the escaping issues. please feel free to use the labels' literal value directly, such as below, without manually escaping by `\`
```
zo_span_duration_milliseconds_count{service_name=~"hasystem",operation_name=~"GET /jmreport/checkParam/{id}"}
```
