### ISSUE TITLE
Support for aggregation in WHERE clause or support subqueries

### ISSUE THREAD

**Issue by tgy** [openobserve/openobserve#3912]
### Which OpenObserve functionalities are relevant/related to the feature request?

alerts, metrics

### Description

Say you're using a Counter metric to count the number of failed pings on some servers (tagged with a `hostname` attribute). This counter is monotonically increasing all the time.

When you want to define an alert that checks for any failed ping over the past 10 minutes, you want to define a SQL query like this:

```sql
select
  hostname,
  cast((max("value") - min("value")) as int) as n_new_failures
from
  n_failed_pings
where
  cast((max("value") - min("value")) as int) > 0
group by
  hostname
```

The alert is going to be triggered for any non-empty result of this query. This means that we have to filter on the max of the counter minus the min of the counter being greater than zero.

Thing is, at the moment this results in the following error:

> This feature is not implemented: Physical plan does not support logical expression AggregateFunction(AggregateFunction { func_def: BuiltIn(Max), args: [Column(Column { relation: Some(Bare { table: "tbl" }), name: "value" })], distinct: false, filter: None, order_by: None, null_treatment: None })

Another solution would be to be able to express subqueries, but this is also not implemented.

### Proposed solution

Add support for either aggregations in WHERE clauses or for SQL subqueries.

### Alternatives considered

I could use something else than a Counter, but this is a pretty classic opentelemetry metric, and not using it because OpenObserve does not support some basic SQL functionalities does not seem to be the right approach.

**Comment by hengfeiyang** [comment]
You can write the sql like this:
```sql
select
  hostname,
  cast((max("value") - min("value")) as int) as n_new_failures
from
  n_failed_pings
group by
  hostname
having (max("value") - min("value")) > 0 
```

**Comment by choucavalier** [comment]
Thanks. Tried that but it does not work. The `having` syntax is 
unsupported

**Comment by hengfeiyang** [comment]
<img width="625" alt="image" src="https://github.com/openobserve/openobserve/assets/1628250/7a5690f2-0911-40fd-bcf5-5c2d5bde9eeb">

it works like this

**Comment by prabhatsharma** [comment]
Window functions may work - https://datafusion.apache.org/user-guide/sql/window_functions.html . Nede to test. However you should simply move on to using PromQL in this case. PromQL is much better suited for counters.  `increase(n_failed_pings[10m]) >= 1`
