### ISSUE TITLE
Dashboard:  The button of 'wrap table content' is ineffective on query log page

### ISSUE THREAD

**Issue by quinniup** [openobserve/openobserve#3919]
### Which OpenObserve functionalities are the source of the bug?

dashboards

### Is this a regression?

Yes

### Description

1. The button of 'wrap table content' is ineffective on query log page;
    ![image](https://github.com/openobserve/openobserve/assets/28534155/86703994-7669-4f7c-a199-d14e768b6c59)
3. Invalid hotkey to trigger query(Cmd/Ctrl + Enter).
    ![image](https://github.com/openobserve/openobserve/assets/28534155/4e2eae1b-5617-4254-93b8-1355d8f72cbf)

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.10.7
Commit Hash: 611f2e1c29df33a2df8e3be8a726889b07485284
Build Date: 2024-06-12T14:30:31Z
OS: linux x64
```

**Comment by quinniup** [comment]
How is the progress going?

**Comment by prabhatsharma** [comment]
completed by https://github.com/openobserve/openobserve/pull/4097
