### ISSUE TITLE
The conditional routing function of Stream pipelines does not take effect 

### ISSUE THREAD

**Issue by hexiang1219** [openobserve/openobserve#3941]
### Which OpenObserve functionalities are the source of the bug?

streams, routing

### Is this a regression?

Yes

### Description

**Question**:
I created a pipeline based on the default stream. The pipeline configuration is to generate a new stream through conditional routing. Found not effective
![图片](https://github.com/openobserve/openobserve/assets/34543240/956a96f9-c68f-479a-a055-5530f3dfdf3c)
![图片](https://github.com/openobserve/openobserve/assets/34543240/6467b44f-0bbf-4940-93c5-32d4060ffb95)
![图片](https://github.com/openobserve/openobserve/assets/34543240/52589919-ae21-4744-9803-97f65ad61d8f)

Please tell me what caused it?

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.10.8-rc4
```

**Comment by hengfeiyang** [comment]
Which ingestion API did you use?

**Comment by hexiang1219** [comment]
> Which ingestion API did you use?

What exactly is this? Does it refer to the way of writing data to the default stream? I write it to the stream through http otlp.

**Comment by hengfeiyang** [comment]
@oasisk i think the routing only support `_bulk` API for now, otlp haven't support, we need to do that.
