### ISSUE TITLE
Unable to query based on _timestamp

### ISSUE THREAD

**Issue by miversen33** [openobserve/openobserve#3950]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

I don't know if this is a bug or if I am just missing something but I cannot perform SQL queries including any sort of comparison on `_timestamp` except `=`.

What I mean here is, the following SQL query works
```sql
SELECT * FROM "syslog" WHERE _timestamp = 1720643134044773 ORDER BY _timestamp DESC
```
![image](https://github.com/openobserve/openobserve/assets/2640668/d3927b46-cb80-4d76-aba5-56f9caa11726)

However the following SQL returns "no results"
```sql
SELECT * FROM "syslog" WHERE _timestamp > 1720643134044773 ORDER BY _timestamp DESC
```
![image](https://github.com/openobserve/openobserve/assets/2640668/30c3cd3a-0407-4384-bdf2-5d3573d2d105)

Mind you, there are certainly timestamps newer than that
![image](https://github.com/openobserve/openobserve/assets/2640668/7ae9391b-e77c-4104-ae54-5a305f9e3c41)

I don't know what database engine is used under the hood for storing this information but I would assume that you could do things like `>` and `<` comparators on _timestamp, especially as there is no index column being shown.

Am I missing something here?

### Please provide a link to a minimal reproduction of the bug

NA

### Please provide the exception or error you saw

```true
NA
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.10.5
Commit Hash: 30d06f180da82120f75eb08b702eeb0e10438470
Build Date: 2024-04-30T09:31:56Z
```

### Anything else?

This is probably just me doing something wrong but its not clear how this is supposed to work, or if it is a thing at all. In traditional SQL land you can usually compare `timestamp` fields so I assumed you could here as well, especially given that you can sort by them.

**Comment by hengfeiyang** [comment]
`_timestamp` is a particular field, if you want filter `_timestamp` please use range. like:
```
SELECT * FROM "syslog" WHERE _timestamp >= 1720643134044773 and _timestamp < 1720643194044773 ORDER BY _timestamp DESC

```

**Comment by miversen33** [comment]
I know `_timestamp` is a particular field, that is why I am attempting to filter against it.

Your suggestion worked, though I am curious why I needed to add an upper bound to the query. It's not the end of the world, that is very useful. Just interesting.

I appreciate your help!

**Comment by hengfeiyang** [comment]
```
I am curious why I needed to add an upper bound to the query.
```

Because this is a particular field, so it need something special. without upper, we have no idea how many data need to scan. the searching based on a time range then we can only scan the data in the time range.

At the beginning, we have no limit, but it will scan the time to `now`, if the time is last month then it will be a nightmare, so user need provider it now.

**Comment by miversen33** [comment]
Ya that makes sense to me. I appreciate the insight!
