### ISSUE TITLE
Release candidates are marked as latest

### ISSUE THREAD

**Issue by erkexzcx** [openobserve/openobserve#3956]
### Which OpenObserve functionalities are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Basically here is an issue:

![image](https://github.com/openobserve/openobserve/assets/5955795/1faccd1a-5219-408a-82dd-c32fe635fc3d)

RC is not a "latest release", it is pre-release and would be great if you keep checking this checkbox if you release a release candidate:

![image](https://github.com/openobserve/openobserve/assets/5955795/01c456db-06ca-4eef-82f1-376ed704e283)

Now, the impact of this is that update monitoring tools wouldn't report invalid pre-release versions. For example, https://newreleases.io/ incorrectly marks such releases as latest (instead of pre-release):

![image](https://github.com/openobserve/openobserve/assets/5955795/b75f1441-4694-412a-ae82-b33918a992e5)

### Please provide a link to a minimal reproduction of the bug

N/A

### Please provide the exception or error you saw

```true
N/A
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
N/A
```

### Anything else?

N/A

**Comment by hengfeiyang** [comment]
Thank you for report this. we will discuss the release management.
