### ISSUE TITLE
Stream with Type = "index" is not working

### ISSUE THREAD

**Issue by kpikamlesh** [openobserve/openobserve#3965]
### Which OpenObserve functionalities are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

I have a stream that has few attributes that are bloom and inverted set.  
I have an env var set on my laptop:
ZO_ENABLE_INVERTED_INDEX=true
once I do that and restart the OpenObserve I see the index type show up in the stream list with valid stats values.

these fields are firstname, lastname, fullname, email address ,etc...
data in loaded into the stream and search only working for following:
kamlesh
patel

*** the issue is:
keep in mind full name contains "kamlesh patel"; firstname contains "kamlesh"; lastname contains "patel" in the stream records.

however: following is not working:
patel kamlesh
kamlesh patel

both of these search should return a result.  It is returning zero (0) rows.

**Comment by hengfeiyang** [comment]
Let me repeat your question:

1. you enabled `ZO_ENABLE_INVERTED_INDEX=true`
2. you enabled `Inverted index` for field `fullname`
3. you want to search `match_all('patel kamlesh')` or `match_all('kamlesh patel')` and expect it return data.

Right?

**Comment by prabhatsharma** [comment]
We had a discussion with @kpikamlesh . This not an issue.
