### ISSUE TITLE
Log results section rebuild for performance and column reordering

### ISSUE THREAD

**Issue by bjp232004** [openobserve/openobserve#3973]
### Description

Current log result table grid layout uses quasar component which doesn't has column reordering feature. It takes time to render high volume of data. To improve this we need to consider light weight table component design which provide all these features.

### Proposed solution

We can consider external opensource library:
- https://datatables.net/

Let's discuss if any other opensource library provide table grid feature.

### Alternatives considered

NA

**Comment by gaby** [comment]
@bjp232004 On the other hand `quasar` has a lot of features not being used like Colored Rows. I have been using O2 for over a year, and can count the amount of times I needed to reorder columns 😂

Related https://github.com/quasarframework/quasar/issues/4138

**Comment by omkarK06** [comment]
Used TanStack table, with some new features.
#4097 

1. Column Resizing
2. Column Reordering
3. Column ordering and Column resizing context will be saved with saved views.
4. Improved Performance
