### ISSUE TITLE
str_match(body, 'INFO abc')  query in absolute time range for past 4 weeks gives an error

### ISSUE THREAD

**Issue by neha00290** [openobserve/openobserve#3977]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

```
SELECT * FROM "stream" WHERE str_match(body, 'abc') ORDER BY _timestamp DESC
```

<img width="1059" alt="Screenshot 2024-07-15 at 6 42 50 PM" src="https://github.com/user-attachments/assets/1df8cf5d-3934-43b4-b019-7f64c3bbc872">

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version
Commit Hash
Build Date
v0.10.8-rc5
761815708550aed26b133aa9dd0bc6afde7d7087
2024-07-15T08:57:45Z
```

**Comment by hengfeiyang** [comment]
@neha00290 is this the issue we have no data for past 4 weeks?

**Comment by neha00290** [comment]
yes, this was an issue and is fixed now. closing the same @hengfeiyang
