### ISSUE TITLE
Alert rules configured do not take effect

### ISSUE THREAD

**Issue by hexiang1219** [openobserve/openobserve#3995]
### Which OpenObserve functionalities are the source of the bug?

alerts

### Is this a regression?

No

### Description

I configured the following alert rules：Every query meets the alarm conditions
![图片](https://github.com/user-attachments/assets/5d3e8f68-ab95-4342-9bb6-8d7a4b60b751)

But I found that in the service logs of the alertmanager component (a total of 3 pods), no alert job was pulled. No other err logs were found
![图片](https://github.com/user-attachments/assets/40ead7da-dcb5-43fa-9c75-7cd3b67f8875)
![图片](https://github.com/user-attachments/assets/9fc135f9-ec09-4f79-8952-dde7882eef2e)
![图片](https://github.com/user-attachments/assets/a4dc4288-3109-40a5-a452-94d2b55b01ec)

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.10.8-rc4
```

**Comment by hengfeiyang** [comment]
there is a silence `10 minutes` after an alert. maybe you want set it to `0`

**Comment by hexiang1219** [comment]
> there is a silence `10 minutes` after an alert. maybe you want set it to `0`

![图片](https://github.com/user-attachments/assets/4b08d7a3-a077-4e19-a15d-3c7df0a57ba8)

set silence to 0, the alarm is still not received. 

I used `nc -k -l 4321` to start the alarm receiving service. This is okay, right?
![图片](https://github.com/user-attachments/assets/c26b3507-11d5-402e-a47c-e1b6d84f8e3a)

**Comment by hengfeiyang** [comment]
it looks fine. please check:
1. if the alert enabled
2. ingest more records
3. any error logs?

**Comment by hexiang1219** [comment]
> it looks fine. please check:
> 
>     1. if the alert enabled
> 
>     2. ingest more records
> 
>     3. any error logs?

1. alert enabled
![图片](https://github.com/user-attachments/assets/2f351cfe-96fa-48af-a6f4-1e0155b46ba9)

2. It is possible to query records that meet the alarm triggering conditions.
![图片](https://github.com/user-attachments/assets/6881ceb6-c7e2-4ee0-8e78-b70ee0c6a93e)

3. no error message was found. Open the debug log of the alert component and find the following information:
![图片](https://github.com/user-attachments/assets/5c5d9aa6-1427-4c3f-a8a6-77f88277d7ec)

**Comment by hengfeiyang** [comment]
sorry for late response. Can you try upgrade to `v0.11.0-rc3` and then check the logs:
- send success: `Alert notification sent`
- send failed: `could not be sent`
- other error: `Error sending alert notification`
