### ISSUE TITLE
Batch Deletion of Streams

### ISSUE THREAD

**Issue by raviranjan5937** [openobserve/openobserve#4003]
### Which OpenObserve functionalities are relevant/related to the feature request?

streams, metrics

### Description

Currently, there is no way to delete multiple streams at once in OpenObserve, which becomes a significant challenge when managing a large number of streams. This is particularly important for maintaining storage efficiency and operational ease.

As a user managing a large organization in OpenObserve, I need to be able to delete multiple streams at once to avoid storage issues and to maintain a clean and efficient working environment. This is critical for both ongoing operations and future scalability.

### Proposed solution

1. Add a feature that allows batch deletion of streams.
2. Provide an option to delete streams for specific intervals of time.
3. Ensure that the feature can be used securely and efficiently in a production environment.

### Alternatives considered

1. Deleting each stream individually through the OpenObserve UI. This method is not feasible due to the large number of streams, making it time-consuming.
2. Writing a script to automate the deletion process using the API. This approach faced limitations as current token-based authentication only supports data ingestion, not stream deletion.

**Comment by gaby** [comment]
The UI needs a way of selecting multiple or all streams and deleting them.

I have around 1k streams created from using Metrics Ingest, and there's no way to clean them. Deleting each stream takes 2 clicks
