### ISSUE TITLE
Interacting with boolean data causes queries to become unresponsive

### ISSUE THREAD

**Issue by mattrankin83** [openobserve/openobserve#4033]
### Which OpenObserve functionalities are the source of the bug?

log search, dashboards

### Is this a regression?

No

### Description

We are ingesting data from an application (via fluentd) and in the message there is potentially a number of boolean data fields. Whenever I try to use those fields as a filter, or use them in any dashboard panel, it locks the system up (it seems like the query is maybe having an issue?). 

Eventually I'm returned an error. On the below screenshot I am filtering on the logs screen by one other field (a text match) and the boolean field. 
![image](https://github.com/user-attachments/assets/0e1be301-196e-4336-a5c8-ce83b91a9ce5)

If I run that same query without the boolean field it completes totally fine, and very fast. But if I try to find the 'True' values within that result set (which was 11 records) I am stuck with the loading icon for approximately 10-12 minutes and it results in the log screen displaying "Error: Search SQL execute error."

During those 10 minutes I'm unable to load any other data, whether it be a different log stream, or a dashboard/graph. If I try to view a Dashboard I just get the "No Data" message:

![image](https://github.com/user-attachments/assets/e50a4210-8c25-4ff4-894c-623629ccda8e)

The same thing happens when I try to incorporate that field into a dashboard, the entire system fails to load data until that first action errors out. But on the graphs I do get a different, and more informative, error message: 
type_coercion caused by Error during planning: Can not find compatible types to compare Boolean with [Utf8]

![image](https://github.com/user-attachments/assets/bc742a69-ce97-428f-b33d-51517a6a29b9)

On the "Stream Detail" page, these fields have been classified, correctly, as Boolean. Although this field is not incorporated in every message that is logged (not sure if that's relevant). 

![image](https://github.com/user-attachments/assets/c1280c16-d8dd-428f-9f25-74edd755d8da)

The most minimal reproduction I can think of is just trying to display a count (Metric Text panel) of messages where a particular boolean field is true, the SQL is quite simple (this is using a different boolean field from the one above):

![image](https://github.com/user-attachments/assets/c1e05983-59ff-4066-8dc4-0f03051f49a9)

This returns the same error as above:

![image](https://github.com/user-attachments/assets/bb32ca01-f12b-453d-80e1-b3af5a9072ac)

This deployment is running in Kubernetes. I have tried watching the logs on various pods but I didn't see anything that looked particularly relevant but I'm more than happy to retrieve any log entries that may help.

### Please provide the exception or error you saw

```true
"Error: Search SQL execute error."
type_coercion caused by Error during planning: Can not find compatible types to compare Boolean with [Utf8]
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version v0.10.7
Commit Hash 611f2e1c29df33a2df8e3be8a726889b07485284
Build Date 2024-06-12T14:11:18Z
```

### Anything else?

To mitigate this I have written a VRL function that applies on ingestion to create a new field set to a 1 or 0 and that works, but the issue can pop its head up when you click on the wrong field and it prevents any users from loading dashboards until the problem resolves itself, and that only works for data going forward, not the old data.

Let me know if there is any additional information I can provide! Absolutely loving using o2 otherwise!

**Comment by hengfeiyang** [comment]
You should use `dev_build is true` if the field is `boolean`, it is not string, you can't use `dev_build='true'` for it.

**Comment by mattrankin83** [comment]
@hengfeiyang Thank you! That does seem to do the trick. 

I guess where I got confused is that when I click the filters from the list on the left of the log screen, for example in the image below if I click that equals sign (=):

![image](https://github.com/user-attachments/assets/bed8ae64-1fee-4deb-baa4-3b61525d889b)

The query in the editor that fills in above the log becomes "dev_build='true' " rather than "  dev_build is true "

![image](https://github.com/user-attachments/assets/011f69e6-2224-4a8d-bad5-87e4d9f26699)

**Comment by hengfeiyang** [comment]
@mattrankin83 did your issue resolved?

**Comment by hengfeiyang** [comment]
@bjp232004 i think this issue is the same case, we can't apply `'true'` when the dataType is `boolean`, we should use `filed is true` or `filed is false`

**Comment by hengfeiyang** [comment]
ralated #4788

**Comment by mattrankin83** [comment]
Hi Hengfei,
Sorry I forgot to reply to this! Yes that work around makes sense and works for me. Sorry about the slow reply.
I do wonder if it would be possible to put in the query builder "is true" if the only values available are boolean but I don't want to pretend to know what would go into doing that in background, it may not make sense or even be possible.

Thanks again for the reply!

**Comment by hengfeiyang** [comment]
@mattrankin83 we found this is a bug, we are fixing it...
