### ISSUE TITLE
Logs page reduce default events

### ISSUE THREAD

**Issue by bjp232004** [openobserve/openobserve#4038]
### Description

Currently we are displaying 250 events on logs page. In some scenario it call multiple partitions to get those number of events. 

### Proposed solution

Reduce default settings to 100 will help to call less number of partition.

### Alternatives considered

NA

**Comment by gaby** [comment]
@bjp232004 Is the backend calling 100 records at a time too?

**Comment by bjp232004** [comment]
> @bjp232004 Is the backend calling 100 records at a time too?

Yes, backend will stop scanning further data once it received requested number of records. @hengfeiyang please correct if I am wrong.
