### ISSUE TITLE
I must select a field for y-axis but i only need select(*)

### ISSUE THREAD

**Issue by hengfeiyang** [openobserve/openobserve#406]
### Which ZincObserve functionalities are relevant/related to the feature request?

dashboards

### Description

<img width="913" alt="image" src="https://user-images.githubusercontent.com/1628250/227691273-6f07c5ab-4d78-4a4b-bbff-835fd81e8597.png">

In this case actually in most cases, we just need a value for `y-axis`, we can default use `count(*)` for `y-axis`, then we will no need to select a field for  `y-axis`. in this case i must select a field just for `count` a value. it is not friendly.

### Proposed solution

we can default use `count(*)` for `y-axis`

### Alternatives considered

--

**Comment by ktx-kirtan** [comment]
There might be a couple of options:

1. Adding a * as the field in the field list. We can auto-add in some cases that we need to define
2. Adding count(*) by default in query if y axis is not present. But in that case, it would be difficult to know what goes on y axis for all charts.

Let's discuss this further to finalize what approach to choose from or let us know if you have any other idea for this
