### ISSUE TITLE
Log data is lost after upgrading from v0.10.6-rc1 to v0.10.8

### ISSUE THREAD

**Issue by hexiang1219** [openobserve/openobserve#4072]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

No

### Description

after the upgrade, I found that the log query was abnormal. After rolling back to v0.10.6-rc1, it became normal, but the log query during the upgrade process could not be displayed.
![image](https://github.com/user-attachments/assets/c058f687-5013-411b-a9c4-912f3e97459b)

It was found that the querier service reported the following error
`2024-07-26T10:45:49.125716031+00:00 ERROR openobserve::service::search::cache::cacher: [trace_id 585f2afd639e422daabca982a34cba38] Get results from disk failed : Custom { kind: NotFound, error: "File not found" }    
`
![image](https://github.com/user-attachments/assets/0f67225b-e0ae-4552-8531-a7330e7f9e43)

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.10.8
```

**Comment by hengfeiyang** [comment]
@oasisk i remember you fixed this case, right?

**Comment by hengfeiyang** [comment]
@hexiang1219 Can you try to upgrade to `v0.11.0-rc3` and check the issue again?
