### ISSUE TITLE
When using SELECT DISTINCT with large datasets, it has been observed that sharded queries can result in duplicate data

### ISSUE THREAD

**Issue by addname** [openobserve/openobserve#4077]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

When using SELECT DISTINCT with large datasets, it has been observed that sharded queries can result in duplicate data

**Comment by hengfeiyang** [comment]
<img width="871" alt="image" src="https://github.com/user-attachments/assets/bf6d6c78-5c28-4c3e-861d-581c546707c5">

@bjp232004 i think we should set `distinct` is aggregation query and then don't apply search partition for it.
