### ISSUE TITLE
Alert Rule with `contains` method trigger alert  failed Intermittently

### ISSUE THREAD

**Issue by JasonWangA** [openobserve/openobserve#4086]
### Which OpenObserve functionalities are the source of the bug?

alerts

### Is this a regression?

Yes

### Description

we configured rules as below screenshot with log_processed_msg **Contains** [Application]:
![微信截图_20240730152742](https://github.com/user-attachments/assets/f75a9e0e-b7de-404c-a6cb-e2a236a7f543)

while four logs ingested in the openobeseve, but only triggerd one but  4 alert during that time,
![微信截图_20240730153218](https://github.com/user-attachments/assets/953c8268-caa9-458c-9917-26318f2ea1d3)

### Please provide a link to a minimal reproduction of the bug

No response

### Please provide the exception or error you saw

```true
No response
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.10.8
```

### Anything else?

is the alert search interval settings is not proper or any other environment settings about alert should be adjusted?

**Comment by hexiang1219** [comment]
can you send the complete alarm configuration? I have configured it here so that the data can be found based on the alarm conditions, but the webhook has not received the alarm information.
![图片](https://github.com/user-attachments/assets/204da0a2-220d-45e1-a0c4-98a4927af4a4)

**Comment by JasonWangA** [comment]
below is the specific screenshot for the alert config, could  you  please give any suggestions?
![image](https://github.com/user-attachments/assets/4b7d9d12-6ff9-40fb-8a55-66de07781b51)

**Comment by Subhra264** [comment]
Hello @JasonWangA , can you try with the latest release, if the issue is persisting? Also, can you mention the db you are using i.e. sqlite/mysql/postgres. Your silence period seems to be `0`, so the alert should actually trigger immediately.

**Comment by hengfeiyang** [comment]
@JasonWangA For each ingestion batch, we only trigger alert once. it means if you ingest two records in one request, it only trigger once.

How did you ingest the 4 records? and in you screenshot we can't see any keyword matched your condition `[Application:Shutdown]`, can you upgrade to `v0.11.0-rc3` and test again?

**Comment by CrisLi** [comment]
> ingestion batch

I think the root cause maybe the ingestion batch.  Is there any way we can tigger the real time alert based on the condition matched records? I think this issue started to have in recently 2 releases.

**Comment by Subhra264** [comment]
> I think the root cause maybe the ingestion batch. Is there any way we can tigger the real time alert based on the condition matched records? I think this issue started to have in recently 2 releases.

If I am understanding it correctly, you are talking about something like `threshold` in scheduled alerts, but for realtime alerts. @hengfeiyang correct me if I am wrong, but I think we don't support threshold yet in case of realtime alerts.

**Comment by hengfeiyang** [comment]
@CrisLi @Subhra264 Yes we have no `threshold` for realtime alert. and for this issue, 3 users report they work fine on `v.0.10.7`, so we need to check `v0.10.8` and `v0.10.9` what we changed on alert and try to find the root cause.

**Comment by hengfeiyang** [comment]
@JasonWangA if you still have problem please connect me in our Wechat Group.

**Comment by JasonWangA** [comment]
> @JasonWangA if you still have problem please connect me in our Wechat Group.

which wechat Group ?

**Comment by hengfeiyang** [comment]
The QRcode in the README
