### ISSUE TITLE
Change password for root user not working

### ISSUE THREAD

**Issue by neha00290** [openobserve/openobserve#4115]
### Which OpenObserve functionalities are the source of the bug?

users

### Is this a regression?

Yes

### Description

Steps
1. Go to root user and enter correct old password
2. Enter new password and save changes
3. After user gets logged out, observe if user is able to login using the new password

Actual result: User is not able to login using new password but old password works

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version
Commit Hash
Build Date
v0.10.9-rc3
84ba1a72e823143cb90e1fb2182feb7c10e035b9
2024-08-05T03:45:16Z
```

**Comment by hengfeiyang** [comment]
@neha00290 @oasisk I tried change password for `root` on alpha1, then i found lost all the organizations, i can only access `default` now.

**Comment by hengfeiyang** [comment]
i found the issue: the user role will become to `admin` when we update password. that is a problem. it should be always `root` for `root` user.

**Comment by hengfeiyang** [comment]
@neha00290 i only found the role changing issue, i can't reproduce password issue.
