### ISSUE TITLE
Since OpenObserve lacks the concept of primary keys, does that mean I cannot overwrite the same data entry using a specific key?

### ISSUE THREAD

**Issue by cheng8868789** [openobserve/openobserve#4117]
Since OpenObserve lacks the concept of primary keys, does that mean I cannot overwrite the same data entry using a specific key?

**Comment by gaby** [comment]
@cheng8868789 OpenObserve is *not* a database. Data is immutable after ingestion.

**Comment by Chengyh8848** [comment]
> @cheng8868789 OpenObserve is _not_ a database. Data is immutable after ingestion.

ok ok
