### ISSUE TITLE
Reports are unusable when using OpenObserve in Docker

### ISSUE THREAD

**Issue by gaby** [openobserve/openobserve#4147]
### Which OpenObserve functionalities are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

When using OpenObserve with Docker the release image has minimal packages, this makes it that even if you mount the `chromedriver` binary from selenium it won't work.

There are several .so files require for chromedriver to work inside Docker. For example libnss3, and libglibc.

The final image should have the require libs for all the features to work, or install the chromedriver via `apt` in the image to make it an all-in-one package.

### Please provide a link to a minimal reproduction of the bug

n/a

### Please provide the exception or error you saw

```true
The logs show that the binary can't start because .so files are missing.
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
v0.10.9-rc3
Linux
Docker
```

### Anything else?

I tried debugging this for around +3hrs and found no fix with the current image.

**Comment by gaby** [comment]
Another issue, the feature is disabled by default but there's no indication of this in the UI. The UI makes it look like its doing something in the background, errors only show up in the container logs, never in the UI.

**Comment by hengfeiyang** [comment]
@gaby for o2 main image, it have to tiny. it will very big if include all the libraries. and we created another image for this case.

https://gallery.ecr.aws/zinclabs/report-server

you can configure `ZO_REPORT_SERVER_URL` the separate server address.

**Comment by Subhra264** [comment]
@gaby you can have a look at https://github.com/openobserve/o2_report_server. Since https://gallery.ecr.aws/zinclabs/report-server docker image already contains chromium, you don't need to set any of the chromium related configs (You may need to set `ZO_CHROME_NO_SANDBOX` to `true` in case you see errors like - Running as root without --no-sandbox is not supported). You can go with the example env setup mentioned in the [README](https://github.com/openobserve/o2_report_server/blob/main/README.md) and make sure in every o2 alert manager you setup the `ZO_REPORT_SERVER_URL` and the `ZO_WEB_URL`.

You can also set `ZO_HTTP_PORT` (default `5090`) and `ZO_HTTP_ADDR` (default `127.0.0.1`)

**Comment by gaby** [comment]
@hengfeiyang @Subhra264 Doesnt O2 already have the server build-in?

I was trying to avoid having to run another service, I already have to run NGINX because O2 doesnt support HTTPS. I also have to run Vector because O2 doesnt support Elastic v8.x (See #3427).

Ideally the image has the dependencies to at least be able to run a provided Chromiun binary, haven't check how much in size it adds to the image yet.

**Comment by hengfeiyang** [comment]
@gaby first, support es 8.x  shouldn't be a problem, just i haven'y look into it. second, because of `Chromiun` need a lot of dependencies, we can't install everything inside o2 image, it is too big and most of users never use it. so we provide a separate image for it.

By the way, if you are running o2 with binary, you can install anything in the node, then you don't need a separate `report_server` you can use embed feature.

**Comment by gaby** [comment]
@hengfeiyang Yeah, I understand that but my point is that it goes against everything O2 says:

- This feature does not work at all with the way O2 is shipped to users.
- There's `0 documentation` for it. I spent hours and still can't get it to work.
- The UI has `0 errors/warnings` that the feature is not working or enabled.
- This features require running another container and also enabling like `8-12 ENV variables`, even though its enabled by default in the UI.

As a new user starting O2, I click reports and nothing works because its disabled by default on the backend, and even if I enable it it won't work cause it requires running an extra service or dependencies are missing.

The current O2 container is 62MB, if it goes up to 150-300MB that still way smaller than running: ElasticSearch, Kibana, Logstash which is +1GB 😂

**Comment by hengfeiyang** [comment]
@gaby zero document is means we didn't public it, but you found it😂. actually we only provide it for some special users, and we will train them. truly, the document is poor, we will improve it in the next.

By the way, we try to embed everything in to one binary, but not everything. for this case, it will never embed into the main image, as i said it is too large and 99% users never use it. they don't need to download a 1GB  image for never used feature.

**Comment by gaby** [comment]
If that's the case, then completely `disable` or `remove` the `Reports` feature from the UI unless the user enables it. The default setup has that feature enabled, and when you configure it through the UI there's 0 errors that it's not working.

I did a test locally and installing it via `apt install chromium-driver` adds around 600MB. The problem with installing it that way is that it's assumes you are in a desktop environment.. If you only install the dependencies, and copy-in the binary the whole size is around `250 MB`.

**Comment by gaby** [comment]
Let me see what I can come up with, and will share it here.

**Comment by hengfeiyang** [comment]
we can consider disable it for default.

**Comment by gaby** [comment]
@hengfeiyang This is what I have so far, that could be incorporated into `OpenObserve` to make this experience easier for users. 

## Multi-Stage Dockerfile (with chrome/chromium)
```Dockerfile
# Stage 1: Build stage
FROM ubuntu:22.04 AS builder

# Set environment variables to avoid interactive prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Update and install necessary packages
RUN apt-get update && apt-get install -y \
    wget \
    curl \
    unzip \
    ca-certificates \
    --no-install-recommends

# Install Google Chrome manually
RUN curl -sSL https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o google-chrome.deb && \
    apt-get install -y ./google-chrome.deb && \
    rm google-chrome.deb

# Install Chromium Driver manually
RUN CHROMEDRIVER_VERSION=$(curl -sSL https://chromedriver.storage.googleapis.com/LATEST_RELEASE) && \
    echo "Chromedriver version: $CHROMEDRIVER_VERSION" && \
    wget -q https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip && \
    unzip chromedriver_linux64.zip && \
    mv chromedriver /usr/local/bin/chromedriver && \
    chmod +x /usr/local/bin/chromedriver && \
    rm chromedriver_linux64.zip

# Stage 2: Final stage
FROM ubuntu:22.04

# Set environment variables to avoid interactive prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Install minimal dependencies required by Chrome and Chromedriver
RUN apt-get update && apt-get install -y \
    ca-certificates \
    fonts-liberation \
    libappindicator3-1 \
    libasound2 \
    libatk-bridge2.0-0 \
    libcups2 \
    libdrm2 \
    libgbm1 \
    libnspr4 \
    libnss3 \
    libx11-xcb1 \
    libxcomposite1 \
    libxdamage1 \
    libxrandr2 \
    xdg-utils \
    --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

# Copy Chrome and Chromedriver from the builder stage
COPY --from=builder /opt/google/chrome/ /opt/google/chrome/
COPY --from=builder /usr/bin/google-chrome /usr/bin/google-chrome
COPY --from=builder /usr/local/bin/chromedriver /usr/local/bin/chromedriver

# Remove existing symlink or file and create a new symlink for google-chrome
RUN rm -f /usr/bin/google-chrome && ln -s /opt/google/chrome/google-chrome /usr/bin/google-chrome

# Set environment variables for Chrome and Chromedriver
ENV CHROME_BIN=/opt/google/chrome/google-chrome \
    CHROMEDRIVER_BIN=/usr/local/bin/chromedriver

# Set entrypoint for debugging purposes
ENTRYPOINT ["/bin/bash"]
```

Total image size: `584 MB`

### Debug
```console
root@8e2b4dcda09f:/# chromedriver --version
ChromeDriver 114.0.5735.90 (386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052})
root@8e2b4dcda09f:/# google-chrome --version
Google Chrome 128.0.6613.113 
root@8e2b4dcda09f:/# /opt/google/chrome/chrome --version
[0901/171739.688121:WARNING:chrome_main_linux.cc(80)] Read channel stable from /opt/google/chrome/CHROME_VERSION_EXTRA
Google Chrome 128.0.6613.113 
```

## Base dependencies

Dockerfile with only dependencies needed for running `Chrome/Chromium`

```Dockerfile
FROM ubuntu:22.04

# Install minimal dependencies required by Chrome and Chromedriver
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    ca-certificates \
    fonts-liberation \
    libappindicator3-1 \
    libasound2 \
    libatk-bridge2.0-0 \
    libcups2 \
    libdrm2 \
    libgbm1 \
    libnspr4 \
    libnss3 \
    libx11-xcb1 \
    libxcomposite1 \
    libxdamage1 \
    libxrandr2 \
    xdg-utils \
    --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

# Set entrypoint for debugging purposes
ENTRYPOINT ["/bin/bash"]
```

Total size: `210 MB`

Original size for `ubuntu:22.04` -> `77.9MB`

## Conclusion:

The image for `OpenObserve` is around `70MB`, with `140MB` more it would be ready to run chrome itself it the user provides it or when the chromiumoxide downloads the binary it would work too.

**Comment by gaby** [comment]
Gave up trying to use reports, the feature is too complicated to use.
