### ISSUE TITLE
Custom label on Dashboard

### ISSUE THREAD

**Issue by lens0021** [openobserve/openobserve#4149]
### Which OpenObserve functionalities are relevant/related to the feature request?

Dashboard

### Description

When I use the count() function as a field, the chart shows the field as the name of the column instead of `count`. It makes the chart and the legends unnatural.

![image](https://github.com/user-attachments/assets/0317d2ba-66b1-4b71-b6c3-c4300e9850bf)

### Proposed solution

Make `as count` work and use it as the label.

### Alternatives considered

Showing `count()` fields as `count`

**Comment by gaby** [comment]
@lens0021 You mean it should show as `count(Timestamp)` in the legend? Yeah that would look better

**Comment by ktx-abhay** [comment]
@lens0021 @gaby we have an option to give label.

![image](https://github.com/user-attachments/assets/9a78f893-ea4a-4b28-a97b-fd598c096ff7)

**Comment by gaby** [comment]
@ktx-abhay I use all the time, trying to understand what @lens0021 Is asking about 😂

**Comment by lens0021** [comment]
I didn't know that. I will try it. Thank you!
