### ISSUE TITLE
Invalid HTTP Endpoint specification

### ISSUE THREAD

**Issue by demonisius** [openobserve/openobserve#4157]
### Which OpenObserve functionalities are the source of the bug?

ingestion

### Is this a regression?

Yes

### Description

When I go to the "Ingestion" menu - "Recommended" section - "Traces (OpenTelemetry)" item, I get parameters for sending data, namely:
**OTLP HTTP**
HTTP Endpoint: `http://url:5080/api/<orgname>`

Although the documentation states
`https://url:5080/api/<orgname>/v1/traces`
[Docs](https://openobserve.ai/docs/ingestion/traces/)

In my project I spent several minutes trying to understand why I was getting a 404 error.

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.10.9-rc3
Commit Hash: 42359ddc5bed64a2173ea59f6070212a8c33b2a4
Build Date: 2024-07-30T10:40:04Z
```

**Comment by gaby** [comment]
@demonisius I think the `/v1/traces` gets appended by O2

**Comment by demonisius** [comment]
What do you mean by O2?

**Comment by gaby** [comment]
OpenObserve

**Comment by demonisius** [comment]
Some logs when try from endpoint from O2

> 2024-08-08T11:39:12.935128187+00:00 INFO actix_web::middleware::logger: 192.168.140.25 "POST /api/default HTTP/1.1" 404 0 "135" "-" "OTel-OTLP-Exporter-Python/1.26.0" 0.000480    
> 2024-08-08T11:39:22.953445295+00:00 INFO actix_web::middleware::logger: 192.168.140.25 "POST /api/default HTTP/1.1" 404 0 "202" "-" "OTel-OTLP-Exporter-Python/1.26.0" 0.000066    
> 2024-08-08T11:50:29.208885602+00:00 INFO actix_web::middleware::logger: 192.168.140.25 "POST /api/default HTTP/1.1" 404 0 "284" "-" "OTel-OTLP-Exporter-Python/1.26.0" 0.000091  

And logs when I added part of the line from the documentation

> 2024-08-08T12:06:10.530221988+00:00 INFO actix_web::middleware::logger: 192.168.140.25 "POST /api/default/v1/traces HTTP/1.1" 200 0 "122" "-" "OTel-OTLP-Exporter-Python/1.26.0" 0.020737

**Comment by hengfeiyang** [comment]
Different otlp version have different behavior. if `https://url:5080/api/<orgname>/v1/traces` works then will be fine, if you  got `404` then you can try `https://url:5080/api/<orgname>`.

**Comment by demonisius** [comment]
Got it, thanks.
