### ISSUE TITLE
AWS S3 Endpoints: Difference Between China and Other Regicons

### ISSUE THREAD

**Issue by deepX95** [openobserve/openobserve#4162]
### Which OpenObserve functionalities are the source of the bug?

streams

### Is this a regression?

Yes

### Description

  When using AWS S3 in the China regions, the endpoints differ from those in other regions, which can lead to issues if not properly configured. Specifically, the endpoints for China regions include `.cn` at the end, whereas other regions do not. This discrepancy can cause problems when pushing to S3 if the endpoints are not correctly specified.

#### China Regions Endpoint Details
Beijing Region (operated by Sinnet):
Endpoint: `s3.cn-north-1.amazonaws.com.cn`
Region name: `cn-north-1`
Ningxia Region (operated by NWCD):
Endpoint: `s3.cn-northwest-1.amazonaws.com.cn`
Region name: `cn-northwest-1`

#### Non-China Regions Endpoint Example
US East (N. Virginia):
Endpoint: `s3.us-east-1.amazonaws.com`
Region name: `us-east-1`

![image](https://github.com/user-attachments/assets/a946be1b-aaed-416d-b490-bc0a47bb1788)

  Currently, when configuring the AWS S3 endpoint in the repository, if the region is set to one of the China regions, the endpoint must include `.cn` at the end. However, if this is not done correctly, it leads to push failures or connection issues. This issue arises due to the hardcoded endpoints that don't account for the `.cn` suffix required for China regions.

To address this, we need to:
  Identify the region: Check if the region specified is one of the China regions (`cn-north-1` or `cn-northwest-1`).
Append `.cn` to the endpoint: Automatically append `.cn` to the endpoint URL if the region is identified as a China region.

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.10.8
Commit Hash: 8e51607ddeead104a5de98447ec1297851f67947
Build Date: 2024-07-25T04:10:44Z
OS:linuxx64
```

**Comment by hengfeiyang** [comment]
You can try set this ENV:
```
ZO_S3_SERVER_URL=https://s3.cn-northwest-1.amazonaws.com.cn
```

**Comment by deepX95** [comment]
> You can try set this ENV:
> 
> ```
> ZO_S3_SERVER_URL=https://s3.cn-northwest-1.amazonaws.com.cn
> ```

This is fine. I previously set 
```ZO_S3_SERVER_URL=s3.cn-northwest-1.amazonaws.com.cn```,which caused it to have no effect.
