### ISSUE TITLE
Self-log collection and log parsing

### ISSUE THREAD

**Issue by haitun3721** [openobserve/openobserve#4167]
### Which OpenObserve functionalities are relevant/related to the feature request?

other

### Description

the /var/log/messages file is too large.

For example: “<190>FW-Core %%: %%01SECLOG/6/SESSION_TEARDOWN(l): IPVer=4, Protocol=tcp, SourceIP=10.0.0.1, DestinationIP=8.8.8.8, SourcePort=56189, DestinationPort=80,SourceNatIP=100.0.0.0,SourceNatPort=3010,BeginTime=1723214003,EndTime=1723214003,SendPkts=6,SendBytes=551,RcvPkts=5,RcvBytes=280,SourceVpnID=0, DestinationVpnID=0,SourceZone=trust,DestinationZone=untrust,PolicyName=intelnet,CloseReason=tcp-fin,ApplicationName=BT.”
As for the log information, it was best to be able to search it by group.

### Proposed solution

Add your own to the stream to automatically collect the logs it generates, the /var/log/messages file is too large.
The logs collected on port 5514 (such as firewalls and switches) can be parsed using regular expressions or delimiters.

### Alternatives considered

Or use a better way of dealing with it that you can consider

**Comment by hengfeiyang** [comment]
If you want to parse when ingestion, you can use `pipeline` to create an function and associate to the destination stream.

in the function you can use regexp to parse the field.

You can try:
https://vector.dev/docs/reference/vrl/functions/#parse_syslog

also read:
https://openobserve.ai/docs/user-guide/functions/

**Comment by haitun3721** [comment]
Thank you! I'll try
