### ISSUE TITLE
Alert SQL not working

### ISSUE THREAD

**Issue by Lockie85** [openobserve/openobserve#4173]
### Which OpenObserve functionalities are the source of the bug?

alerts

### Is this a regression?

Yes

### Description

Hi,

I have an alert with the following SQL which triggers without issue:
```
SELECT *
FROM StreamA
WHERE (
    LOWER(message) LIKE '%blue%'
    OR LOWER(message) LIKE '%green%'
    OR LOWER(message) LIKE '%red%'
);
```

However, then I add a string to exclude from that alert like this:
```
SELECT *
FROM StreamA
WHERE (
    LOWER(message) LIKE '%blue%'
    OR LOWER(message) LIKE '%green%'
    OR LOWER(message) LIKE '%red%'
)
AND LOWER(message) NOT LIKE '%192.168.1.10%';
```

The alert does not work anymore. Any ideas why this might be?

Many Thanks

### Please provide the version you discovered this bug in (check about page for version information)

```true
v0.10.9-rc3
```

**Comment by hengfeiyang** [comment]
any errors returns by the API? and can you try `v0.11.0-rc3`?
