### ISSUE TITLE
Unable to sort streams by size

### ISSUE THREAD

**Issue by gaby** [openobserve/openobserve#4197]
### Which OpenObserve functionalities are the source of the bug?

streams

### Is this a regression?

No

### Description

In the streams page, if you have multiple when sorting by size it doesn't sort properly. This is because the value in the column has the size unit, making the final value a String insted of Int.

Potential fix:

```javascript
sort: (a, b, rowA, rowB) => {
  const getNumericValue = (sizeString) => {
    if (!sizeString || typeof sizeString !== 'string') return 0;
    // Remove 'MB' and any whitespace, then parse the number
    return parseFloat(sizeString.replace('MB', '').trim());
  };

  const sizeA = getNumericValue(rowA.storage_size);
  const sizeB = getNumericValue(rowB.storage_size);

  return sizeA - sizeB;
}
```

### Please provide a link to a minimal reproduction of the bug

N/a

### Please provide the exception or error you saw

```true
N/a
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
v0.10.9-rc3
Latest
```

**Comment by Func86** [comment]
I cannot reproduce. As far as I can see, the value of `row.storage_size` is already a numeric value without units.
![image](https://github.com/user-attachments/assets/cbe566d0-cf28-43d9-b9da-c979a724d660)

The current sorting function should work fine.
```js
        sort: (a, b, rowA, rowB) => {
          return parseInt(rowA.storage_size) - parseInt(rowB.storage_size);
        }
```

**Comment by gaby** [comment]
Sorting issues are happening in a lot of places where the data value has a unit.
