### ISSUE TITLE
"Doc Num" should be sorted numerically

### ISSUE THREAD

**Issue by Func86** [openobserve/openobserve#4201]
### Which OpenObserve functionalities are the source of the bug?

streams

### Is this a regression?

No

### Description

Currently, "Doc Num" are sorted alphabetically:

![Screenshot 2024-08-10 152309](https://github.com/user-attachments/assets/d50af52b-febf-44a6-b296-15239e2bcea5)

### Please provide the version you discovered this bug in (check about page for version information)

```true
v0.10.9-rc4
4abd93b5016754483b18442055925a80f7b184cb
2024-08-13T14:26:15Z
```

**Comment by gaby** [comment]
Same issue as #4197 both columns need a custom sort function

**Comment by Func86** [comment]
> Same issue as #4197 both columns need a custom sort function

It seems the sorting on size columns are working correctly for me.

![Screenshot 2024-08-14 095714](https://github.com/user-attachments/assets/3ff3494b-2e90-4aa7-84d4-e7d5632be445)

**Comment by gaby** [comment]
@Func86 I have +700 streams and it doesnt sort 😂
