### ISSUE TITLE
Sankey Panel Throwing Error

### ISSUE THREAD

**Issue by naeemu** [openobserve/openobserve#4213]
### Which OpenObserve functionalities are the source of the bug?

dashboards

### Is this a regression?

Yes

### Description

Sankey panel was working fine to visualize calls from Traefik (client -> host). After the last update it throws this error:

```Error during planning: Projection references non-aggregate values: Expression tbl.requesthost could not be resolved from available columns: tbl.clienthost, tbl.target, count(tbl._timestamp)```

From the error it looks like instead of using `tbl.requesthost` it is trying to use `tbl.target`.

Query used - unchanged:
```SELECT clienthost as source, requesthost as target, count(_timestamp) as value FROM "app_logs" WHERE clienthost NOT LIKE '10.%' AND container_name = 'traefik' GROUP BY source, target```

### Please provide the exception or error you saw

```true
during planning: Projection references non-aggregate values: Expression tbl.requesthost could not be resolved from available columns: tbl.clienthost, tbl.target, count(tbl._timestamp)
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version v0.10.9-rc4
Commit Hash 4abd93b5016754483b18442055925a80f7b184cb
Build Date 2024-08-13T14:26:15Z
```

**Comment by gaby** [comment]
@naeemu If you add fields in the query, they need to be in the fields row above, else it won't work

**Comment by naeemu** [comment]
> @naeemu If you add fields in the query, they need to be in the fields row above, else it won't work

Do you mean here? If so, they were always there - I should have mentioned that. This was working fine until the latest update.
![image](https://github.com/user-attachments/assets/311966bd-a612-44c1-a678-25f15a34b26d)

**Comment by naeemu** [comment]
This seems to have been resolved with:
Version v0.10.9
Commit Hash dec66d405a9a94255eb5f13c0ec2186867809f36
Build Date 2024-08-16T06:27:15Z
