### ISSUE TITLE
Add support for formatting per Field

### ISSUE THREAD

**Issue by gaby** [openobserve/openobserve#4215]
### Which OpenObserve functionalities are relevant/related to the feature request?

dashboards

### Description

When creating visualizations the field formatting gets applied to all fields. If I have a column with Bytes and one with Numbers, I can't use any formatting since the data representation will be wrong.

### Proposed solution

Move the field formatting to *each* field, same place the sorting is at. 

### Alternatives considered

N/A

**Comment by ktx-kirtan** [comment]
Work is being done here: https://github.com/openobserve/openobserve/pull/4798

**Comment by gaby** [comment]
> Work is being done here: #4798

Awesome! 💪

**Comment by gaby** [comment]
Fixed in #4798
