### ISSUE TITLE
Log metric ingest curl doesn't work

### ISSUE THREAD

**Issue by agardnerIT** [openobserve/openobserve#4216]
### Which OpenObserve functionalities are the source of the bug?

ingestion

### Is this a regression?

No

### Description

The sample `curl` I'm given doesn't work.

```
curl -u root@example.com:REDACTED -k https://REDACTED.dev/api/default/default/_json -d '[{"level":"info","job":"test","log":"test message for openobserve"}]'
```

I've also tried various other ways such as `Basic` authorisation:

```
import requests

headers = {
    "accept": "application/json",
    "Content-Type": "application/json",
    "Authorization": "Basic REDACTED"
}
body = [
  {
    "Athlete": "Alfred",
    "City": "Athens",
    "Country": "HUN",
    "Discipline": "Swimming",
    "Sport": "Aquatics",
    "Year": 1896
  },
  {
    "Athlete": "HERSCHMANN",
    "City": "Athens",
    "Country": "CHN",
    "Discipline": "Swimming",
    "Sport": "Aquatics",
    "Year": 1896
  }
]
resp = requests.post("https://REDACTED.dev/api/default/default/_json", json=body, headers=headers)

print(resp.status_code)
```

Result: `401`

Strangely, the Swagger UI works but when I copy / paste the provided cURL from Swagger, it doesn't:

```
{
  "code": 200,
  "status": [
    {
      "name": "stream3",
      "successful": 2,
      "failed": 0
    }
  ]
}
```
## Different base encoding

When I inspect the cookies, I see:

```
auth_tokens={"access_token":"Basic cm9vd****GFtcGxlLmNvbTpDb21wbGV4cGFzcyMxMjM=","refresh_token":""};
```

But the OTEL collector integration shows a very slightly different base64 encoded string: `cm9vd****GFtcGxlLmNvbTplWE9CQXQxOXVFOUdRMFJH`

So:

```
cm9vd******************Db21wbGV4cGFzcyMxMjM=
cm9vd******************lWE9CQXQxOXVFOUdRMFJH
```

Yes, the `****` values are identical

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version
Commit Hash
Build Date
v0.10.9-rc4
4abd93b5016754483b18442055925a80f7b184cb
2024-08-13T14:04:31Z
```

**Comment by hengfeiyang** [comment]
The cookie use `username` and `password`, but ingestion use `ingestion token` it is different things. the `curl` ingestion should be work, if it can't work, try to restart your pod. and refresh UI, try again?

There is some bugs about user cache, but fixed in latest version.
