### ISSUE TITLE
Logs page: Reduce total number of events

### ISSUE THREAD

**Issue by bjp232004** [openobserve/openobserve#4221]
### Which OpenObserve functionalities are relevant/related to the feature request?

log search

### Description

Currently total 250 events displayed on logs page. Many times user not looking for those many event so reduce the default settings to 100 and user can change those if more events are required.

### Proposed solution

Change default settings 100 events per page.

### Alternatives considered

NA

**Comment by neha00290** [comment]
this is fixed
