### ISSUE TITLE
Toggling shows wrong stream?

### ISSUE THREAD

**Issue by agardnerIT** [openobserve/openobserve#4254]
### Which OpenObserve functionalities are the source of the bug?

metrics

### Is this a regression?

Yes

### Description

I open the metrics page and choose a stream. When I toggle to a new stream, the UI still shows the old one.

It's hard to explain so here's a video.

https://github.com/user-attachments/assets/5d108456-3e7c-4262-9126-3f46130b4ebe

Perhaps this isn't even a bug? I don't really know how to describe it :)

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version
Commit Hash
Build Date
v0.10.9
dec66d405a9a94255eb5f13c0ec2186867809f36
2024-08-16T06:06:56Z
```

**Comment by gaby** [comment]
This bug has been there for months, I thought it was just how it works 😆

**Comment by hengfeiyang** [comment]
@omkarK06 we need find time to fix it.

**Comment by prabhatsharma** [comment]
Let's leave it for now. Once we revamp metrics UI, this won't be an issue.
