### ISSUE TITLE
Several Major Issues with Dashboards/Visualizations

### ISSUE THREAD

**Issue by gaby** [openobserve/openobserve#4256]
### Which OpenObserve functionalities are the source of the bug?

dashboards

### Is this a regression?

No

### Description

When creating visualizations there's several issues with CSS/resizing and spacing across. These take away from the beauty of creating dashboards. There's also issues with the colors when multiple visualizations for the same data are present.

Examples:

Y-Axis Title needs space:

![image](https://github.com/user-attachments/assets/e3c0a2cd-0196-4a3d-929b-9c93ae9d80e6)

Pie Chart legend is touching the chart:

![image](https://github.com/user-attachments/assets/4a26b9ce-215a-4990-8d0d-45bf12366445)

Colors don't match for same data in the same dashboard (Critical issue):

![image](https://github.com/user-attachments/assets/555f5bd8-606a-47a9-8c54-eef069f32ed5)

Metric Visualization always tries to use the whole panel regardless of size:

![image](https://github.com/user-attachments/assets/0b1b8eef-1700-493a-9128-42ff1ec6bc50)

The size of the text + units is not taken into account for resizing:

![image](https://github.com/user-attachments/assets/b2bdbc6f-d00c-4df3-ad83-de92954c605d)

![image](https://github.com/user-attachments/assets/ebffd45e-1dda-49cb-8df1-64a282998ca5)

### Please provide the version you discovered this bug in (check about page for version information)

```true
v0.10.8 - https://cloud.openobserve.ai/
```

**Comment by gaby** [comment]
@ktx-kirtan Probably related to you, I could help but I can't find where is the code for this? 😆

**Comment by gaby** [comment]
@ktx-kirtan Has there been any updates on this? It has gotten worse since the release of 0.12.x

**Comment by gaby** [comment]
Dashboards and visualizations are not a priority it seems.

**Comment by gaby** [comment]
@neha00290 @ktx-akshay @ktx-abhay Out of all these issues, only one still happens.

This one:
![image](https://github.com/user-attachments/assets/b2bdbc6f-d00c-4df3-ad83-de92954c605d)

There's a point where even though I can resize the visualization the text doesn't shrink further.

**Comment by ktx-abhay** [comment]
Thanks @gaby. will check.

**Comment by ktx-abhay** [comment]
@gaby I checked. It is working for me. can you help me to replicate?

https://github.com/user-attachments/assets/15b0b38c-417b-4521-925c-935669804512

**Comment by gaby** [comment]
@ktx-abhay I will check today at work. Maybe i'm confusing it with the "6m ago" label that breaks all over the visualization. Look at 32 secs, it says "🕜 6m ago" but it's all over the visualization. 

That label prob needs to be hidden based on the size of the visualization.
