### ISSUE TITLE
"Getting a 503 error while fetching histogram data. The error message is: 'Failed to connect to host: Internal error - connector has been disconnected

### ISSUE THREAD

**Issue by ktx-akshay** [openobserve/openobserve#4260]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

![image](https://github.com/user-attachments/assets/4d29e841-2565-4b3a-aa3b-97d10b7c6831)

**Comment by oasisk** [comment]
fixed https://github.com/openobserve/openobserve/pull/4259
