### ISSUE TITLE
There is no cache result displayed for the time range 2024/08/15 00:00 - 2024/08/15 03:00 (Cache3 = 0).

### ISSUE THREAD

**Issue by ktx-akshay** [openobserve/openobserve#4271]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

"sql": "SELECT COUNT(_timestamp) AS xyz, _timestamp FROM \"stream_pytest_data\" GROUP BY _timestamp ORDER BY _timestamp DESC LIMIT 10000",

2024/08/15 00:00 - 2024/08/15 01:00    Cache1 = 0
2024/08/15 01:30 - 2024/08/15 02:30    Cache2= 0
2024/08/15 00:00 - 2024/08/15 03:00     Cache3 = 0

issue is there is no cache result showing  for 2024/08/15 00:00 - 2024/08/15 03:00     Cache3 = 0
 this time range

**Comment by oasisk** [comment]
this query doesnt make sense for caching , we cache aggregate queries with histogram only
