### ISSUE TITLE
stream/document stats not updating

### ISSUE THREAD

**Issue by agardnerIT** [openobserve/openobserve#4279]
### Which OpenObserve functionalities are the source of the bug?

streams

### Is this a regression?

No

### Description

The stream `doc_number` count doesn't seem to be updating even though there is data.

<img width="938" alt="Screenshot 2024-08-21 at 9 52 21 PM" src="https://github.com/user-attachments/assets/ec1c5189-bed1-4839-9feb-b06d93292e36">

<img width="1399" alt="Screenshot 2024-08-21 at 9 54 39 PM" src="https://github.com/user-attachments/assets/21e14cfd-5162-4f1f-8321-fdd42518e9c0">

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.10.9
Commit Hash: dec66d405a9a94255eb5f13c0ec2186867809f36
Build Date: 2024-08-16T06:06:56Z
```

**Comment by gaby** [comment]
@agardnerIT Stats are schedule to update every `10 minutes`. You can change this by setting the `ZO_CALCULATE_STATS_INTERVAL` environment variable as documented at the bottom of this table: https://openobserve.ai/docs/environment-variables/#common

Ex:

- `ZO_CALCULATE_STATS_INTERVAL=60`, will make stats update every 60 seconds.
