### ISSUE TITLE
Add total document count to Home Page

### ISSUE THREAD

**Issue by gaby** [openobserve/openobserve#4281]
### Which OpenObserve functionalities are relevant/related to the feature request?

home

### Description

The home page currently displays the number of Streams, total Ingested data size, and total compressed size of the data. It's currently missing 1 metric which is the total `docs` count across all streams.

This is a minimal change, but i'm assuming that data is already there, just not displayed? 

### Proposed solution

Add the total doc count across all streams to the home-page next to the total ingested/compressed size. 

### Alternatives considered

N/a

**Comment by hengfeiyang** [comment]
@bjp232004 also we need add `index size` on home page.
