### ISSUE TITLE
Dashboard top N results

### ISSUE THREAD

**Issue by ktx-vaidehi** [openobserve/openobserve#4302]
### Which OpenObserve functionalities are relevant/related to the feature request?

dashboards

### Description

**Top N Results with "Others" Aggregation Feature**

This PR introduces a new feature that allows for dynamic extraction of the top N results based on a breakdown key from your dataset. The key aspects of this feature are:

- **Top N Results**: The implementation identifies the top N unique values from the breakdown key, allowing you to focus on the most significant data points.

- **"Others" Aggregation**: An optional toggle enables aggregating all remaining values outside the top N into a single "others" category. This is particularly useful when dealing with large datasets or visualizing time series data.

![image](https://github.com/user-attachments/assets/f0a1de06-3f26-4f58-b22f-cf853db7b0a3)

### Proposed solution

-

### Alternatives considered

-

**Comment by gaby** [comment]
@ktx-vaidehi Is this related to https://github.com/openobserve/openobserve/issues/4235  ?
