### ISSUE TITLE
How to Configure Storage with Huawei Cloud OBS

### ISSUE THREAD

**Issue by vb3328998** [openobserve/openobserve#4354]
Hello,

I'm using Huawei Cloud CCE and would like to store logs in OBS (Object Storage Service). The official documentation currently provides configuration details for Alibaba Cloud and Tencent Cloud, but I couldn't find any instructions for Huawei Cloud OBS.
https://openobserve.ai/docs/storage/
Could you please guide me on how to configure OpenObserve to use Huawei Cloud OBS for storage?

Thank you!

**Comment by hengfeiyang** [comment]
i never used huawei cloud, but it should be same. you can check huawei cloud document they also should support s3 compatible API.

Or, you can join us wechat group, i think some user is using huawei cloud.
