### ISSUE TITLE
Count query issue - API displays 500 error

### ISSUE THREAD

**Issue by neha00290** [openobserve/openobserve#4362]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

`SELECT service_name,_timestamp, COUNT(*) AS log_count FROM "default" GROUP BY service_name,_timestamp`

`
{
    "code": 10001,
    "message": "Server Internal Error",
    "error_detail": "search node error",
    "trace_id": "30192c9bee7b4d51b90cba33ea6a113d"
}
`

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version
Commit Hash
Build Date
v0.11.0-rc3
2f670beafc0781acb20c4d5d1dc79ed9dcde46b3
2024-08-28T04:41:25Z
```

**Comment by hengfeiyang** [comment]
@neha00290 this is an issue about resource limit, you are trying to `group by _timestamp`, it is a huge of groups, because each record has different _timestamp, at the end, it got error `over memory limit`. please try `histogram(_timestamp)`.
