### ISSUE TITLE
feat: display when was the condition last satisfied in the alerts page

### ISSUE THREAD

**Issue by nikhilsaikethe** [openobserve/openobserve#4379]
### Which OpenObserve functionalities are relevant/related to the feature request?

alerts

### Description

I dont see when was the alert last satisfied / last met in the UI

### Proposed solution

there should be a similar column same as last triggered at called last satisfied at in the alerts page so that user can able to see when was the alert last satisfied / last met

### Alternatives considered

No

**Comment by Subhra264** [comment]
Fixed by #4368
