### ISSUE TITLE
Logs- Issues/ Observations

### ISSUE THREAD

**Issue by neha00290** [openobserve/openobserve#4396]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

- [ ] When user selects saved view directly without selecting any stream, the table is not rendered and page appears blank
- [ ] Switching records per page when result is expanded, the result does not collapse/expand again
- [ ] Search around record not getting highlighted
- [ ] Quick mode enabled (body, timestamp, k8s_container_name) fields selected as interesting fields
SQL Mode Enabled
Got the data
Download the table -> Observation: CSV doesn't contains body column. but table grid contains data for body column for few rows

<img width="1455" alt="Screenshot 2024-08-29 at 3 59 11 PM" src="https://github.com/user-attachments/assets/df53831c-1dec-4034-9cf4-a20aaa3339c6">

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version
Commit Hash
Build Date
v0.11.0-rc3
2edf51e27ad68fbcf9c606208d5520fa5639328d
2024-08-29T09:20:55Z
```

**Comment by gaby** [comment]
@neha00290 When you click "Download Table", it's using the query to generate the data instead of the table. This happens if SQL mode is enabled.

For example by query is: `SELECT * FROM LOGS`, but my table only has 4-5 columns. When i click download i get a csv file with ALL the fields.
