### ISSUE TITLE
front end resource '/web/assets/editor.api.v1.js' 404 when o2 run with ZO_BASE_URI

### ISSUE THREAD

**Issue by shuaiyy** [openobserve/openobserve#4404]
### Is this a regression?

Yes

### Description

![image](https://github.com/user-attachments/assets/bd01f582-bbf7-4911-94c2-82a65844233c)

it should be  {ZO_BASE_URI}/open-observe/web/assets/editor.api.v1.js

### Please provide the version you discovered this bug in (check about page for version information)

```true
v0.11.0-rc3
0193aaddf1e53e614137decc0bf4339b74f49d43
```

**Comment by hengfeiyang** [comment]
What is the value of `ZO_BASE_URI`? only this file not found?
