### ISSUE TITLE
Support SQL FILTER clause on aggregate functions

### ISSUE THREAD

**Issue by ghost** [openobserve/openobserve#4434]
### Which OpenObserve functionalities are relevant/related to the feature request?

log search

### Description

As a user, I want to make use of the SQL `FILTER` clause, so that I can present the same metric with different criteria in a single chart.

Example:
```sql
SELECT
    count(DISTINCT user_id) AS num_users,
    count(DISTINCT user_id) FILTER (WHERE role = 'manager') AS num_managers,
    count(DISTINCT user_id) FILTER (WHERE duration > 1000) AS num_affected_slow
FROM access_log
```

Looks like DataFusion already supports that for a while:
* https://github.com/apache/datafusion/pull/5868

### Proposed solution

Expose newer DataFusion features to the user.

### Alternatives considered

Multiple charts

**Comment by Loaki07** [comment]
Hi @hengfeiyang,

I'm interested to work on this issue, if its available.

**Comment by hengfeiyang** [comment]
@Loaki07 actually in our new search engine (v3), we already support it:

<img width="993" alt="image" src="https://github.com/user-attachments/assets/bcc52a91-8ff4-4336-97ee-7a2bdf37e1b9">
