### ISSUE TITLE
copy button on logs page to copy the json

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#444]
### Which ZincObserve functionalities are relevant/related to the feature request?

logs search

### Description

Sometimes, I may want to copy the log record. A simple copy button would be great.

### Proposed solution

A simple copy button at top right hand side.

<img width="948" alt="image" src="https://user-images.githubusercontent.com/4242188/228110459-72b5270b-605f-4e34-b276-9eddad01a04c.png">

### Alternatives considered

manually copy.

**Comment by hengfeiyang** [comment]
done
