### ISSUE TITLE
No Full Example for Rust Tracing

### ISSUE THREAD

**Issue by stevenhuyn** [openobserve/openobserve#4448]
### Describe the problem that you experienced

All the other languages documented so far have a corresponding repository besides Rust.

### Enter the URL of the topic with the problem

https://openobserve.ai/docs/ingestion/traces/rust/

### Describe what you were looking for in the documentation

A `cargo.toml` would be nice to see all the dependencies.

### Describe the actions that led you to experience the problem

Trying to adapt the docs to my own project.

### Describe what you want to experience that would fix the problem

Potentially a repository to reference.

### Add a screenshot if that helps illustrate the problem

There is no Rust example
![image](https://github.com/user-attachments/assets/12240834-9d0c-442b-8702-991f671cd84b)

**Comment by stevenhuyn** [comment]
Existing `cargo.toml` here:
https://github.com/openobserve/openobserve/issues/4248#issuecomment-2296908198

**Comment by taimingl** [comment]
Sample repo added here: https://github.com/openobserve/sample-tracing-rust

**Comment by stevenhuyn** [comment]
The docs should be updated to point to the example.
