### ISSUE TITLE
Add FST Index files to file_list table

### ISSUE THREAD

**Issue by uddhavdave** [openobserve/openobserve#4457]
### Which OpenObserve functionalities are relevant/related to the feature request?

log search

### Description

This feature will help manage the index files and will enable us to maintain mapping of each index file with its parquet file. 
It is also a prerequisite for showing the file sizes on UI which will be tracked in another ticket.

The subtasks for this are as follows in this order:
- [ ] Add index files to file_list table for management (maintaining 1:1 relation between inverted index and parquet file)
- [ ] Remove the index files from file_list table on compaction. (Currently we instantly delete them from Object Store)
- [ ] Handle case where file deleted manually on Object Store is marked as deleted.

### Proposed solution

Same as above

### Alternatives considered

None

**Comment by hengfeiyang** [comment]
we dropped FST feature, no longer need it.
