### ISSUE TITLE
Query restriction error displayed even when query set within time range

### ISSUE THREAD

**Issue by neha00290** [openobserve/openobserve#4465]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

<img width="1426" alt="Screenshot 2024-09-04 at 7 43 12 PM" src="https://github.com/user-attachments/assets/5692ab12-6762-42b6-ba88-25a02d11c87f">

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version
Commit Hash
Build Date
v0.11.0
6297cf4de51a45ee2dcd80ca25fd8e91ecc8ae36
2024-09-04T12:40:08Z
```

**Comment by oasisk** [comment]
fixed with https://github.com/openobserve/openobserve/pull/4482
