### ISSUE TITLE
Tracing bars in detail view have wrong start time

### ISSUE THREAD

**Issue by freswa** [openobserve/openobserve#4477]
### Which OpenObserve functionalities are the source of the bug?

traces

### Is this a regression?

Yes

### Description

All the bars in the tracing detail view start at 0 ms, while their actual start time is later.
![image](https://github.com/user-attachments/assets/3500a546-ed83-44b8-aeb1-451f2daadcc6)

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.11.0
Commit Hash: 7bbe192c015640ce643364b83b8ebb9c76a13331
Build Date: 2024-09-02T08:02:25Z
```

**Comment by dszczyt** [comment]
👍🏻
