### ISSUE TITLE
Support for Dark Mode

### ISSUE THREAD

**Issue by gaby** [openobserve/openobserve#450]
### Which ZincObserve functionalities are relevant/related to the feature request?

home, dashboards

### Description

Are there any plans to add support for Dark Mode in ZO?

### Proposed solution

N/a

### Alternatives considered

N/a

**Comment by gaby** [comment]
@hengfeiyang Any chance of getting this? 😂

**Comment by hengfeiyang** [comment]
I support it, but we have no plan for now, it is not a high priority.

**Comment by gaby** [comment]
This can be closed now, right?

**Comment by gaby** [comment]
Fixed via https://github.com/openobserve/openobserve/pull/1078
