### ISSUE TITLE
“No Record Found” Error on Pagination when Searching Across Multiple Partitions

### ISSUE THREAD

**Issue by bjp232004** [openobserve/openobserve#4502]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

When a user searches data across multiple partitions, the system encounters an issue with pagination. The first few partitions may not contain any data, but the system still processes the request. Initially, the search results may display correctly on the first page, but when the user clicks on subsequent pages (e.g., to view more data), the system throws an error: “No Record Found.”

This error occurs because the system is attempting to paginate across empty partitions without properly skipping them or accounting for the lack of data.

Steps to Reproduce:

	1.	Initiate a search query that spans across multiple data partitions.
	2.	In the first couple of partitions, there is no data available, but the search results for the first page are displayed correctly.
	3.	Click on the “Next” button to go to the second or third page.
	4.	The system throws a “No Record Found” error, halting the user’s ability to continue navigating through the search results.

Expected Behavior:

	•	The system should gracefully handle partitions with no data and continue to the next partition where data is available.
	•	Pagination should work seamlessly, displaying relevant search results on each page without errors.

Actual Behavior:

	•	On the first page of results, the system might display the correct data.
	•	However, on subsequent pages, the system throws a “No Record Found” error due to the empty partitions encountered during pagination.

Impact:

	•	Users are unable to fully navigate through search results, especially when there are multiple partitions without data.
	•	This can cause confusion for the user, and they are unable to retrieve all of the relevant data.

**Comment by pitastrudl** [comment]
Experiencing this as well on Openobserve v11/v10.8.
