### ISSUE TITLE
Vector healthcheck

### ISSUE THREAD

**Issue by goastler** [openobserve/openobserve#4513]
### Description

The template for vector's config is:
```
[sinks.zinc]
type = "http"
inputs = [ source or transform id ]
uri = "***"
method = "post"
auth.strategy = "basic"
auth.user = "***"
auth.password = "***"
compression = "gzip"
encoding.codec = "json"
encoding.timestamp_format = "rfc3339"
healthcheck.enabled = false
```
`healthcheck.enabled` is set to false. It would be great to enable this health check. In slack, prabhat said:
> I don't recall fully why we did this, but if I remember it correctly we   initially supported  ES ndjson _bulk format and vector tried to do healthcheck using ES APIs which would always fail, hence we disabled that. We haven't looked back at it since then.

### Proposed solution

Enable vector healthcheck

### Alternatives considered

None

**Comment by hengfeiyang** [comment]
Can you or anyone help check how to support it? we have no energy on it recently.

**Comment by gaby** [comment]
I replied on Slack explaining how to use it, but no one replied back

**Comment by Loaki07** [comment]
@goastler @gaby You can now enable vector healthcheck for openobserve. [Updated docs](https://openobserve.ai/docs/ingestion/logs/vector/)

Add the following config to `vector.toml`.

### NOTE: To ensure that Vector checks the health of the OpenObserve service specifically, set both `healthcheck.enabled = true` and provide a `healthcheck.uri` that points to the OpenObserve health check endpoint.

```toml
# Enable healthcheck
healthcheck.enabled = true
healthcheck.uri = "http://localhost:5080/healthz"
```
