### ISSUE TITLE
Getting a 503 error randomly on the dashboard for both absolute and relative time, when long query is fired.

### ISSUE THREAD

**Issue by ktx-akshay** [openobserve/openobserve#4519]
### Which OpenObserve functionalities are the source of the bug?

dashboards

### Is this a regression?

Yes

### Description

When executing a long query on an absolute or relative time range (e.g., 3 to 4 days), a 503 error occurs.

![image](https://github.com/user-attachments/assets/2836e7b0-cec1-4ac5-b5ab-7e0ac8a5204a)

**Comment by hengfeiyang** [comment]
it is because of the kubernets cluster memory allocate over 100%. fixed.
