### ISSUE TITLE
Histogram not displayed when #ResultArray# added in vrl

### ISSUE THREAD

**Issue by neha00290** [openobserve/openobserve#4543]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

<img width="1199" alt="Screenshot 2024-09-13 at 4 16 01 PM" src="https://github.com/user-attachments/assets/e5a5fecf-438b-4cc2-82af-75d54bc1eb33">

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version
Commit Hash
Build Date
v0.11.0
daef771f1754ba53b34428d9ec698a003296c12e
2024-09-13T09:51:42Z
```

**Comment by kethesainikhil** [comment]
The issue is related to the function not with the #ResultArray# that is used

**Comment by nikhilsaikethe** [comment]
The issue is related to the function not with the #ResultArray# that is used
