### ISSUE TITLE
When adding a user, how do I add a role except admin

### ISSUE THREAD

**Issue by Xuzan9396** [openobserve/openobserve#4549]
### Which OpenObserve functionalities are the source of the bug?

users

### Is this a regression?

Yes

### Description

![image](https://github.com/user-attachments/assets/7216b0f8-b938-4c6c-b7bf-df461edc1748)
When adding a user, how do I add a role except admin，I couldn't find the place to create a character.

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version v0.11.0
Commit Hash 7bbe192c015640ce643364b83b8ebb9c76a13331
Build Date 2024-09-02T07:42:45Z
```

**Comment by gaby** [comment]
@Xuzan9396 In the `Open Source` edition that's the only role available. The `Enterprise` edition has support for using RBAC with `OpenFGA`. See here: https://github.com/openobserve/openobserve#enterprise-vs-open-source-vs-cloud-edition

**Comment by hengfeiyang** [comment]
@Xuzan9396 Yep. you can try `Enterprise` version and it is free for small user which less than `200GB/day`
