### ISSUE TITLE
feat: need variable to pass current query for dashboard drilldown

### ISSUE THREAD

**Issue by ktx-abhay** [openobserve/openobserve#4552]
### Which OpenObserve functionalities are relevant/related to the feature request?

dashboards

### Description

Currently, there is no way to pass the current query when redirecting to the logs page using a dashboard drilldown. Two possible variables could be used:

1. query: `${query}`
2. Base64-encoded query: `${query_encoded}`

Steps to drilldown logs page:

1.  Go to logs page.
2.  Select the stream.
3.  Select any absolute time range and click on apply button.
4.  Copy browser url.
5.  Go to dashboard panel.
6.  Add drilldown.
7.  Paste copied logs page url.
8.  Replace `query`, `start_time` and `end_time` query params as given below.

![image](https://github.com/user-attachments/assets/038a25d8-31b7-4bae-bb57-c28c8cc68dbf)

### Proposed solution

-

### Alternatives considered

-

**Comment by ndejong** [comment]
An alternative to consider here - instead of using the URL "Go to:" mechanism, could OpenObserve provide another magic "Go to:" that is similar to the Dashboard type that is for Logs types?

This perhaps makes it easier for the user to put drill downs together.

That said - a magic `$query` (or maybe `$_query` because it is a magic variable) is likely to be very useful elsewhere too, so please don't stop the in-the-run feature development

**Comment by charl3y15** [comment]
How do I use this? I don't see anything in the documentation

**Comment by ktx-abhay** [comment]
@charl3y15 Currently, There is no documentation for this feature. You can follow the steps shown in the PR description.


Also, you can follow `User Guide`.
![image](https://github.com/user-attachments/assets/275978e3-fe15-4459-94b5-8d41dc6cc14f)

**Comment by ktx-abhay** [comment]
@ndejong @charl3y15 
Also, we added new type called `Logs`. which will redirect to Logs page. Which will be available in next release
![image](https://github.com/user-attachments/assets/d7d489f1-d75f-45e7-ab42-00877cbfffe8)

**Comment by ktx-kirtan** [comment]
for the logs page more details can be found here: https://github.com/openobserve/openobserve/issues/5194
