### ISSUE TITLE
organisations not shown in cloud version open observe

### ISSUE THREAD

**Issue by flo-jan** [openobserve/openobserve#4570]
### Which OpenObserve functionalities are the source of the bug?

users

### Is this a regression?

Yes

### Description

my organisations do not show in the cloud client, altthough they are succesfully retrieved. See screenshots

![fetched](https://github.com/user-attachments/assets/25da88a3-4b6f-4b8a-83a6-0f2138045d13)

![but not shown](https://github.com/user-attachments/assets/ed0ca8f8-1ae1-47b5-b637-b562b3ef25ab)

### Please provide a link to a minimal reproduction of the bug

Login at cloud service, go to section IAM -> organisations

### Please provide the exception or error you saw

```true
AppOrganizations.6f027280.js:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'id')
    at AppOrganizations.6f027280.js:1:9602
    at Array.filter (<anonymous>)
    at AppOrganizations.6f027280.js:1:9561
    at Array.map (<anonymous>)
    at AppOrganizations.6f027280.js:1:9520
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
v0.11.0 (used at cloud from https://cloud.openobserve.ai/)
7bbe192c015640ce643364b83b8ebb9c76a13331
2024-09-02T07:45:15Z
Os linux x64 browser Chrome (Version 127.0.6533.119 (Official Build) (64-bit)
```

**Comment by bjp232004** [comment]
Can you please try to logout and login again? Let me know if you still face issue.

**Comment by flo-jan** [comment]
after login three of the four organisations disappeared from the server response and the one that remained did show up in the interface.
The other three organisations where previously attached to another account. We cannot reach that account anymore because we switched an e-mail address from google to microsoft, so we couldn't login anymore (we used google login). Or better said: we could still login with the same account, but the e-mail adress of that google account had changed. Maybe that was what caused the faulty behaviour in your application?

Anyway, we are not interested in any of the old logs of the old account so our problem has been solved. You can close this ticket if you want.

**Comment by flo-jan** [comment]
I am back to where I was. Logging in and out, incognito mode, nothing helps. Same thing happens as I described in my first post at  Sep 17
