### ISSUE TITLE
Shorten url when sharing link

### ISSUE THREAD

**Issue by lospejos** [openobserve/openobserve#4576]
### Which OpenObserve functionalities are relevant/related to the feature request?

home, dashboards, other

### Description

It would be nice to have an option to shorten link before sharing it.

### Proposed solution

Add drop-down menu or button next to "Share Link" button on the top right corner. After pressing the "Shorten Link" (or "Share short link") shorten the current URL before putting it on clipboard. Of course some URL shortening module should be implemented in OpenObserve to be able to shorten URLs and to handle shortened URLs correctly.

### Alternatives considered

Use some external URL shortener

**Comment by sroy07** [comment]
Hi, I would like to work on this issue.

**Comment by Loaki07** [comment]
This is implemented and merged to `main`, ref: #4697.
