### ISSUE TITLE
Dashboard Configuration - New Enhancements

### ISSUE THREAD

**Issue by ktx-vaidehi** [openobserve/openobserve#4589]
### Which OpenObserve functionalities are relevant/related to the feature request?

dashboards

### Description

**Chart Configuration Options**

These configuration options allow you to customize various aspects of your charts, providing greater control over how data is displayed. Below are the available options:

**1. Line Thickness**

- Description: Adjust the thickness of the lines in line-based charts.
- Type: `Number`

![image](https://github.com/user-attachments/assets/f2f6b127-7a5b-4167-bc34-6f9c414c577c)

**2. Label Options**

- Description: Controls the display and rotation of values on the chart.
- Type: `Object`

**Sub-options:**

`value_position:` Determines where the values are displayed on the chart.

**Options:**

- `none:` No label displayed
- `top:` Display value at the top of the data point
- `bottom:` Display value at the bottom of the data point
- `inside_top:` Display value inside the top of the data point
- `inside_bottom:` Display value inside the bottom of the data point

`value_rotate:` Rotates the displayed value based on the specified angle.
Type: `Number (degrees)`

![image](https://github.com/user-attachments/assets/5d7083c0-f9ca-4db4-abdf-d972f0fdd4ae)

**3. Show Symbol**

- Description: Determines whether to display symbols at the data points on line, area, and area-stacked charts. If set to `true`, the `label_options `configuration will also become visible.
- Type: `Boolean`

![image](https://github.com/user-attachments/assets/dd8e2806-2cfa-485a-832b-1f45aa48cb27)

**4. Line Interpolation**

- Description: Defines the interpolation type for line charts, controlling how lines are drawn between data points.
- Type: `String`

**Options:**

- `smooth:` Smooth curve
- `linear:` Straight line between points
- `step_before:` Step-like line with the step before the data point
- `step_after:` Step-like line with the step after the data point
- `step_middle:` Step-like line with the step in the middle between points

![image](https://github.com/user-attachments/assets/fc02eaa8-f4b0-45de-a1d6-70159173896c)

### Proposed solution

-

### Alternatives considered

-

**Comment by gaby** [comment]
Related https://github.com/openobserve/openobserve/issues/3425 https://github.com/openobserve/openobserve/issues/2335
