### ISSUE TITLE
total number is wrong when the query include `distinct`

### ISSUE THREAD

**Issue by hengfeiyang** [openobserve/openobserve#4590]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

For query:
```sql
select distinct user_id from default
```

The UI will shows a wrong total number

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.11.0
```

**Comment by gaby** [comment]
@hengfeiyang This is not regression, it has been happening for a while now.
