### ISSUE TITLE
Feature: Upload big compacted files using Multi-part upload instead of normal PUT requests

### ISSUE THREAD

**Issue by TessaIO** [openobserve/openobserve#4638]
### Which OpenObserve functionalities are relevant/related to the feature request?

other

### Description

When the compactor is configured with 1Gb as the size of compacted files, we started seeing many OOMs on the Compactor side. The logs show something like:
```
 ERROR infra::storage::remote: s3 File upload error: Generic { store: "S3", source: Reqwest { retries: 1, max_retries: 1, elapsed: 2.582922163s, retry_timeout: 180s, source: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("s3.eu-central-1.amazonaws.com")), port: None, path: "xxxxxxxx/files/default/logs/ecs/2024/09/24/11/7244317660924633277.parquet", query: None, fragment: None }, source: hyper_util::client::legacy::Error(SendRequest, hyper::Error(Canceled, "connection closed")) } } }    
```

### Proposed solution

Currently, the compactor uploads using the PUT command, it would be better to have the possibility to use multi-part upload to have more timeout during the upload phase.

### Alternatives considered

Decreasing the compacted file size is not an option since we want to keep the file sizes pretty

**Comment by TessaIO** [comment]
If the feature makes sense, you can assign it to me

**Comment by hengfeiyang** [comment]
Sound good. Thank you.

**Comment by TessaIO** [comment]
Closed by https://github.com/openobserve/openobserve/pull/4644
