### ISSUE TITLE
Ingester regression: Database issues

### ISSUE THREAD

**Issue by TessaIO** [openobserve/openobserve#4646]
### Which OpenObserve functionalities are the source of the bug?

ingestion

### Is this a regression?

Yes

### Description

After upgrading to v0.12.0, we started seeing a couple of issues related to the ingester which caused some missing logs.
1. `Error while writing logs: DbError# error LockTimeout performing operation on key`. this is a repeated error on the ingester side and it reaches the maximum number of retries and then it goes OOM.
2. `Error update metadata metrics: SqlxError# error returned from database: 1243 (HY000): Unknown prepared statement handler (31) given to mysql_stmt_precheck`. This is also a persistent issue

### Please provide a link to a minimal reproduction of the bug

For us, we just deployed Openobserve with MySQL Database

**Comment by hengfeiyang** [comment]
I think we have no change on the database side from `v0.11` to `v0.12`, Can you confirm it's because of `v0.12`, maybe you can try back to `v0.11`, downgrade is safe, you can try. And what is you setting of:
```
ZO_META_CONNECTION_POOL_MIN_SIZE
ZO_META_CONNECTION_POOL_MAX_SIZE
ZO_META_TRANSACTION_RETRIES
```

And which database are you using, MySQL or PostgreSQL?

**Comment by TessaIO** [comment]
We're using MySQL.
before downgrading to 0.11, there's an important observation which is, that in other environments with v0.12, we don't have issues. When I checked the DB I found that there's one additional table on the environments experiencing the issue which is the `file_list_jobs` and the status is equal to 2 for all entries. Can it be the issue there?

**Comment by TessaIO** [comment]
@hengfeiyang Also the issue is that there are some Locks in the DB that get only released after the timeout which is 10 minutes. Probably we don't reach the point where we release the lock after finishing or in case of errors

**Comment by TessaIO** [comment]
> ZO_META_CONNECTION_POOL_MIN_SIZE
> ZO_META_CONNECTION_POOL_MAX_SIZE
> ZO_META_TRANSACTION_RETRIES

values are:
1
2
3

**Comment by TessaIO** [comment]
Also, it might be related, we're also seeing this error:
```
Error update metadata metrics SqlxError# error returned from database: 1243 (HY000): Unknown prepared statement handler (31) given to mysql_stmt_precheck    
```

**Comment by hengfeiyang** [comment]
i haven't saw this error before, you can try double the number:
```
ZO_META_CONNECTION_POOL_MIN_SIZE=2
ZO_META_CONNECTION_POOL_MAX_SIZE=4
ZO_META_TRANSACTION_RETRIES=3
```

**Comment by TessaIO** [comment]
> ZO_META_CONNECTION_POOL_MIN_SIZE=2
> ZO_META_CONNECTION_POOL_MAX_SIZE=4
> ZO_META_TRANSACTION_RETRIES=3

Didn't help

**Comment by TessaIO** [comment]
Is it normal that the file_list_jobs table is always there in the environment that has the error but not for other environments?
Especially if the status=2 and if I got the code well these entries should be deleted right?

**Comment by hengfeiyang** [comment]
The table `file_list_jobs` is added recently, it used for compactor, and now the compactor works like this:
1. generate `jobs` for each period, default is 1 hour, based on your setting `ZO_COMPACT_STEP_SECS`
2. the default status is `0` means waiting for process.
3. the compactor will fetch merge job from table `file_list_jobs` where `status=0` and change the status to `1` means processing.
4. it will change the status to `2` when the job merged done.

So, the data in this table all of `2` it is fine, because of the merge jobs was done. and the done job will clean after 1 day.

**Comment by TessaIO** [comment]
Thanks for the explanation, I appreciate it!
For now, It seems that the issue doesn't occur anymore (for some reason), So I will close the issue.

**Comment by TessaIO** [comment]
@hengfeiyang 
After investigating this issue, I found that there are two functions using the `SELECT GET_LOCK` statement that are `get_for_update` and `get_pending_jobs`. Both of these functions require 2 database connections since we have in each function 2 `pool.begin().await` but we never handle the case where the second call can fail, after releasing the lock, which in our case failed because we only specify 2 DB connections instead of 4, and it failed during the second call for the `pool.begin().await` function and left the Lock in the DB without releasing it.
I think that:
1. We should handle the case where `pool.begin().await` can fail and release the lock if it's the case
2. Specify in the docs that we should have at least 4 DB connections to make everything work without any issues.

WDYT?

**Comment by hengfeiyang** [comment]
@TessaIO Thank you for report this, i didn't notice that before, i agree with you. we can do both. 

i saw you already create one PR for item 1, also i am thinking we can put the limit in this PR, if the connection pool setting less than `4` we set it to `4`.

**Comment by TessaIO** [comment]
> i saw you already create one PR for item 1, also i am thinking we can put the limit in this PR, if the connection pool setting less than `4` we set it to `4`.

I can create another PR for that, wdyt?

**Comment by hengfeiyang** [comment]
Another PR or change it in the same PR, both fine.

**Comment by TessaIO** [comment]
I'll do it in another one!
Thinking about it, I think that enforcing it to be 4 can make other components allocate extra DB connections that they don't need like compactor/alertmanager/querier. So, I think the administrator should be responsible about this. Thoughts?

**Comment by hengfeiyang** [comment]
You are right, but our first rule is `keep simple`. 90% user never change the default setting. we should let the default setting working well for most users. 

- Small users that only have a few node, it doesn't matter have `2` more connection to the db.
- Big users that always have more than `4` CPU cores and connections to the db. never effect them.

**Comment by TessaIO** [comment]
Okay I'm down for that!
