### ISSUE TITLE
Distorted area plot

### ISSUE THREAD

**Issue by HiFiPhile** [openobserve/openobserve#4653]
### Which OpenObserve functionalities are the source of the bug?

log search, Don't known / other

### Is this a regression?

Yes

### Description

Hi, I'm using openobserve to collect sensor data from 2 days ago and currently it has about 80k records.
Below is the data format: 
```
{
_timestamp:1727366179130577,
data:0006000B,
dstid:00000002,
funcno:0000,
length:4,
mfrid:0000,
rorg:4BS,
rssi:61,
srcid:00000001,
status:00,
timestamp:2024-09-26T17:56:19.128000,
type:Inbound
}
```
With the bar graph I can get the histogram correctly, with `histogram(_timestamp)` as X axis and `count(_timestamp)` as Y axis:
![image](https://github.com/user-attachments/assets/ab90e63a-2378-4c21-bc06-bdfd95d24587)

If I add `srcid` as breakdown in stacked graph I can get a nice graph:
![image](https://github.com/user-attachments/assets/9ec59f0f-0b7b-466e-a74a-327ac5de02d2)

However, if I run area or stacked area graph I got a distorted graph:
Without breakdown:
![image](https://github.com/user-attachments/assets/1454ea7f-b239-416c-8c74-8b87194586d5)
With breakdown:
![image](https://github.com/user-attachments/assets/8c37e805-7590-42fd-b532-4f2a9e0122cf)

### Please provide the exception or error you saw

```true
No error occurred
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version v0.12.1
Commit Hash f8a27b5c0dc3376663efd1e9400fa2ad43edee9f
Build Date 2024-09-19T13:05:50Z
OS: Arch Linux x64
```

**Comment by prabhatsharma** [comment]
Sort the _timestamp manually and it will be fine. This has already been fixed and will be available in next release.

**Comment by HiFiPhile** [comment]
Thank you, sort timestamp fixed the issue.
