### ISSUE TITLE
Feat: Implement Short Url Service

### ISSUE THREAD

**Issue by Loaki07** [openobserve/openobserve#4689]
### Which OpenObserve functionalities are relevant/related to the feature request?

log search, alerts, routing

### Description

Current Behaviour:

- When query parameters become excessively long, generated URLs can break or fail to redirect due to browser limitations or server constraints.

### Implement a URL shortener service to address the issue of long URLs:

-  Shortening: Generate a fixed-length, unique short URL for each long URL.
-  Storage: Store the mapping between original and shortened URLs in a cache and database.
-  Redirection: Redirect users from shortened URLs to their corresponding original URLs.

### Implementation Details:
- Hashing and Encoding: Use a suitable hashing algorithm (e.g., SHA-256) to generate a hash of the original URL. Encode the hash using a compact encoding scheme (e.g., Base62).
- Shortened ID Generation: Create a fixed-length shortened ID by truncating the encoded hash.
- Validation: Before generating a new shortened ID, validate that it doesn't already exist in the cache or database to ensure uniqueness.
- Cache and Database: Employ a cache (use existing cache) for fast lookups and a database (create a new table in PostgreSQL) for persistent storage.

### Integration: Integrate the URL shortener service with:
- Alerts
- Reports
- Middleware: Implement middleware for web services to intercept requests with shortened URLs and redirect them to their original destinations.

### Alternatives considered

None

**Comment by hengfeiyang** [comment]
@Loaki07 In my mind the simplest short url algorithm is use `auto-generated-id` of database, and use `unique index` to guarantee data have no duplicated. and use `base62` for the record id, then we can get the short id like this `Ua`, `xeB`, it is pretty short.

the logic maybe like this:
1. create a table, with id auto-generated and field `url` to store the original url, also create an `unique index` for `url` field.
2. insert to url to the table and get the id, then `base62` will get the short url.
3. also add a in-memory cache for it, like what we did, just add a `HashMap` in memory.
4. when we visit the short url, get the original url from memory cache (if cache missing get from db again), and redirect to it.

What do you think?

**Comment by hengfeiyang** [comment]
Yes. this solution has problem with super cluster ,the id maybe duplicated.

**Comment by hengfeiyang** [comment]
LGTM. 

some detail
1. we can use md5 for simply the work. directly use 32 chars or 16 chars (middle) both fine.
2. create the table need both for, sqlite/mysql/postgres, and the table should create an `unique index` for original url.
3. the memory cache, we can simple use `Mutex<HashMap>` like others.
4. we need an API for frontend to short the url. `POST /api/short`
5. we need an endpoint for visit the short url and redirect to original url. `GET /short/3f9ad7a444e7c275`
6. if the hashing conflict we can use original url + timestamp to generate a new hashsing.

**Comment by hengfeiyang** [comment]
@Subhra264 @oasisk i think we don't need RBAC for short URL, anyone can create or visit.

**Comment by oasisk** [comment]
> @Subhra264 @oasisk i think we don't need RBAC for short URL, anyone can create or visit.

This will be only for /web so we should be fine

**Comment by Subhra264** [comment]
> @Subhra264 @oasisk i think we don't need RBAC for short URL, anyone can create or visit.

LGTM.
