### ISSUE TITLE
Enforce Max DB Connections to be at least 4

### ISSUE THREAD

**Issue by TessaIO** [openobserve/openobserve#4712]
### Description

Since there are 2 functions `get_pending_jobs` and `get_file_list` functions, each requiring 2 DB connections, it would make sense to enforce at least 4 DB connections.

### Proposed solution

Enforce at least 4 DB connections

### Alternatives considered

N/A

**Comment by TessaIO** [comment]
FYI @hengfeiyang

**Comment by hengfeiyang** [comment]
Thank you
