### ISSUE TITLE
The _timestamp field get rendered using browser timezone

### ISSUE THREAD

**Issue by gaby** [openobserve/openobserve#473]
### Which ZincObserve functionalities are the source of the bug?

log search, dashboards, ingestion

### Is this a regression?

No

### Description

Currently when searching, and viewing dashboard the _timestamp field gets rendered using the browser timezone which is confusing for when accessed from multiple timezones.

Provide a way via ENV variable to set a default timezone regardless of users browser, or make the default be `UTC`.

**Comment by gaby** [comment]
I just tried the latest `zincobserve-dev` image and this still happens. I'm sending UTC timestamp data but it gets render with whatever timezone my browser is using. The field does say -# as a way of saying the original timezone, but for me to see data I have to change the interval to `Last 2-3hrs` even though the data is recent.

@prabhatsharma @hengfeiyang

**Comment by hengfeiyang** [comment]
Yes, we store data in UTC, but shows data in UI use local timezone. we will support set timezone in UI later.

**Comment by neha00290** [comment]
Testing for this ticket is complete.
