### ISSUE TITLE
Dashboard: value mapping for table chart to alter display text or color

### ISSUE THREAD

**Issue by ktx-abhay** [openobserve/openobserve#4742]
### Which OpenObserve functionalities are relevant/related to the feature request?

dashboards

### Description
need a configuration option for **value mapping** in the table chart panel. This feature will allow users to:
- Alter the display text based on specific value conditions.
- Apply background colors to table cells based on the mapped values.

### Steps to Implement

1. **Add/Edit a Table Chart Panel**: 
   - Navigate to the table chart panel.
   - Open the configuration panel for the table.
   
2. **Access Value Mapping**:
   - Click on the `Add/Edit Value Mapping` button to configure the value mappings.

   ![image](https://github.com/user-attachments/assets/f7f45a0e-1cd9-431a-8c00-811bb6bf0e2b)

### Value Mapping Types

There are three types of value mappings that should be supported:

1. **Value Mapping**: Directly map specific values to custom text or background colors.
2. **Range Mapping**: Map a range of numerical values to custom text or background colors.
3. **Regex Mapping**: Use regular expressions to match patterns and map them to custom text or background colors.

   ![image](https://github.com/user-attachments/assets/0eca0d08-fc0e-46fe-a811-4365a7caaa03)

### Expected Output

Once the value mapping is configured, the table cells should display the mapped text and/or background colors based on the defined rules.

   ![image](https://github.com/user-attachments/assets/c2d1e487-817d-4b99-bef3-1345526fa457)

### Proposed solution

-

### Alternatives considered

-

**Comment by gaby** [comment]
Can't wait for this feature 💪
