### ISSUE TITLE
Getting 500 in almost all api endpoints without any further detail

### ISSUE THREAD

**Issue by mfyz** [openobserve/openobserve#4766]
### Which OpenObserve functionalities are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Hi,

I am trying to perform a search via API but getting HTTP 500 with no body in the API call response.
I recently created my account and struggled to find what the rest API authentication should be in the docs. I simply tried to follow the ingestion CURL (`/default/_json`) request that has the ingest token. I set up a collection in insomnia with "basic" auth with my email and the ingest token as password from the ingest API endpoint. Maybe I'm not getting the authentication right but regardless, the response of the API should not be 500, at least that part is "bug" and I can help troubleshoot.

Exact same authentication that works for "ingest" is not working on other endpoints, including the ones that does not have any input, like `/summary`, or `/dashboards`.

Here is the insomnia screenshot of the dashboard call:
![Screenshot 2024-10-12 21 49 47](https://github.com/user-attachments/assets/bc4f50c8-93f9-4e3b-8f01-85496afaf138)

Another thing I tried is to use the Web UI, copy the search request I want to use from the network tab as Curl and import that in insomnia. Which works, but it works with the cookie that has the authentication token which will expire. I could use the current cookie value and set a corn somewhere with regresh_token and keep saving that. But I shouldn't, and not sure the integrity of that process will be.

### Please provide a link to a minimal reproduction of the bug

https://api.openobserve.ai/api/fatih_organization_46366_sq1rLLgsbauwv9d/dashboards

### Please provide the exception or error you saw

```true
HTTP 500
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
I'm using the openobserve.ai cloud version.
Version v0.12.1
Commit Hash f8a27b5c0dc3376663efd1e9400fa2ad43edee9f
Build Date 2024-09-19T13:09:58Z
```

**Comment by hengfeiyang** [comment]
Sorry, it should be fixed, please try again. @mfyz

**Comment by mfyz** [comment]
Still HTTP 500.
I've tried `/summary`, `/dashboards`, `/functions` endpoints.

**Comment by hengfeiyang** [comment]
It works for me, if you still have issue please find us in the slack channel. we can discuss the detail.
