### ISSUE TITLE
Support download full log from queried result

### ISSUE THREAD

**Issue by davistran86** [openobserve/openobserve#4769]
### Which OpenObserve functionalities are relevant/related to the feature request?

log search

### Description

Currently when downloading log from queried result I see it only support max 10000 records. I need to download all records and sometime I have to do it multiple times. It would be great that we can download all. Thank you :)

### Proposed solution

No

### Alternatives considered

No

**Comment by hengfeiyang** [comment]
This make sense, but it is difficult to download million or billion records directly, maybe it is over GB data. so we have some limit on it.
