### ISSUE TITLE
gRPC Configuration Works Locally but Fails in Saas Cloud Environment

### ISSUE THREAD

**Issue by Ignaciojeria** [openobserve/openobserve#4786]
### Which OpenObserve functionalities are the source of the bug?

traces, logs & metrics

### Is this a regression?

Yes

### Description

For some reason, the SAAS cloud environment with gRPC credentials fails while the local setup works correctly.

Environment:
Go version: 1.22.0
OTLP via gRPC

Error Details:
context deadline exceeded: rpc error: code = DeadlineExceeded 
desc = received context error while waiting for new LB policy update: context deadline exceeded
2024/10/15 00:11:39 gRPC Method: /opentelemetry.proto.collector.trace.v1.TraceService/Export, Request: resource_spans:{resource:{attributes:{key:"deployment.environment" value:{string_value:"local"}} attributes:{key:"service.name" value:{string_value:"multi-folder-components"}}} scope_spans:{scope:{name:"observability"} spans:{trace_id:"]6\x98\x95'\xc1\x92\xd6H;\xefNN\x19\xee\xaf" span_id:"\x14\xcc\xd3\x02c\xa4\xef\x11" flags:256 name:"hello" kind:SPAN_KIND_INTERNAL start_time_unix_nano:1728961898756416400 end_time_unix_nano:1728961898761304900 status:{}} schema_url:"[https://opentelemetry.io/schemas/1.4.0"}](https://opentelemetry.io/schemas/1.4.0%22%7D)
2024/10/15 00:11:39 INFO: [core] [Channel https://github.com/openobserve/openobserve/pull/1]Channel exiting idle mode
2024/10/15 00:11:39 INFO: [core] [Channel https://github.com/openobserve/openobserve/pull/1]Resolver state updated: {
"Addresses": [
{
"Addr": "3.14.38.180:5081",
"ServerName": "",
"Attributes": null,
"BalancerAttributes": null,
"Metadata": null
},
{
"Addr": "3.14.203.203:5081",
"ServerName": "",
"Attributes": null,
"BalancerAttributes": null,
"Metadata": null
},
{
"Addr": "3.19.183.237:5081",
"ServerName": "",
"Attributes": null,
"BalancerAttributes": null,
"Metadata": null
}
],
"ServiceConfig": null,
"Attributes": null
} (resolver returned new addresses)
2024/10/15 00:11:39 INFO: [core] [Channel https://github.com/openobserve/openobserve/pull/1]Channel switches to new LB policy "pick_first"
2024/10/15 00:11:39 INFO: [core] [Channel https://github.com/openobserve/openobserve/pull/1 SubChannel https://github.com/openobserve/openobserve/pull/2]Subchannel created
2024/10/15 00:11:39 INFO: [core] [Channel https://github.com/openobserve/openobserve/pull/1]Channel Connectivity change to CONNECTING
2024/10/15 00:11:39 INFO: [core] [Channel https://github.com/openobserve/openobserve/pull/1 SubChannel https://github.com/openobserve/openobserve/pull/2]Subchannel Connectivity change to CONNECTING
2024/10/15 00:11:39 INFO: [core] [Channel https://github.com/openobserve/openobserve/pull/1 SubChannel https://github.com/openobserve/openobserve/pull/2]Subchannel picks a new address "3.14.38.180:5081" to connect
2024/10/15 00:11:49 gRPC Error in method /opentelemetry.proto.collector.trace.v1.TraceService/Export: rpc error: code = DeadlineExceeded desc = received context error while waiting for new LB policy update: context deadline exceeded
2024/10/15 00:11:49 traces export: context deadline exceeded: rpc error: code = DeadlineExceeded desc = received context error while waiting for new LB policy update: context deadline exceeded
2024/10/15 00:11:59 WARNING: [core] [Channel https://github.com/openobserve/openobserve/pull/1 SubChannel https://github.com/openobserve/openobserve/pull/2]grpc: addrConn.createTransport failed to connect to {Addr: "3.14.38.180:5081", ServerName: "api.openobserve.ai:5081", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 3.14.38.180:5081: i/o timeout"
2024/10/15 00:11:59 INFO: [core] [Channel https://github.com/openobserve/openobserve/pull/1 SubChannel https://github.com/openobserve/openobserve/pull/2]Subchannel picks a new address "3.14.203.203:5081" to connect
2024/10/15 00:11:59 WARNING: [core] [Channel https://github.com/openobserve/openobserve/pull/1 SubChannel https://github.com/openobserve/openobserve/pull/2]grpc: addrConn.createTransport failed to connect to {Addr: "3.14.203.203:5081", ServerName: "api.openobserve.ai:5081", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 3.14.203.203:5081: i/o timeout"
2024/10/15 00:11:59 INFO: [core] [Channel https://github.com/openobserve/openobserve/pull/1 SubChannel https://github.com/openobserve/openobserve/pull/2]Subchannel picks a new address "3.19.183.237:5081" to connect
2024/10/15 00:11:59 WARNING: [core] [Channel https://github.com/openobserve/openobserve/pull/1 SubChannel https://github.com/openobserve/openobserve/pull/2]grpc: addrConn.createTransport failed to connect to {Addr: "3.19.183.237:5081", ServerName: "api.openobserve.ai:5081", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 3.19.183.237:5081: i/o timeout"
2024/10/15 00:12:09 gRPC Error in method /opentelemetry.proto.collector.trace.v1.TraceService/Export: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 3.14.38.180:5081: i/o timeout"

Additional Info:

- In the cloud environment, the gRPC request times out with the error shown above.
- The exact same configuration works fine locally, as demonstrated below:

Cloud Environment Error:
![image](https://github.com/user-attachments/assets/84f08924-3a27-421d-b335-98cb20419db9)

Local Environment Success:
![image](https://github.com/user-attachments/assets/eedfe762-3039-429b-91df-0f8d0602a983)

### Please provide a link to a minimal reproduction of the bug

# OpenObserve gRPC Issue Reproduction

This repository demonstrates an issue with gRPC credentials in the cloud environment. Locally, the same configuration works without any issues.

## Reproduction Steps

1. Clone the repository:

   git clone https://github.com/Ignaciojeria/openobserve-grpc-issue.git
   cd openobserve-grpc-issue

2. Replace the .env.example file with .env, and set the appropriate values in the .env file.

3. Run the project:

   go run main.go

4. Make a `GET` request to the following endpoint to test:

   curl http://localhost:8081/testing-obs

---

_No response_

**Comment by Ignaciojeria** [comment]
I added more detailed logs ⇨ http server started on [::]:8081
2024/10/15 00:11:39 gRPC Method: /opentelemetry.proto.collector.trace.v1.TraceService/Export, Request: resource_spans:{resource:{attributes:{key:"deployment.environment"  value:{string_value:"local"}}  attributes:{key:"service.name"  value:{string_value:"multi-folder-components"}}}  scope_spans:{scope:{name:"observability"}  spans:{trace_id:"]6\x98\x95'\xc1\x92\xd6H;\xefNN\x19\xee\xaf"  span_id:"\x14\xcc\xd3\x02c\xa4\xef\x11"  flags:256  name:"hello"  kind:SPAN_KIND_INTERNAL  start_time_unix_nano:1728961898756416400  end_time_unix_nano:1728961898761304900  status:{}}  schema_url:"https://opentelemetry.io/schemas/1.4.0"}
2024/10/15 00:11:39 INFO: [core] [Channel #1]Channel exiting idle mode
2024/10/15 00:11:39 INFO: [core] [Channel #1]Resolver state updated: {
  "Addresses": [
    {
      "Addr": "3.14.38.180:5081",
      "ServerName": "",
      "Attributes": null,
      "BalancerAttributes": null,
      "Metadata": null
    },
    {
      "Addr": "3.14.203.203:5081",
      "ServerName": "",
      "Attributes": null,
      "BalancerAttributes": null,
      "Metadata": null
    },
    {
      "Addr": "3.19.183.237:5081",
      "ServerName": "",
      "Attributes": null,
      "BalancerAttributes": null,
      "Metadata": null
    }
  ],
  "ServiceConfig": null,
  "Attributes": null
} (resolver returned new addresses)
2024/10/15 00:11:39 INFO: [core] [Channel #1]Channel switches to new LB policy "pick_first"
2024/10/15 00:11:39 INFO: [core] [Channel #1 SubChannel #2]Subchannel created
2024/10/15 00:11:39 INFO: [core] [Channel #1]Channel Connectivity change to CONNECTING
2024/10/15 00:11:39 INFO: [core] [Channel #1 SubChannel #2]Subchannel Connectivity change to CONNECTING
2024/10/15 00:11:39 INFO: [core] [Channel #1 SubChannel #2]Subchannel picks a new address "3.14.38.180:5081" to connect
2024/10/15 00:11:49 gRPC Error in method /opentelemetry.proto.collector.trace.v1.TraceService/Export: rpc error: code = DeadlineExceeded desc = received context error while waiting for new LB policy update: context deadline exceeded
2024/10/15 00:11:49 traces export: context deadline exceeded: rpc error: code = DeadlineExceeded desc = received context error while waiting for new LB policy update: context deadline exceeded
2024/10/15 00:11:59 WARNING: [core] [Channel #1 SubChannel #2]grpc: addrConn.createTransport failed to connect to {Addr: "3.14.38.180:5081", ServerName: "api.openobserve.ai:5081", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 3.14.38.180:5081: i/o timeout"
2024/10/15 00:11:59 INFO: [core] [Channel #1 SubChannel #2]Subchannel picks a new address "3.14.203.203:5081" to connect
2024/10/15 00:11:59 WARNING: [core] [Channel #1 SubChannel #2]grpc: addrConn.createTransport failed to connect to {Addr: "3.14.203.203:5081", ServerName: "api.openobserve.ai:5081", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 3.14.203.203:5081: i/o timeout"
2024/10/15 00:11:59 INFO: [core] [Channel #1 SubChannel #2]Subchannel picks a new address "3.19.183.237:5081" to connect
2024/10/15 00:11:59 WARNING: [core] [Channel #1 SubChannel #2]grpc: addrConn.createTransport failed to connect to {Addr: "3.19.183.237:5081", ServerName: "api.openobserve.ai:5081", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 3.19.183.237:5081: i/o timeout"
2024/10/15 00:12:09 gRPC Error in method /opentelemetry.proto.collector.trace.v1.TraceService/Export: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 3.14.38.180:5081: i/o timeout"

**Comment by hengfeiyang** [comment]
Our cloud version doesn't support gRPC for now.

**Comment by Ignaciojeria** [comment]
> Our cloud version doesn't support gRPC for now.

Thanks for the response! I understand that self-hosting is the current option if I want to use OTLP + gRPC, but I was wondering if there are any plans or discussions around supporting this in the future? No rush, just curious about the roadmap. Thanks again!

**Comment by prabhatsharma** [comment]
It's on roadmap. No ETA.

**Comment by kellpossible** [comment]
does the cloud version now support grpc @prabhatsharma ?

**Comment by hengfeiyang** [comment]
Cloud haven't support gRPC ingestion now.

**Comment by kellpossible** [comment]
Thanks @hengfeiyang Looks like this area of the documentation on the cloud instance might need updating then?

<img width="2644" height="1192" alt="Image" src="https://github.com/user-attachments/assets/c32c51bd-3ec7-47a2-9e0f-dd92f48c7790" />

**Comment by kellpossible** [comment]
Why is this issue closed if it's on the roadmap but not implemented yet? Is there a separate issue tracker for cloud?

**Comment by hengfeiyang** [comment]
@kellpossible thank you for you help, we have no plan support gRPC on cloud. @bjp232004 let's remove gRPC support for cloud. if we support it later will add this back.

**Comment by bjp232004** [comment]
gRPC option hide for cloud version.
