### ISSUE TITLE
When querying logs, the query will fail when using convenient query for non-string fields.

### ISSUE THREAD

**Issue by hexiang1219** [openobserve/openobserve#4788]
### Which OpenObserve functionalities are the source of the bug?

log search, alerts

### Is this a regression?

No

### Description

**Query logs:** 
When querying logs, the query will fail when using convenient query for non-string fields.
![图片](https://github.com/user-attachments/assets/f5aeb572-261a-49c2-b0ad-b0c30c800e08)
![图片](https://github.com/user-attachments/assets/d97396a4-b737-47fd-b094-69fb4d287897)
You need to manually remove the single quotes to query normally.
![图片](https://github.com/user-attachments/assets/9af4412d-01fc-4300-b237-3a24cffe46fd)

In addition, it was also discovered that when configuring alarms, non-string type data query will also fail.
![图片](https://github.com/user-attachments/assets/b0226e67-b4a3-486a-9f1d-e523f690bbb0)

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.12.1
```

**Comment by hengfeiyang** [comment]
@bjp232004 If the dataType is `float` and we add the value to filter with single quote, then can't get result. we need to fix it by remove single quote if the dataType is `int` or `float`.
