### ISSUE TITLE
Custom Logo on Enterprise Settings and Login page

### ISSUE THREAD

**Issue by ShyamOOAI** [openobserve/openobserve#4839]
### Which OpenObserve functionalities are the source of the bug?

login

### Is this a regression?

Yes

### Description

- [x] Upload Custom Logo with .svg formats is not displayed
- [x] Upload Custom Logo with .gif, .bmp, and .tif formats are displayed
- [x] Remove content from Custom Logo Text then click "Cancel" button, content is removed.
- [x]  Maximum Lenght for Custom Logo Text  is not fixed

**Comment by gaby** [comment]
Is this a bug or a feature request?

**Comment by ShyamOOAI** [comment]
Both bug and feature improvement as per requirement.

**Comment by hengfeiyang** [comment]
@gaby We are adding a new feature that allow user to custom the logo and hide our logo.
