### ISSUE TITLE
Trace Api / Set Status to ERROR ignores optional `description` value.

### ISSUE THREAD

**Issue by fdcastel** [openobserve/openobserve#4851]
### Which OpenObserve functionalities are the source of the bug?

ingestion, traces

### Is this a regression?

Yes

### Description

In a trace activity, when calling [`Set Status`](https://opentelemetry.io/docs/specs/otel/trace/api/#set-status) with the optional error description:

```csharp 
// opentelemetry-dotnet
Activity.SetStatus(ActivityStatusCode.Error, "myErrorDescription");
```

OpenObserve 0.12.1 seems to discard the error message. In _Traces / Span Details / Tags_ we get these tags:

```
span_kind	2
span_status	ERROR
```

This same code when pointed to a [HoneyComb](https://www.honeycomb.io/) endpoint captures the expected tags:

```
status_code: 2
status_message: myErrorDescription
```

### Please provide the exception or error you saw

```true
There is no error/exception.

But the string `myErrorDescription` is nowhere to be found in the trace history (it should).
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.12.1
Commit Hash: f8a27b5c0dc3376663efd1e9400fa2ad43edee9f
Build Date: 2024-10-10T08:40:19Z
```

### Anything else?

The above example was made in C# with `opentelemetry-dotnet` library. But I presume the problem can be reproduced by any library.

To the best of my understanding the code:

```csharp 
Activity.SetStatus(ActivityStatusCode.Error, "myErrorDescription");
```

Just set the tags `otel.status_code` and `otel.status_description`. ([reference](https://github.com/open-telemetry/opentelemetry-dotnet/blob/0343715f49ac8e121ec39acd92f8d5572b3d036d/src/Shared/SpanAttributeConstants.cs))

**Comment by YashodhanJoshi1** [comment]
Hey @fdcastel , I added two new tags which takes values from the span status - `status_code` and `status_message` . If possible, can you verify that this solves your issue  using the image `public.ecr.aws/zinclabs/openobserve-dev:v0.12.1-66d6f18` ?

**Comment by fdcastel** [comment]
@YashodhanJoshi1 I'm rebuilding my test system. Will return to you ASAP.

**Comment by fdcastel** [comment]
@YashodhanJoshi1 its working fine, now! Thank you!

![image](https://github.com/user-attachments/assets/d2ef3eb8-e7b9-4a78-860b-ee20e4d68616)

**Comment by YashodhanJoshi1** [comment]
Great, thanks for checking and responding!
