### ISSUE TITLE
Rename “Ingestion” Label to “Data Source”

### ISSUE THREAD

**Issue by bjp232004** [openobserve/openobserve#4872]
### Which OpenObserve functionalities are relevant/related to the feature request?

other

### Description

In the current UI, the label “Ingestion” is being used to represent data sources. To make this more intuitive, we propose renaming this label to “Data source” across the UI and relevant components.

### Proposed solution

Change the label in left menu navigation.

### Alternatives considered

NA

**Comment by fdcastel** [comment]
**My $0.02:  The previous name seemed more intuitive to me.**

I might be overlooking something, but this page

![image](https://github.com/user-attachments/assets/bb04f48f-7458-4687-aa42-79c9eb22ae73)

does not display any 'Data sources' to me.

Instead, what it does show are _instructions on how to ingest data_ from different platforms/sources.
