### ISSUE TITLE
openobserve-enterprise Viewer Permission issues

### ISSUE THREAD

**Issue by pycgo** [openobserve/openobserve#4887]
### Which OpenObserve functionalities are the source of the bug?

users

### Is this a regression?

No

### Description

Viewer  has some root Permissions，But it shouldn't be owned：

1、can Add & delete Stream
![image](https://github.com/user-attachments/assets/f3fb47e4-86d8-4759-9218-e90b57020eb6)
2、can Reset Token
![image](https://github.com/user-attachments/assets/1acb587d-48f0-43d2-a5f8-7cd0ec5140d6)
3、can change setting
![image](https://github.com/user-attachments/assets/98095b8c-d774-4d5e-8c16-241b399cced0)
4、can add addresses and templates in the alarm
5、can Add Report
6、can add Add Pipeline
7、Can add dashboard

**Comment by sobakaio** [comment]
I second this. In enterprise version permissions feature is broken, everybody has root permissions regardless of dropdown selection in IAM.

**Comment by Subhra264** [comment]
Hello @pycgo, @wombatinua  can you please share the version you are using? Also I suspect, you have not enabled openfga (that we use for RBAC). Make sure, you have these ENVs specified - 
```
O2_OPENFGA_ENABLED = true
O2_OPENFGA_BASE_URL = "http://localhost:8080" # Change it to the base url where Openfga is running
```

**Comment by hengfeiyang** [comment]
@Subhra264 i think the user didn't enable OFGA, only deploy the enterprise version. and the enterprise version embed some roles like: `admin` `viewer`, and the `viewer` doesn't work as expect.

Does the role work without `OpenFGA` ?

**Comment by sobakaio** [comment]
I run O2 in docker and now have

```
ERROR o2_enterprise::enterprise::openfga::model: Error creating store: Reqwest(reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("localhost")), port: Some(8080), path: "/stores", query: None, fragment: None }, source: hyper_util::client::legacy::Error(Connect, ConnectError("tcp connect error", Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" })) }) 
```

Maybe localhost must be something like host.docker.internal ?

**Comment by hengfeiyang** [comment]
@wombatinua this is for example:
```
O2_OPENFGA_ENABLED = true
O2_OPENFGA_BASE_URL = "http://localhost:8080" # Change it to the base url where Openfga is running
```

You need to run the `OpenFGA` first and then set this to the `OpenFGA` endpoint, i think you have no `OpenFGA`, please disable the option:
```
O2_OPENFGA_ENABLED = false
```

Then your o2 will back to work.

**Comment by sobakaio** [comment]
So Openfga is not a part of the O2 container? If not can we get instructions on how to run it in docker container?

**Comment by Subhra264** [comment]
@wombatinua check this out - https://openfga.dev/docs/getting-started/setup-openfga/docker

> Does the role work without OpenFGA ?
@hengfeiyang  no without openfga they don't work.

**Comment by sobakaio** [comment]
So this dependency is for RBAC only? isn't it an overkill for roles to work? Are there any plans for supporting internal RBAC backend? Thank you.

**Comment by prabhatsharma** [comment]
OpenFGA is required for RBAC to work. No plans to support internal RBAC.

**Comment by sobakaio** [comment]
Can one instance of OpenFGA work with several O2 instances simultaneously?

**Comment by hengfeiyang** [comment]
@wombatinua Yes, you should configure all the o2 nodes connect to the same OpenFGA node.

**Comment by sobakaio** [comment]
I managed to get O2 EE up with RBAC enabled. Thank you very much for hints regarding OpenFGA, this process desperately lacking documentation.
