### ISSUE TITLE
Swagger UI error in v0.13.0-rc1

### ISSUE THREAD

**Issue by fdcastel** [openobserve/openobserve#4894]
### Which OpenObserve functionalities are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

In v0.13.0-rc1, the OpenAPI documentation page ("Swagger UI") is showing the following error:

![image](https://github.com/user-attachments/assets/f856db54-1dc9-457b-b314-66c03e8ed13f)

### Please provide the exception or error you saw

```true
Resolver error at paths./api/{org_id}/summary.get.responses.200.content.application/json.schema.properties.alerts.items.properties.query_condition.properties.multi_time_range.items.$ref
Could not resolve reference: Could not resolve pointer: /components/schemas/CompareHistoricData does not exist in document
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.13.0-rc1
Commit Hash: 38434399482c97d32157c6195747c92d3921c68a
Build Date: 2024-10-23T13:01:07Z

P.S.: Thank you for the new layout of About page :)
```

### Anything else?

This GitHub Issue form really should have an "Api" option in the _"Which OpenObserve functionalities are the source of the bug?"_ selection box.

**Comment by hengfeiyang** [comment]
fixed in `v0.13.0-rc2`
