### ISSUE TITLE
Use a different URL for gRPC? (new env var `ZO_GRPC_URL`)

### ISSUE THREAD

**Issue by fdcastel** [openobserve/openobserve#4898]
### Which OpenObserve functionalities are relevant/related to the feature request?

ingestion

### Description

To host OpenObserve behind a reverse proxy, it's essential to differentiate between requests made to HTTPS and gRPC protocols. 

Currently, I'm looking for the presence of the `organization` HTTP header to route requests to port 5081 (gRPC). But this is somewhat hacky.

A more flexible configuration would be ideal, enabling a setup like:

- https://openobserve.example.com for the main Web UI and the HTTP API (port 5080)
- https://grpc.openobserve.example.com for gRPC (port 5081)

### Proposed solution

Introducing a new environment variable, such as `ZO_GRPC_URL`, would be a nice solution. This would allow explicit configuration for the gRPC endpoint, making the setup more intuitive and less reliant on workarounds like using HTTP headers.

### Alternatives considered

To check for the presence of "special" HTTP headers in the request to route the requests.

**Comment by hengfeiyang** [comment]
Sorry, I am not sure the exactly issue what you are except. as my understand you want to add a domain for the gRPC proxy. then you can add it by nginx (ingress), there is no need add a new ENV in o2.

**Comment by snovak7** [comment]
Well, I think Zo_GRPC_URL is more meant for the user interface experience, that you can copy paste directly with proper grpc configuration shown by UI, otherwise you're correct @hengfeiyang, today you can route grpc without issues.
