### ISSUE TITLE
Delete log entries based on a query

### ISSUE THREAD

**Issue by lynxaegon** [openobserve/openobserve#4906]
### Which OpenObserve functionalities are relevant/related to the feature request?

streams

### Description

It would be a nice to have to be able to run a query and delete log entries.
For example, i entered some logs with a tag "testing" and after the testing is done, i would want to delete those specific tagged logs.

### Proposed solution

Run a SQL Query and delete the matched logs (DELETE FROM "stream_name" WHERE tag = "testing"

### Alternatives considered

-

**Comment by hengfeiyang** [comment]
We didn't provide feature to delete or update records. we suggest that you should use different stream, we have stream delete and stream data retention.
