### ISSUE TITLE
Cannot infer common argument type for comparison operation Boolean = Utf8

### ISSUE THREAD

**Issue by lynxaegon** [openobserve/openobserve#4907]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

No

### Description

I have some log entries that contain a bool "initialize" which is true/false. 
Searching in logs like:
- `initialize='true'` -> returns Cannot infer common argument type for comparison operation Boolean = Utf8
- `initialize=true` -> returns SqlExpr::Identifier: We only support Identifier at the moment undefined
- `initialize!=false` -> returns correctly
- using SQL mode returns the same errors

### Please provide the exception or error you saw

```true
- type_coercion caused by Error during planning: Cannot infer common argument type for comparison operation Boolean = Utf8
- SqlExpr::Identifier: We only support Identifier at the moment undefined
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.12.1
Commit Hash: f8a27b5c0dc3376663efd1e9400fa2ad43edee9f
Build Date: 2024-10-10T08:40:19Z
OS: linux x64 (docker image)
```

**Comment by hengfeiyang** [comment]
this fixed in the latest release `v0.13.0-rc1`
