### ISSUE TITLE
The same search conditions returns abnormal results at different times

### ISSUE THREAD

**Issue by azhezzzz** [openobserve/openobserve#4959]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

When I search using the condition `match_all('code 5')`, the time range `Past xxx Minutes` is work good, 
but when I select `Past xxx Hours/Days`,  its wrong and the exception 

`Search SQL execute error
TraceID:eaeb77853e2a4fa28edfae26b65a7f03
Execution error: status: Internal, message: "ErrorCode# {\"error_code\": 20006, \"error_msg\": \"Search parquet file not found\"}", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Thu, 31 Oct 2024 03:56:12 GMT", "content-length": "0"} }`

Past 45 Minutes Result
![企业微信截图_cad72454-08d8-4139-9165-5adb949f20b2](https://github.com/user-attachments/assets/8a03d8a4-7a18-4bf8-82e2-181543bf826f)

Past 1 Hours Result
![企业微信截图_8d71cbae-41b4-413b-baee-4a6a1e2755b5](https://github.com/user-attachments/assets/dfbe12aa-da98-47a8-9c54-b59372eb7cc6)

### Please provide the exception or error you saw

```true
Search SQL execute error
TraceID:eaeb77853e2a4fa28edfae26b65a7f03
Execution error: status: Internal, message: "ErrorCode# {\"error_code\": 20006, \"error_msg\": \"Search parquet file not found\"}", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Thu, 31 Oct 2024 03:56:12 GMT", "content-length": "0"} }
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.13.0
Commit Hash: eeecb3f1305ca6cccf7fdae06930438ebbe92cc1
Build Date: 2024-10-29T03:55:58Z
```

**Comment by hengfeiyang** [comment]
This is a bug. fixed in #4962, will release new version soon.
