### ISSUE TITLE
The same browser cannot open log queries from multiple organizations at the same time.

### ISSUE THREAD

**Issue by hexiang1219** [openobserve/openobserve#4960]
### Which OpenObserve functionalities are relevant/related to the feature request?

other

### Description

When I want to query stream data from different organizations by opening multiple tabs in the same browser, it is not supported. You can only open one first and then switch to the other after completing the query.

### Proposed solution

The front-end service can dynamically request the corresponding back-end interface based on the organization selected on the current page.

### Alternatives considered

none

**Comment by hengfeiyang** [comment]
Yes, one browser only can access one organization.  because we stored the currently org in local storage.

**Comment by hexiang1219** [comment]
Do you have any plans to adjust in the future?

**Comment by hengfeiyang** [comment]
Let's leave this issue, maybe we can back to this later.

**Comment by prabhatsharma** [comment]
completed
