### ISSUE TITLE
Add detailed error message for openobserve program

### ISSUE THREAD

**Issue by ayers-ltd** [openobserve/openobserve#4967]
### Which OpenObserve functionalities are relevant/related to the feature request?

other

### Description
When running the helm --version v0.13.1 of openobserve for the first time, you may encounter multiple pods that fail to run successfully on the first try. The program error is too simple, which makes it difficult for novices to roughly troubleshoot the startup failure.

The error is as follows：
```
2024-11-01T06:10:31.494797828+00:00 INFO o2_enterprise::enterprise: init enterprise    
thread '<unnamed>' panicked at /o2-enterprise/src/enterprise/common/infra/config.rs:67:10:
called `Result::unwrap()` on an `Err` value: ParseBoolError
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: backend job init failed: channel closed
```
The cause was found to be that the helm value O2_CUSTOM_HIDE_SELF_LOGO value was empty, resulting in startup exception.
```
enterprise:
  enabled: true
  parameters:
    O2_CUSTOM_HIDE_SELF_LOGO: ""
 ```
I hope to change the error reporting mechanism to indicate which value has a problem.
I tried changing RUST_LOG to debug, but the log still did not show any key information.
This may be confusing for first-time users.

### Proposed solution

I hope to optimize the error message text to be more elegant as follows
```
2024-11-01T06:10:31.494797828+00:00 INFO o2_enterprise::enterprise: init enterprise    
thread '<unnamed>' panicked at /o2-enterprise/src/enterprise/common/infra/config.rs:67:10:
called `Result::unwrap()` on an `Err` value: ParseBoolError
Error: Invalid value for O2_CUSTOM_HIDE_SELF_LOGO. It should be either 'true' or 'false'.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: backend job init failed: channel closed
```

### Alternatives considered

By default, the program will be affected and error reporting will be provided to provide more detailed exception capture and throwing.

**Comment by hengfeiyang** [comment]
Added, it will like this in next release:
```
thread 'main' panicked at src/config/src/config.rs:1227:17:
EnvConfig: ZO_NATS_REPLICAS except a value of [usize]
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
