### ISSUE TITLE
Dynamic stream name

### ISSUE THREAD

**Issue by fclairamb** [openobserve/openobserve#4968]
### Which OpenObserve functionalities are relevant/related to the feature request?

streams, functions, ingestion

### Description

Following up on[ this thread](https://zincobserve.slack.com/archives/C02R473PNP2/p1730414700868939?thread_ts=1729634054.857509&cid=C02R473PNP2),

- In many cases, we only search logs in the context of one or two apps/services
- The currently recommended way of handling is by merging all logs into one stream
- When we have many fields in a stream, the compaction consumes a huge amount of memory (>10GB)

### Proposed solution

In the pipelines, allow to define a stream based on an attribute (for example `k8s.container.name`) 

### Alternatives considered

A recommended way to set the OTLP exporter to define the `stream-name` header based on one of the logs attributes.

**Comment by hengfeiyang** [comment]
@fclairamb I have the same idea, we can use header to define the stream name extract from the special attribute.

**Comment by hengfeiyang** [comment]
We already support it by using `pipeline`, am i right? @taimingl

**Comment by taimingl** [comment]
> We already support it by using `pipeline`, am i right? @taimingl

Yep, using `pipeline` has been merged into main.
