### ISSUE TITLE
Log search doesn't work anymore in v0.13.0

### ISSUE THREAD

**Issue by TessaIO** [openobserve/openobserve#4983]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

Hi,
after upgrading from v0.12.0 to v0.13.0, the basic log search for a specific stream doesn't work at all. It just hangs out and then it reports an error, as shown in the screenshot below
<img width="782" alt="Screenshot 2024-11-04 at 11 37 18" src="https://github.com/user-attachments/assets/cda8e2d1-9e43-4cc2-94f3-d4869987e9b1">

### Please provide the exception or error you saw

```true
async_nats: event: client error: nats: IO error
search error: Error# Error# nats lock for key: /locker/search/cluster_queue/global, acquire timeout in 600s
```

**Comment by hengfeiyang** [comment]
@TessaIO Please use `v0.13.1-rc2`, the previous version have bugs that can't query data.

**Comment by TessaIO** [comment]
@hengfeiyang We upgraded to `v0.13.1` on a sandbox environment, but I can see that the querier performance is degraded. The first search goes as expected, but afterward if I select a specific time range (not last 15 minutes) The querier fails (without any log tho).

**Comment by hengfeiyang** [comment]
timeout?

**Comment by TessaIO** [comment]
Yes, probably. There's no error log btw

**Comment by hengfeiyang** [comment]
You can wait, if it timeout, also will print some error like: timeout

**Comment by hungbbear** [comment]
I got the same issue here. It just hanging and do not return any thing or super slow. Pods also exit with code 1

```
thread '<unnamed>' panicked at src/main.rs:194:17:
cluster init failed: Error# nats lock for key: /locker/nodes/register, acquire timeout in 30s
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
2024-11-17T14:45:59.933168683+00:00 ERROR openobserve::common::infra::cluster::nats: [CLUSTER] register failed: Error# nats lock for key: /locker/nodes/register, acquire timeout in 30s    
Error: backend job init failed, exiting
```

**Comment by hengfeiyang** [comment]
this is because the NATS lock issue, if you got this, you can clean the lock in NATS by this command:
```
nats stream purge KV_o2_locker
```

**Comment by minhle-shopee** [comment]
hi @TessaIO , have you solved the issue? I met the exact same problem with you on version v0.13.2-rc1-debug

**Comment by hengfeiyang** [comment]
Please try to upgrade to latest version first.
