### ISSUE TITLE
Issues and improvements with Email Alerts

### ISSUE THREAD

**Issue by gaby** [openobserve/openobserve#4996]
### Which OpenObserve functionalities are the source of the bug?

alerts

### Is this a regression?

No

### Description

Now that OpenObserve has support for email alerts, I decide to create some alerts for my data. The `body` for the alert template expects `JSON`. When using email alerts you want to be able to write an email body template.

Issues: 
- [x] When sending an alert OpenObserve will remove all the `end lines` and formatting and send the whole email `body` as 1 line. This is because currently the email manager sends the alert template body as a html body. There should be support for both plain text and html body.
- [x] The subject pre-appends `Openobserve alert -`, and there's no way to disable it. This is hard-coded here: https://github.com/openobserve/openobserve/blob/main/src/service/alerts/alert.rs#L559
- [x] The pre-appended subject says `Openobserve` instead of `OpenObserve`.

### Please provide the exception or error you saw

```true
N/a
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.13.1-rc2
```

**Comment by gaby** [comment]
Does this mean the `body` when using email alerts has to be `html` ? https://github.com/openobserve/openobserve/blob/main/src/service/alerts/alert.rs#L559

What if the email provider doesn't support `HTML` emails?

**Comment by Subhra264** [comment]
Hmm, Currently it wraps the msg with the HTML email header type. Will do a fix soon. I think we need to introduce a new field to template payload indicating whether the body is plain text or html (default). Or may be try to figure out from the body itself whether this is html or plain text.

**Comment by gaby** [comment]
@Subhra264 So HTML should work for email? I will test it today.

But yeah, ideally when the user selects "Email" the UI should use plaintext and/or email.

This could be done by trying run a check if html is present, else use plaintext when sending the email.

**Comment by Subhra264** [comment]
> @Subhra264 So HTML should work for email? I will test it today.

Yes, it should

**Comment by Subhra264** [comment]
In fact, when you write plain text, I believe it is actually renders the plain text inside `<p>` html tag, which is why all the lines are concatenated into a single line. You can try some thing like -

![Screenshot 2024-10-16 at 12 58 13 PM](https://github.com/user-attachments/assets/16710df4-05c0-4094-9d16-9394a308970e)

**Comment by gaby** [comment]
@Subhra264 Excellent, I will try that today. 💪

**Comment by gaby** [comment]
@Subhra264 Using HTML tags made my emails work. I found other issues but will report those in a separate issue.

Reported here: https://github.com/openobserve/openobserve/issues/5009 and #5008

**Comment by gaby** [comment]
@Subhra264 Found another bug. The `_timestamp` field can't be using in alerts. It's render as stored instead of the string.

**Comment by Subhra264** [comment]
> It's render as stored instead of the string.

Sorry, didn't get this part. Can you share a screen shot if possible? or copy paste the rendered output you got?

Also, would like to see your template as well.

**Comment by gaby** [comment]
@Subhra264 The template is:

`"This is an event {_timestamp}"`

The email will have `1723123456.12344` instead of `Nov 12, 2024 HH:MM:SS`.

OpenObserve server needs to render that field before sending the email.

**Comment by Subhra264** [comment]
Thanks @gaby , got the issue. Will fix them by next week.

**Comment by Subhra264** [comment]
Hello @gaby, currently the `_timestamp` field can be used in two ways in templates. In the main template if you use it e.g. -
```
Alert: {alert_name}, timestamps: {_timestamp}
```

This will generate the below message in both cases of email and normal alert notifications -
```
Alert: Demo_alert, timestamps: 1733139509390228, 1733139589590741, 1733139509532808, 1733139587199086, 1733139545979793, 1733139519162326, 1733139507112853, 1733139563447512, 1733139579562586, 1733139585582507, 1733139564784858, 1733139559517878
```

And if you use `_timestamp` inside row template of an alert, e.g. -
```
This is an event {_timestamp}
```

This will generate the below message for both email and non-email alert notifications -
```
This is an event 1733139509390228
This is an event 1733139509390228
This is an event 1733139509390228
...
```

I am not sure if we want to directly convert the `_timestamp` value into formatted string (cc @hengfeiyang ), but if you want to format the timestamp inside row template, you can use `alert_start_time` instead inside the row template. This basically formats the `_timestamp` field for each row. So, you can use something like this for email alert row template -
```
<p> This is an event {alert_start_time} </p>
```

In the email body, you should see something like -
```
This is an event 2024-12-02T11:25:40
\n
This is an event 2024-12-02T11:26:40
\n
This is an event 2024-12-02T11:27:40
\n
...
```

The `\n` is automatically added to the last for email body, I will fix that shortly.

**Comment by gaby** [comment]
@Subhra264 The problem with `alert_start_time` is that it's not real-time. That's the time when O2 saw the data, in my case the data is batched and goes through vector. Using `_timestamp` lets me correlate when the event really happened.

The field should be rendered with whatever time zone O2 is running on at the moment.

**Comment by prabhatsharma** [comment]
Renewing it lin whatever time zone O2 is running could be a problem.b while in many cases it would yield the expected result, but not in all. If an O2 installation is being used by folks in multiple time zones this is a problem.

**Comment by gaby** [comment]
That data is not stored per users, so i'm not sure how O2 is going to do it per user.

**Comment by hengfeiyang** [comment]
@gaby @Subhra264 the `alert_start_time` and `alert_end_time` is the time range of the matched events. if you want a time when the alert evaluated, yes, there is no the variables. 

What about we add two new variables?
- alert_trigger_time: micro_seconds
- alert_trigger_time_str: format string like `2024-12-02T11:25:40`

**Comment by gaby** [comment]
> @gaby @Subhra264 the `alert_start_time` and `alert_end_time` is the time range of the matched events. if you want a time when the alert evaluated, yes, there is no the variables.
> 
> What about we add two new variables?
> 
> * alert_trigger_time: micro_seconds
> * alert_trigger_time_str: format string like `2024-12-02T11:25:40`

That works 💪

**Comment by Subhra264** [comment]
In that case I am closing this issue, as all the mentioned issues are fixed and merged. Feel free to reopen if I am missing anything.

**Comment by gaby** [comment]
@Subhra264 Thanks! Will report back once a new release is out. So I can try them on my instance 💪
