### ISSUE TITLE
Search Management record the slow query

### ISSUE THREAD

**Issue by domyway** [openobserve/openobserve#5002]
### Which OpenObserve functionalities are the source of the bug?

dashboards

### Is this a regression?

Yes

### Description

search Management do not show backgournd group of querier when I set ZO_NODE_ROLE_GROUP interactive/background for two group querier

### Please provide the version you discovered this bug in (check about page for version information)

```true
Commit: openobserve-enterprise-dev:v0.13.1-rc1-1f35ce5
```

**Comment by hengfeiyang** [comment]
I checked code, it should work, let's confirm that again.

**Comment by domyway** [comment]
> dashboard

c
