### ISSUE TITLE
Can't login UI by the OpenObserve Router

### ISSUE THREAD

**Issue by yzhengwei** [openobserve/openobserve#5046]
I cannot login UI by the OpenObserve Router, but I can login by the OpenObserve Ingester or OpenObserve Querier.  When i use OpenObserve Querier, a serious delay occurs in the queried data, and the newly captured data cannot be displayed.  However, I can query the latest data by OpenObserve Ingester.  Why?

**Comment by hengfeiyang** [comment]
1. please check your router configure and logs, is there any error report? if it connect to same database, it should't happen.
2. sounds you cluster have issue, they can't be known each other. please check your etcd / nats setting, confirm they both connect to same etcd / nats.

**Comment by yangzw1024** [comment]
I know this because I set ZO_HTTP_ADDR and ZO_GRPC_ADDR to 0.0.0.0, and when I set these, ingester and querier are working properly, but the router cannot login.

**Comment by hengfeiyang** [comment]
Yes, you can set it to empty, or set it to a fix ip. it will work. `0.0.0.0` is a problem.
