### ISSUE TITLE
Variable Not Working in LIMIT for Custom SQL in Dashboard

### ISSUE THREAD

**Issue by LeoLawes** [openobserve/openobserve#5063]
### Which OpenObserve functionalities are the source of the bug?

dashboards

### Is this a regression?

Yes

### Description

I have an dashboard written with custom SQL to generate tables, where a variable is used to control the number of returned rows. The SQL is roughly like `select xxx from xxx order by xxx limit $limit` Previously, both querying and editing worked fine, but after updating to the latest version, it still allows querying but displays a prompt saying 'Please add valid query syntax' when I try to edit. Is this a bug or a feature?
![20241114155929](https://github.com/user-attachments/assets/cc583a18-4f06-4159-bd76-8f72b1c627ab)
(It throws this error when I try to make modifications.)
![20241114155449](https://github.com/user-attachments/assets/426cff48-5cb7-4fd8-bd0a-4cf2af9a75ed)
(It’s still usable in the https://cloud.openobserve.ai)

### Please provide the exception or error you saw

```true
My previous dashboard queries using similar syntax still work fine, but it throws an error when I try to make modifications.
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.13.1-rc3
Commit Hash: 9298a663fb2882ed9a7757adfea9e3a19e5682c3
Build Date: 2024-11-08T05:22:48Z
```

**Comment by ktx-kirtan** [comment]
@LeoLawes What was the previous version where it worked? And the current version?

**Comment by LeoLawes** [comment]
@ktx-kirtan My current version is v0.13.1-rc3. I'm not sure what the exact version was before, but the current format is still allowed in https://cloud.openobserve.ai/, where the version is v0.12.1
