### ISSUE TITLE
How to get a higher compression rate ? 

### ISSUE THREAD

**Issue by yzhengwei** [openobserve/openobserve#5067]
My log is json format like nginx. openobserve shows ingested data 597GB and compressed data 51GB.  The compression rate is only about 11x, Why?

**Comment by hengfeiyang** [comment]
That is based on your data. it will have better compress ratio if most part is same. what is your data like?

**Comment by yangzw1024** [comment]
> That is based on your data. it will have better compress ratio if most part is same. what is your data like?

My log is like this:

```json
{
	"_timestamp": 1731573417031000,
	"appname": "pictor",
	"authority": "api2.xxxx.com",
	"bytes_received": 1404,
	"bytes_sent": 64,
	"downstream_local_address": "10.67.47.74:80",
	"downstream_remote_address": "103.195.24.180:55262",
	"duration": 7,
	"env": "prod",
	"from": "collector",
	"groupname": "ops",
	"host": "ops-pictor-ubuntu-prod-l9hx4hqx",
	"logfilename": "stdout",
	"method": "POST",
	"path": "/config/page/url/ecpm/get?trace_id=88fac348dd8b4e94b2aabe3510d54ec6",
	"protocol": "HTTP/1.1",
	"request_id": "99e3c536-1e54-44f5-b7aa-b305bcb63c98",
	"response_code": 200,
	"response_flags": "-",
	"route": "digest",
	"upstream_cluster": "ops-turbo-sg2-prod-server_80",
	"upstream_host": "10.120.53.244:8540",
	"upstream_local_address": "10.67.47.74:47276",
	"upstream_service_time": "5",
	"user_agent": "okhttp/4.10.0",
	"x_forwarded_for": "103.195.24.180"
}
```
Is the compression ratio higher for longer fields?

**Comment by prabhatsharma** [comment]
It's not about longer fields. It's about how much repeatability is present in the field values. e.g. method field should have very high compression. Also, what is the size of each parquet file in your storage? The bigger the individual files are, higher the compression rate. You can try setting higher values for `ZO_COMPACT_MAX_FILE_SIZE` to get higher compression.

**Comment by yangzw1024** [comment]
> It's not about longer fields. It's about how much repeatability is present in the field values. e.g. method field should have very high compression. Also, what is the size of each parquet file in your storage? The bigger the individual files are, higher the compression rate. You can try setting higher values for `ZO_COMPACT_MAX_FILE_SIZE` to get higher compression.

I didn't set ZO_COMPACT_MAX_FILE_SIZE, and file sizes in S3 now range from 20MB to 150MB

**Comment by hengfeiyang** [comment]
You can try set it to 1GB
```
ZO_COMPACT_MAX_FILE_SIZE=1024
```
Please upgrade to `v0.13.1` then make this change.
