### ISSUE TITLE
order by _timestamp statement did not work completely

### ISSUE THREAD

**Issue by LeoLawes** [openobserve/openobserve#5070]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

![image](https://github.com/user-attachments/assets/cdfb3e12-69d4-49c0-b15a-14449e024baa)
↑ He implemented pagination using order by correctly, but within each page, the data is not sorted as specified by the order by clause.( v0.13.1-rc3)
> Version: v0.13.1-rc3
> Commit Hash: 9298a663fb2882ed9a7757adfea9e3a19e5682c3
> Build Date: 2024-11-08T05:22:48Z

---

![image](https://github.com/user-attachments/assets/2f80a7b0-cbe4-4121-a47f-a72319a8950d)
↑ In earlier versions, both pagination and the data within each page were sorted as specified by the order by clause.( v0.12.1)
> Version v0.12.1
> Commit Hash f8a27b5c0dc3376663efd1e9400fa2ad43edee9f
> Build Date 2024-10-10T08:40:19Z

Is this a feature? This doesn’t seem quite reasonable.

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.13.1-rc3
Commit Hash: 9298a663fb2882ed9a7757adfea9e3a19e5682c3
Build Date: 2024-11-08T05:22:48Z
```

**Comment by hengfeiyang** [comment]
Please try `ORDER BY _timestamp ASC` or `ORDER BY _timestamp DESC`

**Comment by hengfeiyang** [comment]
this is a bug, will fix it in next reelase.
