### ISSUE TITLE
gRPC service support using TLS with certification

### ISSUE THREAD

**Issue by hengfeiyang** [openobserve/openobserve#5228]
### Which OpenObserve functionalities are relevant/related to the feature request?

other

### Description

We are using gRPC without certification, we should add it.

### Proposed solution

Add certification support.

### Alternatives considered

-

**Comment by gaby** [comment]
@hengfeiyang I'm surprised this was added since TLS for HTTPS was rejected months ago 😂

**Comment by hengfeiyang** [comment]
Yeap. the HTTP you can use a proxy (nginx) to do that. but gRPC is internal communication. particularly the big customer ask for that.😁

**Comment by gaby** [comment]
@hengfeiyang That's what I do now, but NGINX adds overhead/latency. It also means running 2 containers.

Related: https://github.com/openobserve/openobserve/issues/2341

**Comment by hengfeiyang** [comment]
I know that, maybe we can add it later if more users ask for that.
