### ISSUE TITLE
Add fuzzy function to the UI search tips

### ISSUE THREAD

**Issue by hengfeiyang** [openobserve/openobserve#5281]
### Description

We added two new function `fuzzy_match` and `fuzzy_match_all`, need to add to the UI search page.

the detail is here: https://github.com/openobserve/openobserve/pull/5280

### Proposed solution

-

### Alternatives considered

-

**Comment by hengfeiyang** [comment]
@bjp232004 I need you help on this issue.

**Comment by bjp232004** [comment]
Sure I will add these on the syntax guide as well as auto suggestions in the editor.
