### ISSUE TITLE
With the new menu changes the view dashboard's sticky header is broken

### ISSUE THREAD

**Issue by ktx-kirtan** [openobserve/openobserve#5282]
### Which OpenObserve functionalities are the source of the bug?

dashboards

### Is this a regression?

Yes

### Description

![image](https://github.com/user-attachments/assets/9feb03ab-5ae3-4c89-b82f-31fa85a5bb2b)

**Comment by gaby** [comment]
@ktx-kirtan That scrollbar on the side menus looks awful 😆

**Comment by ktx-kirtan** [comment]
@gaby It just because of the inspect menu open. It will not be there in a normal view
