### ISSUE TITLE
Distinct stream should be merged periodically to improve search performance

### ISSUE THREAD

**Issue by domyway** [openobserve/openobserve#5290]
### Which OpenObserve functionalities are relevant/related to the feature request?

traces

### Description

distinct_values_traces_default do not merge periodically, search performance will be a issue when the stream data is increasing

### Proposed solution

merge periodically

### Alternatives considered

none

**Comment by hengfeiyang** [comment]
It's related to `ZO_DISTINCT_VALUES_HOURLY`

**Comment by hengfeiyang** [comment]
@YashodhanJoshi1 i will fix it soon
