### ISSUE TITLE
support no auth

### ISSUE THREAD

**Issue by erikwoo** [openobserve/openobserve#5314]
### Description

We are using istio authn wasm plugin to route http traffic to openobserve, so that we don't have to config every employee's credential in openobserve

### Proposed solution

make ZO_ROOT_USER_EMAIL and ZO_ROOT_USER_PASSWORD optional, so that ingester and querier do not need authoriztion

### Alternatives considered

add another option like ZO_AUTH_PASSTHROUGH

**Comment by prabhatsharma** [comment]
We are unlikely to do this for security reasons. Way too many people will enable it and risk their data being exposed. We have seen this happen with Elasticsearch a billion times. You can use the enterprise version of O2 to achieve the same functionality, which is free if you are ingesting data under 200 GB/Day.
