### ISSUE TITLE
Expanded user management for Open-source edition

### ISSUE THREAD

**Issue by rmnijgh** [openobserve/openobserve#5324]
### Which OpenObserve functionalities are relevant/related to the feature request?

login, dashboards, users

### Description

Currently it is not possible to create roles in OpenObserve for each user. I and the company I work for love OpenObserve but cant use it because our ISO certification and audits require our applications to have a sufficient user management with roles and permissions for each user.

There is only admin, and we can't give all our employees who aren't obligated to have full admin to have the admin role.

Request 1:
We would love to see a read-only / query role for these users so that they can view and search through logs. While some admins have the possibility to create/edit/delete users.

Request 2:
Easier way to add / unadd existing users to organizations.

Right now we can't officially use the application because of ISO certification requirements. This is a big blocker for especially European tech businesses that want to use this application in there infrastructure. 

### Proposed solution

Having more roles available by default. Or, the ability to make your own roles with adjustable permissions.

### Alternatives considered

n/a

**Comment by prabhatsharma** [comment]
You can use the enterprise version of O2 to get RBAC and SSO features. It's free if you are ingesting under 200 GB of data per day.

Organizations functionality is being reworked that will allow easier organization management. Should be available soon.

**Comment by rmnijgh** [comment]
Hi @prabhatsharma, what about the self hosted version? Is that also being worked on for this?

**Comment by prabhatsharma** [comment]
It is free to use the enterprise version for self-hosted if you are ingesting under 200 GB of data per day.

**Comment by gaby** [comment]
A docker-compose for running enterprise edition would be great to have.
