### ISSUE TITLE
Getting 2 popups in the UI when there is a 403 error 

### ISSUE THREAD

**Issue by nikhilsaikethe** [openobserve/openobserve#5328]
### Which OpenObserve functionalities are the source of the bug?

users, streams, functions, alerts, real user monitoring

### Is this a regression?

Yes

### Description

When the user is unauthorized getting two popups one is at the top and other is at the bottom 
only show the bottom pop up when the user is authorized

**Comment by ShyamOOAI** [comment]
Same is required on Dashboard, Roles and "User Group" Pages
