### ISSUE TITLE
Add "Export" to dashboards folder

### ISSUE THREAD

**Issue by gaby** [openobserve/openobserve#5345]
### Which OpenObserve functionalities are relevant/related to the feature request?

dashboards

### Description

Currently for backup/transfer it requires exporting each dashboard one by one.

At the folder level there's already an `Import` option, but there's no option for `Export`. This could be use for backing up your dashboards and making it easier to Share/Move to another OpenObserve instance.

### Proposed solution

At the folder level add an `Export` button that lets you either export all the dashboards in the folder, or select which ones to export together.

This output can then be used with the `Import` button in another OpenObserve instance.

### Alternatives considered

Exporting each dashboard one by one.

**Comment by gaby** [comment]
@ktx-kirtan I think this one is overcome by #5356 ? If so this can be closed and the feature added to that one

**Comment by ktx-kirtan** [comment]
True, closing
