### ISSUE TITLE
log field has unicode encoding handling

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#536]
### Which ZincObserve functionalities are the source of the bug?

log search

### Is this a regression?

No

### Description

Table view:

<img width="934" alt="image" src="https://user-images.githubusercontent.com/4242188/231018461-a59f8171-fcb2-4524-9c01-a6f8a03e6ec5.png">

JSON view:

<img width="924" alt="image" src="https://user-images.githubusercontent.com/4242188/231018586-ba46c90c-8f84-4ada-ba66-ef7ac70ff7d9.png">

**Comment by hengfeiyang** [comment]
@prabhatsharma I think this is not about frontend, it is original logs.
