### ISSUE TITLE
Pipeline- User is allowed to add pipeline with same name and same stream using API

### ISSUE THREAD

**Issue by neha00290** [openobserve/openobserve#5381]
### Which OpenObserve functionalities are the source of the bug?

users

### Is this a regression?

Yes

### Description

Steps
1. Create pipeline with same name and same stream multiple times using API for pipeline creation
2. Observe the pipeline UI

- [x] API allows create pipeline without name

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.14.0
Commit Hash: d4412c869b95a71a757812b2160eb51a91d5df85
Build Date: 2024-12-17T00:19:45Z
```

**Comment by taimingl** [comment]
@neha00290 Pipeline is identified by ID that they can have same names. I've added checks for existing pipeline with the same stream and empty name in the linked pr.
