### ISSUE TITLE
Logs: fuzzy_match_all search cause panic

### ISSUE THREAD

**Issue by neha00290** [openobserve/openobserve#5419]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

- [ ] First issue

Steps
1. Search for `SELECT * FROM "abc" WHERE fuzzy_match_all('f', 1)` 
2. Observe the UI

Actual result: Search this query causes panic

Expected result: Either the query to work or if incorrect, it should display error and not cause panic

- [ ] Second issue 

1. Enter SELECT * FROM "default" WHERE fuzzy_match(abc, '', 4) 
2. Observe if error displayed for this.

Actual result: No error displayed, indicating wrong query.

Expected result: Error to be displayed if query invalid

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.14.0
Commit Hash: 4ae10c0abf13d1ccae7098f7294c900e85eff3b4
Build Date: 2024-12-19T18:01:31Z
```

**Comment by hengfeiyang** [comment]
It paniced, but it is because of someone set one `int64` field as full text search field. we can run fuzzy on a `int64` field. let me add some limit, can set full text search on `int64` field. it only support `text` field.
