### ISSUE TITLE
openObserve UI SQL switch button lose data

### ISSUE THREAD

**Issue by LinPr** [openobserve/openobserve#5427]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

When I use the switch buttion of SQL,  it works well when i switch some text to SQL clause， but on the opposite， when I want to go back to see the original text and click SQL button again, the original text lost.
Hope this can be fixed , thanks!!!!!

### original data
![image](https://github.com/user-attachments/assets/60884662-a905-4bc6-ad52-85a4e0917e5f)

### after click SQL button
![image](https://github.com/user-attachments/assets/bce80475-06e3-4c1b-b15f-474ac0e48880)

### click again and wanna see original text, but there is nothing
![image](https://github.com/user-attachments/assets/312b22a2-a9a1-42cd-8bda-924285fc29a2)

**Comment by prabhatsharma** [comment]
This is the implemented desired behavior. SQL can be very complex, and going to standard mode may not always be possible, hence this behavior.
