### ISSUE TITLE
UI: Logs: Resizable column width for log search result

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#573]
### Which ZincObserve functionalities are relevant/related to the feature request?

logs search

### Description

Columns get their default width.

<img width="1405" alt="image" src="https://user-images.githubusercontent.com/4242188/231985233-51cdfbef-41a7-4e6a-ab1c-c45282acae86.png">

In order to better manage the real estate while log search, resizing the column would come in very handy.

### Proposed solution

As a user, I should be able to resize the columns to my liking.

### Alternatives considered

Just click on the row, to see the detail of the row in the side panel.

**Comment by bjp232004** [comment]
There is an open issue in quasar with implementing the drag and resize columns. Please find below the issue link to track. Till that time moving out this issue from the release.

https://github.com/quasarframework/quasar/issues/5115

Workaround: https://codepen.io/Hawkeye64/pen/dypyNWL
