### ISSUE TITLE
UI: Could not create web worker(s)

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#613]
### Which ZincObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

Getting below error in browser console.

```shell
Could not create web worker(s). Falling back to loading web worker code in main thread, which might cause UI freezes. Please see https://github.com/microsoft/monaco-editor#faq


You must define a function MonacoEnvironment.getWorkerUrl or MonacoEnvironment.getWorker
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
v0.4.1
```

**Comment by hengfeiyang** [comment]
fixed
