### ISSUE TITLE
Handle invalid json files in WAL

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#614]
### Which ZincObserve functionalities are the source of the bug?

log search

### Is this a regression?

No

### Description

- [x] If the ingester pod/node gets terminated for whatever reason while it has not written the WAL file completely, it may have invalid JSON data. 
- [x] Some data may be invalid and may cross the upper bounds of int64. This causes query failure in querying

Both of the above issues make the stream un-query-able.

**Comment by oasisk** [comment]
fixed
