### ISSUE TITLE
Suggestions for Alert module 

### ISSUE THREAD

**Issue by hanqian200705** [openobserve/openobserve#615]
### Which ZincObserve functionalities are relevant/related to the feature request?

alerts

### Description

Suggestions for Alert module :

- [x] 1. Template variables can use the values of multiple fields in SQL - covered as part of #824
- [x] 2. Both value and condition can be treated as variables - provide value of condition
- [x] 3. Time supports formatting, and a global time formatting environment variable can be defined for consistent formatting in all modules where time is displayed. - UTC
- [x] 4. The Alert module provides the most recent running logs or checks for configuration errors (such as SQL errors) upon saving, with direct prompts. - start & end time stamp  for every alert - mandatory 
- [ ] 5. Support for sending alert recovery reminders. - TBD
- [x] 6. Support for setting alert time periods. - Work Schedule based alerts - 0.5.5
- [x] 7. Support for quickly enabling/disabling alert settings. #1196
- [ ] 8. Configuration support import and export. - 0.5.5

### Proposed solution

no

### Alternatives considered

no

**Comment by muathendirangu** [comment]
@hengfeiyang I am interested in contributing to this feature, I have been able to run the product on my local dev and I have a mental model of the workflows within the repo, Just got here by filtering good first issue label, I would like to know what is done and where I can get started, thanks

**Comment by hengfeiyang** [comment]
@muathendirangu thank you, but most part already done in the PR #1973, after we make the new release, i will check that again which part haven't done then i will ping you.

**Comment by muathendirangu** [comment]
@hengfeiyang thanks for the update could you point me to issues that potentially no one has started working on I have a look

**Comment by hengfeiyang** [comment]
sure, let me check. Can you talk to me in our Slack?

**Comment by muathendirangu** [comment]
sure let me reach out

**Comment by hengfeiyang** [comment]
we will track it in #1970
