### ISSUE TITLE
Avoid small files in the bucket

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#617]
### Which ZincObserve functionalities are relevant/related to the feature request?

streams, ingestion

### Description

Partitioning with not much data can lead to too many small files in the bucket which can be extremely inefficient:

<img width="1457" alt="image" src="https://user-images.githubusercontent.com/4242188/233834009-3cf43fb8-b5d3-44d9-8419-f48dddbd7da3.png">

### Proposed solution

We should be able to specify that the resulting file size should be larger than 5 MB for the partitioning to be enabled on the specified field.

### Alternatives considered

manually figure out if partitioning helps.

**Comment by hengfeiyang** [comment]
It shows that you shouldn't use those fields as the partition key. You have a tiny data size no need to set an additional partition key like `kubernetes_host`. Just delete the partition key. 

And we will support a custom time range as the partition key, default 1 hour.
