### ISSUE TITLE
Functions : build for linux_musl fails because of mlua with luau feature 

### ISSUE THREAD

**Issue by oasisk** [openobserve/openobserve#624]
### Which ZincObserve functionalities are the source of the bug?

functions

### Is this a regression?

Yes

### Description

 build for linux_musl fails because of mlua with luau feature 

### Please provide the version you discovered this bug in (check about page for version information)

```true
v0.4.1
1020e09a076d5aca53d1fc9a771e39bb2efa13de
```

**Comment by hengfeiyang** [comment]
we dropped lua support
