### ISSUE TITLE
Reduce whitespace for side menu

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#662]
### Which ZincObserve functionalities are the source of the bug?

home

### Is this a regression?

Yes

### Description

<img width="75" alt="image" src="https://user-images.githubusercontent.com/4242188/235390904-5e6cf678-995f-4fcc-8c47-e75bc376f52c.png">

**Comment by bjp232004** [comment]
Right now it's aligned with logo and menu icon but once we remove space it will look like: 

![image](https://user-images.githubusercontent.com/551527/235393549-3fcf4cfc-320a-461e-adf1-2b442b94720c.png)
