### ISSUE TITLE
URL sharing of logs page

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#680]
### Which ZincObserve functionalities are relevant/related to the feature request?

logs search

### Description

Currently, logs page has only organization in the URL. It does not contain the details of stream name, query, and time window that can allow sharing of logs page with anyone.

### Proposed solution

Add stream name, query and time window in URL that will allow sharing of the logs page and get the desired page

### Alternatives considered

None

**Comment by lileiseven** [comment]
Has this feature been released yet? @prabhatsharma

**Comment by prabhatsharma** [comment]
> Has this feature been released yet? @prabhatsharma

Not yet

**Comment by omkarK06** [comment]
This issues has been resolved by #947 #1146
