### ISSUE TITLE
Is there any percentile, quantile function for SQL query like elasticsearch , bigquery, influxdb?

### ISSUE THREAD

**Issue by WENPIN1** [openobserve/openobserve#684]
### Which ZincObserve functionalities are relevant/related to the feature request?

functions, metrics

### Description

Is there any percentile, quantile function for SQL query like elasticsearch , bigquery, influxdb?
SQL Avg() is not enough.
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-percentile-aggregation.html

Thank you!

-Patrick

### Proposed solution

N/A

### Alternatives considered

N/A

**Comment by hengfeiyang** [comment]
We are working on metrics part and will be compatible with Prometheus API & PromQL. then you can use metrics to do those.

**Comment by WENPIN1** [comment]
However, a similar function  (percentile, quantile) on SQL query might be useful and straightforward.
Because many TSDB have this function builtin.


Thank you!

**Comment by hengfeiyang** [comment]
Is this useful for you? we use datafusion, so support all functions by datafusion.

https://arrow.apache.org/datafusion/user-guide/sql/aggregate_functions.html#approx-percentile-cont
