### ISSUE TITLE
Import grafana dashboards into ZO dashboards

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#689]
### Which ZincObserve functionalities are relevant/related to the feature request?

dashboards

### Description

Users migrating from Grafana should be able to export their existing dashboards into ZO.

### Proposed solution

This might not be possible for all the scenarios since grafana supports multiple sources. We should be able to import all the prometheus based dashboards from grafana.

### Alternatives considered

Build dashboards from scratch.

**Comment by gaby** [comment]
This would be really cool feature. Another thing to consider is Elasti Beats dashboards. I currently use those heavily. Especially Metricbeat, Filebeat, and Auditbeat.

**Comment by prabhatsharma** [comment]
By elastibeats dashboards you mean kibana/Opensearch dashboards. Right?

**Comment by gaby** [comment]
@prabhatsharma Kibana doesnt come bundled with Beats dashboards. They are hosted on the Beats repo as .json files. For example:

https://github.com/elastic/beats/tree/main/x-pack/metricbeat/module/aws/_meta/kibana/7

https://github.com/elastic/beats/tree/main/x-pack/filebeat/module/aws/_meta/kibana/7

Although now that I look at it, they do have a ton of files, it's not as clean as Graphana dashboards that are mostly a single file.

**Comment by prabhatsharma** [comment]
https://github.com/openobserve/openobserve/discussions/2885

Initial work here - https://github.com/kubserv/converter

**Comment by gaby** [comment]
> #2885
> 
> Initial work here - [kubserv/converter](https://github.com/kubserv/converter)

Looks awesome!

**Comment by gaby** [comment]
@prabhatsharma Any plans to make the Grafana plugin open source?

The community could help with maintainance and getting it signed/publish in the grafana store.

**Comment by prabhatsharma** [comment]
No plans to make grafana plugin open source.
