### ISSUE TITLE
Background Image for Query Editor and VRL Editor

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#690]
### Which ZincObserve functionalities are relevant/related to the feature request?

logs search

### Description

Query Editor and VRL editor label text takes 1 line. This is valuable real estate. We should be able to save this one line

<img width="1504" alt="image" src="https://user-images.githubusercontent.com/4242188/236383160-b9721e8b-8061-46e3-b061-a86829f1b710.png">

### Proposed solution

Have a background image for Query Editor and VRL editor which says `Query Editor` and `VRL Editor`

### Alternatives considered

Do nothing and lose a line of real estate :-(

**Comment by gaby** [comment]
Any idea why the "Fields" toggle was removed? It was useful.

**Comment by prabhatsharma** [comment]
> Any idea why the "Fields" toggle was removed? It was useful.

The screen was getting crowded. Trying to avoid that. And you could always remove fields manually too if you want.

**Comment by neha00290** [comment]
this is tested. works fine. closing the same
