### ISSUE TITLE
Dynamic sidebar reload by query results

### ISSUE THREAD

**Issue by exgame** [openobserve/openobserve#699]
### Which ZincObserve functionalities are relevant/related to the feature request?

logs search

### Description

When querying data from logs, sidebar doesn't automatically refresh and show top 10 fields. It is independent and shows only global top 10 list for fields.

### Proposed solution

I would be nice to see updated sidebar while querying logs. For example, you select server1 and sidebar reloads to show latests tops 10 domains for this server.

### Alternatives considered

-

**Comment by gaby** [comment]
I noticed this too, I thought it was an issue on my data.

**Comment by hengfeiyang** [comment]
Yes, i think we should improve this, The top n values should based on the query condition. for example:

the query editor input: `kubernetes_namespace_name='ziox-alpha1'`, then you click the field `pod_name`, it should list the top values of `namespace ziox-alpha1`.

**Comment by hengfeiyang** [comment]
@oasisk @omkarK06 I checked our code, i think to fix this issue we only need to pass the `sql` when we fire the `_values` request. and I saw we already sent the `sql` but it always be `select * from table`, any consideration for that?

I think we should change it to the query `sql` then it will be fixed.

**Comment by oasisk** [comment]
@omkarK06  ui should pass proper value for  "sql" parameter for _values api
