### ISSUE TITLE
Syslog server

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#701]
### Which ZincObserve functionalities are relevant/related to the feature request?

logs search

### Description

Ingestion of syslog logs from network devices today requires setting up a proxy fluentbit/vector server that will accept the requests and forward them to ZO. This can be rather inconvenient.

### Proposed solution

ZO should be able to act as a syslog server. Following should be brief specs:

1. Listen on UDP & TCP port 5514
2. User should be disabled by default. It should be possible to enable it using the UI
3. User should be able to specify IP addresses or subnet masks to limit from where the syslog logs can be accepted.

### Alternatives considered

set up a fluentbit / vector server to accept logs and forward to ZO.

Tasks:

- [x]  Server implementation - accept stream name , org name , subnets
- [x] API to toggle syslog ingestion
- [x] UI development

**Comment by gaby** [comment]
I currenrly do this using Vector -> ZO. I bundle syslog before sending it, so having vector be able to manipulate the logs is convinient.
