### ISSUE TITLE
Store alerts that have been fired for reference

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#705]
### Which OpenObserve functionalities are relevant/related to the feature request?

alerts

### Description

Scheduled or realtime alerts are currently in a fire and forget fashion. What this means is that we do not maintain the knowledge/history of any alerts which the user may want to refer in future. 

### Proposed solution

- [ ] We should store the history of all triggered alerts in a stream with name "alerts-history" or metadata store
- [ ] Provide a UI to see the list of alert history

### Alternatives considered

none

**Comment by tleerai** [comment]
This would be great, to see the various permutations of an alert, per server etc, which are either actively being triggered now or have been historically. This would give the interface to acknowledge or permanently silence or un-silence an alert for a specific server that you know is a problem, such as a server being disabled for maintenance etc. It would be good to know how long an alert has been active for, how long it's been unacknowledged, etc this would create a pathway toward having alert escalation policies.

**Comment by Subhra264** [comment]
This was completed in #3086. If the `ZO_USAGE_REPORTING_ENABLED = true` is set, then apart from the `usage` stream (that reports user generated events e.g. search, ingestion etc.), `triggers` stream is also created under the `_meta` org (can be customized by setting the `ZO_USAGE_ORG` env). `triggers` stream contains all the trigger events for alerts as well as reports. You can also set the `ZO_USAGE_BATCH_SIZE` (default batch size is `2000`) and `ZO_USAGE_PUBLISH_INTERVAL` (default interval is `600` in seconds) after which the events should be ingested into `usage` and `triggers` streams. Events are published into those streams if either the batch size is full or the interval is ticked.
