### ISSUE TITLE
Exponential loading of records on log search

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#731]
### Which ZincObserve functionalities are relevant/related to the feature request?

logs search

### Description

Currently, log search returns only 150 records in results area. 150 results might be insufficient in many cases. User has an option to scroll down and once the user scrolls down, ZO returns another 150 results and so on. If I want to see/download 15,000 records I am going to have a very difficult time scrolling and getting results 100 times.

### Proposed solution

I propose that we download records in exponentially increasing order.

e.g. 
1. Search results returns 150 records.
2. Next scroll returns 300 records
3. Next scroll returns 600 records
4. Next scroll returns 1,200 records
5. Next scroll returns 2,400 records
6. Next scroll returns 4,800 records
7. Next scroll returns 9,600 records
8. Next scroll returns 19,200 records

and so on.

### Alternatives considered

keep scrolling

**Comment by gaby** [comment]
I have run into this issue, it gets worst if auto-refresh is enabled.
