### ISSUE TITLE
Trigger an alert manually

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#743]
### Which ZincObserve functionalities are relevant/related to the feature request?

alerts

### Description

triggers are meant to be passed on to external systems to perform a certain activity (send email, trigger a workflow, etc). There is no way to test these external systems today. We need a way to trigger alerts manually.

### Proposed solution

Have an API to trigger the alert.
Have a UI to trigger the alert.

### Alternatives considered

none

**Comment by ansrivas** [comment]
API is implemented here - https://github.com/zinclabs/zincobserve/pull/789

**Comment by gaby** [comment]
@ansrivas Only thing missing is a button in the UI to trigger that endpoint.

**Comment by bjp232004** [comment]
This will be covered in alert redesign.

**Comment by hengfeiyang** [comment]
done
