### ISSUE TITLE
Audit trail storage

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#759]
### Which ZincObserve functionalities are relevant/related to the feature request?

streams, other

### Description

Currently, we do not track data around who made what API calls. Having this information will be helpful in understanding any changes made to the system and who made it.

### Proposed solution

We create a meta stream by the name `audit`  which will have the following fields:

1. _timestamp
2. API called
3. API caller
4. Request URL
5. Request body
6. Response body
7. organization
8. ResponseStatus
9. source_ip

This will not be applicable to ingestion APIs

A middleware should be able to achieve this.

### Alternatives considered

none

**Comment by ansrivas** [comment]
Related https://github.com/openobserve/openobserve/pull/3211
