### ISSUE TITLE
Possibility to delete unused labels from field list sidebar

### ISSUE THREAD

**Issue by exgame** [openobserve/openobserve#761]
### Which ZincObserve functionalities are relevant/related to the feature request?

logs search

### Description

Possibility to delete unused labels from field list sidebar

### Proposed solution

Possibility to delete unused labels from field list sidebar

### Alternatives considered

It could disappear if no data collected after certain time frame.

**Comment by hengfeiyang** [comment]
For now, actually, we don't know which fields are no long used. this is a problem, but there is no good solution.

if you want to delete the old field, the only way is to delete the stream for now.

**Comment by prabhatsharma** [comment]
we can allow to delete the fields in stream details side panel.

**Comment by mbonsack** [comment]
A more elegant solution might be to provide an option to hide fields that are not populated by the events in the current search window.  They would still be in your database, but by default would simply not be shown.  This can be useful if you want to keep the list intact, but not "clutter" the interface if, say, you do a 5 minute search on data that is normally searched hourly, and only a small subset of the normal set of fields are populated.

**Comment by hengfeiyang** [comment]
We will implement this:

- [x] support in API
- [x] support in UI
- [x] Zinc-cp API Implementation

**Comment by neha00290** [comment]
testing complete. closing this ticket
