### ISSUE TITLE
Query Editor history

### ISSUE THREAD

**Issue by exgame** [openobserve/openobserve#762]
### Description

Doing a lot of specific queries takes some time, it would be nice to get some kind of history.

### Proposed solution

It would be nice to see history of past query editor entires.

### Alternatives considered

List of last few queries

**Comment by hengfeiyang** [comment]
@prabhatsharma Maybe this will like Grafana query history

**Comment by prabhatsharma** [comment]
I am thinking that we should first implement https://github.com/zinclabs/zincobserve/issues/759 . This could be base for history, versioning, and security of almost everything.

**Comment by hengfeiyang** [comment]
done
