### ISSUE TITLE
PromQL Sample Queries for testing

### ISSUE THREAD

**Issue by ktx-kirtan** [openobserve/openobserve#781]
### Which ZincObserve functionalities are relevant/related to the feature request?

dashboards

### Description

Please provide some example queries which we can use to test the dashboard with promQL for different types of result types.

### Proposed solution

-

### Alternatives considered

-

**Comment by hengfeiyang** [comment]
You can check this issue: https://github.com/zinclabs/zincobserve/issues/582

**Comment by prabhatsharma** [comment]
Some examples at https://prometheus.io/docs/prometheus/latest/querying/examples/
