### ISSUE TITLE
PromQL - Multiple charts

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#799]
### Which ZincObserve functionalities are relevant/related to the feature request?

metrics

### Description

Currently a single PromQL query can be used for one panel. If I want to use use 2 promql queries to be charted on a single panel that is currently not possible. e.g. query would be to get p95 and p99 latencies:

p95
```ruby
histogram_quantile(0.95, sum(irate(zo_http_response_time_bucket{namespace="ziox-alpha1"}[5m])) by (le, exported_endpoint))
```

p99
```ruby
histogram_quantile(0.99, sum(irate(zo_http_response_time_bucket{namespace="ziox-alpha1"}[5m])) by (le, exported_endpoint))
```

### Proposed solution

Provide a mechanism to specify and run multiple queries for each panel.

### Alternatives considered

use multiple panels

**Comment by ktx-kirtan** [comment]
Multi-Query is now available. When you switch to PromQL mode, you will now have an option to add more queries and the data will me merged to show in the chart

![image](https://github.com/openobserve/openobserve/assets/124270523/e7abc159-5efc-4a22-93ca-be907bbeb788)

You can also specify the different legend names from the config for each query:

![image](https://github.com/openobserve/openobserve/assets/124270523/29d6b127-1946-46b1-be56-81ee3f90afaf)

You can use the format like `p95-{exported_endpoint}` for query 1 and `p99-{exported_endpoint}` for query 2
