### ISSUE TITLE
Timeline is hiding beneath the legend

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#801]
### Which ZincObserve functionalities are the source of the bug?

dashboards

### Is this a regression?

Yes

### Description

Can't see timeline if there are many legend items

<img width="1492" alt="image" src="https://github.com/zinclabs/zincobserve/assets/4242188/d8f2957a-bf5f-42d6-b53f-848eb27780d9">

**Comment by ktx-kirtan** [comment]
Open issue in plotly: https://github.com/plotly/plotly.js/issues/1199

**Comment by ktx-kirtan** [comment]
With the implementation of the echarts, this issue is solved and the timeline doesn't overlap with the legends.

Fixed with https://github.com/openobserve/openobserve/pull/1468
