### ISSUE TITLE
No vertical scrollbar when many items in legend

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#802]
### Which ZincObserve functionalities are the source of the bug?

dashboards

### Is this a regression?

Yes

### Description

<img width="756" alt="image" src="https://github.com/zinclabs/zincobserve/assets/4242188/d696383f-822a-4616-9fbe-997bd031b9aa">

**Comment by ktx-kirtan** [comment]
Issue from plotly. Doesn't seem to have any solution at the moment

**Comment by ktx-kirtan** [comment]
With the implementation of the echarts, this issue is solved and longer legends are trimmed and shown as a tooltip on hover.

Fixed with #1468
