### ISSUE TITLE
field variables for dashboards

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#805]
### Which ZincObserve functionalities are relevant/related to the feature request?

dashboards

### Description

Currently if want CPU, and memory charts to be shown from multiple namespaces in a Kubernetes cluster, I cannot do it in a single dashboard. I will need to create a new dashboard fore each namespace.for

### Proposed solution

Have field variables for dashboard that can pickup data which can then be passed as values.

### Alternatives considered

create a dashboard for each namespace.

**Comment by gaby** [comment]
This is how i current do this in Kibana: https://www.elastic.co/blog/interactive-inputs-on-kibana-dashboards

**Comment by ktx-kirtan** [comment]
@prabhatsharma We have discussed this today with the team and we are starting with the query type variable first
