### ISSUE TITLE
Email Regex for ZO_ROOT_USER_EMAIL is overly restrictive

### ISSUE THREAD

**Issue by jabbrwcky** [openobserve/openobserve#807]
### Which ZincObserve functionalities are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

When deploying zincobserve via Helm the components failed to come up complaining that `ZO_ROOT_USER_EMAIL` and `ZO_ROOT_USER_PASSWORD` should be set.

After checking possible causes (see [Slack discussion](https://zincobserve.slack.com/archives/C04QC53TPD2/p1685023671818659)) I found that the issue is cause by the [regex](https://github.com/zinclabs/zincobserve/blob/7cc730a12f7af63ef4ee3da6392e7d08a0f87f58/src/job/mod.rs#L33) that checks the email does not match emails of the form `foo-bar@example.com`.

The cause is a little obscured by the error message that prints the same text for the three conditions:
* regex parsing of email fails
* email is empty
* password is empty

### Please provide a link to a minimal reproduction of the bug

https://regex101.com/r/Af7NbR/1

### Please provide the exception or error you saw

```true
Please set root user email-id & password using ZO_ROOT_USER_EMAIL & ZO_ROOT_USER_PASSWORD enviornment variables
```

### Please provide the version you discovered this bug in (check about page for version information)

```true
public.ecr.aws/zinclabs/zincobserve-dev:v0.4.3-23b3a0e-amd64
```

### Anything else?

The space of valid email adresses according to RFC is not validatable by regex, so the best solution IMO would be to relax the regex so it permits plausible email addresses and separate the error message into missing data and failed validation (there was a lot of head scratching going on before finding the cause :))

**Comment by prabhatsharma** [comment]
Need to fix https://github.com/zinclabs/zincobserve/blob/7cc730a12f7af63ef4ee3da6392e7d08a0f87f58/src/job/mod.rs#L33
