### ISSUE TITLE
option to provide legend on right hand side instead of bottom of the pane.

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#812]
### Which ZincObserve functionalities are relevant/related to the feature request?

dashboards

### Description

It is not always convenient to have legend for panel at the bottom. Sometimes it makes more sense to have it on right side of the chart as well.

### Proposed solution

Provide an option to have legend on the right side.

### Alternatives considered

n/a

**Comment by ktx-kirtan** [comment]
Kept it at the bottom for the PromQL mode only, as we have very large legends names. For SQL it is on the right side. If they are on the right, they are expanding to overlap the chart and sometimes hiding the full chart as well.
