### ISSUE TITLE
Incomplete series name on tooltip makes it difficult to understand the value, decimal precision

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#813]
### Which ZincObserve functionalities are the source of the bug?

dashboards

### Is this a regression?

Yes

### Description

1. It would help to have full value of the series.
2. It would help to reduce the precision from current 6 digits to max 2 digits (can be lower if the significant values do not exist. e.g. 2.1 or 2.01 but not 2.10).

<img width="1171" alt="image" src="https://github.com/zinclabs/zincobserve/assets/4242188/59861dd5-95c9-481c-9ca6-a9263c9c3261">

**Comment by ktx-kirtan** [comment]
With the long lables, it will look like this: 

![image](https://github.com/zinclabs/zincobserve/assets/124270523/b70f935d-559d-4455-bae8-7972a5a5f8b1)
