### ISSUE TITLE
Alerts Template requires more Variables

### ISSUE THREAD

**Issue by eddyyuen** [openobserve/openobserve#824]
### Which ZincObserve functionalities are relevant/related to the feature request?

alerts

### Description

Alerts Template requires more Variables
My sql is
 ```
select count(1) as errcnt from 'nginx' where status >=  500
```
So All Variables just like :

stream_name
org_name
alert_name
alert_type
timestamp
 **start_time
end_time
 errcnt**

And our alerts should be 
```
{errcnt }  5xx errors have occurred between {start_time} and  {end_time}
```

### Proposed solution

none

### Alternatives considered

none

**Comment by jurgenhaas** [comment]
I'd also need variables from the row which triggered the alert, like e.g. `instance` when alerting based on metrics in real-time.

**Comment by marksugar** [comment]
```
str_match(log, 'error')
```
If you match a log field that contains an error, you can emit the contents of the most recent log that contains the error

Now the template can only prompt simple data
![1692545278695](https://github.com/openobserve/openobserve/assets/21120630/cfd5abe5-7579-426d-a1b9-dcc352a0301f)

**Comment by luciferhs** [comment]
logs alert  Required variables:

Alarm topic

Alarm conditions

Alarm time

Business Name

Namespaces

Alarm message

Recovery time

**Comment by luciferhs** [comment]
> ### Which ZincObserve functionalities are relevant/related to the feature request?
> alerts
> 
> ### Description
> Alerts Template requires more Variables My sql is
> 
> ```
> select count(1) as errcnt from 'nginx' where status >=  500
> ```
> 
> So All Variables just like :
> 
> stream_name org_name alert_name alert_type timestamp **start_time end_time errcnt**
> 
> And our alerts should be
> 
> ```
> {errcnt }  5xx errors have occurred between {start_time} and  {end_time}
> ```
> 
> ### Proposed solution
> none
> 
> ### Alternatives considered
> none

Opening this post is all about May, and without these features, it is difficult for everyone to truly use them in the generation environment. Please add these features, which is urgent for many people. Thank you

**Comment by abrowne2** [comment]
This is a deal breaker for my team. Not going with openobserve because of lack of functionality with alerts.
Wish we had the row that triggers the alert.

**Comment by prabhatsharma** [comment]
We are working on multiple improvements to alerts. This and more features around alerts will be available by mid Dec.

**Comment by CrisLi** [comment]
Would that possible to use the matched alert condition result as variables?

For example, I have a real-time alert that queries a `Log` type `stream`. Currently, once there is a matched result, one alert is sent. My log would like `{"app":"xyz-service", "log", "java.lang.OutofMemoryError happened", "ts": "2023-12-11T00:00:12"}`. Then if we can have a template like `${app} has OOM error at ${ts}` would be great.

<img width="1560" alt="image" src="https://github.com/openobserve/openobserve/assets/360767/86eabdf2-dd6f-4439-9571-b7ca8706641a">

**Comment by hengfeiyang** [comment]
@CrisLi it is already done in dev tag.

**Comment by CrisLi** [comment]
> @CrisLi it is already done in dev tag.

looking forward for the next release 😁
