### ISSUE TITLE
Suggest modifying the add and subtract icons on the UI page

### ISSUE THREAD

**Issue by cooting-cn** [openobserve/openobserve#837]
### Description

![4a8ca4f72d9ee0896b3dec744e00a24](https://github.com/zinclabs/zincobserve/assets/131133433/8d12876e-a34d-467f-9eca-166efa4fcaf4)
加减图标容易引起误导,认为是增加和删除

The add and subtract icons can easily cause confusion, as they may be mistaken for adding and deleting.

### Proposed solution

修改下图标样式,更加看上去清晰

Change the icon style in the image below to make it look clearer.

### Alternatives considered

更改图标

Change Icon

**Comment by hanqian200705** [comment]
icon suggestion:
=  , ≠
<img width="166" alt="image" src="https://github.com/zinclabs/zincobserve/assets/4269408/476a4fd8-8ca7-4384-b990-6f1ae9ce7bff">
