### ISSUE TITLE
[UI] The left menu bar is expected to be expand/close by buttons

### ISSUE THREAD

**Issue by Mashull** [openobserve/openobserve#842]
version: 0.4.5

### Description

The current switching menu requires the mouse to move to the left sidebar to switch. The expanded menu bar will block the main display panel, which makes me feel very strange, and the expansion animation is not smooth, so I hope the left side menu bar can provide a button of switching the expand/closed state, and the main display area can be displayed adaptively.

----
当前切换菜单，需要鼠标移动到左侧栏进行切换，展开的菜单栏会挡住主要的显示面板，这让我感觉非常的奇怪，并且展开动画并不流畅,所以我希望左侧菜单栏可以提供一个切换展开/收缩状态的机制，并且主显示区域可以进行自适应展示.

### Proposed solution

provide a button of switching the expand/closed state

### Alternatives considered

nothing

**Comment by prabhatsharma** [comment]
What do you think of this design like in gmail? 
![image](https://github.com/zinclabs/zincobserve/assets/4242188/76db4a4a-76e9-40db-9190-bdd4c40e52fb)

**Comment by Mashull** [comment]
> What do you think of this design like in gmail? ![image](https://user-images.githubusercontent.com/4242188/241825753-76db4a4a-76e9-40db-9190-bdd4c40e52fb.png)

I think this design simple and effective, such a design can reduce some unnecessary interactive operations and visual elements.

**Comment by fanbuz** [comment]
@prabhatsharma I think this design is simple and effective, can reduce some unnecessary interactive operations and visual elements, and will not interfere too much with the main panel area.
