### ISSUE TITLE
[UI]Firefox Incompatible，three scroll bars appear in the log page

### ISSUE THREAD

**Issue by e8tg001** [openobserve/openobserve#844]
### Which ZincObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

Open through Firefox under Windows 10 and scroll down, three scroll bars appear in the log interface, and blank bars appear at the top of the chart;
![4522](https://github.com/zinclabs/zincobserve/assets/40289299/1ea904d4-28dd-403e-9f1f-90c1a08387b4)

System: Windows 10
Firefox version:107.0.1

### Please provide the version you discovered this bug in (check about page for version information)

```true
v0.4.5
```

**Comment by prabhatsharma** [comment]
Can you update firefox.

This is on my firefox 112

<img width="1601" alt="image" src="https://github.com/zinclabs/zincobserve/assets/4242188/f3d207bd-4822-40f2-943a-906fcc70cac8">

**Comment by e8tg001** [comment]
For some reason, I can't upgrade the firefox version, and if the latest firefox version has no this problem, you can consider closing this issue;
