### ISSUE TITLE
[UI]click to open a log,results open multiple

### ISSUE THREAD

**Issue by e8tg001** [openobserve/openobserve#846]
### Which ZincObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

if log is with the same timestamp,click to open a log,results open multiple log.
![image](https://github.com/zinclabs/zincobserve/assets/40289299/152e6083-1593-41f8-88ea-372fb167cfea)

### Please provide the version you discovered this bug in (check about page for version information)

```true
v0.4.5
```

**Comment by hengfeiyang** [comment]
fixed
