### ISSUE TITLE
Easily visualize span events within traces

### ISSUE THREAD

**Issue by bbkane** [openobserve/openobserve#872]
### Description

Slack Context: https://zincobserve.slack.com/archives/C02R473PNP2/p1685370812955759

When creating a span event, the event shows up in the trace "field" view, but there doesn't appear to be a way visualize the events when clicking into a span.

For comparison, see https://app.uptrace.dev/traces/1/1764bbf3eb32c147aa9fbeedb9c8eb71?span=902154934877&dialog=1 (not sure how stable that link is):

![image](https://github.com/openobserve/openobserve/assets/6081085/4284d41b-5c9b-4640-b257-40ee8ed84767)

### Proposed solution

Add a way to visualize span events.

### Alternatives considered

It's possible to use OpenObserve's "Logs" tab to view granular events, but (as far as I know), there's not an easy way to associate that with traces.

**Comment by prabhatsharma** [comment]
I think I misunderstood you in Slack earlier. You are able to see events for a span today. see the screenshot below. The UI is in its first version and needs a lot of work, but is this what you were looking for?

<img width="1545" alt="image" src="https://github.com/openobserve/openobserve/assets/4242188/3524829a-4a4b-42fb-b9cb-31f2ea0e829f">

**Comment by bbkane** [comment]
Ooh I think so, I'll try to look for that
