### ISSUE TITLE
The statistical chart in the trace panel shows unstable data

### ISSUE THREAD

**Issue by hanqian200705** [openobserve/openobserve#893]
### Which OpenObserve functionalities are the source of the bug?

traces

### Is this a regression?

Yes

### Description

The statistical chart in the trace panel shows unstable data.
Sometimes the same query with the same conditions displays different results.

<img width="1346" alt="image" src="https://github.com/openobserve/openobserve/assets/4269408/59501c8c-8eca-4893-b644-30dfea3c4672">
<img width="1336" alt="image" src="https://github.com/openobserve/openobserve/assets/4269408/173547b8-beae-4959-8dec-4386ee9134fd">

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version
v0.4.6
Commit Hash
4903f41b4ebd0d5b09a38b811be097fb700db164
Build Date
2023-05-31T04:32:23Z
```

**Comment by hengfeiyang** [comment]
@hanqian200705 fixed in v0.4.7
