### ISSUE TITLE
Does log ingestion support OpenTelemetry-collector?

### ISSUE THREAD

**Issue by hengfeiyang** [openobserve/openobserve#901]
### Which OpenObserve functionalities are relevant/related to the feature request?

ingestion

### Description

Does log ingestion support OpenTelemetry-collector?

### Proposed solution

support

### Alternatives considered

no

**Comment by prabhatsharma** [comment]
OTEL collector has an elasticsearch exporter. That can be used with OpenObserve

**Comment by agardnerIT** [comment]
I don't understand. If OpenObserve uses clickhouse by default, and [clickhouse has an exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/clickhouseexporter/README.md#example).

So surely I can point that exporter at an OpenObserve endpoint?
