### ISSUE TITLE
Ingested Trace Duration Showing as 0ms

### ISSUE THREAD

**Issue by omkarK06** [openobserve/openobserve#910]
### Which OpenObserve functionalities are the source of the bug?

traces

### Is this a regression?

Yes

### Description

Ingested trace durations are consistently showing as 0ms. These values should instead be displayed in microseconds (µs) if they are less than 1ms to ensure accuracy.
<img width="1380" alt="Screenshot 2023-06-07 at 2 48 24 PM" src="https://github.com/openobserve/openobserve/assets/127078473/71fa78fd-0a96-47b3-9927-d252c98ff73e">

### Please provide a link to a minimal reproduction of the bug

Generate traces that complete execution in less than 1ms.

### Please provide the exception or error you saw

```true
-
```

**Comment by prabhatsharma** [comment]
Let' store the data in float in ms and handle it appropriately on front end.

**Comment by lilos** [comment]
v0.5.1 still has this problem

**Comment by omkarK06** [comment]
Traces with duration less than 1ms won't have a significant effect, so we decided not to work on this.

**Comment by omkarK06** [comment]
Traces with duration less than 1ms won't have a significant effect, so we decided not to work on this issue. Therefore, closing this issue.
