### ISSUE TITLE
North Korean flag used

### ISSUE THREAD

**Issue by krisrang** [openobserve/openobserve#916]
### Which OpenObserve functionalities are the source of the bug?

localization

### Is this a regression?

No

### Description

The language dropdown menu uses the North Korean flag for Korean. I assume this is not intentional?

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.4.7
Commit Hash: 3c855155fbbd467e191a82d20a2d345c668add9c
Build Date: 2023-06-05T14:24:34Z
```

**Comment by prabhatsharma** [comment]
Thanks for pointing that. Not intentional. We will fix it.
