### ISSUE TITLE
[DOCUMENTATION|EXAMPLE] Opsgenie Alert using the RestAPI

### ISSUE THREAD

**Issue by mrabdibdi-anvil** [openobserve/openobserve#921]
### Which OpenObserve functionalities are relevant/related to the feature request?

alerts, other

### Description

Documentation or example to configure the alert system

### Proposed solution

Example to setup the alert with Atlassian Opsgenie

# References

https://docs.opsgenie.com/docs/alert-api#create-alert
https://docs.opsgenie.com/docs/authentication

# Template example

## P1 or P2 or P3

> Review the official documentation to see available fields.

```json
{
    "message": "{alert_name} is active",
    "alias": "{alert_name}",
    "description":"{stream_name}",
    "priority":"P3"
}
```

# Destination

> Follow Atlassian Documentation to generate you API Key, 

**URL**: `https://api.opsgenie.com/v2/alerts`
**Method**: `POST`
**Headers**:
- `Authorization`: `GenieKey __YOUR_API_KEY__`

### Alternatives considered

None. 
I only tested the P1 quickly to validate the solution. 

And it works great !

**Comment by dhenry123** [comment]
# The Same for Matrix

**An alert test button would be very welcome...**

## Prerequisites
- **[your matrix domain]** : Your matrix domain eg: matrix.org
- **[roomID]** : the room Id where you want to post  - **Not the name** 
**Important :** replace the first char **"!"**, with url_encoded : **%21**
eg : !xxxxx:matrix.org => %21xxxxx:matrix.org 
- **[Your token]** : Your access token 

## Template example
```json
{
    "msgtype":"m.text","body":"From Stream : {stream_name} - Alert Type [{alert_type}] - Alert Name [{alert_name}]"
}
```

## Destination

**URL**: https://**[your matrix domain]**/_matrix/client/r0/rooms/**[roomID]**/send/m.room.message
**Method**: `POST`
**Headers**:  `Authorization`
**Value**: `Bearer [Your token]` 


**Many many thanks for your Amazing job !** today more than 9 Millions log ingested :)

**Comment by prabhatsharma** [comment]
We already have docs for matrix. https://openobserve.ai/docs/user-guide/alerts/templates/#matrix
We will update docs for Opsgenie

Thanks @mrabdibdi-anvil  @dhenry123

**Comment by prabhatsharma** [comment]
closing as added to docs
