### ISSUE TITLE
When querying expired trace data, the trace details panel display blank

### ISSUE THREAD

**Issue by hanqian200705** [openobserve/openobserve#926]
### Which OpenObserve functionalities are the source of the bug?

traces

### Is this a regression?

Yes

### Description

For example, if the query time is set to one minute, the trace data is queried, and then the trace details are opened by clicking the row one minute later, the page is blank.
<img width="355" alt="image" src="https://github.com/openobserve/openobserve/assets/4269408/5e079408-8cff-4892-bbff-b1b0d8909be0">
<img width="500" alt="image" src="https://github.com/openobserve/openobserve/assets/4269408/b6f06e06-8841-4f3d-8817-6717675cfdd0">

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version
v0.4.7
Commit Hash
3c855155fbbd467e191a82d20a2d345c668add9c
Build Date
2023-06-05T14:51:01Z
```

**Comment by omkarK06** [comment]
@hanqian200705 Thanks for the issue. This will be resolve in #918
