### ISSUE TITLE
Support Protobuf serialization data ingestion

### ISSUE THREAD

**Issue by honganan** [openobserve/openobserve#937]
### Which OpenObserve functionalities are relevant/related to the feature request?

ingestion

### Description

When ingesting data, Protobuf serialization consumes significantly less CPU than JSON.

Here is a comparision of two methods from Loki:
<img width="1262" alt="image" src="https://github.com/openobserve/openobserve/assets/4892550/e842566c-5999-46fe-8edd-7dfdeb84f821">

### Proposed solution

Support Protobuf serialization data ingestion

### Alternatives considered

None

**Comment by prabhatsharma** [comment]
This will get covered in https://github.com/openobserve/openobserve/issues/981
