### ISSUE TITLE
Need an OTEL collector exporter support logs,traces,metrics

### ISSUE THREAD

**Issue by hengfeiyang** [openobserve/openobserve#952]
### Which OpenObserve functionalities are relevant/related to the feature request?

other

### Description

Here list some exporters: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter

- We need to use `elasticsearchexporter` to write logs
- we need to use `prometheus` to write metrics
- We need to use otlp to write traces

We can provide an exporter to support everything, it will be awesome.

**Comment by oasisk** [comment]
Added supoort for OTLP in 0.6.0
