### ISSUE TITLE
Add ability to set log timezone for openobserve container

### ISSUE THREAD

**Issue by unixfox** [openobserve/openobserve#972]
### Which OpenObserve functionalities are relevant/related to the feature request?

other

### Description

The timezone in the logs of the openobserve container are in UTC, it would be great to be able to read the logs in the local timezone.

### Proposed solution

Add the ability to configure the timezone using an environment variable. A common environment variable is `TZ`, example: `TS: Europe/Paris`

### Alternatives considered

N/A

**Comment by gaby** [comment]
@unixfox I don't think they are in UTC, they are using the Web browser timezone. I'm sending logs with UTC and they showup with "-x:xx"in the UI.

Related: https://github.com/openobserve/openobserve/issues/473

**Comment by prabhatsharma** [comment]
Storage is in UTC. Display is in browser TZ

**Comment by prabhatsharma** [comment]
I think we will not change the storage time zone, but will allow to see logs in any time zone

**Comment by gaby** [comment]
> I think we will not change the storage time zone, but will allow to see logs in any time zone

That sounds good to me. Everytime I show someone OpenObserve I have to explain the TZ issue.

**Comment by unixfox** [comment]
> @unixfox I don't think they are in UTC, they are using the Web browser timezone. I'm sending logs with UTC and they showup with "-x:xx"in the UI.
> 
> Related: https://github.com/openobserve/openobserve/issues/473

I'm not talking about the web interface but the logs of the container when you do `docker logs`.

**Comment by prabhatsharma** [comment]
Do you mean logging of OpenObserve logs itself?

**Comment by unixfox** [comment]
Yes these ones:
![image](https://github.com/openobserve/openobserve/assets/4016501/8e60bf5f-8965-4206-91c8-462c37691ebd)

**Comment by hengfeiyang** [comment]
@unixfox Already implement this in v0.8.0, you can configure it like this:

```
ZO_LOG_LOCAL_TIME_FORMAT="%Y-%m-%dT%H:%M:%S.%3f%z"
```

it will print logs with local timezone. also you can set `ZO_LOG_JSON_FORMAT=true` to print logs as json format.

**Comment by unixfox** [comment]
> @unixfox Already implement this in v0.8.0, you can configure it like this:
> 
> ```
> ZO_LOG_LOCAL_TIME_FORMAT="%Y-%m-%dT%H:%M:%S.%3f%z"
> ```
> 
> it will print logs with local timezone. also you can set `ZO_LOG_JSON_FORMAT=true` to print logs as json format.

Mmh this doesn't change the timezone of logs printed in the container logs though?

This only display the same date, hour, minute but in another format?

**Comment by hengfeiyang** [comment]
Yep, there are two different problems.
1. the log always print in UTC format, we can use this setting to show it in local timezone.
2. the timezone of the container, how to change the container timezone is not an issue of OpenObserve itself.

We can talk about how to change the timezone of the container. but i haven't deep in this question. let's others help on this.

**Comment by unixfox** [comment]
Doesn't that PR https://github.com/openobserve/openobserve/pull/2499 fixes the issue?

**Comment by hengfeiyang** [comment]
I checked for the timezone of container, don't need do that, just add a ENV `TZ=Asia/Shanghai` for setting timezone, like this:

```
docker run -tdi --name oo \
  --hostname oo \
  -p 5080:5080 \
  --volume "/Users/yanghengfei/docker/data/openobserve/data:/data" \
  -e TZ=Asia/Shanghai \
  -e ZO_LOG_LOCAL_TIME_FORMAT="%Y-%m-%dT%H:%M:%S.%3f%z" \
  -e ZO_ROOT_USER_EMAIL="root@example.com" \
  -e ZO_ROOT_USER_PASSWORD="Complexpass#123" \
  -e ZO_DATA_DIR="/data" \
  -e ZO_LOCAL_MODE=true \
  public.ecr.aws/zinclabs/openobserve:v0.8.0-rc1
```

Then it will print logs in `Asia/Shanghai` like this:
```
2024-01-18T10:54:44.184+0800 INFO openobserve: Starting OpenObserve v0.8.0-rc1
2024-01-18T10:54:44.184+0800 INFO openobserve: System info: CPU cores 8, MEM total 15986 MB, Disk total 237146 GB, free 71096 GB
2024-01-18T10:54:45.217+0800 INFO openobserve::service::db::user: Start watching user
2024-01-18T10:54:45.217+0800 INFO openobserve::service::db::user: Users Cached
```

Also you can change it to other timezone like this:

```
docker run -tdi --name oo \
  --hostname oo \
  -p 5080:5080 \
  --volume "/Users/yanghengfei/docker/data/openobserve/data:/data" \
  -e TZ=Asia/Karachi \
  -e ZO_LOG_LOCAL_TIME_FORMAT="%Y-%m-%dT%H:%M:%S.%3f%z" \
  -e ZO_ROOT_USER_EMAIL="root@example.com" \
  -e ZO_ROOT_USER_PASSWORD="Complexpass#123" \
  -e ZO_DATA_DIR="/data" \
  -e ZO_LOCAL_MODE=true \
  public.ecr.aws/zinclabs/openobserve:v0.8.0-rc1
```

Then it will print logs in `Asia/Karachi` like this:
```
2024-01-18T07:56:51.531+0500 INFO openobserve: Starting OpenObserve v0.8.0-rc1
2024-01-18T07:56:51.531+0500 INFO openobserve: System info: CPU cores 8, MEM total 15986 MB, Disk total 237146 GB, free 71263 GB
2024-01-18T07:56:52.564+0500 INFO openobserve::service::db::user: Start watching user
2024-01-18T07:56:52.564+0500 INFO openobserve::service::db::user: Users Cached
```

**Comment by unixfox** [comment]
OK thank you! I promise I did try that back when I created the issue and it didn't work.

Good that it works now.
