### ISSUE TITLE
Map panel in dashboards

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#979]
### Which OpenObserve functionalities are relevant/related to the feature request?

dashboards

### Description

In order to display map data in a dashboard currently we do not have an option. It makes a lot of sense to be able to visualize network traffic on a map to easily grasp the source flow.

### Proposed solution

A map panel type can allow for easy visualization of data.

We will provide Geolocation mapping from IP addresses using maxmind data which can then be used for mapping.

### Alternatives considered

none

**Comment by prabhatsharma** [comment]
Some sample files that can be used for reference
1. https://zinc-public-data.s3.us-west-2.amazonaws.com/geoip/sample/logs_with_geoip.zip
2. https://zinc-public-data.s3.us-west-2.amazonaws.com/geoip/sample/geoip.zip

**Comment by neha00290** [comment]
testing complete for this. closing the same
