### ISSUE TITLE
OTLP support for logs and metrics ingestion

### ISSUE THREAD

**Issue by prabhatsharma** [openobserve/openobserve#981]
### Which OpenObserve functionalities are relevant/related to the feature request?

ingestion

### Description

It is possible to ingest traces using OTLP in OpenObserve. OpenObserve supports processing of trace messages and could support processing of metrics and log messages.

gRPC ingestion incurs much lower CPU on server for processing. This will allow for higher ingestion rate of logs and metrics than is currently supported

### Proposed solution

Messages can be sent in 3 formats:

- [x] Logs : OTLP/gRPC
- [x] Logs : OTLP/HTTP - Binary protobuf encoding
- [x] Logs :  OTLP/HTTP - JSON protobuf encoding
- [x] Metrics : OTLP/gRPC
- [x] Metrics : OTLP/HTTP - Binary protobuf encoding
- [x] Metrics :  OTLP/HTTP - JSON protobuf encoding

Traces support all 3 formats above. The same can be extended to logs and metrics

### Alternatives considered

None

**Comment by oasisk** [comment]
GRPC handling has challenges with functions using vrl
