### ISSUE TITLE
How to push traces to a specific stream using openTelemetry?

### ISSUE THREAD

**Issue by chiikin** [openobserve/openobserve#994]
### Describe the problem that you experienced

As the title issue: How to push traces to a specific stream using openTelemetry?

As shown in the figure below, I tried to push traces through openTelemetry, but the actual push path is “http://192.168.122.220:5081/api/default/traces”, where the port is incorrect.

![image](https://github.com/openobserve/openobserve/assets/21117413/74887050-ce34-4f5c-b74f-331bae2a5363)

In fact, I also need to set zinc-org-id = default in the headers, but the key of the header is different from the default configuration of the environment variable.

 Finally, I also found that I do not know how to push to a specific stream.

**Comment by prabhatsharma** [comment]
All traces are currently stored in a single stream in an organization, which cannot be changed for now. We would recommend you use the service name for categorization.

**Comment by chiikin** [comment]
> All traces are currently stored in a single stream in an organization, which cannot be changed for now. We would recommend you use the service name for categorization.

 Is there a plan to add this feature?
Can the document instructions be updated?

**Comment by oasisk** [comment]
@chiikin thank you for your feedback..we would update our documentation.For traces we support two mechanisms:

- JSON over HTTP , which is using end point : http://hostname:5080/api/default/traces
- for GRPC end point is http://hostname:5081 & as there is no way to provide organisation to which traces should be sent we need two headers Authorization & zinc-org-id
