### ISSUE TITLE
Local disk storage file format for direct read using external tools

### ISSUE THREAD

**Issue by rinshadka** [openobserve/openobserve#997]
Hi, 

I would like to query the local storage files directly using any utilities. Just like qurerying an SQLite DB file. For that can I know in which DB format openobserve is writing the stream data and its metadata in to local Disk, Is there any option currently we have in place to read the data directly from Disk itself from any external utility?

Thanks.

**Comment by prabhatsharma** [comment]
OpenObserve stores data in parquet files. You can find a lot of tools to read parquet files directly. big data tools like trino, presto, spark, hadoop. small time tools like datafusion-cli, duckdb, and many more.
