### ISSUE TITLE
About log retention settings for streams in the WEB UI

### ISSUE THREAD

**Issue by cold01water** [openobserve/openobserve#998]
### Which OpenObserve functionalities are the source of the bug?

streams

### Is this a regression?

No

### Description

In v0.4.7, the log retention period can be set from the WEB UI.

However, the mention of ZO_COMPACT_DATA_RETENTION_ENABLED in the manual is very confusing.
If you are using v0.4.7, the actual process is activated when the value of ZO_COMPACT_DATA_RETENTION_DAYS is greater than 0.

https://openobserve.ai/docs/guide/environment-variables/#common

I think it needs to be corrected because the manual and the actual movement is different.

**Comment by hengfeiyang** [comment]
You are right, we only need one ENV to enable data retention:

`ZO_COMPACT_DATA_RETENTION_DAYS` greater than 0.

the correct doc URL is: https://openobserve.ai/docs/environment-variables/

Can you tell me where did you find the link of `https://openobserve.ai/docs/guide/environment-variables/`

**Comment by cold01water** [comment]
I was very unlucky.

I just checked and found that some of the links in Readme.md are in /docs/guide/.

```
# Installation

You can install OpenObserve in under 2 minutes by following the [quickstart](https://openobserve.ai/docs/guide/quickstart/) documentation
```

Since I had started working from this quickstart, I think I was looking at the same manual as it was.

**Comment by hengfeiyang** [comment]
Thanks, we already updated the README.
